test: Implement unit tests for CWallet::CreateTransaction
dashpay/dash pull request #3667
Opened 2020-08-22 15:46 UTC by xdustinface

I decided to add this because i worked on a fix for `CreateTransaction` and while doing that i figured its very hard to say for sure by just manual test/reviewing if things are still good since this is quite complex method imo with a lot possible routes. I think this should catch all currently possible cases in there. If someone can think about any improvement or more test cases, let me know!

Requires #3666 and #3668 to pass all the tests.

2020-08-24 08:50 UTC, xdustinface commented
Ready for review!

2020-08-24 13:58 UTC, PastaPastaPasta commented
You should probably move #3668 into this PR, cause unit tests need to be passing for us to merge this

2020-08-24 14:07 UTC, xdustinface commented
> Requires #3666 and #3668 to pass all the tests.

Hmm imo separating them makes sense (depending on what will happen during review process :D). Why not just merge #3666 and #3668 first and then rebase this one as the others still pass without this PR. You can still verify #3668 locally with this PR for now. Still prefer a merge? Let me know!

2020-08-24 16:07 UTC, UdjinM6 commented
I'd prefer rebasing this on top of develop after 3668 is merged.

2020-09-03 22:08 UTC, PastaPastaPasta requested changes

2020-09-03 22:34 UTC, xdustinface commented on src/wallet/test/wallet_tests.cpp
> +        CheckEqual(vecEntries.size(), wtx.tx->vout.size() - (nChangePos != -1 ? 1 : 0));
What about 29b9e0f?

2020-09-03 22:35 UTC, xdustinface commented on src/wallet/test/wallet_tests.cpp
> +    BOOST_CHECK(CreateTransaction({{10000, false}, {100, false}}, false));
Hm i just dropped those initial tests, c7e34f5. They are anyway covered in the rest of the test cases.

2020-09-04 17:15 UTC, PastaPastaPasta approved these changes
utACK

2020-09-04 21:20 UTC, UdjinM6 approved these changes
utACK

2020-09-04 21:24 UTC, merged