docs: Properly alphabetize output of CLI --help option (backport 12331)
dashpay/dash pull request #3681
Opened 2020-08-30 03:50 UTC by Minh20

Alphebetize CLI --help output #3614

2020-08-30 04:46 UTC, PastaPastaPasta commented
haven't taken a look yet, however, in the future, try to avoid closing a PR just to open a new one, because now the discussion we had on the old PR we can't view here. Also it kindof just clutters up the repo. Granted, I did this exact same thing when I was getting started because git was confusing and I didn't understand it, so if you need help with something like git stuff, let us know and we can likely help you

2020-08-30 05:09 UTC, Minh20 commented
> haven't taken a look yet, however, in the future, try to avoid closing a PR just to open a new one, because now the discussion we had on the old PR we can't view here. Also it kindof just clutters up the repo. Granted, I did this exact same thing when I was getting started because git was confusing and I didn't understand it, so if you need help with something like git stuff, let us know and we can likely help you

Thanks for the feedback and offering help for the git stuff. I'll pay attention for future pull requests.

2020-08-30 15:18 UTC, UdjinM6 requested changes

2020-08-30 15:18 UTC, UdjinM6 commented on src/init.cpp
> +        strUsage += HelpMessageOpt("-fuzzmessagestest=<n>", "Randomly fuzz 1 of every <n> network messages");
```suggestion
```

2020-08-31 18:24 UTC, PastaPastaPasta commented
feature_shutdown.py failure here: https://gitlab.com/dashpay/dash/-/jobs/711537367 is weird... No need for you to worry about this @Minh20

2020-09-01 15:40 UTC, UdjinM6 requested changes

2020-09-01 15:40 UTC, UdjinM6 commented on src/init.cpp
> +            "(default: 0 = disable pruning blocks, 1 = allow manual pruning via RPC, >%u = automatically prune block files to stay under the specified target size in MiB)"), MIN_DISK_SPACE_FOR_BLOCK_
```suggestion
            "(default: 0 = disable pruning blocks, 1 = allow manual pruning via RPC, >=%u = automatically prune block files to stay under the specified target size in MiB)"), MIN_DISK_SPACE_FOR_BLOCK_FILES / 1024 / 1024));
```

2020-09-01 15:40 UTC, UdjinM6 commented on src/dash-cli.cpp
> +    strUsage += HelpMessageOpt("-rpcwallet=<walletname>", _("Send RPC for non-default wallet on RPC server (argument is wallet filename in dashd directory, required if dashd/-Qt runs with multiple wa
```suggestion
    strUsage += HelpMessageOpt("-rpcwallet=<walletname>", _("Send RPC for non-default wallet on RPC server (needs to exactly match corresponding -wallet option passed to dashd)"));
```

2020-09-01 15:40 UTC, UdjinM6 commented on src/dash-cli.cpp
> +    strUsage += HelpMessageOpt("-stdin", _("Read extra arguments from standard input, one per line until EOF/Ctrl-D (recommended for sensitive information such as passphrases)"));
```suggestion
    strUsage += HelpMessageOpt("-stdin", _("Read extra arguments from standard input, one per line until EOF/Ctrl-D (recommended for sensitive information such as passphrases).  When combined with -stdinrpcpass, the first line from standard input is used for the RPC password."));
```

2020-09-01 15:40 UTC, UdjinM6 commented on src/init.cpp
> +    strUsage += HelpMessageOpt("-conf=<file>", strprintf(_("Specify configuration file (default: %s)"), BITCOIN_CONF_FILENAME));
```suggestion
    strUsage += HelpMessageOpt("-conf=<file>", strprintf(_("Specify configuration file. Relative paths will be prefixed by datadir location. (default: %s)"), BITCOIN_CONF_FILENAME));
```

2020-09-01 15:40 UTC, UdjinM6 commented on src/init.cpp
> +
```suggestion
```

2020-09-01 15:40 UTC, UdjinM6 commented on src/init.cpp
> +        strUsage += HelpMessageOpt("-checkblockindex", strprintf("Do a full consistency check for mapBlockIndex, setBlockIndexCandidates, chainActive and mapBlocksUnlinked occasionally. Also sets -ch
```suggestion
        strUsage += HelpMessageOpt("-checkblockindex", strprintf("Do a full consistency check for mapBlockIndex, setBlockIndexCandidates, chainActive and mapBlocksUnlinked occasionally. (default: %u)", defaultChainParams->DefaultConsistencyChecks()));
```

2020-09-01 15:40 UTC, UdjinM6 commented on src/init.cpp
> +    strUsage += HelpMessageOpt("-rpcauth=<userpw>", _("Username and hashed password for JSON-RPC connections. The field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python scri
```suggestion
    strUsage += HelpMessageOpt("-rpcauth=<userpw>", _("Username and hashed password for JSON-RPC connections. The field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is included in share/rpcauth. The client then connects normally using the rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This option can be specified multiple times"));
```

2020-09-01 15:40 UTC, UdjinM6 commented on src/init.cpp
> +    strUsage += HelpMessageOpt("-rpcbind=<addr>[:port]", _("Bind to given address to listen for JSON-RPC connections. This option is ignored unless -rpcallowip is also passed. Port is optional and ov
```suggestion
    strUsage += HelpMessageOpt("-rpcbind=<addr>[:port]", _("Bind to given address to listen for JSON-RPC connections. Do not expose the RPC server to untrusted networks such as the public internet! This option is ignored unless -rpcallowip is also passed. Port is optional and overrides -rpcport. Use [host]:port notation for IPv6. This option can be specified multiple times (default: 127.0.0.1 and ::1 i.e., localhost, or if -rpcallowip has been specified, 0.0.0.0 and :: i.e., all addresses)"));
```

2020-09-03 13:43 UTC, UdjinM6 commented
Pls see https://github.com/UdjinM6/dash/commit/769f08ff51ef981a435bc2cdf1c08e360620f166 and maybe https://github.com/UdjinM6/dash/commit/bc2ac58418d103ff39b654507869ade26bb54db1 (or just sort options in `src/wallet/init.cpp` properly instead but imo wallet has so many options already that it kind of makes sense to split them in few more groups)

2020-09-10 07:10 UTC, Minh20 commented
> Pls see [UdjinM6@769f08f](https://github.com/UdjinM6/dash/commit/769f08ff51ef981a435bc2cdf1c08e360620f166) and maybe [UdjinM6@bc2ac58](https://github.com/UdjinM6/dash/commit/bc2ac58418d103ff39b654507869ade26bb54db1) (or just sort options in `src/wallet/init.cpp` properly instead but imo wallet has so many options already that it kind of makes sense to split them in few more groups)

2020-09-10 11:40 UTC, UdjinM6 commented
Still waiting for `src/wallet/init.cpp` updates...

2020-09-16 18:31 UTC, PastaPastaPasta commented
Look https://github.com/dashpay/dash/pull/3681/files, you messed some stuff up

2020-09-20 22:44 UTC, PastaPastaPasta commented
@Minh20 see commits https://github.com/UdjinM6/dash/commit/bc2ac58418d103ff39b654507869ade26bb54db1 and https://github.com/UdjinM6/dash/commit/769f08ff51ef981a435bc2cdf1c08e360620f166

2020-09-23 09:26 UTC, UdjinM6 approved these changes
ACK

2020-09-24 02:28 UTC, PastaPastaPasta approved these changes
utACK, looks good

2020-09-24 10:58 UTC, merged