[v0.16.x] V16 more backports
dashpay/dash pull request #3732
Opened 2020-09-24 05:51 UTC by PastaPastaPasta

https://github.com/dashpay/dash/pull/3710 had conflicts
https://github.com/dashpay/dash/pull/3701 had conflicts
https://github.com/dashpay/dash/pull/3707 had conflicts

All others had no conflicts

2020-09-24 06:20 UTC, PastaPastaPasta commented
@xdustinface I expect you to create a replacement for https://github.com/dashpay/dash/pull/3732/commits/065300715fd0826757b963632169cd3fa20f293f :D

2020-09-24 16:04 UTC, xdustinface commented
> @xdustinface I expect you to create a replacement for [0653007](https://github.com/dashpay/dash/commit/065300715fd0826757b963632169cd3fa20f293f) :D

See 2eb91ad423ff93adeb122754f53930304367feee

2020-09-24 16:20 UTC, PastaPastaPasta commented
@xdustinface see latest

2020-09-24 16:34 UTC, xdustinface approved these changes
Looks all good, slightly tested ACK

2020-09-25 17:04 UTC, UdjinM6 requested changes

2020-09-25 17:04 UTC, UdjinM6 commented on src/qt/overviewpage.cpp
> +    bool fIsEnabled = CPrivateSendClientOptions::IsEnabled();
```suggestion
    bool fIsEnabled = privateSendClient.fEnablePrivateSend;
```

2020-09-25 18:50 UTC, UdjinM6 approved these changes
ACK

2020-09-25 19:50 UTC, PastaPastaPasta commented
(weird kindof self-)utACK https://github.com/dashpay/dash/pull/3732/commits/dbfdf8cb157954ec350edfbc2ccc5a96582ddc1b

2020-09-26 01:04 UTC, xdustinface approved these changes
ACK

2020-09-26 11:05 UTC, merged