Translations 2020-09
dashpay/dash pull request #3736
Opened 2020-09-25 18:16 UTC by UdjinM6

Note: strings were produced via `make translate` on #3732, not on `develop` to make sure we have the right ones in v0.16

2020-09-25 18:21 UTC, PastaPastaPasta commented
Would it make sense to merge this straight into v16? or to develop then backport?

2020-09-25 18:49 UTC, UdjinM6 commented
Well, everything but release notes goes into `develop` first usually. Merging translations into v0.16.x doesn't help much because we'll have to merge it back anyway and I personally prefer to keep the merge-back PR/commit as simple/trivial as possible (release notes fit this criteria perfectly imo).

2020-09-26 16:20 UTC, xdustinface requested changes
Some fixes for german. Is someone around who is able to review my german suggestions? That would be nice :D

2020-09-26 16:20 UTC, xdustinface commented on src/qt/locale/dash_de.ts
> +        <translation>Mempool beim Start von anderen Nodes her synchronisieren (Standard: %u)</translation>
```suggestion
        <translation>Mempool beim Start von anderen Knoten synchronisieren (Standard: %u)</translation>
```

2020-09-26 16:20 UTC, xdustinface commented on src/qt/locale/dash_de.ts
> +    </context>
Intention?

2020-09-26 16:20 UTC, xdustinface commented on src/qt/locale/dash_de.ts
> +        <translation>Versuche mindestens N Inputs jeder Denomination zu erstellen (%u-%u, Standard: %u)</translation>
```suggestion
        <translation>Versuche mindestens N Inputs jeder Stückelung zu erstellen (%u-%u, Standard: %u)</translation>
```

2020-09-26 16:20 UTC, xdustinface commented on src/qt/locale/dash_de.ts
> +        <translation>Dies ist zu erwarten, da eine pruned Node betrieben wird.</translation>
```suggestion
        <translation>Dies ist zu erwarten, da ein gekürzter (pruned) Knoten betrieben wird.</translation>
```

2020-09-26 16:20 UTC, xdustinface commented on src/qt/locale/dash_de.ts
> +        <translation>N unterschiedliche Masternodes für jeden denominierten Input benutzen, um Dash zu anonymisieren (%u-%u, Standard: %u) </translation>
```suggestion
        <translation>N unterschiedliche Masternodes für jeden gestückelten Input benutzen, um Dash zu anonymisieren (%u-%u, Standard: %u) </translation>
```

2020-09-26 16:20 UTC, xdustinface commented on src/qt/locale/dash_de.ts
> +        <translation>Erstelle bis zu N Inputs jeder Denomination (%u-%u, Standard: %u) </translation>
```suggestion
        <translation>Erstelle bis zu N Inputs jeder Stückelung (%u-%u, Standard: %u) </translation>
```

2020-09-26 16:20 UTC, xdustinface commented on src/qt/locale/dash_de.ts
> +        <translation>Validierung der Governance zum Start hin deaktiviert.</translation>
```suggestion
        <translation>Starte mit deaktivierter Governance-Validierung.</translation>
```

2020-09-26 16:31 UTC, UdjinM6 commented
>Now that i posted them.. i guess they need to be updated in a transifex rather (honestly not sure how we handle that at the moment)? 🙈

Yes, this kind of PRs are not for suggestions :) I pull all translations from Transifex, run them through `python3 contrib/devtools/update-translations.py` and commit as is.

2020-09-26 19:16 UTC, akijuh commented
> 
> 
> > Now that i posted them.. i guess they need to be updated in a transifex rather (honestly not sure how we handle that at the moment)? see_no_evil
> 
> Yes, this kind of PRs is not for suggestions :) I pull all translations from Transifex, run them through `python3 contrib/devtools/update-translations.py` and commit as is.
> 
> EDIT: re `as is`: Well, I do fix some inconsistencies on Transifex and re-pull fixed translations again if that script complains about smth but it's mostly about missing placeholders and such (e.g. translators confuse %1 with 1% sometimes etc.).

Hi,
What you mean with "%1 with 1%" ?
To me those two look the same both.

AjM

2020-09-28 07:46 UTC, UdjinM6 commented
> Found this from the source, is this right? Syncing Headers (%1%)...

Yes, `%1` will be replaced with a number, say 89, an this string will become `Syncing Headers (89%)...`

2020-09-28 16:56 UTC, PastaPastaPasta approved these changes
utACK

2020-09-28 17:03 UTC, xdustinface approved these changes
utACK, but still, who is managing the transifex stuff? I requested to become german translator but but didn't get a respone yet :D

2020-09-28 17:27 UTC, akijuh commented
> 
> 
> utACK, but still, who is managing the transifex stuff? I requested to become german translator but but didn't get a respone yet :D

@schinzelh is transifex manager.

2020-09-28 18:53 UTC, merged