test: Optimize feature_block_reward_reallocation.py
dashpay/dash pull request #3743
Opened 2020-09-27 07:33 UTC by PastaPastaPasta

Locally, develop is running in 308 seconds while this branch is running at 199 seconds. A nice improvement if I do say so myself :D

2020-09-28 09:25 UTC, UdjinM6 commented
Can confirm 340s -> 130s improvement locally here 👍 I remember that we had to do `sync_blocks` every so often to make sure nodes aren't overwhelmed with blocks which was critical for Travis builds at some point, waiting for https://travis-ci.com/github/UdjinM6/dash/builds/186965759 to confirm that I was too cautious :) Also, pls see 4abd311c98 and 902c35156d

2020-09-29 02:42 UTC, PastaPastaPasta commented
I don't see the point of 902c35156d96b081f6f35c54cdb7b436c1cb93d4

2020-09-29 02:49 UTC, UdjinM6 commented
We push all blocks and check chain state changes via node0 only. Would probably make sense to make sure blocks are propagated via p2p and accepted on the other node too, just in case.

2020-09-29 02:55 UTC, PastaPastaPasta commented
Maybe I'm misunderstanding something, but in my mind, this other node is really just needed to serve as the mn to get paid in block reward, there should be no situation where we accept a block (in test suite) where our peer doesn't since we are running the same build and generating / submitblock will validate the block against validation rules in the same way the peer would..

Maybe I'm missing some value

2020-09-29 03:00 UTC, UdjinM6 commented
>generating / submitblock will validate the block against validation rules in the same way the peer would

But, technically, these are two different routes (rpc vs p2p). If we would need to test internal validation rules only we could probably be simply using unit tests instead.

2020-09-29 03:28 UTC, PastaPastaPasta commented on test/functional/feature_block_reward_reallocation.py
> +
```suggestion
```

2020-09-29 03:29 UTC, PastaPastaPasta commented
Seems fair, cherry-picked

2020-09-29 19:28 UTC, UdjinM6 approved these changes
ACK

2020-09-30 01:40 UTC, xdustinface requested changes
I guess you didn't add those intentionally?

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +
```suggestion
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +        self.signal(399, False)  # 1 block short
```suggestion
        self.signal(399, False) # 1 block short
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +        self.signal(398, False)  # 1 block short again
```suggestion
        self.signal(398, False) # 1 block short again
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +        self.signal(396, True)  # just enough to lock in
```suggestion
        self.signal(396, True) # just enough to lock in
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +        self.nodes[0].generate(1)  # activation
```suggestion
        self.nodes[0].generate(1) # activation
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +        for period in range(19):  # there will be 19 adjustments, 3 superblocks long each
```suggestion
        for period in range(19): # there will be 19 adjustments, 3 superblocks long each
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +        for period in range(10):  # check 10 next superblocks
```suggestion
        for period in range(10): # check 10 next superblocks
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +        for i in range(8):  # 7 to reach min level and 1 more to check it doesn't go lower than that
```suggestion
        for i in range(8): # 7 to reach min level and 1 more to check it doesn't go lower than that
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +            self.signal(0, False)  # no need to signal
```suggestion
            self.signal(0, False) # no need to signal
```

2020-09-30 01:40 UTC, xdustinface commented on test/functional/feature_block_reward_reallocation.py
> +
```suggestion
```

2020-09-30 01:42 UTC, PastaPastaPasta commented
Those changes are intentional in order to make the file more in line with python formatting standards

2020-09-30 02:00 UTC, xdustinface approved these changes
Ok well then its fine.. it just looked like a mistake lol.. i guess you should (at least try to) split such changes out in a separate commits to make it obvious or write it down somewhere in the description. 

utACK

2020-09-30 12:30 UTC, merged