Backports 0.17 pr21
dashpay/dash pull request #3786
Opened 2020-11-01 06:09 UTC by PastaPastaPasta

2020-11-01 18:43 UTC, PastaPastaPasta commented
I don't understand why CI is unhappy...

2020-11-04 11:15 UTC, UdjinM6 requested changes
Pls see 8f5851b714 + one suggestion below

2020-11-07 23:35 UTC, UdjinM6 approved these changes
utACK

2020-11-09 20:54 UTC, xdustinface approved these changes
utACK

2020-11-09 21:56 UTC, merged