contrib: Update makeseeds.py
dashpay/dash pull request #3790
Opened 2020-11-03 19:17 UTC by xdustinface

The `dnspython` package complained about  `dns.resolver.Resolver.query()` being deprecated and suggested to use `dns.resolver.Resolver.resolve()` instead.

2020-11-04 12:08 UTC, UdjinM6 requested changes
NACK

```
2.0.0
...
- dns.resolver.resolve() has been added, allowing control of whether search lists are used. dns.resolver.query() is retained for backwards compatibility, but deprecated. ....
....
```
https://dnspython.readthedocs.io/en/latest/whatsnew.html#id1

but the newest version available on Ubuntu 18.04 is `1.15.0-1` and running `makeseeds.py` with this patch fails with multiple `ERR: Could not resolve ASN for <someip>` errors.

2020-11-04 12:50 UTC, xdustinface commented
> but the newest version available on Ubuntu 18.04 is `1.15.0-1` and running `makeseeds.py` with this patch fails with multiple `ERR: Could not resolve ASN for <someip>` errors.

@UdjinM6 Hm it works well here on my 18.04 VPS. Running `pip3 install dnspython` installed `2.0.0` and with the patch `makeseeds.py` still prints the correct list of IPs without any error. Do you maybe have python 3.5 installed? Also weird that you get `1.1.15-1`.. shouldn't you at least get `1.1.16` (assuming you run python3.5)?

2020-11-04 12:59 UTC, UdjinM6 commented
Ahhh... Well, I followed https://github.com/dashpay/dash/blob/master/contrib/seeds/README.md#dependencies to install it:
```
sudo apt-get install python3-dnspython
```

Should replace it with
```
sudo apt-get install python3-pip
pip3 install dnspython
```
then to ensure consistency between docs and scripts.

2020-11-04 13:30 UTC, xdustinface commented
> then to ensure consistency between docs and scripts.

Ahh, fixed! Didn't even realise there are docs about this 🙈

2020-11-04 13:30 UTC, UdjinM6 approved these changes
ACK

2020-11-07 20:52 UTC, PastaPastaPasta approved these changes
utACK

2020-11-08 14:44 UTC, merged