Add v0.16.1.0 release notes
dashpay/dash pull request #3805
Opened 2020-11-09 22:00 UTC by UdjinM6

2020-11-10 00:27 UTC, xdustinface requested changes
What about either the suggestions in the comments or maybe just bc28d901efa94444b87d83407b46a31cf9036d91, thats what i came up with while/after adding the comments :)

2020-11-10 00:27 UTC, xdustinface commented on doc/release-notes.md
> +a couple of crashes which could occur when a node is compiled or started with wallets disabled etc.
```suggestion
a couple of crashes which could occur when a node is compiled or started with wallets disabled
```

2020-11-10 00:27 UTC, xdustinface commented on doc/release-notes.md
> +p2p message. Some other internal optimizations were made to the way object requests are handled.
Probably not very important to mention but weren't the "Some other internal.." rather bugfixes than optimizations? (of course, bugfixes also optimize things 😆)

2020-11-10 13:46 UTC, thephez reviewed
A few small comments

2020-11-10 13:46 UTC, thephez commented on doc/release-notes.md
>  This release is mandatory for all nodes.
Is this accurate?

2020-11-10 13:46 UTC, thephez commented on doc/release-notes.md
> +InstantSend locks were not relayed correctly when another node was requesting updates via `mempool`
```suggestion
InstantSend locks were not relayed correctly when another node was requesting updates via the `mempool`
```

2020-11-10 13:46 UTC, thephez commented on doc/release-notes.md
> +Fixed an issue when wallet would refuse to load if no valid GUI theme was found in settings.
```suggestion
Fixed an issue where the wallet would refuse to load if no valid GUI theme was found in settings.
```

2020-11-10 13:46 UTC, thephez commented on doc/release-notes.md
> +Few other GUI issues like fonts acting strange sometimes, window size not updating correctly,
Maybe "... like inconsistently scaled font sizes, ..."

2020-11-11 20:38 UTC, xdustinface approved these changes
utACK

2020-11-12 00:36 UTC, PastaPastaPasta requested changes

2020-11-12 00:36 UTC, PastaPastaPasta commented on doc/release-notes.md
> +- The wallet did refuse to load if no valid GUI theme was found in settings.
```suggestion
- The wallet crashed if no valid GUI theme was found in settings.
```

2020-11-12 00:36 UTC, PastaPastaPasta commented on doc/release-notes.md
> +- There were randomly occurring font size scaling issues like abnormal font sizes.
```suggestion
- There were randomly occurring font size scaling issues.
```

2020-11-12 00:36 UTC, PastaPastaPasta commented on doc/release-notes.md
> +- Open and close the settings while the application was in fullscreen/maximised
```suggestion
- Opening or closing the settings while the application was in full-screen/maximized
```

2020-11-12 00:36 UTC, PastaPastaPasta commented on doc/release-notes.md
> +- There was an unexpected checkmark in the "Encrypt wallet" menu item on linux/windows
```suggestion
- There was an unexpected checkmark in the "Encrypt wallet" menu item on Linux and Windows
```

2020-11-12 16:33 UTC, xdustinface approved these changes
re-utACK

2020-11-12 17:22 UTC, PastaPastaPasta approved these changes
utACK

2020-11-12 19:08 UTC, thephez approved these changes
ACK

2020-11-12 23:10 UTC, merged