Implement new hardfork for v17 to be used in future changes
dashpay/dash pull request #3808
Opened 2020-11-11 18:06 UTC by PastaPastaPasta

Not sure I'm a huge fan of `DEPLOYMENT_V17` name, lmk if there are any suggestions

2020-11-11 18:24 UTC, thephez commented
Will the fork primarily be to support platform requirements? If so, the name could reflect that.

2020-11-17 15:59 UTC, UdjinM6 requested changes

2020-11-17 15:59 UTC, UdjinM6 commented on src/consensus/params.h
> +    DEPLOYMENT_V17, // Deployment of Block Reward Reallocation
```suggestion
    DEPLOYMENT_V17, // Deployment of V17 Hard Fork
```

2020-11-17 16:03 UTC, UdjinM6 commented
Agree that a better name should be picked at some point but we can tweak this later, it's not a blocker imo.

2020-11-17 16:06 UTC, UdjinM6 approved these changes
utACK

2020-11-17 19:19 UTC, xdustinface approved these changes
utACK

2020-11-17 19:28 UTC, merged