rpc: Add `submit` option to `protx register(_fund)` RPC commands
dashpay/dash pull request #3830
Opened 2020-11-27 10:05 UTC by UdjinM6

Setting `submit` to `false` will force these RPCs to return raw tx hex instead of sending it to the network.

2020-11-27 10:41 UTC, xdustinface requested changes
Two nits see comments, and a question: 

Wouldn't it be better to just return a JSON object instead of different data depending on parameter? Like 

```
{
    "txid" : "...", 
    "hex" : "..."
}
```

I know it would make it a breaking change but those commands are probably anyway only used locally so far?

2020-11-27 10:41 UTC, xdustinface commented on src/rpc/rpcevo.cpp
> +            "protx register_fund \"collateralAddress\" \"ipAndPort\" \"ownerAddress\" \"operatorPubKey\" \"votingAddress\" operatorReward \"payoutAddress\" ( \"fundAddress\" submit )\n"
```suggestion
            "protx register_fund \"collateralAddress\" \"ipAndPort\" \"ownerAddress\" \"operatorPubKey\" \"votingAddress\" operatorReward \"payoutAddress\" ( \"fundAddress\" \"submit\" )\n"
```

2020-11-27 10:41 UTC, xdustinface commented on src/rpc/rpcevo.cpp
> +            "protx register \"collateralHash\" collateralIndex \"ipAndPort\" \"ownerAddress\" \"operatorPubKey\" \"votingAddress\" operatorReward \"payoutAddress\" ( \"feeSourceAddress\" submit )\n"
```suggestion
            "protx register \"collateralHash\" collateralIndex \"ipAndPort\" \"ownerAddress\" \"operatorPubKey\" \"votingAddress\" operatorReward \"payoutAddress\" ( \"feeSourceAddress\" \"submit\" )\n"
```

2020-11-27 13:17 UTC, UdjinM6 commented
Hmm.. So I just tried implementing it beec90dec4 and while it looks kind of cleaner code-wise it feels a bit awkward from a user perspective imo - you need txid only when you submit the tx (and you don't care about its hex here because why would you, it's gone already) and you only need hex when you don't submit the tx (because you need it to send the tx later and you don't care about txid in this case, can't query by the id while it's not in mempool or in the blockchain yet). So this kind of output is kind of excessive in both cases. Also, it's a common thing (for wallet/raw rpcs) to return txid when tx is sent and to return raw tx when it's not sent. I don't know, I'd rather keep it as is.

2020-11-27 13:57 UTC, xdustinface approved these changes
Ok right, there are also other commands returning either a hex string or json depending on parameter or fun like this so i guess its just ok how it is 👍  

utACK

2020-11-28 19:12 UTC, PastaPastaPasta commented on src/rpc/rpcevo.cpp
> +    bool fSubmit{true};
What's the benefit of doing this over `bool fSubmit = true`?

2020-11-28 19:14 UTC, PastaPastaPasta approved these changes
utACK, I like seeing the test :D

2020-11-28 19:14 UTC, merged