Use system default fixed pitch font for Console
dashpay/dash pull request #3831
Opened 2020-11-27 10:22 UTC by UdjinM6

We dropped the fixed pitch font usage in https://github.com/dashpay/dash/pull/3734/commits/5d2854c84999173e32127311dbbab0b1dd7750b2 because we thought that it was no longer used anyway. And it was true but it was a bug, not a feature :) The bug was introduced in https://github.com/dashpay/dash/pull/3555/commits/3f8023311b2186ec969ccdb1aae0636b0f7dca34 which ignored the fact that rpc Console actually _needs_ a fixed pitch font for commands and their output to look correctly and not like a mess. Also, Console has its own font size controls so applying app wide font settings doesn't help much here anyway.

| Before | After |
|-|-|
| <img width="975" alt="Screenshot 2020-11-27 at 13 16 25" src="https://user-images.githubusercontent.com/1935069/100438182-de7d5600-30b2-11eb-8922-a260b3af1749.png">|<img width="980" alt="Screenshot 2020-11-27 at 13 20 03" src="https://user-images.githubusercontent.com/1935069/100438523-4fbd0900-30b3-11eb-98fe-b69249048d10.png"> |

2020-11-27 11:52 UTC, xdustinface requested changes
I have no idea why, but d50dbd70e69c2d3cf7b4da1440872f0aa1e1325e does't have any impact on the console font here on my system (macOS 10.15.6) 🤔 Thoughts about the why?

However, 1c46f566bd523ea485d1226217eba08978a4bf3b gives me the same outcome like in your screenshots. But without f55c8379d63a560dae509923fb7d33d8cef3f262 its getting messed up by general font size changes (e.g. if you open settings) and e997c61433ae2af950dcbc20dadf57ecc7f7b5b2 is probably not really required but it rounds things up :D

2020-11-27 14:11 UTC, UdjinM6 commented
Cherry-picked all of them, seems to be working as expected on my machine too (macOS 10.14.6). Also added 64da0c4 to ensure we won't stuck in some crazy font size if settings or defaults are broken somehow.

2020-11-27 14:23 UTC, xdustinface approved these changes
ACK

2020-11-28 19:26 UTC, PastaPastaPasta approved these changes
ACK, works as expected. Unable to break it :D

2020-11-28 19:26 UTC, merged