rpc: GetRequiredPaymentsString should also add operator addresses
dashpay/dash pull request #3862
Opened 2020-12-09 14:13 UTC by UdjinM6

Based on #3861 atm

2020-12-12 06:58 UTC, PastaPastaPasta commented
Looks good overall, wanna write a test?

2020-12-22 21:54 UTC, thephez commented
> Looks good overall, wanna write a test?

:cricket: :cricket: :cricket: :smile:

2020-12-23 09:39 UTC, UdjinM6 commented
Done. Had to rebase to include `rpcmasternode.py` from recent changes.

2020-12-23 13:20 UTC, xdustinface requested changes
The changes in `MasternodeInfo` look like leftover and should probably be dropped or used somehow but currently they are not even assigned in `__init__`.

2020-12-23 13:20 UTC, xdustinface commented on test/functional/test_framework/test_framework.py
> +    def __init__(self, proTxHash, ownerAddr, votingAddr, pubKeyOperator, keyOperator, ipAndPort, operatorReward, operatorPayoutAddress, collateral_address, collateral_txid, collateral_vout):
```suggestion
    def __init__(self, proTxHash, ownerAddr, votingAddr, pubKeyOperator, keyOperator, collateral_address, collateral_txid, collateral_vout):
```

2020-12-23 13:20 UTC, xdustinface commented on test/functional/test_framework/test_framework.py
> +        self.mninfo.append(MasternodeInfo(proTxHash, ownerAddr, votingAddr, bls['public'], bls['secret'], ipAndPort, operatorReward, operatorPayoutAddress, address, txid, collateral_vout))
```suggestion
        self.mninfo.append(MasternodeInfo(proTxHash, ownerAddr, votingAddr, bls['public'], bls['secret'], address, txid, collateral_vout))
```

2020-12-23 15:55 UTC, xdustinface approved these changes
utACK

2020-12-23 23:23 UTC, PastaPastaPasta approved these changes
utACK

2020-12-23 23:24 UTC, merged