Backport bitcoin#10637 (partial)
dashpay/dash pull request #3878
Opened 2020-12-16 08:34 UTC by UdjinM6

This one is pretty complex, backported it commit-by-commit. It's partial because I omitted most of the changes in `CWallet::CreateTransaction` (see 5137de5, original commit https://github.com/bitcoin/bitcoin/pull/10637/commits/6a34ff5335786615771ca423134a484b04831c4e), so bnb is not actually used there atm and the main reason to backport it is simply to avoid future merge conflicts everywhere else.

2020-12-16 16:56 UTC, PastaPastaPasta requested changes
shouldn't f9509816be8dffdbfba85640e8108e4255b8b7a4 be called "More of 10637..."?

2020-12-16 16:56 UTC, PastaPastaPasta commented on src/script/sign.cpp
>  }
Shouldn't UpdateInput be above UpdateTransaction?

2020-12-16 21:50 UTC, PastaPastaPasta approved these changes
utACK

2020-12-17 12:43 UTC, xdustinface approved these changes
utACK

2020-12-18 17:43 UTC, merged