backport: bitcoin#11536 Rename account to label where appropriate
dashpay/dash pull request #3886
Opened 2020-12-18 01:44 UTC by xdustinface

2020-12-18 10:33 UTC, UdjinM6 commented
Would probably make sense to backport it together with https://github.com/bitcoin/bitcoin/pull/12892 and https://github.com/bitcoin/bitcoin/pull/13060.

2020-12-18 15:42 UTC, UdjinM6 requested changes

2020-12-18 15:42 UTC, UdjinM6 commented on src/rpc/client.cpp
> +    { "getreceivedbylabel", 2, "addlocked" },
```suggestion
    { "getreceivedbylabel", 1, "minconf" },
    { "getreceivedbylabel", 2, "addlocked" },
```

2020-12-18 19:42 UTC, xdustinface commented on src/rpc/client.cpp
> +    { "getreceivedbylabel", 2, "addlocked" },
Fixed and squashed

2020-12-18 20:58 UTC, UdjinM6 requested changes
`test/functional/wallet_listtransactions.py` is empty (`git mv` went wrong it seems) + see below

2020-12-18 20:58 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> +            "                     The selected account, or \"*\" for entire wallet. It may be the default account using \"\".\n"
It looks like all the params should be marked as deprecated, see https://github.com/bitcoin/bitcoin/pull/12953/files#diff-63c7710d72381cffe692175dd70e47f1891bf75c3e09249ed826f9df3917d02dR870

2020-12-18 20:58 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> +            "\nSend multiple times. Amounts are double-precision floating point numbers."
missing https://github.com/bitcoin/bitcoin/pull/12953/files#diff-63c7710d72381cffe692175dd70e47f1891bf75c3e09249ed826f9df3917d02dR1093-R1094

2020-12-18 20:58 UTC, UdjinM6 commented on test/functional/wallet_import_rescan.py
> +        self.add_nodes(self.num_nodes, stderr=sys.stdout)
```suggestion
        self.add_nodes(self.num_nodes, extra_args=extra_args, stderr=sys.stdout)
```

2020-12-18 22:52 UTC, xdustinface commented
@UdjinM6 Good findings 👍 _Should_ have fixed/squashed them all now and `wallet_listtransactions.py` content is back and adjusted with the changes of bitcoin#13075.

2020-12-19 06:41 UTC, UdjinM6 requested changes
Recent changes looks good 👍 however it looks like we need more backports to fix some issues introduced in already backported ones, at least https://github.com/bitcoin/bitcoin/pull/13498, https://github.com/bitcoin/bitcoin/pull/13566, https://github.com/bitcoin/bitcoin/pull/13130 and https://github.com/bitcoin/bitcoin/pull/14441.

2020-12-22 03:19 UTC, xdustinface commented
@UdjinM6 Added the ones you mentioned. Will squash 692830b and 74a3513 into 9a3d528 before merge if someone prefers it, just left it out there yet for reviewing.

2020-12-22 16:32 UTC, UdjinM6 requested changes
Looks good 👍 A couple of minor issues, see below.

2020-12-22 16:32 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> +    if (request.fHelp || (request.params.size() > 4 ))
```suggestion
    if (request.fHelp || (request.params.size() > 4))
```

2020-12-22 16:32 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
>      { "wallet",             "getbalance",                       &getbalance,                    {"account","minconf","addlocked","include_watchonly"} },
```suggestion
    { "wallet",             "getbalance",                       &getbalance,                    {"account|dummy","minconf","addlocked","include_watchonly"} },
```
https://github.com/bitcoin/bitcoin/pull/13566/files#diff-63c7710d72381cffe692175dd70e47f1891bf75c3e09249ed826f9df3917d02dR4426

2020-12-22 16:59 UTC, xdustinface commented on src/rpc/client.cpp
> +    { "listreceivedbylabel", 1, "addlocked" },
Squashed into 1914effbbb5316ecf933fd24809eae0e67f3d419

2020-12-22 17:00 UTC, xdustinface commented on test/functional/wallet_txn_doublespend.py
> +        # Create two spends using 1 50 BTC coin each
Squashed into 42a98b0bc81dea90280c1dc07780bedd7fc18157

2020-12-22 17:00 UTC, xdustinface commented on src/wallet/rpcwallet.cpp
>      { "wallet",             "getbalance",                       &getbalance,                    {"account","minconf","addlocked","include_watchonly"} },
Squashed into 341b5a9714200b69cef3d66056605bcefef93e54

2020-12-22 17:00 UTC, xdustinface commented on src/wallet/rpcwallet.cpp
> +    if (request.fHelp || (request.params.size() > 4 ))
Squashed into 341b5a9714200b69cef3d66056605bcefef93e54

2020-12-22 17:01 UTC, xdustinface commented
> A couple of minor issues, see below.

Squashed them all into the related commits 👍

2020-12-22 17:59 UTC, UdjinM6 approved these changes
LGTM

utACK

2020-12-23 23:49 UTC, PastaPastaPasta requested changes
Please backport #14411 instead of #14441

Instead of backporting a backport, you should always backport the original PR instead, this makes life easier in the future.

(Probably fine to just change name it doesn't look like there's a diff)

2020-12-28 12:12 UTC, UdjinM6 commented
> Please backport bitcoin#14411 instead of bitcoin#14441

Unlike other backports, 14441 is more like a standalone fix because the changes to `src/wallet/rpcwallet.cpp` are significantly different from 14411 - it basically backports the idea, not the code. Backporting 14411 would require backporting many more PRs from 0.18 to merge cleanly it seems and it's probably why it was done this way in btc. I would propose to keep it as is and instead revert 96d3063 once we get to related 0.18 PRs later.

2020-12-30 19:37 UTC, PastaPastaPasta commented
Ahh, gotcha, didn't realize that :+1:

2020-12-30 19:38 UTC, PastaPastaPasta approved these changes
utACK

2020-12-30 19:38 UTC, merged