core: add dash-config.h only if macro is defined
dashpay/dash pull request #3888
Opened 2020-12-19 16:36 UTC by kittywhiskers

2020-12-19 21:25 UTC, UdjinM6 requested changes
Good catch! 👍 

I changed the branch to `develop` to make it mergeable (we don't merge into `master`). Also, the original `include` was broken actually 🙈 we need to fix it too, not just wrap it with `#if`/`#endif`, pls see a suggestion below.

2020-12-19 21:25 UTC, UdjinM6 commented on src/stacktraces.cpp
> +#include <dash-config.h>
```suggestion
#include <config/dash-config.h>
```

2020-12-20 13:17 UTC, kittywhiskers commented
Glad I could help 👍 

I'll keep the `develop` base branch in mind, I was trying to build Dash using CMake and needed to build it without header generation, so I didn't notice that, my bad!

2020-12-20 23:37 UTC, UdjinM6 approved these changes
utACK

2020-12-21 15:43 UTC, xdustinface approved these changes
utACK

2020-12-21 21:24 UTC, PastaPastaPasta approved these changes
utACK

2020-12-21 21:24 UTC, merged

2020-12-21 21:25 UTC, PastaPastaPasta commented
@kittywhiskers Thanks very much for this PR!

If you have a dash address I'd be glad to send over a tip for this. 

Looking forward to maybe future PRs :D

2020-12-23 15:15 UTC, kittywhiskers commented
Glad to have helped!