Consensus: DIP-0020: Dash opcode updates. Remaining dip0020 opcodes
dashpay/dash pull request #3893
Opened 2020-12-21 13:09 UTC by tomthoros

As CAT/SPLIT were added, the rest of the opcodes brought out in https://github.com/dashpay/dips/blob/master/dip-0020.md had to follow.

Currently missing script tests for checkdatasig opcodes. The ones added in the reference implementation https://reviews.bitcoinabc.org/D1621 don't work out of the box, seemingly because some changes in the signature format. I will add them when I figure out how they work. Also the unit tests for other opodes have been omitted, but I will reevaluate what may be useful to include.

2020-12-28 18:47 UTC, tomthoros commented
OP_LEFT and OP_RIGHT are removed and their opcodes are now assigned to OP_NUM2BIN = 0x80 and OP_BIN2NUM = 0x81. The functionality of OP_LEFT and OP_RIGHT was replaced by OP_SPLIT.

Unit tests are again omitted like before as they pretty much check the same stuff as the script tests. But I don't have a strong opinion in here though, as long as everything is covered by tests.

Also using the same activation mechanism as before.

2020-12-29 17:09 UTC, UdjinM6 commented
Looks good overall 👍 I would probably extend json data with some edge cases from cpp unit tests e.g. smth like https://github.com/UdjinM6/dash/commit/3314de68e875e6cc4dea361638d6025704530227#diff-ef0159635ee0fee8864cd9570a04337cabb63e9c49a9e96d7b746194ecaa427dR936-R941 etc. and move other re-enabled opcode checks to where they belong to like https://github.com/UdjinM6/dash/commit/3314de68e875e6cc4dea361638d6025704530227#diff-ef0159635ee0fee8864cd9570a04337cabb63e9c49a9e96d7b746194ecaa427dL914 -> https://github.com/UdjinM6/dash/commit/3314de68e875e6cc4dea361638d6025704530227#diff-ef0159635ee0fee8864cd9570a04337cabb63e9c49a9e96d7b746194ecaa427dR927 like we did for SPLIT and CAT earlier.

2021-01-04 10:34 UTC, tomthoros commented
It was easier for me to just add the unit tests than to try to (re)write the tests to json. I guess extra testing doesn't hurt too much?

2021-01-06 22:55 UTC, UdjinM6 reviewed
>It was easier for me to just add the unit tests than to try to (re)write the tests to json. I guess extra testing doesn't hurt too much?

Yeah, I was hoping to keep script tests data in one place but it looks like we can't really do this because of some test data being generated on the fly... ok, I guess having some extra won't make much difference in this case, let's keep it as is.

Well, just one tiny issue then, otherwise looks good imo 👍

2021-01-07 10:28 UTC, UdjinM6 submitted a review, later dismissed
LGTM, utACK 👍

2021-01-11 00:36 UTC, xdustinface approved these changes
utACK 👍

2021-01-11 05:40 UTC, PastaPastaPasta requested changes
See comments, primarily nits, formatting, comments

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/script/interpreter.cpp
> +bool BaseSignatureChecker::VerifySignature(const std::vector<uint8_t> &vchSig, const CPubKey &pubkey, const uint256 &sighash) const {
{ should be on new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/script/script.cpp
> +                                    const size_t nMaxNumSize) {
We normally have this on one line, I'd probably want to keep it that way, also { on new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/script/script.cpp
> +    // If we the whole thing is zeros, then we have a zero.
Doesn't make sense

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/script/script.cpp
> +                // We found a byte with it sign bit set so we need one more
I think
```suggestion
                // We found a byte with its sign bit set so we need one more
```

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/script/script.cpp
> +    // If the next byte has it sign bit set, then we are minimaly encoded.
```suggestion
    // If the next byte has its sign bit set, then we are minimally encoded.
```

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/script/interpreter.cpp
> +                    // byte requested.
```suggestion
                    // Try to see if we can fit that number in the number of
                    // bytes requested.
```

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/script_tests.cpp
> +    std::vector<uint8_t> DoSignECDSA(const CKey &key, const uint256 &hash, unsigned int lenR = 32, unsigned int lenS = 32) const {
don't change `{`

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/script_tests.cpp
> +    TestBuilder& PushDataSig(const CKey &key, const std::vector<uint8_t> &data, unsigned int lenR = 32, unsigned int lenS = 32) {
{ second line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/script_tests.cpp
> +    TestBuilder& Push(const uint256& hash) {
{ second line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/script/script.cpp
> +bool CScriptNum::MinimallyEncode(std::vector<uint8_t> &data) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                       const CScript &script, ScriptError expected) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                      const CScript &script, const stacktype &expected) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                                       const stacktype &expected) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                                  const CScript &script, ScriptError expected) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                       const stacktype &expected) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                       const CScript &script, ScriptError expected_error) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                  ScriptError expected_error) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                         ScriptError expected_error) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                    ScriptError expected_error) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                          const valtype &expected) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +static valtype NegativeValtype(const valtype &v) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                        const valtype &expected_xor) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                             const valtype &expected_xor) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                               const valtype &expected_or) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                          const valtype &n) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +static void CheckTypeConversionOp(const valtype &bin, const valtype &num) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                              ScriptError expected_error) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                              ScriptError expected_error) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                        const valtype &modExpected) {
{ new line

2021-01-11 05:40 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                             ScriptError expected_error) {
{ new line

2021-01-11 08:49 UTC, tomthoros commented
Updated formatting, I think i got them all.

2021-01-11 11:55 UTC, UdjinM6 approved these changes
utACK

2021-01-11 12:21 UTC, xdustinface approved these changes
utACK

2021-01-11 17:24 UTC, PastaPastaPasta requested changes
Sorry, more formatting stuff!

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/script/interpreter.cpp
> +bool BaseSignatureChecker::VerifySignature(const std::vector<uint8_t> &vchSig, const CPubKey &pubkey, const uint256 &sighash) const
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/script/interpreter.h
> +    virtual bool VerifySignature(const std::vector<uint8_t> &vchSig, const CPubKey &vchPubKey, const uint256 &sighash) const;
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/script/script.cpp
> +bool CScriptNum::IsMinimallyEncoded(const std::vector<uint8_t> &vch, const size_t nMaxNumSize)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/script/script.cpp
> +bool CScriptNum::MinimallyEncode(std::vector<uint8_t> &data)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/script/script.h
> +    inline CScriptNum operator%(const CScriptNum &rhs)    const { return operator%(rhs.m_value);    }
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                       const CScript &script, ScriptError expected)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                      const CScript &script, const stacktype &expected)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                                       const stacktype &expected)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/checkdatasig_tests.cpp
> +                                  const CScript &script, ScriptError expected)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                       const stacktype &expected)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                       const CScript &script, ScriptError expected_error)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                  ScriptError expected_error)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                         ScriptError expected_error)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                    ScriptError expected_error)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                          const valtype &expected)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                        const valtype &expected_xor)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                                             const valtype &expected_xor)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                               const valtype &expected_or)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +static void CheckStringOp(const valtype &a, const valtype &b, const valtype &n)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +static void CheckTypeConversionOp(const valtype &bin, const valtype &num)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/dip0020opcodes_tests.cpp
> +                        const valtype &modExpected)
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/script_tests.cpp
> +    std::vector<uint8_t> DoSignECDSA(const CKey &key, const uint256 &hash, unsigned int lenR = 32, unsigned int lenS = 32) const
align references to the left, see developer-notes.md

2021-01-11 17:24 UTC, PastaPastaPasta commented on src/test/script_tests.cpp
> +    TestBuilder& PushDataSig(const CKey &key, const std::vector<uint8_t> &data, unsigned int lenR = 32, unsigned int lenS = 32)
align references to the left, see developer-notes.md

2021-01-12 21:44 UTC, xdustinface requested changes
@tomthoros Looks like you change some unrelated ones also, see below.

2021-01-12 21:44 UTC, xdustinface commented on src/script/interpreter.h
> +bool CheckSignatureEncoding(const std::vector<unsigned char>& vchSig, unsigned int flags, ScriptError* serror);
```suggestion
bool CheckSignatureEncoding(const std::vector<unsigned char> &vchSig, unsigned int flags, ScriptError* serror);
```

2021-01-12 21:44 UTC, xdustinface commented on src/script/interpreter.h
> +uint256 SignatureHash(const CScript& scriptCode, const CTransaction& txTo, unsigned int nIn, int nHashType, const CAmount& amount, SigVersion sigversion, const PrecomputedTransactionData* cache = nul
```suggestion
uint256 SignatureHash(const CScript &scriptCode, const CTransaction& txTo, unsigned int nIn, int nHashType, const CAmount& amount, SigVersion sigversion, const PrecomputedTransactionData* cache = nullptr);
```

2021-01-12 21:44 UTC, xdustinface commented on src/test/script_tests.cpp
> +sign_multisig(CScript scriptPubKey, const CKey& key, CTransaction transaction)
```suggestion
sign_multisig(CScript scriptPubKey, const CKey &key, CTransaction transaction)
```

2021-01-12 21:48 UTC, xdustinface approved these changes
utACK

2021-01-12 21:49 UTC, tomthoros commented
Whoops got carried away I guess. I see there is some tool to help with formatting, clang-format-diffpy. Haven't tried, but does that format references and brackets, etc as well?

2021-01-12 23:22 UTC, UdjinM6 approved these changes
utACK

2021-01-13 20:44 UTC, PastaPastaPasta approved these changes
utACK

2021-01-13 20:45 UTC, merged