rpc: Introduce `verifyislock`
dashpay/dash pull request #3906
Opened 2020-12-28 23:12 UTC by UdjinM6

2021-01-05 00:11 UTC, xdustinface requested changes
I guess referenced commit in description was meant to be 592238faf9e87d94ad62a40d88973d55f08295bc instead of 91905ce? I would say this should be either mentioned in the title, moved to a seperate PR or we merge this PR without squashing?

Also see one suggestion below

2021-01-05 00:11 UTC, xdustinface commented on test/functional/rpc_verifyislock.py
> +        tx.rehash()
```suggestion
```

Could be dropped, hash is not really needed here.

2021-01-06 04:09 UTC, xdustinface requested changes
The two below can also be dropped

2021-01-06 04:09 UTC, xdustinface commented on test/functional/rpc_verifyislock.py
> +        inputs = []
```suggestion
```

2021-01-06 04:09 UTC, xdustinface commented on test/functional/rpc_verifyislock.py
> +            inputs.append(txin.prevout)
```suggestion
```

2021-01-08 19:53 UTC, UdjinM6 commented
Rebased, `auto->int` for `signOffset`, squashed.

2021-01-08 20:11 UTC, xdustinface approved these changes
utACK

2021-01-11 03:59 UTC, PastaPastaPasta requested changes

2021-01-11 03:59 UTC, PastaPastaPasta commented on test/functional/rpc_verifyislock.py
> +# Copyright (c) 2015-2020 The Dash Core developers
```suggestion
# Copyright (c) 2020 The Dash Core developers
```

2021-01-11 12:29 UTC, xdustinface approved these changes
utACK. I honestly don't have a very strong opinion about those copyright years so im good with 2020 (because it was implemented there?).. but shouldn't we use 2021 or at least "2020-2021" now to be accurate? :D

2021-01-11 17:13 UTC, PastaPastaPasta approved these changes
utACK

2021-01-11 17:13 UTC, merged