Adjust version formatting and add formatted version to rpc
dashpay/dash pull request #3908
Opened 2020-12-31 02:00 UTC by PastaPastaPasta

see commits

2021-01-01 21:20 UTC, UdjinM6 requested changes
Unit tests fail + see below

2021-01-04 13:45 UTC, thephez commented on src/rpc/net.cpp
> +            "  \"subversion\": \"/Dash Core:x.x.x/\",   (string) the server subversion string\n"
:+1: I like `buildversion` as well

2021-01-11 03:53 UTC, PastaPastaPasta commented
adjusted tests

2021-01-11 11:11 UTC, UdjinM6 commented
>adjusted tests

👀 

Are you sure?

2021-01-11 17:14 UTC, PastaPastaPasta commented
Gaaah, I hate it when I forget to push :D

2021-01-11 18:55 UTC, UdjinM6 approved these changes
ACK

2021-01-11 19:34 UTC, xdustinface approved these changes
utACK

2021-01-11 19:34 UTC, merged