tests: Test all rpc commands in rpc_platform_filter.py
dashpay/dash pull request #3913
Opened 2021-01-06 16:04 UTC by UdjinM6

2021-01-07 03:09 UTC, xdustinface requested changes
Looks good, just two nits below.

2021-01-07 03:09 UTC, xdustinface commented on test/functional/rpc_platform_filter.py
> +            if command != "stop": # avoid stoping the node while testing
```suggestion
            if command != "stop":  # avoid stoping the node while testing
```
Just a python thing

2021-01-07 03:15 UTC, xdustinface approved these changes
utACK

2021-01-08 19:43 UTC, PastaPastaPasta approved these changes
utACK

2021-01-08 19:43 UTC, merged