llmq|rpc|test: Fix "quorumHash" parameter of "quorum sign"
dashpay/dash pull request #3914
Opened 2021-01-06 16:53 UTC by xdustinface

The current implementation just always returns `true` no matter if the signing already happened or if the MN is not even a member of the provided quorum. This PR fixes this by just adjusting `AsyncSignIfMember` and using it for both cases: `quorumHash` provided or not.

2021-01-06 19:43 UTC, UdjinM6 requested changes
Hmm.. not sure about 0d71e77... I think it introduces a race condition where 2 threads can sign 2 conflicting messages, no? Would need smth like a patch in the suggestion below or maybe 06c7ecad5e (and then https://github.com/dashpay/dash/commit/f7fc6cb722d03b137e04d18a56977f2b104a0d89?w=1 on top of it to make things a bit clearer).

2021-01-06 23:14 UTC, xdustinface commented
@UdjinM6 Good catch 👍 I dropped it and added aff420b instead.

2021-01-07 00:54 UTC, UdjinM6 approved these changes
utACK

2021-01-11 04:07 UTC, PastaPastaPasta commented
Needs rebase

2021-01-11 13:27 UTC, UdjinM6 approved these changes
utACK

2021-01-11 17:17 UTC, PastaPastaPasta approved these changes
utACK

2021-01-11 17:17 UTC, merged