random: backport bitcoin 0.17 random changes, apply them to dash-specific logic
dashpay/dash pull request #3923
Opened 2021-01-09 18:12 UTC by kittywhiskers

## Overview

`std::random_shuffle` has been deprecated and Bitcoin has opted to implement an alternative to `std::shuffle` for `FastRandomContext` due to a bug specific to `libstdc++` named `Shuffle`. 

Unlike `std::random_shuffle`, `std::shuffle` does not accept only two arguments so those invocations now use `FastRandomContext`.

Replicating the commit would only implement changes to Bitcoin-derived logic while leaving Dash-specific logic using the deprecated call, changes have been made for LLMQ, Governance and Privatesend accordingly.

## Disclosure

Dash-specific changes have not been tested, only compilation has been ensured. Running the client on (a) testnet may be necessary.

## Resources

* https://github.com/bitcoin/bitcoin/commit/3db746beb407f7cdd9cd6a605a195bef1254b4c0 (Introduce a Shuffle for FastRandomContext and use it in wallet and coinselection, Dec 13, 2018 by sipa)
* https://en.cppreference.com/w/cpp/algorithm/random_shuffle 
* https://stackoverflow.com/questions/22915325/avoiding-self-assignment-in-stdshuffle (mentioned in sipa's commit)

2021-01-10 03:12 UTC, UdjinM6 requested changes
Thanks for looking into it 👍 Those `random_shuffle` deprecation warnings on compilation are pretty annoying and concerning indeed.

Few thoughts/suggestions:
- The original commit was included into btc 0.18 and was not backported to 0.17 afaik. Are there any real issues or is it simply to fix compilation warnings/make it C++17 compatible?
- PR title should say smth like `Partial merge bitcoin#14624: Some simple improvements to the RNG code` (makes it easier to track backported PRs in `git log`)
- see below

2021-01-10 03:39 UTC, kittywhiskers commented
I was attempting to have Dash compile with Apple Clang and it wasn't happy with the deprecated references. PR title has been changed, changes have been made!

Thanks!

2021-01-10 11:45 UTC, xdustinface commented on src/bench/bls.cpp
> +
```suggestion

```

Just to make the linter happy :)

2021-01-10 12:36 UTC, UdjinM6 commented
>I was attempting to have Dash compile with Apple Clang and it wasn't happy with the deprecated references.

Does it fail to compile or does it simply complain via warnings (but succeeds otherwise)? Cause I'm on mac too (macOS 10.14.6, Apple clang version 11.0.0) and it compiles just fine for me.

2021-01-10 13:16 UTC, kittywhiskers commented
```
governance/governance.cpp:1023:10: error: 'random_shuffle<std::__1::__wrap_iter<uint256 *>, FastRandomContext &>' is deprecated [-Werror,-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:3116:1: note: 'random_shuffle<std::__1::__wrap_iter<uint256 *>, FastRandomContext &>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX14 void
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1036:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX14'
#  define _LIBCPP_DEPRECATED_IN_CXX14 _LIBCPP_DEPRECATED
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1019:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
```

I'm using `clang-1200.0.32.28` (shipped with Xcode) on macOS Catalina 10.15.7

2021-01-10 13:23 UTC, UdjinM6 approved these changes
Interesting. Makes sense to fix it then I guess.

utACK

2021-01-11 00:55 UTC, xdustinface approved these changes
utACK, nice that those deprecation warning will be gone now :)

2021-01-14 19:45 UTC, PastaPastaPasta approved these changes
utACK. Be aware, your contribution may be worthy of a bounty https://trello.com/c/dbkj327J/86-dash-core-contributions

2021-01-14 19:46 UTC, merged