More accurate handling of the BLOCK_CONFLICT_CHAINLOCK flag
dashpay/dash pull request #3924
Opened 2021-01-11 01:37 UTC by UdjinM6

There is an inconsistency in the way we handle conflicting blocks atm - we add blocks to the block index as conflicting in `AcceptBlockHeader` but we mark re-orged blocks as invalid in `EnforceBestChainLock`. Because of the latter, it works most of the time despite the fact that some logic for conflicting blocks is actually missing. This PR should fix it by always sticking to the `BLOCK_CONFLICT_CHAINLOCK` flag for conflicting blocks and implementing all the required logic around it.

2021-01-11 13:51 UTC, thephez commented on test/functional/feature_llmq_chainlocks.py
> +        self.log.info("Restart it so that it forgets all the chainlocks messages from the past")
```suggestion
        self.log.info("Restart it so that it forgets all the chainlock messages from the past")
```

2021-01-14 19:47 UTC, PastaPastaPasta requested changes
Can you introduce a regression test for this?

2021-01-15 12:57 UTC, xdustinface requested changes
Looks good, just one potential change see below

2021-01-15 12:57 UTC, xdustinface commented on src/validation.cpp
>              if (it->second->IsValid(BLOCK_VALID_TRANSACTIONS) && it->second->nChainTx && setBlockIndexCandidates.value_comp()(chainActive.Tip(), it->second)) {
```suggestion
            if (it->second->IsValid(BLOCK_VALID_TRANSACTIONS) && !(it->second->nStatus & BLOCK_CONFLICT_CHAINLOCK) && it->second->nChainTx && setBlockIndexCandidates.value_comp()(chainActive.Tip(), it->second)) {
```

Maybe, to align with the other similar checks?

2021-01-15 12:57 UTC, xdustinface commented on src/validation.cpp
> +                }
```suggestion
                setBlockIndexCandidates.insert(it->second);
```

2021-01-15 16:57 UTC, xdustinface approved these changes
utACK

2021-01-16 19:46 UTC, PastaPastaPasta approved these changes
utACK

2021-01-16 19:47 UTC, merged