wallet: Upgrade path for non-HD wallets to HD (alternative)
dashpay/dash pull request #3933
Opened 2021-01-14 18:16 UTC by UdjinM6

This PR is an alternative attempt to fix #3740. It borrows some ideas and code snippets from #3932 (thanks @KolbyML! 👍 ) but it takes a step back to refactor things first and then uses these results to actually fix the issue, specifically:
a) move an already existing code around to ensure data consistency (9ed6a18) and split responsibility for different steps/paths of generating a HD wallet (b3066e7),
b) implement missing wallet functionality for generating an encrypted HD chain in an encrypted wallet (4c8797c) - `GenerateNewHDChainEncrypted` - which not only covers the non-HD->HD upgrade path but can also be used later to replace one encrypted HD chain with another (just like `GenerateNewHDChain` can be used for non-encrypted wallets),
c) implement a different version (comparing to #3932) of the `upgradetohd` rpc (fe54252) which uses (a) and (b) instead of pulling wallet/bip39 logic into `rpcwallet.cpp` and utilises `SetMnemonic` implementation details (empty mnemonic == generate a new random one) to simplify rpc interface.

2021-01-14 19:08 UTC, KolbyML commented
Great PR, I think I can learn a lot from this. A lot of what you did I didn't even think of or didn't even come to mind. Somethings I could have probably read the code better to get a better understanding of what I was working with. Like for example the comment above NewKeyPool I didn't even notice till now. So I think I can use a lot of the differences between the PR and improve my code/PR's in the future. Thank you for the insight.

2021-01-16 20:02 UTC, PastaPastaPasta commented on src/wallet/wallet.cpp
> +            if(gArgs.IsArgSet("-hdseed") && IsHex(strSeed)) {
```suggestion
            if (gArgs.IsArgSet("-hdseed") && IsHex(strSeed)) {
```

2021-01-17 17:13 UTC, UdjinM6 commented
Tests are expected to fail without https://github.com/dashpay/dash/pull/3944

2021-01-21 00:25 UTC, UdjinM6 commented
Rebased

2021-01-23 11:17 UTC, xdustinface requested changes
Looks good, just some nits below :)

2021-01-23 11:17 UTC, xdustinface commented on src/wallet/rpcwallet.cpp
> +    CWallet * const pwallet = GetWalletForJSONRPCRequest(request);
```suggestion
    CWallet* const pwallet = GetWalletForJSONRPCRequest(request);
```

2021-01-23 16:37 UTC, xdustinface approved these changes
utACK

2021-01-25 03:03 UTC, PastaPastaPasta approved these changes
utACK

2021-01-25 03:03 UTC, merged