chainlocks: Rely more on clsigs with known blocks instead of pure clsigs
dashpay/dash pull request #3978
Opened 2021-02-03 00:47 UTC by UdjinM6

A malicious quorum can sign a clsig with some (random) hash and some future height, up to `tip + SIGN_HEIGHT_OFFSET` (anything above it won't pass `VerifyRecoveredSig`/`SelectQuorumForSigning`, see tests for `fake_clsig2`). Such a clsig not only does not lock the chain but it also prevents new clsigs (for heights up to that future one) from forming or being accepted, see tests for `fake_clsig3` (fails without b010bc9). Chances to form such a quorum are close to 0 e.g. 1.29e-38 if you control 1500 MNs (see `Success probability of creating a malicious ChainLock` [here](https://github.com/dashpay/dips/blob/master/dip-0008.md#calculations) for more info), so it's not a critical issue by any means but I feel like it still makes sense to reduce any potential impact of such an event when possible.

Note: the issue is only for _future_ clsigs, the best clsig with a known block is not affected, no reorgs _below_ the already locked block are possible.

2021-02-10 00:28 UTC, xdustinface requested changes
Good catch! 👍 See [suggestions-3978](https://github.com/xdustinface/dash/tree/suggestions-3978) for a few potential (trivial) tweaks in the test. In any case it looks like we need a rebase here after #3976 before an approval (if we merge that one first).

2021-02-10 00:28 UTC, xdustinface commented on src/llmq/quorums_chainlocks.cpp
> +                      __func__, clsig.ToString(), bestChainLockWithKnownBlock.ToString(), from);
^

2021-02-15 10:10 UTC, UdjinM6 commented
Rebased

2021-02-15 10:17 UTC, xdustinface approved these changes
utACK

2021-02-17 07:40 UTC, PastaPastaPasta commented
I'm not sure how I feel about this... Really, I'd say this is the best case for a malicious chainlock. If someone forms a malicious chainlock, the best outcome is the chain halting, because that prevents any attacker from actually making any money or anything off of the attack.

2021-02-17 16:02 UTC, UdjinM6 commented
@PastaPastaPasta I don't understand... can you elaborate pls?

2021-03-23 17:28 UTC, closed without merging