docs: cli option help additions
dashpay/dash pull request #3981
Opened 2021-02-04 17:06 UTC by thephez

Adds help text for some options that were lacking it

2021-02-05 10:22 UTC, UdjinM6 approved these changes
utACK

2021-02-07 03:08 UTC, PastaPastaPasta approved these changes
utACK

2021-02-08 13:36 UTC, xdustinface requested changes
Looks good but all those `strprintf` calls can be dropped :)

2021-02-08 13:36 UTC, xdustinface commented on src/init.cpp
> +    strUsage += HelpMessageOpt("-llmqtestparams=<size:threshold>", strprintf(_("Override the default LLMQ size for the LLMQ_TEST quorum (default: 3:2)")));
```suggestion
    strUsage += HelpMessageOpt("-highsubsidyblocks=<n>", _("The number of blocks with a higher than normal subsidy to mine at the start of a devnet (default: 0)"));
    strUsage += HelpMessageOpt("-highsubsidyfactor=<n>", _("The factor to multiply the normal block subsidy by while in the highsubsidyblocks window of a devnet (default: 1)"));
    strUsage += HelpMessageOpt("-llmqchainlocks=<quorum name>", _("Override the default LLMQ type used for ChainLocks on a devnet. Allows using ChainLocks with smaller LLMQs. (default: llmq50_60)"));
    strUsage += HelpMessageOpt("-llmqdevnetparams=<size:threshold>", _("Override the default LLMQ size for the LLMQ_DEVNET quorum (default: 10:6)"));
    strUsage += HelpMessageOpt("-llmqinstantsend=<quorum name>", _("Override the default LLMQ type used for InstantSend on a devnet. Allows using InstantSend with smaller LLMQs. (default: llmq50_60)"));
    strUsage += HelpMessageOpt("-llmqtestparams=<size:threshold>", _("Override the default LLMQ size for the LLMQ_TEST quorum (default: 3:2)"));
```

2021-02-08 13:36 UTC, xdustinface commented on src/init.cpp
> +    strUsage += HelpMessageOpt("-minimumdifficultyblocks=<n>", strprintf(_("The number of blocks that can be mined with the minimum difficulty at the start of a devnet (default: 0)")));
```suggestion
    strUsage += HelpMessageOpt("-minimumdifficultyblocks=<n>", _("The number of blocks that can be mined with the minimum difficulty at the start of a devnet (default: 0)"));
```

2021-02-08 13:36 UTC, xdustinface commented on src/init.cpp
> +    strUsage += HelpMessageOpt("-sporkkey=<privatekey>", strprintf(_("Set the private key to be used for signing spork messages.")));
```suggestion
    strUsage += HelpMessageOpt("-sporkkey=<privatekey>", _("Set the private key to be used for signing spork messages."));
```

2021-02-08 14:09 UTC, xdustinface approved these changes
utACK

2021-02-08 15:35 UTC, UdjinM6 approved these changes
re-utACK

2021-02-11 16:22 UTC, PastaPastaPasta approved these changes
utACK

2021-02-11 16:22 UTC, merged