instantsend: Introduce KnownInstantSendLock, optimize ProcessInstantSendLock a bit
dashpay/dash pull request #3984
Opened 2021-02-06 12:14 UTC by UdjinM6

Please see individual commits.

Extracted from #3970, based on #3983 atm

2021-02-15 19:31 UTC, PastaPastaPasta commented on src/llmq/quorums_instantsend.cpp
> +        if (pendingInstantSendLocks.count(hash) || db.KnownInstantSendLock(hash)) {
why'd you add the `pendingInstantSendLocks.count(hash)` here?

2021-02-15 19:31 UTC, PastaPastaPasta commented on src/llmq/quorums_instantsend.cpp
> +        if (llmq::chainLocksHandler->HasChainLock(pindexMined->nHeight, pindexMined->GetBlockHash())) {
We should probably assert that pindexMined isn't null, though that's arguable outside of this PRs scope

2021-02-16 15:47 UTC, xdustinface requested changes
Looks good, but see comment below for one nit.

2021-02-16 15:47 UTC, xdustinface commented on src/llmq/quorums_instantsend.cpp
>          otherIsLock = db.GetInstantSendLockByTxid(islock->txid);
```suggestion
        CInstantSendLockPtr otherIsLock = db.GetInstantSendLockByTxid(islock->txid);
```

2021-02-16 15:55 UTC, xdustinface approved these changes
utACK

2021-02-17 07:08 UTC, PastaPastaPasta commented on src/llmq/quorums_instantsend.h
> +
extra line?
```suggestion
```

2021-02-17 09:17 UTC, xdustinface approved these changes
utACK

2021-02-17 15:59 UTC, PastaPastaPasta approved these changes
utACK

2021-02-17 15:59 UTC, merged