instantsend|sigs: Sleep when there is no more work
dashpay/dash pull request #3988
Opened 2021-02-06 12:38 UTC by UdjinM6

Instead of sleeping only when no work has been done. Avoids useless cycles, improves batching.

Extracted from #3970

2021-02-10 11:49 UTC, xdustinface requested changes
Makes sense, see [suggestions-3988](https://github.com/xdustinface/dash/commits/suggestions-3988) for some tweaks. I think 0db9da9e5c976a3db1e01b547f83d584e15f26bd is definitely required to be accurate if i didn't get it wrong, thoughts?

2021-02-10 14:31 UTC, UdjinM6 commented
Picked them all. Good catch re count vs size (0db9da9)! 👍

2021-02-10 14:40 UTC, xdustinface approved these changes
utACK

2021-02-11 16:32 UTC, PastaPastaPasta approved these changes
utACK

2021-02-11 16:32 UTC, merged