net: Use Intra-Quorum Relay connections for other messages too
dashpay/dash pull request #4021
Opened 2021-02-28 14:03 UTC by UdjinM6

Make intra-quorum data delivery more robust.

We stopped relaying this data (https://github.com/dashpay/dash/pull/3368) when we were preparing to implement Concentrated Recovery (https://github.com/dashpay/dash/pull/3389) one part of which was spork21 ("all connected" mode) (https://github.com/dashpay/dash/pull/3380) because relaying all the data via 50+ connections from each member to everyone else in the quorum at once could be wasteful potentially. But I _think_ it should still be fine for quorum masternodes to re-use a small subset (in case of "all connected" mode) of intra-quorum connections to relay the data inside quorums. Syncing via these connections should also be safe (unlike syncing via potentially short-living pure "masternode" connections). Not having to rely on non-maliciousness of (regular) nodes surrounding each quorum member is yet another good thing imo.

Thoughts?

Based on #4020 atm.

2021-03-26 17:33 UTC, xdustinface requested changes
Makes sense 👍 Please let me know your thoughts about the two comments below, i thought quite some time about it now but it seems to be tricky with all those flags involved 🙈

2021-03-27 02:13 UTC, xdustinface approved these changes
utACK

2021-03-29 18:13 UTC, PastaPastaPasta approved these changes
utACK, would be nice if there were tests around this

2021-03-29 19:54 UTC, thephez commented
@PastaPastaPasta  Sometimes I think you're using a template response message for PRs :smile: 
> ... would be nice if there were tests around this

2021-04-03 17:24 UTC, merged