partial merge #10785: serialization improvements
dashpay/dash pull request #4037
Opened 2021-03-10 06:31 UTC by kittywhiskers

## Overview

As part of https://github.com/dashpay/dash/pull/4025, component pull requests that are required by TorV3 logic are being broken down into branches wherever feasable. This PR deals with serialization improvements taken from https://github.com/bitcoin/bitcoin/pull/10785 (split into #17850, #17896, #17957, #18021, #18112 and others)

## Contents

* Partial merge of #17850 ("Serialization improvements (minimal initial commits)" by sipa)
  *  9250a087d2f450f37342010aea0a5d583eea508b has been skipped for the sake of brevity, not relevant to https://github.com/dashpay/dash/pull/4025
* Partial merge of #17896 ("Serialization improvements (step 2)" by sipa)
  * 9b66083788581c264a097e26795561cb3eac455d has been skipped for reasons mentioned above
* Partial merge of #17957 ("Serialization improvements step 3 (compression.h)" by sipa)
  * 4de934b9b5b4be1bac8fe205f4ee9a79e772dc34 has been skipped 
* Partial merge of #18021 ("Serialization improvements step 4 (undo.h)" by sipa)
  * 3c94b0039d2ca2a8c41fd6127ff5019a2afc304e is skipped
* Partial merge of #18112 ("Serialization improvements (minimal initial commits)" by sipa)
  * 353f376277ad9b87e03c9ccbc1028c4b6d12e8ea skpd

2021-03-10 17:27 UTC, UdjinM6 submitted a review, later dismissed
Not sure if I like skipping commits here, would be nice to finalize these backports while we are at it... But LGTM otherwise, so

utACK

2021-03-12 15:01 UTC, xdustinface requested changes
One nit see below and i also feel like we shouldn't just randomly skip commits while backporting PRs only because they are "not relevant". There is imo no good reason to only partially backport PRs if its possible to completely merge them in.. skipping parts of them just makes reviewing the PR as a whole a bit weird/confusing here and there imo and this even two times, now and when backporting the remaining parts.

2021-03-16 13:23 UTC, UdjinM6 requested changes

2021-03-16 17:04 UTC, kittywhiskers commented on src/chain.h
> +
Good catch. Resolved in cf52d88!

2021-03-17 01:48 UTC, UdjinM6 submitted a review, later dismissed
slightly tested ACK

2021-03-23 01:00 UTC, xdustinface submitted a review, later dismissed
utACK

2021-04-18 09:27 UTC, PastaPastaPasta commented
please resolve conflicts

2021-04-18 20:24 UTC, PastaPastaPasta commented
@UdjinM6 is this merge okay, or does it need to be a rebase?

2021-04-18 20:44 UTC, UdjinM6 commented
¯\\\_(ツ)_/¯

Personally, I'd prefer a rebase but technically this merge should be ok too I guess

2021-04-18 21:46 UTC, PastaPastaPasta commented
Yeah, I prefer rebase I think. @kittywhiskers please see https://github.com/PastaPastaPasta/dash/commits/pr_4027 I rebased on develop and squashed your commits

2021-05-05 22:31 UTC, kittywhiskers commented
Branch updated with @PastaPastaPasta's fork as-is

2021-05-06 03:04 UTC, PastaPastaPasta approved these changes
utACK, although should probably adjust title

2021-05-06 06:37 UTC, UdjinM6 approved these changes
utACK

2021-05-14 23:06 UTC, merged