partial/logic backport #18544: net: limit BIP37 filter lifespan (active between 'filterload'..'filterclear')
dashpay/dash pull request #4043
Opened 2021-03-15 17:19 UTC by UdjinM6

This backports https://github.com/bitcoin/bitcoin/pull/18544/commits/5eae034996b340c19cebab9efb6c89d20fe051ef
```
Previously, a default match-everything bloom filter was set for every peer,
i.e. even before receiving a 'filterload' message and after receiving a
'filterclear' message code branches checking for the existence of the filter
by testing the pointer "pfilter" were _always_ executed.
```

The original PR was merged into btc 0.21, so this "backports" logic, not code. Not backporting test changes because `p2p_filter.py` test simply does not exist in our code base yet, was introduced in btc 0.20.

This is required for #4016 (which is how I found the issue) but even otherwise it's an actual bugfix e.g. for node eviction logic https://github.com/dashpay/dash/blob/develop/src/net.cpp#L1119.

2021-03-17 23:58 UTC, PastaPastaPasta approved these changes
utACK

2021-03-18 23:50 UTC, xdustinface requested changes
Any reason why you didn't do more like in the backport PR? Like in  2d73cdfef8a3e4f05136fd3c675a509a891af1e8

2021-03-19 21:21 UTC, PastaPastaPasta approved these changes
utACK

2021-03-22 10:17 UTC, xdustinface approved these changes
utACK

2021-03-22 10:29 UTC, merged