backport: Some wallet related PRs
dashpay/dash pull request #4081
Opened 2021-04-04 03:33 UTC by xdustinface

This PR:
- Includes backports related to the `unloadwallet` RPC command and some fixes.
- Removes the "Restart requirement" from wallet encryption
- Fixes issue #3521
- Backports bitcoin#13506 which was already backported in #3877 but the recently merged #4076 revert it.gitlab

2021-04-04 19:28 UTC, UdjinM6 requested changes
pls see 77b5738eba, c3bff63839 and suggestions below

2021-04-04 19:28 UTC, UdjinM6 commented on src/wallet/db.cpp
> +                CheckUniqueFileid(env.second, strFilename, *pdb_temp, this->env->m_fileids[strFilename]);
this fix belongs to 85349ca1f763cb5360edcea431f02331323be195

2021-04-04 19:28 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> +        throw JSONRPCError(RPC_WALLET_ERROR, "Wallet " + location.GetName() + " already exists.");
this fix belongs to 8bb98a53373ddb20e6ec8b3a41c408b4e68c1d5d

2021-04-04 19:28 UTC, UdjinM6 commented on src/wallet/test/coinjoin_tests.cpp
> +        wallet = MakeUnique<CWallet>(WalletLocation(), WalletDatabase::CreateMock());
this fix belongs to 8bb98a53373ddb20e6ec8b3a41c408b4e68c1d5d

2021-04-04 19:28 UTC, UdjinM6 commented on src/wallet/test/wallet_tests.cpp
> +        wallet = MakeUnique<CWallet>(WalletLocation(), WalletDatabase::CreateMock());
this fix belongs to 8bb98a53373ddb20e6ec8b3a41c408b4e68c1d5d

2021-04-04 19:28 UTC, UdjinM6 commented on src/wallet/wallet.cpp
> +    std::unique_ptr<CWallet> tempWallet = MakeUnique<CWallet>(location, WalletDatabase::Create(wallet_path));
this fix belongs to 8bb98a53373ddb20e6ec8b3a41c408b4e68c1d5d

2021-04-05 01:48 UTC, xdustinface commented
@UdjinM6 Ops 😄 moved the fixes (including yours) into the correct commits

2021-04-05 13:21 UTC, thephez approved these changes
Slightly tested ACK.
Confirmed #3521 fixed and `unloadwallet` appeared to work.

2021-04-05 19:22 UTC, UdjinM6 approved these changes
Slightly tested ACK

2021-04-06 17:32 UTC, PastaPastaPasta approved these changes
utACK

2021-04-06 21:38 UTC, merged