qt: Apply themes globally
dashpay/dash pull request #4086
Opened 2021-04-08 08:48 UTC by UdjinM6

Not sure why we apply themes on a per-widget basis atm (and how/why doing so breaks styling in some cases)... This patch works just fine for me on mac and linux (and fixes comboboxes on mac).

2021-04-08 14:54 UTC, xdustinface requested changes
> Not sure why we apply themes on a per-widget basis atm

Me neither, good idea with the `qApp` 🙂 But two points:

- Currently this PR breaks custom css updates: d44579a9b203e8c56cd62e39b6d941f7b1efcb57
- The prompt icon now shows up in dash themes: e0c9b5a67bc9ca30d970aa87ff5c8a72c374752e

2021-04-08 18:00 UTC, UdjinM6 commented
Picked e0c9b5a (5ac7c5d) but how about 58fa3cb instead of d44579a?

2021-04-08 19:13 UTC, xdustinface approved these changes
> how about [58fa3cb](https://github.com/dashpay/dash/commit/58fa3cbbda8380a1ee49019e90d9d3093afef822) instead of [d44579a](https://github.com/dashpay/dash/commit/d44579a9b203e8c56cd62e39b6d941f7b1efcb57)?

Jup thats better 👍

Seems to be all good now, ACK

2021-04-10 20:31 UTC, PastaPastaPasta approved these changes
utACK

2021-04-10 20:31 UTC, merged