llmq/rpc: Adjust verify islock, don't err when transaction isn't known locally
dashpay/dash pull request #4106
Opened 2021-04-15 17:17 UTC by PastaPastaPasta

2021-04-15 18:34 UTC, UdjinM6 requested changes

2021-04-15 18:34 UTC, UdjinM6 commented on src/rpc/rpcquorums.cpp
> +            }
```suggestion
        if (GetTransaction(txid, tx, Params().GetConsensus(), hash_block, true) && !hash_block.IsNull()) {
            pindexMined = LookupBlockIndex(hash_block);
```

2021-04-15 22:26 UTC, xdustinface submitted a review, later dismissed
utACK

2021-04-15 23:07 UTC, UdjinM6 commented
Let's also add some tests to make sure it works as expected ;) https://github.com/UdjinM6/dash/commit/39cc45e7cfec161b50fda5f447cc1d8a1211993f

2021-04-16 09:37 UTC, UdjinM6 approved these changes
utACK

2021-04-16 15:03 UTC, xdustinface approved these changes
utACK

2021-04-16 15:03 UTC, merged