rpc|llmq|test: Implement `verifychainlock`
dashpay/dash pull request #4119
Opened 2021-04-23 16:08 UTC by xdustinface

Implements a wrapper for ChainLock verification similar to  `verifyislock` for InstantSend verification. This has been requested by the platform team.

2021-04-23 18:33 UTC, PastaPastaPasta submitted a review, later dismissed
utACK

2021-04-24 22:43 UTC, UdjinM6 requested changes

2021-04-24 22:43 UTC, UdjinM6 commented on src/rpc/rpcquorums.cpp
> +            "verifychainlock \"blockHash\" \"blockHeight\" \"signature\"\n"
```suggestion
            "verifychainlock \"blockHash\" \"signature\" ( blockHeight )\n"
```

2021-04-25 01:40 UTC, PastaPastaPasta approved these changes
utACk

2021-04-25 08:28 UTC, UdjinM6 approved these changes
utACK

2021-04-26 11:51 UTC, merged