refactor: Resolve a number of data races
dashpay/dash pull request #4122
Opened 2021-04-24 05:34 UTC by PastaPastaPasta

Was working around with `./configure --with-sanitizers=thread` and found data races around this. These locks / added cses resolved the issues. It might be overly broad or not broad enough :shrug:

2021-04-24 23:17 UTC, UdjinM6 requested changes

2021-04-24 23:17 UTC, UdjinM6 commented on src/masternode/masternode-sync.h
> +    CCriticalSection cs;
Let's maybe
```suggestion
    mutable CCriticalSection cs;
```
and bring back `const`s you dropped?

2021-04-25 00:34 UTC, UdjinM6 approved these changes
utACK

(dropped "refactor" from the title)

2021-04-25 16:14 UTC, UdjinM6 submitted a review, later dismissed
ok, unit tests failure (on mac) is related to some UB in ctor (cs internals aren't being fully initialized I think but I don't quite understand why tbh). f04ed6ad89 fixes it for me but there is a similar issue with CHDChain too it seems and I can only reproduce this on my mac 🤷‍♂️  It all looks unrelated to this specific PR, will submit patches in a separate PR.

re-utACK

2021-04-26 21:29 UTC, xdustinface requested changes
See 1db3471eb4ed95b2b6b837b5ede836701cf80c2b and 8a581a1dfece77b685b9f3bd5777196476117e5d

2021-04-28 14:38 UTC, xdustinface approved these changes
utACK

2021-04-28 17:36 UTC, UdjinM6 approved these changes
utACK

2021-04-28 18:15 UTC, merged