evo: Refactor (Add/Update/Remove)MNs to do the job in one go
dashpay/dash pull request #4132
Opened 2021-05-04 18:08 UTC by UdjinM6

Instead of hashing the value and querying `mnUniquePropertyMap` both 2 or 3 times per property.

Also unify their error messages while at it.

2021-05-04 22:06 UTC, xdustinface requested changes
Looks good, but lets maybe also add 35d2d944e9e752ae473db6c6914bceb36e137ba6?

2021-05-04 22:11 UTC, UdjinM6 commented
Good point! 👍 Added

2021-05-04 22:14 UTC, xdustinface approved these changes
utACK

2021-05-06 03:20 UTC, PastaPastaPasta approved these changes
utACK

2021-05-06 03:40 UTC, merged