Backport 13066, 13448 and fix `commit-script-check.sh` to make shellcheck 0.7.2 happy
dashpay/dash pull request #4138
Opened 2021-05-05 11:26 UTC by UdjinM6

Fixes `SC2268: Avoid x-prefix in comparisons as it no longer serves a purpose.`

https://github.com/koalaman/shellcheck/wiki/SC2268

2021-05-06 03:40 UTC, PastaPastaPasta requested changes

2021-05-06 03:40 UTC, PastaPastaPasta commented on contrib/verify-commits/allow-incorrect-sha512-commits
> +8040ae6fc576e9504186f2ae3ff2c8125de1095c
We shouldn't have these?

2021-05-06 03:40 UTC, PastaPastaPasta commented on contrib/verify-commits/allow-unclean-merge-commits
> +97d83739db0631be5d4ba86af3616014652c00ec
same

2021-05-10 16:40 UTC, PastaPastaPasta approved these changes
utACK

2021-05-11 16:54 UTC, xdustinface approved these changes
utACK

2021-05-11 16:54 UTC, merged