Backports 0.18 triv pr2
dashpay/dash pull request #4217
Opened 2021-06-27 20:38 UTC by PastaPastaPasta

Based on PR1 and haven't built yet

2021-06-28 23:58 UTC, UdjinM6 requested changes

2021-06-28 23:58 UTC, UdjinM6 commented on src/compat/assumptions.h
> +# error "Bitcoin cannot be compiled without assertions."
87cd2776e5d698822a7c88f574aa700e1ad65599:
```suggestion
# error "Dash Core cannot be compiled without assertions."
```

2021-06-29 00:09 UTC, PastaPastaPasta commented on src/compat/assumptions.h
> +# error "Bitcoin cannot be compiled without assertions."
Done https://github.com/dashpay/dash/compare/57572f45d40eab5388b0dff9751085cf205bbe4f..90fc61450047f81f2eb46d4d9ba57d48ad8457c9

2021-06-29 00:17 UTC, UdjinM6 reviewed
LGTM 👍  waiting for CI...

2021-06-29 09:15 UTC, UdjinM6 requested changes

2021-06-29 09:15 UTC, UdjinM6 commented on test/functional/wallet_basic.py
> +        assert_raises_rpc_error(-3, "Address does not refer to a key", self.nodes[0].dumpprivkey, temp_address)
```suggestion
        assert_raises_rpc_error(-4, "Private key for address %s is not known" % temp_address, self.nodes[0].dumpprivkey, temp_address)
```

2021-07-01 20:25 UTC, UdjinM6 approved these changes
utACK

2021-07-01 20:26 UTC, merged