Backports 0.18 pr5
dashpay/dash pull request #4224
Opened 2021-06-30 19:41 UTC by Munkybooty

2021-07-02 09:42 UTC, UdjinM6 requested changes

2021-07-02 09:42 UTC, UdjinM6 commented on src/txmempool.cpp
> +                setParentCheck.insert(it2);
(13767) this looks incomplete

2021-07-02 22:40 UTC, UdjinM6 commented
13767 is not ok: should not create `descriptor_tests.cpp` and some changes in `src/txmempool.cpp` are missing

2021-07-03 12:00 UTC, UdjinM6 approved these changes
utACK

2021-07-03 17:29 UTC, PastaPastaPasta commented on src/fs.h
> -    FILE *freopen(const fs::path& p, const char *mode, FILE *stream);
13159, why do we not need the changes in logging.cpp

2021-07-03 17:33 UTC, PastaPastaPasta approved these changes
utACK

2021-07-03 17:33 UTC, merged