backport: 'trivial' pr5
dashpay/dash pull request #4225
Opened 2021-07-01 22:12 UTC by PastaPastaPasta

2021-07-02 10:24 UTC, UdjinM6 requested changes

2021-07-02 10:24 UTC, UdjinM6 commented on src/qt/rpcconsole.cpp
> +                autoCompleter->popup()->hide();
(14450) this was fixed via https://github.com/dashpay/dash/pull/1898 already. If you want this to be merged purely to align code/history with bitcoin you should drop line 575.

2021-07-02 10:24 UTC, UdjinM6 commented on test/functional/feature_filelock.py
> +"""Check that it's not possible to start a second bitcoind instance using the same datadir or wallet."""
(14426) needs dashification here and below

2021-07-02 10:24 UTC, UdjinM6 commented on src/qt/test/addressbooktests.cpp
> +              "with 'test_bitcoin-qt -platform cocoa' on mac, or else use a linux or windows build.");
(14011) needs dashification

2021-07-03 17:39 UTC, PastaPastaPasta commented
Done

2021-07-03 21:07 UTC, UdjinM6 approved these changes
utACK

2021-07-03 21:07 UTC, merged