merge #14624, #20788, #16117, #21052, partial #16908, #14978: Auxillary Backports
dashpay/dash pull request #4229
Opened 2021-07-02 07:52 UTC by kittywhiskers

### Notes

bitcoin#20788 was originally having test failures and the lack of bitcoin#14624 was the cause. Tests run fine now.

2021-07-04 15:52 UTC, PastaPastaPasta commented
Windows build borked

2021-07-09 16:07 UTC, kittywhiskers commented
Rebased and updated

2021-07-09 17:11 UTC, PastaPastaPasta commented
Not compiling

2021-07-10 10:25 UTC, UdjinM6 requested changes
16908: missing changes in `test/functional/mempool_persist.py`
18358: see ebc239029c6e464c38cc1010755cfc387cef9a41
20788: lots of changes from other PRs

2021-07-10 10:25 UTC, UdjinM6 commented on src/net.cpp
> +                                        proxyConnectionFailed);
`proxyConnectionFailed` related changes are from 17754

2021-07-10 10:25 UTC, UdjinM6 commented on src/netbase.cpp
> + * @param timeout The total timeout in milliseconds for this read.
this is from some another PR

2021-07-10 10:25 UTC, UdjinM6 commented on src/netbase.cpp
> +                // we're approaching the end of the specified total timeout
same

2021-07-10 10:25 UTC, UdjinM6 commented on src/netbase.cpp
> + */
same

2021-07-10 10:25 UTC, UdjinM6 commented on src/netbase.cpp
> + */
same

2021-07-10 10:25 UTC, UdjinM6 commented on src/netbase.cpp
> +bool ConnectThroughProxy(const proxyType& proxy, const std::string& strDest, int port, const Sock& sock, int nTimeout, bool& outProxyConnectionFailed)
`*outProxyConnectionFailed` -> `&outProxyConnectionFailed` is from 17754

2021-07-13 09:50 UTC, kittywhiskers commented on src/util/time.h
> +
Merged in #18638

2021-07-13 16:50 UTC, PastaPastaPasta commented
functional tests borked

2021-07-15 17:57 UTC, kittywhiskers commented
Dunno what's happening with functional tests so #16908 has been slimmed to the bare essentials needed for successive commits

2021-07-16 00:35 UTC, PastaPastaPasta commented
Needs rebase

2021-07-17 00:20 UTC, PastaPastaPasta commented
Tests are failing

2021-07-28 16:12 UTC, PastaPastaPasta commented
Marking as WIP due to the fact this PR has stalled. Please rebase, and mark as ready for review when this PR is RfR

2021-08-05 14:17 UTC, kittywhiskers commented
Ready for review. Unrelated LLMQ tests failed

2021-08-05 15:42 UTC, PastaPastaPasta commented
Test failures in feature_llmq_data_recovery.py are persistent. Does not seem unrelated.

2021-08-05 15:50 UTC, kittywhiskers commented
> Test failures in feature_llmq_data_recovery.py are persistent. Does not seem unrelated.

Fixed, problem was isolated to 26599604e3739a37fe8d4fea932dd4074b7501eb

2021-08-08 18:10 UTC, UdjinM6 requested changes
Pls see https://github.com/UdjinM6/dash/commits/pr4229

2021-08-09 09:36 UTC, UdjinM6 approved these changes
utACK

2021-08-10 19:34 UTC, merged