merge bitcoin#13671, #13734, #18786, #18792, partial bitcoin#18234: Deboostification
dashpay/dash pull request #4246
Opened 2021-07-13 16:27 UTC by kittywhiskers

2021-07-13 18:45 UTC, UdjinM6 requested changes
13734 was already merged recently
18234 missing earlier scheduler related backports. This part is critical, would prefer to postpone it for now and backport them in the right order.

2021-07-13 18:45 UTC, UdjinM6 commented on src/wallet/walletdb.cpp
>      }
18792:
```suggestion
```

2021-07-13 18:45 UTC, UdjinM6 commented on src/wallet/walletdb.cpp
>      catch (...) {
18792:
```suggestion
    } catch (...) {
```

2021-07-15 18:31 UTC, PastaPastaPasta requested changes

2021-07-15 18:31 UTC, PastaPastaPasta commented on src/test/util_tests.cpp
> +    BOOST_CHECK_EQUAL(testVector, "#hashtag");
Why'd you change this? Should be #hodl

2021-07-15 18:53 UTC, UdjinM6 requested changes
18792 should drop `#include <boost/thread.hpp>` in `src/wallet/db.cpp` like in the original PR. 18792 requires 17405 (which in its turn requires 11911) to be compilable (I hope), pls see https://github.com/UdjinM6/dash/commits/pr4246

EDIT: Hmm.. tests failed, so I guess there smth else is missing (or maybe I backported them incorrectly)

2021-07-15 20:46 UTC, PastaPastaPasta commented
TBH I would just prefer to maybe mark 18792 as partial and merge as is (unless either of you want to get that branch working)

2021-07-15 20:49 UTC, UdjinM6 commented
> (unless either of you want to get that branch working)

working on it :)

2021-07-15 22:54 UTC, UdjinM6 commented
Decided to backport 11911 in a separate PR #4263 since it's kind of unrelated to "deboostification". Once it's merged backporting 17405 and 18792 should be trivial.

2021-07-16 01:19 UTC, kittywhiskers commented
18792 originally dropped `boost/thread.hpp` but apparently it was still required so I modified the commit and placed it back in

2021-07-16 14:25 UTC, UdjinM6 requested changes
> 18792 originally dropped `boost/thread.hpp` but apparently it was still required so I modified the commit and placed it back in

Pls revert this to make 18792 complete. Rebasing and adding 17405 (e.g. 1722e83588d41d9f3455986fc52d058d68300a33) should fix the issue.

2021-07-16 16:41 UTC, PastaPastaPasta approved these changes
utACK

2021-07-16 17:15 UTC, UdjinM6 approved these changes
utACK

2021-07-16 17:16 UTC, merged