backport: 'trivial' pr10
dashpay/dash pull request #4249
Opened 2021-07-14 01:45 UTC by PastaPastaPasta

2021-07-14 23:11 UTC, UdjinM6 requested changes

2021-07-14 23:11 UTC, UdjinM6 commented on contrib/linearize/example-linearize.cfg
> +#input=/home/example/.bitcoin/regtest/blocks
17393:
```suggestion
#netmagic=fcc1b7dc
#genesis=000008ca1832a4baf228eb1553c03d3a2c8e02399550dd6ea8d65cec3ef23d2e
#input=/home/example/.dashcore/regtest/blocks
```

2021-07-14 23:45 UTC, PastaPastaPasta commented on configure.ac
> -
dropped this commit for now

2021-07-14 23:45 UTC, PastaPastaPasta commented on contrib/devtools/symbol-check.py
> -'libanl.so.1', # DNS resolve
Cool

2021-07-14 23:45 UTC, PastaPastaPasta commented on .github/workflows/ci.yml
> +name: bitcoin-core-ci
Okay, will open an issue related to this, as I would like better CI diversity

2021-07-15 01:20 UTC, UdjinM6 approved these changes
utACK

2021-07-15 01:20 UTC, merged