backport: 'trivial' pr11
dashpay/dash pull request #4250
Opened 2021-07-14 02:07 UTC by PastaPastaPasta

2021-07-14 02:16 UTC, PastaPastaPasta commented on doc/productivity.md
> +   * [Format C/C++ diffs with `clang-format-diff.py`](#format-cc-diffs-with-clang-format-diffpy)
drop 19058

2021-07-14 02:16 UTC, PastaPastaPasta commented on src/crc32c/.appveyor.yml
> +# Build matrix / environment variables are explained on:
maybe drop d386a4db0c0e060564b3864b9d7da82f79171d47

2021-07-14 02:16 UTC, PastaPastaPasta commented on src/checkqueue.h
> +                        fAllOk = true;
need to drop 17971

2021-07-14 23:43 UTC, UdjinM6 requested changes

2021-07-14 23:43 UTC, UdjinM6 commented on test/functional/mempool_accept.py
> +            result_expected=[{'txid': tx.rehash(), 'allowed': False, 'reject-reason': 'scriptsig-size'}],
17532:
```suggestion
            result_expected=[{'txid': tx.rehash(), 'allowed': False, 'reject-reason': '64: scriptsig-size'}],
```

2021-07-14 23:43 UTC, UdjinM6 commented on src/test/transaction_tests.cpp
> +    t.nVersion = 3;
17555:
```suggestion
    t.nVersion = 4;
```

2021-07-14 23:43 UTC, UdjinM6 commented on src/test/transaction_tests.cpp
> +
17555:
```suggestion

    t.nVersion = 3;
    BOOST_CHECK(IsStandardTx(CTransaction(t), reason));
```

2021-07-14 23:47 UTC, PastaPastaPasta commented
Let's see how CI likes that. Will squash once it's happy

2021-07-15 17:29 UTC, PastaPastaPasta commented
Squashed and fped

2021-07-15 17:33 UTC, UdjinM6 approved these changes
utACK

2021-07-15 17:34 UTC, merged