core: transition to c++17, deboostification
dashpay/dash pull request #4256
Opened 2021-07-15 17:04 UTC by kittywhiskers

Work in progress, relies on https://github.com/dashpay/dash/pull/4255

2021-09-14 17:14 UTC, PastaPastaPasta submitted a review, later dismissed
utACK for merging via merge commit

For 21064, can we do https://github.com/bitcoin/bitcoin/pull/21064/files#diff-dac26d1a1b4a405373f40090c92278a64cbda24c875d3394d5e7f81747367702L70-L71? git grep doesn't yield any results

Also, does it make sense to remove the cxx17 ci build now?

2021-09-15 01:45 UTC, UdjinM6 requested changes
1. agree with @PastaPastaPasta - we should drop `linux64_cxx17` build (should we add `--with-sanitizers=undefined` to `linux64` build?)
2. should apply 20471 to `depends/packages/protobuf.mk`

2021-09-15 05:59 UTC, kittywhiskers commented
@PastaPastaPasta, we could [remove those two lines from the inter whitelist](https://github.com/bitcoin/bitcoin/pull/21064/files#diff-dac26d1a1b4a405373f40090c92278a64cbda24c875d3394d5e7f81747367702L70-L71) but they're not there to begin with so there's nothing to remove (which is kinda surprising but not too problematic)

@UdjinM6, #20471 has been updated and `linux64_cxx17` has been dropped

2021-09-15 20:49 UTC, UdjinM6 approved these changes
utACK

2021-09-16 18:11 UTC, PastaPastaPasta requested changes

2021-09-16 18:11 UTC, PastaPastaPasta commented on ci/matrix.sh
> -  export BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports --enable-crash-hooks --enable-c++17 --enable-werror --with-sanitizers=undefined"
Hmmmm, we shouldn't just do this b/c of `--enable-werror --with-sanitizers=undefined` which are not on linux64/32

Also the fact that this one doesn't do functional tests. We should probably keep this, but just rename it to be like linux64_nofun :D

2021-09-16 18:12 UTC, PastaPastaPasta commented
(Otherwise everything does good)

2021-09-16 21:07 UTC, UdjinM6 commented
CI is broken:
- linux32: looks like smth that could be fixed by #4398
- linux64: we probably hit some gitlab limit there `ERROR: Uploading artifacts as "archive" to coordinator... too large archive`

Let's maybe drop 63f0fc4 for now and implement it in a separate PR?

2021-09-16 22:46 UTC, PastaPastaPasta commented
> Let's maybe drop [63f0fc4](https://github.com/dashpay/dash/commit/63f0fc4914430abcf03e3f399c7378780f303ad4) for now and implement it in a separate PR?

If we drop 63f0fc4, we should drop https://github.com/kittywhiskers/dash/commit/73de8a61994a993477a0f7b73932dac68939686d as well

2021-09-17 06:39 UTC, kittywhiskers commented
Updated

2021-09-18 04:18 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-09-18 20:27 UTC, UdjinM6 approved these changes
Not a huge fan of merging PRs with failed CI builds but these failures are unrelated, so

utACK

2021-09-18 20:27 UTC, merged