Backport triv pr16
dashpay/dash pull request #4261
Opened 2021-07-15 21:00 UTC by PastaPastaPasta

2021-07-15 21:37 UTC, PastaPastaPasta commented on depends/packages/qt.mk
> +  $(MAKE) -C qttranslations INSTALL_ROOT=$($(package)_staging_dir) install_subtargets
20650 is probably dependant on another backport...

2021-07-15 21:37 UTC, PastaPastaPasta commented on test/functional/feature_anchors.py
> +#!/usr/bin/env python3
drop 21338, I don't think we have anchors.dat and assosiated logic

2021-07-16 14:10 UTC, UdjinM6 requested changes

2021-07-16 14:38 UTC, UdjinM6 commented on src/util/system.h
> +[[nodiscard]] bool RenameOver(fs::path src, fs::path dest);
20519: need 17044 to stop complains about `RenameOver` in `init.cpp`
```
init.cpp:872:13: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
            RenameOver(pathBootstrap, pathBootstrapOld);
            ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2021-07-16 15:05 UTC, PastaPastaPasta commented
Done

2021-07-16 17:17 UTC, UdjinM6 approved these changes
utACK

2021-07-16 17:20 UTC, merged