Backports 0.18 pr8
dashpay/dash pull request #4285
Opened 2021-07-21 21:31 UTC by Munkybooty

2021-07-21 22:49 UTC, UdjinM6 requested changes
14424 breaks psbt tests (should find follow up fixes or drop it for now) + see below + 96aaa411105a02baf41268d1906d240c8497a57f + 19503424a3bd0dd63344355236fa8b82cd2ce480

we have pr9 already (#4278), renamed to pr10

2021-07-21 22:49 UTC, UdjinM6 commented on doc/README.md
> +To download Dash Core, visit [dash.org](https://www.dash.org/downloads/).
let's mark 14511 as DNM

2021-07-22 00:44 UTC, PastaPastaPasta requested changes

2021-07-22 00:44 UTC, PastaPastaPasta commented on src/rpc/rawtransaction.cpp
> +            "                             Allows this transaction to be replaced by a transaction with higher fees. If provided, it is an error if explicit sequence numbers are incompatible.\n"
I don't believe this has been resolved

2021-07-23 02:02 UTC, PastaPastaPasta commented on src/rpc/rawtransaction.cpp
> +            "                             Allows this transaction to be replaced by a transaction with higher fees. If provided, it is an error if explicit sequence numbers are incompatible.\n"
still not done :)

2021-07-23 03:02 UTC, Munkybooty commented on src/rpc/rawtransaction.cpp
> +            "                             Allows this transaction to be replaced by a transaction with higher fees. If provided, it is an error if explicit sequence numbers are incompatible.\n"
Could've sworn I did it

2021-07-23 14:37 UTC, UdjinM6 approved these changes
utACK

2021-07-25 23:32 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-07-25 23:33 UTC, merged