Backports 0.18 pr11
dashpay/dash pull request #4289
Opened 2021-07-23 16:36 UTC by Munkybooty

So something here started breaking PSBT tests, I'm sure there are at least 2 merges responsible for it. Something else broke along the way as well and I have no clue where the error is coming up.

2021-07-26 15:54 UTC, PastaPastaPasta commented
https://github.com/dashpay/dash/pull/4289/commits/1060e0259e80348a351062a796968966548971ba Makes CI not happy. Please resolve. Then mark as ready for review

2021-07-27 10:33 UTC, UdjinM6 requested changes

2021-07-27 10:33 UTC, UdjinM6 commented on src/rpc/misc.cpp
> +    { "util",               "createmultisig",         &createmultisig,         {"nrequired","keys","address_type"} },
14596: we don't have `address_type`

2021-07-27 10:33 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> +            "  \"script\" : \"type\"             (string, optional) The output script type. Only if \"isscript\" is true and the redeemscript is known. Possible types: nonstandard, pubkey, pubkeyhash
14410:
```suggestion
            " \"ischange\" : true|false,       (boolean) If the address was used for change output\n"
            "  \"script\" : \"type\"             (string, optional) The output script type. Only if \"isscript\" is true and the redeemscript is known. Possible types: nonstandard, pubkey, pubkeyhash, scripthash, multisig, nulldata\n"
```

2021-07-28 01:34 UTC, PastaPastaPasta requested changes
14596 should be dropped. No point in the empty commit. Just mark as DMN in sheet

2021-07-28 01:34 UTC, PastaPastaPasta commented on test/functional/test_runner.py
>          runs_ci=args.ci,
move this below failfast?

2021-07-28 01:34 UTC, PastaPastaPasta commented on .gitignore
> +db4/
at best we should mark 14515 as partial. IMO we should drop since we don't support openbsd builds

2021-07-28 16:11 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit once CI is happy

2021-07-28 17:54 UTC, UdjinM6 approved these changes
utACK

2021-07-28 17:54 UTC, merged