[DRAFT] Backport v0.18
dashpay/dash pull request #4303
Opened 2021-07-29 20:15 UTC by linuxsh2

A few cherry-picks that had no conflicts.

2021-07-29 20:33 UTC, PastaPastaPasta commented
We don't want to backport 11526 unless someone will modify it to actually work with Dash buidling

I think appveyor depends on 11526, so can't have that either

2021-07-29 20:36 UTC, linuxsh2 commented
Should I mark 11526 as DNM then?

2021-07-29 20:40 UTC, PastaPastaPasta commented
Probably not... I added a comment outlining the situation

2021-07-31 14:40 UTC, UdjinM6 requested changes

2021-07-31 14:40 UTC, UdjinM6 commented on doc/README.md
> +- [Gitian Building Guide (External Link)](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md)
15132: none of this is relevant, should skip it

2021-07-31 14:40 UTC, UdjinM6 commented on test/lint/check-doc.py
> +        docd = check_output(CMD_GREP_DOCS, shell=True, universal_newlines=True, encoding='utf8')
15196: This part is from 14884, should backport it first

2021-08-06 20:04 UTC, UdjinM6 approved these changes
LGTM, utACK

2021-08-06 21:23 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-08-06 21:23 UTC, merged