Backports 0.18 pr12
dashpay/dash pull request #4313
Opened 2021-08-02 17:34 UTC by Munkybooty

2021-08-02 21:25 UTC, PastaPastaPasta requested changes

2021-08-02 21:25 UTC, PastaPastaPasta commented on doc/build-osx.md
>      echo -e "rpcuser=dashrpc\nrpcpassword=$(xxd -l 16 -p /dev/urandom)" > "/Users/${USER}/Library/Application Support/DashCore/dash.conf"
14684 this needs changing

https://github.com/bitcoin/bitcoin/pull/14684/files#diff-e9ba5bd8b63e72aa2d54d02960c9209823938981691cc8786ba323b54de0659cL85-R85

2021-08-02 21:25 UTC, PastaPastaPasta commented on contrib/debian/examples/dash.conf
> +# Pay a transaction fee every time you send bitcoins.
14684 dash

2021-08-02 21:25 UTC, PastaPastaPasta commented on src/qt/optionsdialog.cpp
> +
This adds too much... Maybe missing a prior backport?

https://github.com/bitcoin/bitcoin/pull/14228/files#diff-1d6f5264407b3b2e18be8d9d9653bbf1d67979f4f95dc26575dc23bb8463b4e7L214-R225

2021-08-02 21:25 UTC, PastaPastaPasta commented on doc/release-notes-14060.md
> +Configuration
drop 14704 and mark DNM

2021-08-02 21:25 UTC, PastaPastaPasta commented on .travis.yml
> -
14770 dont do this

2021-08-04 17:11 UTC, PastaPastaPasta requested changes
14228 needs wrapping https://github.com/dashpay/dash/pull/4313/commits/06d1dfabde3bb42a880dae91388c767008fdb4eb#diff-1d6f5264407b3b2e18be8d9d9653bbf1d67979f4f95dc26575dc23bb8463b4e7R280-R281 like https://github.com/bitcoin/bitcoin/pull/14228/files#diff-1d6f5264407b3b2e18be8d9d9653bbf1d67979f4f95dc26575dc23bb8463b4e7L214-R225

2021-08-06 20:51 UTC, UdjinM6 requested changes

2021-08-06 20:51 UTC, UdjinM6 commented on src/qt/bitcoingui.cpp
> +#ifndef Q_OS_MAC
was not in 14228
```suggestion
```

2021-08-06 20:51 UTC, UdjinM6 commented on src/qt/bitcoingui.cpp
> +
```suggestion
```

2021-08-09 09:35 UTC, UdjinM6 reviewed
One tiny issue, LGTM otherwise

2021-08-09 09:35 UTC, UdjinM6 commented on src/qt/bitcoingui.cpp
> +
14228: nit
```suggestion
```

2021-08-09 22:23 UTC, UdjinM6 approved these changes
LGTM, utACK

2021-08-11 00:11 UTC, PastaPastaPasta requested changes

2021-08-11 00:11 UTC, PastaPastaPasta commented on src/qt/optionsdialog.cpp
> +
14228 I believe this is a problem. 

Should be done here: https://github.com/dashpay/dash/pull/4313/commits/d5372579def7ebce3281241f03e8582a7ee69bdd#diff-1d6f5264407b3b2e18be8d9d9653bbf1d67979f4f95dc26575dc23bb8463b4e7R280-R281 IE line 280-281

2021-08-11 16:11 UTC, PastaPastaPasta approved these changes
LGTM, utACK for merge via merge commit

2021-08-11 16:11 UTC, merged