merge bitcoin#16202, #18260: Refactor network message deserialization
dashpay/dash pull request #4323
Opened 2021-08-05 15:52 UTC by kittywhiskers

2021-08-05 17:02 UTC, PastaPastaPasta commented
13960 was already merged into develop via https://github.com/dashpay/dash/pull/4310

Does this PR need rebase? Or drop that commit?

2021-08-05 17:03 UTC, kittywhiskers commented
Resolved, interactive rebase messed with the commit

2021-08-09 17:58 UTC, UdjinM6 requested changes
Needs at least fixes listed below but `p2p_invalid_messages.py` keeps failing even after applying them (needs more backports).

2021-08-23 02:13 UTC, PastaPastaPasta commented
Marking this as draft for two reasons:
1. Both this PR and #4330 have 14522, 14672, 14812. I believe #4330 should have priority in this regard since Konstantin was the one to mark the PRs as staged in the backport spreadsheet. Additionally, it is in an almost mergable state. Once it is merged, this PR will need to be rebased
2. CI is unhappy

2021-08-23 12:39 UTC, kittywhiskers commented
I was initially planning to wait on #4330 because of Udjin's comment but cherry-picked the patch to test if it'll work, I'll be glad to drop those commits and rebase once Konstantin's PR is merged. +1

2021-09-24 02:03 UTC, vijaydasmp commented
Hello, @kittywhiskers Hope you are well, I was currently blocked by bitcoin#14794: Add AddressSanitizer (ASan) Travis build, I saw the last activity on this PR 2 weeks old, If you are currently working on it, I am happy to wait

2021-09-24 03:17 UTC, kittywhiskers commented
You can take it over, I did a partial of #14794 to resolve merges but if you're planning to do a full merge, that would be of greater value @vijaydasmp

2021-09-24 03:35 UTC, vijaydasmp commented
Hello @kittywhiskers, Thanks for the quick response

2021-11-02 18:04 UTC, PastaPastaPasta requested changes
LGTM

2021-11-02 18:04 UTC, PastaPastaPasta commented on test/functional/p2p_invalid_messages.py
> -            node.p2p.sync_with_ping(timeout=30)
imo, just drop 15005

2021-11-02 18:04 UTC, PastaPastaPasta commented on test/functional/feature_assumevalid.py
> +    msg_headers,
imo let's just drop 16888 since we are missing feature_block stuff

2021-11-03 14:37 UTC, UdjinM6 approved these changes
LGTM, utACK

2021-11-03 19:39 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-11-03 19:40 UTC, merged