Merge bitcoin#13793, #14168, #14208
dashpay/dash pull request #4328
Opened 2021-08-10 05:56 UTC by 5tefan

2021-08-10 16:29 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commits/pr4328

2021-08-12 10:33 UTC, UdjinM6 commented
pls squash the fix (877f254) into the corresponding backport commit (6854734)

2021-08-12 17:26 UTC, UdjinM6 requested changes

2021-08-12 17:26 UTC, UdjinM6 commented on src/dummywallet.cpp
> +class CWallet;
14208:
```suggestion
#include <stdio.h>

class CWallet;
```

2021-08-12 18:18 UTC, 5tefan commented on src/dummywallet.cpp
> +class CWallet;
Done + squashed into 1cea09e.

2021-08-12 18:57 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-08-13 20:23 UTC, UdjinM6 approved these changes
utACK

2021-08-13 20:24 UTC, merged