Backports 0.18 pr13
dashpay/dash pull request #4333
Opened 2021-08-11 16:29 UTC by Munkybooty

This breaks p2p_connect_to_devnet and i'm not too sure as to why.

2021-08-11 16:32 UTC, Munkybooty commented
i swear i pressed develop when i created the pr and yet somehow it switched back to master. weird...

2021-08-11 20:59 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commits/pr4333 + should drop 14670 (it was merged earlier)

2021-08-13 20:29 UTC, UdjinM6 approved these changes
utACK (verified that dash-qt compiles and runs fine with qt 5.9.7 on local macos, no visual issues)

2021-08-14 00:36 UTC, PastaPastaPasta requested changes

2021-08-14 00:36 UTC, PastaPastaPasta commented on test/functional/mining_basic.py
> +from test_framework.script import CScriptNum
14816 this should be below 
```
    bytes_to_hex_str as b2x,
)
```

2021-08-14 22:47 UTC, Munkybooty commented on test/functional/mining_basic.py
> +from test_framework.script import CScriptNum
it should be on line 27

2021-08-15 14:48 UTC, PastaPastaPasta commented on test/functional/mining_basic.py
> +from test_framework.script import CScriptNum
I think. Just down a few lines. Below
```

from test_framework.util import (
    assert_equal,
    assert_raises_rpc_error,
    bytes_to_hex_str as b2x,
)
```

2021-08-16 02:06 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-08-16 16:53 UTC, UdjinM6 approved these changes
re-utACK

2021-08-16 19:24 UTC, merged