build: add support for Dash development within Docker
dashpay/dash pull request #4336
Opened 2021-08-12 17:13 UTC by kittywhiskers

## Why?

There is a possibility that a contributor's host system does not match the distribution used by the CI system that Dash uses, which makes debugging CI failures an increasing pain. Travis CI offered a feature where you could SSH into the CI instance and debug the cause of failure. GitLab CI, to my knowledge does not offer that

## Why now?

The CI failure when building macOS depends on https://github.com/dashpay/dash/pull/4255 happen when building them on a Linux system, I use macOS.

2021-12-15 20:50 UTC, PastaPastaPasta requested changes
fix linter

2021-12-18 05:56 UTC, UdjinM6 requested changes
needs rebase and a tiny fix, LGTM otherwise

2021-12-18 05:56 UTC, UdjinM6 commented on contrib/containers/dev/docker-compose.yml
> +        target: /dash-src
nit:
```suggestion
        target: /dash-src

```

2021-12-19 13:56 UTC, UdjinM6 approved these changes
utACK

2021-12-22 10:39 UTC, UdjinM6 approved these changes
utACK

2021-12-28 18:08 UTC, PastaPastaPasta approved these changes
ACK for merging via merge commit

2021-12-28 18:08 UTC, merged