Backports 0.18 pr14
dashpay/dash pull request #4341
Opened 2021-08-16 03:47 UTC by PastaPastaPasta

A few relatively simple PRs

2021-08-17 20:35 UTC, UdjinM6 commented
Hmm... it looks like you skipped changes to `.travis*` files in 14252, 14673 and 14674. Why?

2021-08-17 21:20 UTC, PastaPastaPasta commented
> Hmm... it looks like you skipped changes to `.travis*` files in 14252, 14673 and 14674. Why?

Normally I go on strike with regards to travis due to the substancial differences, and based on my IDE, the differences looked bad. When looking manually the changes are easy. Pushed / fped

2021-08-17 21:27 UTC, UdjinM6 requested changes

2021-08-17 21:27 UTC, UdjinM6 commented on .travis.yml
>          RUN_FUNCTIONAL_TESTS=false # Disabled for now, can be combined with the other x86_64 linux NO_DEPENDS job when functional tests pass the sanitizers
14252: original PR dropped this line too
```suggestion
```

2021-08-18 18:54 UTC, UdjinM6 commented
Looks good 👍 pls squash the fix

2021-08-18 18:56 UTC, PastaPastaPasta commented
Done

2021-08-18 19:05 UTC, UdjinM6 approved these changes
utACK

2021-08-18 19:05 UTC, merged