backport v0.18 (13529) and Qt5 connect syntax for Dash specific code
dashpay/dash pull request #4345
Opened 2021-08-17 16:09 UTC by linuxsh2

2021-08-17 16:11 UTC, linuxsh2 commented on src/qt/overviewpage.cpp
> -    if(timer) disconnect(timer, SIGNAL(timeout()), this, SLOT(coinJoinStatus()));
Since line 167 is connecting with `this` as a receiver, the signal will be disconnected once `this` is destroyed. So no need to disconnect here.

2021-08-19 22:20 UTC, UdjinM6 requested changes
pls see below + https://github.com/UdjinM6/dash/commit/4e21e4cc82cf3b77004d0f0680df200cf6a3c1e6

2021-08-23 16:10 UTC, linuxsh2 commented on src/qt/bitcoingui.cpp
> +    labelProxyIcon = new GUIUtil::ClickableLabel();
I'll revert this change. This PR has a lot of changes already.

2021-08-23 21:35 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-08-24 16:13 UTC, UdjinM6 approved these changes
utACK

2021-08-24 16:14 UTC, merged