Qt: Adds Governance tab
dashpay/dash pull request #4351
Opened 2021-08-19 08:20 UTC by 5tefan

Towards #4337, implementing DMT-like Governance Functionality.

2021-08-20 07:14 UTC, 5tefan commented
Views of the new functionality:

<img width="716" alt="Screen Shot 2021-08-20 at 01 07 19" src="https://user-images.githubusercontent.com/5855806/130194444-176ce011-9c9f-42dd-a195-c10c2e7b023b.png">

<img width="1200" alt="Screen Shot 2021-08-20 at 01 07 00" src="https://user-images.githubusercontent.com/5855806/130194433-25bddebc-4870-46a5-8987-2212fe2dd316.png">

Questions:
- What columns to display? Probably include vote counts/ratio. Is showing url necessary with right click to open url exists?
- Looking a bit simper than Masternode list, not subscribing to updates from core: just periodically refresh, or include a refresh button?
- Show proposals only?

2021-08-20 18:58 UTC, UdjinM6 commented
Nice! 👍 

> Questions:
> 
> * What columns to display? Probably include vote counts/ratio. Is showing url necessary with right click to open url exists?

Would be nice to have "Voting status" implemented in a similar way it's done in DMT imo. Also, cycles (e.g. current/total) and total amount might be useful in this list. URL, yes/no/abstain counts etc. can be shown in a separate panel like it's done in DMT (i.e. you select a proposal and this populates "Details" panel below).

> * Looking a bit simper than Masternode list, not subscribing to updates from core: just periodically refresh, or include a refresh button?

The list is small here (10s comparing to 1000s in mn list), periodic updates shouldn't be ok I think (assuming they won't cause issues with "Details" panel I mentioned above).

> * Show proposals only?

Yeah, I think it would be better to start with proposals first. We can get back to triggers later when we polish proposals list(/vote?) functionality.

2021-08-25 11:40 UTC, UdjinM6 requested changes

2021-08-25 11:40 UTC, UdjinM6 commented on src/qt/governancelist.cpp
> +    connect(timer, SIGNAL(timeout()), this, SLOT(updateGovernanceListScheduled()));
This should make linter happy again
```suggestion
    connect(timer, &QTimer::timeout, this, &GovernanceList::updateGovernanceListScheduled);
```

2021-08-25 11:40 UTC, UdjinM6 commented on src/qt/optionsdialog.cpp
> +    connect(ui->showGovernanceTab, &QCheckBox::clicked, this, &OptionsDialog::showRestartWarning);
👀 👍

2021-10-14 06:24 UTC, 5tefan commented
Formatting addressed. Thanks, that `clang-format-diff.py` script is super convenient!

2021-10-30 01:14 UTC, PastaPastaPasta approved these changes
ACK for squash merge

2021-10-30 01:14 UTC, PastaPastaPasta commented
Things for future changes: 
Add: Yes count, No count, Abstain Count, Absolute Yes coin, url
Remove: Hash
Replace Start, End dates with computed "Payments Remaining"

We should consider adding a pop-up warning before opening the proposal URL

2021-10-30 01:14 UTC, merged