bitcoin#16787, #17474, #17687, #18165, #18877, #18960, #19010, #19044, #19070: block filters
dashpay/dash pull request #4355
Opened 2021-08-22 17:25 UTC by kittywhiskers

2021-08-22 20:15 UTC, PastaPastaPasta commented
linter + both tests are unhappy

2021-08-22 20:15 UTC, kittywhiskers commented
It's a work in progress

2021-08-22 20:17 UTC, PastaPastaPasta commented
Marked as draft

2021-09-17 23:42 UTC, PastaPastaPasta commented
Please rename all commits to begin with "Merge"

2021-09-17 23:54 UTC, PastaPastaPasta requested changes
LGTM, besides one thing and a comment

2021-09-17 23:54 UTC, PastaPastaPasta commented on src/net_processing.cpp
> +#include <validation.h>
This should be below L16 to be inline with upstream

2021-09-17 23:54 UTC, PastaPastaPasta commented on src/net_processing.h
> +static const bool DEFAULT_PEERBLOCKFILTERS = false;
We should consider what all of these defaults should be, like should normal nodes be serving bloom filters by default for example?

2021-09-18 21:27 UTC, UdjinM6 requested changes
Few small issues

2021-09-18 21:27 UTC, UdjinM6 commented on src/init.cpp
> +    gArgs.AddArg("-peerblockfilters", strprintf("Serve compact block filters to peers per BIP 157 (default: %u)", DEFAULT_PEERBLOCKFILTERS), false, OptionsCategory::CONNECTION);
Should be one above `-peerbloomfilters` (sort A-Z)

2021-09-18 21:27 UTC, UdjinM6 commented on test/functional/test_framework/mininode.py
> +    msg_cfcheckpt,
Should be above `msg_clsig` (A-Z)

2021-09-19 04:39 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-09-21 12:04 UTC, UdjinM6 approved these changes
utACK

2021-09-21 12:05 UTC, merged