merge bitcoin#14437: separate wallet from node
dashpay/dash pull request #4357
Opened 2021-08-22 20:24 UTC by kittywhiskers

2022-03-29 23:10 UTC, PastaPastaPasta requested changes

2022-03-29 23:10 UTC, PastaPastaPasta commented on src/interfaces/chain.cpp
> -        m_notifications->BlockConnected(*block, tx_conflicted);
should drop `getBlockDepth` no? https://github.com/bitcoin/bitcoin/pull/15931/files#diff-efaf73429006d059e7fffab1bf2879769c90187f583d4857b3275b7bf79368d1L61-L66

2022-03-29 23:10 UTC, PastaPastaPasta commented on src/interfaces/chain.cpp
> -        m_notifications->BlockConnected(*block, tx_conflicted);
Also, is there a reason we don't currently have waitForNotificationsIfNewBlocksConnected? https://github.com/bitcoin/bitcoin/pull/15931/files#diff-efaf73429006d059e7fffab1bf2879769c90187f583d4857b3275b7bf79368d1L356-L362

2022-03-29 23:10 UTC, PastaPastaPasta commented on src/interfaces/chain.h
> +        virtual void BlockDisconnected(const CBlock& block, int height) {}
same missing changes mentioned above

2022-03-29 23:10 UTC, PastaPastaPasta commented on src/qt/test/wallettests.cpp
> +        wallet->SetLastBlockProcessed(105, ::ChainActive().Tip()->GetBlockHash());
missing changes in interfaces/wallet.cpp (didn't review all of 15931, moving on for now due to missing changes)

2022-04-05 07:41 UTC, UdjinM6 requested changes
needs rebase + pls see https://github.com/UdjinM6/dash/commits/pr4357

2022-04-05 21:44 UTC, UdjinM6 requested changes
LGTM but gitlab action no longer works for this PR for some reason :/ should replace this PR with a new one

2022-04-06 09:14 UTC, kittywhiskers commented
Superseded by #4756

2022-04-06 09:14 UTC, closed without merging