Backport 14941 and 15149
dashpay/dash pull request #4400
Opened 2021-09-08 20:02 UTC by PastaPastaPasta

Intended for merge via merge commit

2021-09-08 20:42 UTC, UdjinM6 reviewed
LGTM but you might want to also backport 15210 while at it

2021-09-08 21:48 UTC, PastaPastaPasta commented
Happy now!?! :D

2021-09-09 10:35 UTC, UdjinM6 requested changes
Almost :)

2021-09-09 17:13 UTC, PastaPastaPasta commented on src/qt/bitcoingui.cpp
>              window_title += userWindowTitle + " - ";
done, can squash if you want

2021-09-09 20:29 UTC, UdjinM6 commented
Looks good now :) pls squash

2021-09-09 20:30 UTC, PastaPastaPasta commented
Squashed

2021-09-09 20:32 UTC, UdjinM6 approved these changes
utACK

2021-09-09 20:33 UTC, merged