importmulti: Don't add internal addresses to address book  #14679
dashpay/dash pull request #4402
Opened 2021-09-09 14:17 UTC by ogabrielides

2021-09-09 17:19 UTC, PastaPastaPasta commented
Adjusted the name, please use this naming scheme ( / likely backport with -m1 as described in #4000)

2021-09-09 17:33 UTC, PastaPastaPasta requested changes

2021-09-09 17:33 UTC, PastaPastaPasta commented on src/wallet/rpcdump.cpp
>                  // add to address book or update label
this comment is supposed to be updated
```suggestion
                // if not internal add to address book or update label
```

2021-09-09 17:33 UTC, PastaPastaPasta commented on src/wallet/rpcdump.cpp
Missing the changes here 

https://github.com/bitcoin/bitcoin/commit/f617e05c38c9c7e663b824fefe5329cc5cbbf26a#diff-c455c7835ec6d7a6d846c1ce3d3c2ad704b01d0c2215bffb5c28c9a5a1b33369L1105-R1106

2021-09-09 17:33 UTC, PastaPastaPasta commented on test/functional/wallet_importmulti.py
> +        # Address + Public key + !Internal(explicit)
Don't delete this line
```suggestion

        # Address + Public key + !Internal(explicit)
```

2021-09-09 17:33 UTC, PastaPastaPasta commented on test/functional/wallet_importmulti.py
> +
Don't add this line
```suggestion
```

2021-09-10 08:02 UTC, ogabrielides commented
@PastaPastaPasta Updates completed

2021-09-10 10:57 UTC, UdjinM6 requested changes

2021-09-10 10:57 UTC, UdjinM6 commented on test/functional/wallet_importmulti.py
> +        # Bitcoin Address(implicit non-internal)
```suggestion
        # Bitcoin Address (implicit non-internal)
```

2021-09-10 10:58 UTC, UdjinM6 submitted a review, later dismissed
utACK

2021-09-10 15:34 UTC, PastaPastaPasta requested changes

2021-09-10 15:34 UTC, PastaPastaPasta commented on src/wallet/rpcdump.cpp
> +                if(!internal) {
```suggestion
                if (!internal) {
```

2021-09-10 15:35 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2021-09-11 18:08 UTC, UdjinM6 approved these changes
utACK

2021-09-11 19:56 UTC, merged