Backport #11625, #15101, #14854
dashpay/dash pull request #4410
Opened 2021-09-10 20:04 UTC by PastaPastaPasta

2021-09-11 19:54 UTC, UdjinM6 requested changes

2021-09-11 19:54 UTC, UdjinM6 commented on src/qt/dash.cpp
> +        Q_EMIT splashFinished();
11625: this should be a part of 14854

2021-09-11 19:54 UTC, UdjinM6 commented on src/qt/dash.cpp
> +        Q_EMIT splashFinished(); // Make sure splash screen doesn't stick around during shutdown
11625: this should be a part of 14854

2021-09-11 19:54 UTC, UdjinM6 commented on src/qt/dash.h
> +    void splashFinished();
11625:
```suggestion
    void splashFinished(QWidget *window);
````
and then drop `QWidget *window` in 14854

2021-09-18 20:35 UTC, UdjinM6 commented
14854 was merged via #4412 already

2021-09-18 21:14 UTC, PastaPastaPasta commented
Okay, should be ready

2021-09-18 22:14 UTC, UdjinM6 approved these changes
utACK

2021-09-18 22:15 UTC, merged