Backport v18 vijay batch4 1
dashpay/dash pull request #4430
Opened 2021-09-16 11:17 UTC by vijaydasmp

Merge bitcoin#19733: Move comment about BaseIndex::DB from TxIndex::DB …
Merge bitcoin#14667: Add deriveaddresses RPC util method …
Merge bitcoin#15510: [rpc] deriveaddresses: add range to CRPCConvertP… …
Merge bitcoin#14150: Add key origin support to descriptors …

2021-09-16 11:57 UTC, vijaydasmp commented
@PastaPastaPasta  @UdjinM6 
Getting system failure messages from CI system, somebody please check the CI system 

> There has been a runner system failure, please try again

2021-09-17 19:36 UTC, PastaPastaPasta commented
> Hello @PastaPastaPasta @UdjinM6
> Getting system failure messages from CI system, somebody please check the CI system
> 
> > There has been a runner system failure, please try again

Have restarted those runners

2021-09-19 00:03 UTC, UdjinM6 requested changes

2021-09-19 01:00 UTC, vijaydasmp commented
Thanks  @UdjinM6 , will work on those

2021-09-20 08:50 UTC, vijaydasmp commented on src/rpc/misc.cpp
> +            "deriveaddresses"
Thanks @UdjinM6 , I observed that doc/descriptors.md this file was not present , However there is 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/vijay/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/vijay/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
x\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
.font0
	{color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{color:black;}
.xl66
	{color:black;
	border:.5pt solid black;}
-->
</style>
</head>

<body link="#1155CC" vlink="#1155CC">



  |   | 0f681ceca | Add descriptor reference   documentation |   | FALSE
-- | -- | -- | -- | -- | --




</body>

</html>
an entry in the Backport sheet for 0.17 version which wasn't done as it was not marked as "Merged Done" there , So probably I have to pull this change to fix doc/descriptors.md changes

2021-09-20 14:58 UTC, vijaydasmp commented on src/rpc/client.cpp
> +    { "deriveaddresses", 1, "range" },
Hello @UdjinM6 I tried to implement 15497 , It required Merge #14726 which is staged with 
Vlad_Staged (staged to Vladimir (dzutte-cpp) local repo) which is waiting on 
Merge#14023 which is staged with you @UdjinM6 , Now we are in Blocked chain :)

2021-09-20 15:01 UTC, vijaydasmp commented on src/rpc/misc.cpp
> +            "deriveaddresses"
I observed that doc/descriptors.md this file was not present,  There was a change mentioned Backport sheet for 0.17 version in 0f681ce (Add descriptor reference documentation) , however this changed was not merged , thats why this file was not present	, will pull this changes

2021-09-21 00:19 UTC, vijaydasmp commented
In descriptor_test.cpp
```
void Check(const std::string& prv, const std::string& pub, int flags, const std::vector<std::vector<std::string>>& scripts, const std::set<std::vector<uint32_t>>& paths = ONLY_EMPTY)
{
    FlatSigningProvider keys_priv, keys_pub;
    std::set<std::vector<uint32_t>> left_paths = paths;

    // Check that parsing succeeds.
    std::unique_ptr<Descriptor> parse_priv = Parse(MaybeUseHInsteadOfApostrophy(prv), keys_priv);
    std::unique_ptr<Descriptor> parse_pub = Parse(MaybeUseHInsteadOfApostrophy(pub), keys_pub);
    BOOST_CHECK(parse_priv);
    BOOST_CHECK(parse_pub);  <=== This boost check is failing ,
```
trying to understand why

2021-09-23 02:11 UTC, vijaydasmp commented
(Dropped the commits which are dependent on other commits for now) ,
Raising PR to Merge 19733 and 19734

2021-09-23 17:29 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-09-24 09:05 UTC, UdjinM6 approved these changes
utACK

2021-09-24 09:05 UTC, merged