Backport trivial pr18
dashpay/dash pull request #4432
Opened 2021-09-17 20:03 UTC by PastaPastaPasta

2021-09-17 20:15 UTC, PastaPastaPasta commented on test/functional/p2p_sendheaders.py
> -
drop 18496, depends on 18247

2021-09-17 20:18 UTC, PastaPastaPasta commented on test/functional/p2p_sendheaders.py
> -
done

2021-09-18 21:02 UTC, UdjinM6 requested changes
Looks mostly fine. Found just one issue, see below.

2021-09-18 21:16 UTC, PastaPastaPasta commented on src/qt/bitcoingui.cpp
> +    labelWalletEncryptionIcon->hide();
dropped

2021-09-18 21:33 UTC, UdjinM6 approved these changes
utACK

2021-09-18 21:33 UTC, merged