Backport trivial pr21
dashpay/dash pull request #4434
Opened 2021-09-17 20:05 UTC by PastaPastaPasta

2021-09-18 22:55 UTC, UdjinM6 requested changes

2021-09-18 22:55 UTC, UdjinM6 commented on src/net_processing.cpp
> +        // Message: getdata (transactions)
15451: not true for Dash, should be DNM

2021-09-18 22:55 UTC, UdjinM6 commented on test/functional/test_framework/test_framework.py
> +        self.chain: str = 'regtest'
20954: requires 18210

2021-09-18 22:55 UTC, UdjinM6 commented on src/init.cpp
> +    hidden_args.emplace_back("-daemonwait");
21447: we don't have this yet

2021-09-19 01:42 UTC, PastaPastaPasta commented
dropped all

2021-09-19 07:34 UTC, UdjinM6 approved these changes
utACK

2021-09-19 07:35 UTC, merged