Backport trivial pr20
dashpay/dash pull request #4435
Opened 2021-09-17 20:07 UTC by PastaPastaPasta

2021-09-18 03:44 UTC, PastaPastaPasta commented on contrib/linearize/example-linearize.cfg
> +#port=38332
20015 doesn't harm anything, but should probably drop

2021-09-18 03:44 UTC, PastaPastaPasta commented on contrib/signet/README.md
> +A script to call a faucet to get Signet coins.
drop 20145

2021-09-18 03:44 UTC, PastaPastaPasta commented on src/util/system.h
> +[[nodiscard]] bool RenameOver(fs::path src, fs::path dest);
20519 I think this causes a warning somewhere, need to look at

2021-09-21 18:09 UTC, PastaPastaPasta commented on src/test/denialofservice_tests.cpp
> -    dummyNode1.nVersion = 1;
done, also squashed 20519

2021-09-24 09:16 UTC, UdjinM6 requested changes
pls drop 19733 and 19734 (merged via #4430 )

2021-09-24 17:26 UTC, PastaPastaPasta commented
Done

2021-09-24 20:09 UTC, UdjinM6 approved these changes
utACK

2021-09-24 20:10 UTC, merged