Backport 15809 15802 15792
dashpay/dash pull request #4439
Opened 2021-09-18 04:30 UTC by PastaPastaPasta

2021-09-21 13:07 UTC, UdjinM6 requested changes

2021-09-21 13:07 UTC, UdjinM6 commented on src/dummywallet.cpp
> +        "-usehd", "-keepass",
15913: split
```suggestion
        "-usehd",
        "-keepass",
```

2021-09-28 19:48 UTC, UdjinM6 commented
ping?

2021-09-28 20:13 UTC, PastaPastaPasta commented
Done, thanks for the ping :)

2021-09-28 20:38 UTC, UdjinM6 approved these changes
utACK

2021-09-28 20:38 UTC, merged