governance: add threading annotations, add default values, adjust constructors
dashpay/dash pull request #4465
Opened 2021-09-26 21:23 UTC by PastaPastaPasta

2021-09-27 22:24 UTC, PastaPastaPasta commented
I don't understand these test failures... Help wanted :)

2021-09-28 18:43 UTC, pravblockc commented on src/governance/governance.h
> +    CDeterministicMNListPtr lastMNListForVotingKeys GUARDED_BY(cs);
it should be 
CDeterministicMNListPtr lastMNListForVotingKeys GUARDED_BY(cs) {std::make_shared<CDeterministicMNList>()};

Also add below header file as forward declaration is not sufficient
#include <evo/deterministicmns.h>

2021-09-30 19:19 UTC, UdjinM6 requested changes
mac build fails https://gitlab.com/dashpay/dash/-/jobs/1631527804

2021-10-01 18:45 UTC, PastaPastaPasta commented
We'll see how the mac build likes that. Pay special attention to https://github.com/dashpay/dash/pull/4465/commits/21abbc7aceaecc6b5a6beaa4b661149ba3762c62 (will try to resolve todo in a near future PR), would like your feedback / ensure I'm not crazy when it comes to livecycles / saftey there

2021-10-01 19:27 UTC, PastaPastaPasta commented
rebased

2021-10-01 19:32 UTC, PastaPastaPasta commented
I figured https://github.com/dashpay/dash/pull/4466/commits/e80b67f5ec047882e8dfc2a5edaf1da644860f25 would resolve these compilation errors, but I guess I'm missing something...

2021-11-01 10:26 UTC, UdjinM6 requested changes
mac build complains (werror) + see below

2024-09-04 18:35 UTC, closed without merging