merge bitcoin#19817, bitcoin#20470, bitcoin#22993: macOS C++17 bump
dashpay/dash pull request #4477
Opened 2021-10-02 04:06 UTC by kittywhiskers

2021-10-02 04:53 UTC, PastaPastaPasta requested changes
one thing, also not sure why ci is unappy, otherwise looks dandy

2021-10-02 04:53 UTC, PastaPastaPasta commented on depends/hosts/darwin.mk
> +#     -stdlib=libc++ -stdlib++-isystem$(OSX_SDK)/usr/include/c++/v1
19817 missing changes from https://github.com/bitcoin/bitcoin/pull/19817/files#diff-964a007db35da98be548991cbc8815cc400d698508eb4b203921254e5c1bf8baR2-R5 (darwin.mk)

2021-10-04 17:12 UTC, UdjinM6 requested changes

2021-10-05 02:35 UTC, kittywhiskers commented on .gitlab-ci.yml
> +    XCODE_VERSION: 12.1
Thanks for the fix! Odd how CI would behave like that 🙁

2021-10-05 11:57 UTC, UdjinM6 approved these changes
utACK

2021-10-05 16:05 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-10-05 16:05 UTC, merged