Compressed headers implementation.
dashpay/dash pull request #4497
Opened 2021-10-09 12:23 UTC by gabriel-bjg

This pull request aims to implement compressed headers support. Initial proposal can be found [here](https://github.com/willcl-ark/compressed-block-headers/blob/v1.0/compressed-block-headers.adoc), but the current implementation contains one different part: The first header in a `headers2` msg is always uncompressed (it contains the full `nBits`, `timestamp`, `version` and `prev_block_hash`). Otherwise, the following problem may arise:
	A peer (let’s name it P1) receiving headers from 2 different peers (P2 and P3) may not be able to correctly identify the previous block of the first header in a headers2 msg. The above scenario exemplifies such a case:

```
# Request block header from test_node
last_known_block = int(self.nodes[0].getbestblockhash(), 16)
block_a = self.mine_blocks(1)
inv_node.check_last_inv_announcement(inv=[block_a])
test_node.check_last_inv_announcement(inv=[block_a])
test_node.send_get_headers(locator=[last_known_block], hashstop=block_a)
test_node.wait_for_header(block_a)

# Request block header from inv_node
block_b = self.mine_blocks(1)
inv_node.check_last_inv_announcement(inv=[block_b])
test_node.check_last_inv_announcement(inv=[block_b])
inv_node.send_get_headers(locator=[block_a], hashstop=block_b)
inv_node.wait_for_header(block_b)

# At this point, both test_node and inv_node are not on "first connection" with our node as
# both of them sent headers to us
# According to requirements, after the "first connection" headers should be compressed
block_c = self.mine_blocks(1)
inv_node.check_last_inv_announcement(inv=[block_c])
test_node.check_last_inv_announcement(inv=[block_c])
test_node.send_get_headers(locator=[block_b], hashstop=block_c)
test_node.wait_for_header(block_c)  # supposing that the header we receive here is compressed, we should
                                    # decompress it against block_b (as that's the previous block), but the
                                    # last block received  from peer "test_node" is block_a
```

If we keep track of the last block header received from each peer, the above case is problematic as we will wrongly identify the previous block. After some discussions with @UdjinM6 we decided to send the first header uncompressed for now.

Thus, this pull request contains the following updates:
- First header is always compressed in a headers2 msg
- Version is uncompressed if it’s not matched within the last 7 headers block to be sent in the current msg
- Service flag to signal that the peer supports compressed header: `NODE_HEADERS_COMPRESSED`
- If compressed headers service is active, the peer will receive headers compressed
- If both `sendheaders` and `sendheaders2` are sent, the peer will respond with compressed headers
- Functional tests as for uncompressed headers (`p2p_sendheaders.py`)
- Updates regarding the existing functional tests to use the compressed headers if the `NODE_HEADERS_COMPRESSED` service flag is active

2021-12-29 19:36 UTC, PastaPastaPasta commented
@UdjinM6 what do you think? Should we review and hopefully merge this, or do you think we should delay it to v19? (I'm leaning towards merging in early v19)

2022-02-15 13:06 UTC, PastaPastaPasta commented
@UdjinM6 you have thoughts?

2022-02-15 15:48 UTC, PastaPastaPasta approved these changes
utACK for squash merge

I tested syncing uncompressed headers on testnet via this branch, and all worked as expected.

2022-02-16 08:34 UTC, UdjinM6 requested changes
Good job @gabriel-bjg ! 👍 

Tested it and it works as described but:
1. version bit definition and implementation here deviates from the initial proposal https://github.com/willcl-ark/compressed-block-headers/blob/v1.0/compressed-block-headers.adoc#version (blocks vs unique versions). We discussed it briefly back then but never arrived to any conclusion iirc. Should be easy to fix imo and should save some bytes for periods when hf signalling is starting/ending (i.e. lots of blocks with one version and few with the other), "other" headers will be uncompressed most of the time in our implementation when signalling rate is below 15%/above 85%. Thoughts @PastaPastaPasta ?
2. `rpc_net.py` fails, see 7c10d2c6b0
3. we could be a bit more accurate in logs (`getheaders` vs `getheaders2`), see e6addb802c

2022-02-17 13:56 UTC, gabriel-bjg commented
> Good job @gabriel-bjg ! 👍
> 
> Tested it and it works as described but:
> 
> 1. version bit definition and implementation here deviates from the initial proposal https://github.com/willcl-ark/compressed-block-headers/blob/v1.0/compressed-block-headers.adoc#version (blocks vs unique versions). We discussed it briefly back then but never arrived to any conclusion iirc. Should be easy to fix imo and should save some bytes for periods when hf signalling is starting/ending (i.e. lots of blocks with one version and few with the other), "other" headers will be uncompressed most of the time in our implementation when signalling rate is below 15%/above 85%. Thoughts @PastaPastaPasta ?
> 2. `rpc_net.py` fails, see [7c10d2c](https://github.com/dashpay/dash/commit/7c10d2c6b0efb88e3993ce44635326a2ae0519de)
> 3. we could be a bit more accurate in logs (`getheaders` vs `getheaders2`), see [e6addb8](https://github.com/dashpay/dash/commit/e6addb802ce7a1d673e047590804e978935de01b)

Thank you! I have updated the merge request to include points 2 and 3. Regarding point 1, once you confirm the changes with Pasta I will update the code.

2022-02-22 18:42 UTC, PastaPastaPasta commented
> > Good job @gabriel-bjg ! 👍
> > Tested it and it works as described but:
> > 
> > 1. version bit definition and implementation here deviates from the initial proposal https://github.com/willcl-ark/compressed-block-headers/blob/v1.0/compressed-block-headers.adoc#version (blocks vs unique versions). We discussed it briefly back then but never arrived to any conclusion iirc. Should be easy to fix imo and should save some bytes for periods when hf signalling is starting/ending (i.e. lots of blocks with one version and few with the other), "other" headers will be uncompressed most of the time in our implementation when signalling rate is below 15%/above 85%. Thoughts @PastaPastaPasta ?
> > 2. `rpc_net.py` fails, see [7c10d2c](https://github.com/dashpay/dash/commit/7c10d2c6b0efb88e3993ce44635326a2ae0519de)
> > 3. we could be a bit more accurate in logs (`getheaders` vs `getheaders2`), see [e6addb8](https://github.com/dashpay/dash/commit/e6addb802ce7a1d673e047590804e978935de01b)
> 
> Thank you! I have updated the merge request to include points 2 and 3. Regarding point 1, once you confirm the changes with Pasta I will update the code.

sure, fine by me

2022-03-04 17:41 UTC, PastaPastaPasta commented
bump

2022-03-04 19:00 UTC, gabriel-bjg commented
> bump
on it

2022-03-11 19:30 UTC, UdjinM6 approved these changes
LGTM, ACK (synced from genesis on testnet with no issues)

2022-03-11 19:32 UTC, PastaPastaPasta commented on test/functional/rpc_net.py
> +    NODE_HEADERS_COMPRESSED
```suggestion
    NODE_HEADERS_COMPRESSED,
```

2022-03-11 19:33 UTC, PastaPastaPasta approved these changes
re-utACK

2022-03-11 19:38 UTC, UdjinM6 approved these changes
re-ACK

2022-03-11 19:39 UTC, merged

2022-03-17 13:37 UTC, ogabrielides commented
@PastaPastaPasta @UdjinM6 @gabriel-bjg It seems that this thing broke down malort when we added some extra mns on the network.
They all got stuck at block 1 while printing `invalid header received`.
Same when you try to sync local node on malort.

2022-03-21 08:03 UTC, gabriel-bjg commented
> @PastaPastaPasta @gabriel-bjg It would be great to have a version of the doc this started from updated with the details of this specific implementation.

I can do that, please tell me where should I do it (repository, file path).

2022-04-21 19:11 UTC, thephez commented
@gabriel-bjg Have you had an opportunity to work on this?

2022-04-23 10:48 UTC, gabriel-bjg commented
> @gabriel-bjg Have you had an opportunity to work on this?

Yes, I will finish it up and provide a PR in the following days.

2022-06-06 18:18 UTC, thephez commented
@PastaPastaPasta @gabriel-bjg @UdjinM6 I've converted the original doc to the markdown format we typically use and updated some sections to get the ball rolling, but it needs dev input to add/update things that are missing or incorrect. My work can be found here: https://github.com/dashpay/dips/pull/113.