merge bitcoin#15039: Avoid leaking locktime fingerprint when anti-fee-sniping
dashpay/dash pull request #4513
Opened 2021-10-12 16:28 UTC by kittywhiskers

### Additional information

* This pull request's major backports (https://github.com/bitcoin/bitcoin/pull/14146 and https://github.com/bitcoin/bitcoin/pull/14437) done by @PastaPastaPasta 

* https://github.com/bitcoin/bitcoin/pull/15288 only includes the range between 80f52a2267f44a9cae4440615df3ff989be1579c and 00dfb2a440b94a24b61cafb519fb122f6a0ae176 (excluding bdc6628683197945326cbdfea3f53ec0b7d1949f)

2021-10-18 23:29 UTC, PastaPastaPasta commented
tests failing

2021-10-31 19:54 UTC, PastaPastaPasta requested changes
NACK, please open this as a new PR

2021-11-01 05:12 UTC, kittywhiskers commented
Superseded by #4558

2021-11-01 05:12 UTC, closed without merging

2024-03-18 23:36 UTC, Jzchito reviewed
help