Backports 0.19 pr3
dashpay/dash pull request #4524
Opened 2021-10-19 02:44 UTC by Munkybooty

2021-11-12 20:29 UTC, UdjinM6 requested changes
Looks good overall but pls redo 15696 (the code in question https://github.com/dashpay/dash/pull/4524#discussion_r733054282 was merged via https://github.com/dashpay/dash/pull/4484/commits/fce74ffd0c539baf5e9660f31782aa3e70923fc5) and squash 15840 fixes

2021-11-13 15:40 UTC, UdjinM6 commented
should redo 15949 - it should be applied _after_ 15696

2021-11-15 21:08 UTC, UdjinM6 requested changes

2021-11-15 21:08 UTC, UdjinM6 commented on src/wallet/rpcdump.cpp
> +                .ToString() +
16071: drop these lines

2021-11-19 00:16 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-11-20 20:30 UTC, UdjinM6 approved these changes
utACK

2021-11-20 20:30 UTC, merged