Backports 0.19 pr6
dashpay/dash pull request #4566
Opened 2021-11-04 13:18 UTC by Munkybooty

This pr also adds a functional test mempool_package_onemore.py and i haven't been able to get it to pass.

2021-11-19 00:23 UTC, PastaPastaPasta reviewed
lgtm, two changes

2021-11-19 00:23 UTC, PastaPastaPasta commented on contrib/guix/README.md
> +# Bootstrappable Bitcoin Core Builds
drop 15277 for now, maybe open in new PR, it will require significantly more review and changes

2021-11-19 00:23 UTC, PastaPastaPasta commented on src/protocol.cpp
> -    case NODE_XTHIN:           return "XTHIN";
squash 16380

2021-11-20 21:00 UTC, UdjinM6 requested changes

2021-11-29 04:37 UTC, UdjinM6 requested changes

2021-11-29 04:37 UTC, UdjinM6 commented on configure.ac
> +  BITCOIN_QT_CONFIGURE([$use_pkgconfig])
16338: the idea was to move some qt config code into `else` I think, so
```suggestion
  BITCOIN_QT_INIT

  dnl sets $bitcoin_enable_qt, $bitcoin_enable_qt_test, $bitcoin_enable_qt_dbus
  BITCOIN_QT_CONFIGURE([5.5.1])

  dnl Keep a copy of the original $QT_INCLUDES and use it when invoking qt's moc
  QT_INCLUDES_UNSUPPRESSED=$QT_INCLUDES
  if test x$suppress_external_warnings != xno ; then
    QT_INCLUDES=SUPPRESS_WARNINGS($QT_INCLUDES)
    QT_DBUS_INCLUDES=SUPPRESS_WARNINGS($QT_DBUS_INCLUDES)
    QT_TEST_INCLUDES=SUPPRESS_WARNINGS($QT_TEST_INCLUDES)
  fi
```

and drop similar/corresponding lines (1158-1170 in the original file).

2021-11-30 04:28 UTC, UdjinM6 approved these changes
LGTM, utACK

2021-11-30 05:43 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-11-30 05:44 UTC, merged