Backports 0.19 pr10
dashpay/dash pull request #4615
Opened 2021-12-09 18:37 UTC by Munkybooty

2021-12-12 04:55 UTC, PastaPastaPasta requested changes

2021-12-12 04:55 UTC, PastaPastaPasta commented on doc/bips.md
> -* [`BIP 68`](https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki): Sequence locks have been implemented as of **v0.12.1**  ([PR #7184](https://github.com/bitcoin/bitcoin/pull/7184)), and h
17197: DNM don't do PRs when bitcoin does backports to an earlier version (unless strictly necessary)

2021-12-12 04:55 UTC, PastaPastaPasta commented on src/Makefile.am
> -	$(AM_V_at) READELF=$(READELF) CPPFILT=$(CPPFILT) $(PYTHON) $(top_srcdir)/contrib/devtools/symbol-check.py < $(bin_PROGRAMS)
17858: again

2021-12-12 04:55 UTC, PastaPastaPasta commented on src/test/cuckoocache_tests.cpp
> +#include <deque>
17988: again, also this breaks linters

2021-12-12 04:55 UTC, PastaPastaPasta commented on src/qt/walletview.h
> -    QProgressDialog *progressDialog;
18084: again re bitcoin backports

2021-12-12 04:55 UTC, PastaPastaPasta commented on src/psbt.cpp
> -    int prevout_index = tx->vin[input_index].prevout.n;
18079: again is a btc backport

2021-12-17 16:37 UTC, UdjinM6 requested changes

2021-12-23 01:12 UTC, Munkybooty commented on doc/bips.md
> +* [`BIP 70`](https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki) [`71`](https://github.com/bitcoin/bips/blob/master/bip-0071.mediawiki) [`72`](https://github.com/bitcoin/bips/blob/master/
would i just be better off just saying that it is enabled by default?
 I'm not sure which version number to write for it or pr if i were to do that.

2021-12-23 01:22 UTC, Munkybooty commented
whoops, i added back too much

2021-12-25 20:53 UTC, UdjinM6 requested changes

2021-12-25 20:53 UTC, UdjinM6 commented on build-aux/m4/ax_boost_base.m4
> +    dnl this location is chosen if boost libraries are installed with the --layout=system option
432098c99381e564a3796663510534ed48e76e50: this patch was never merged into master and the issue was fixed via 18558 (which we backported already), see 18501

2021-12-25 20:53 UTC, UdjinM6 commented on doc/bips.md
> +* [`BIP 70`](https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki) [`71`](https://github.com/bitcoin/bips/blob/master/bip-0071.mediawiki) [`72`](https://github.com/bitcoin/bips/blob/master/
15584 wasn't backported yet. I'd just drop 16997 for now.

2021-12-28 21:37 UTC, UdjinM6 approved these changes
utACk

2021-12-29 19:23 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-12-29 19:23 UTC, merged