Remove KeePass integration
dashpay/dash pull request #4628
Opened 2021-12-18 21:54 UTC by PastaPastaPasta

This integration is not actively supported. It has zero tests, little documentation, and has not really been actively maintained. As far as I can tell, noone uses this integration, and even if they do, they will simply have to copy/paste password from keepass instead of using this integration.

2021-12-19 08:36 UTC, kittywhiskers commented
Concept ACK.

2021-12-19 08:37 UTC, kittywhiskers reviewed
Concept ACK

2021-12-21 10:59 UTC, UdjinM6 requested changes

2021-12-22 09:52 UTC, UdjinM6 approved these changes
utACK

2021-12-22 09:53 UTC, merged