Backports 0.19 pr11
dashpay/dash pull request #4632
Opened 2021-12-21 04:50 UTC by Munkybooty

I'm unable to build so this may be my worst pr yet. apologies in advance for that if there is a lot of trivial errors that have been missed.

2021-12-22 09:56 UTC, UdjinM6 requested changes

2021-12-23 18:38 UTC, UdjinM6 requested changes

2021-12-23 18:38 UTC, UdjinM6 commented on test/functional/feature_shutdown.py
> +        wait_until(lambda: len(self.nodes[0].getrpcinfo()['active_commands']) == 2)
14958: requires 14982

2021-12-25 21:07 UTC, UdjinM6 requested changes

2021-12-25 21:07 UTC, UdjinM6 commented on src/rpc/server.cpp
> +                .ToString()
14982: add missing parts from 14987 we backported earlier
```suggestion
                "\nReturns details of the RPC server.\n",
                {},
                RPCResults{},
                RPCExamples{""},
            }.ToString()
```

2021-12-25 21:07 UTC, UdjinM6 commented on doc/release-notes-15637.md
> +In getmempoolancestors, getmempooldescendants, getmempoolentry and getrawmempool RPCs, to be consistent with the returned value and other RPCs such as getrawtransaction, vsize has been added and size
15637: this backport is also a part of #4609

2021-12-28 21:39 UTC, UdjinM6 approved these changes
utACK

2021-12-29 19:32 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-12-29 19:32 UTC, merged