Backports 0.19 guix
dashpay/dash pull request #4634
Opened 2021-12-21 18:40 UTC by Munkybooty

2021-12-22 09:58 UTC, UdjinM6 requested changes

2021-12-22 09:58 UTC, UdjinM6 commented on depends/packages/qt.mk
> +  sed -i.old "s/error(\"failed to parse default search paths from compiler output\")/\!darwin: error(\"failed to parse default search paths from compiler output\")/g" qtbase/mkspecs/features/toolchai
15277:
```suggestion
  sed -i.old "s/error(\"failed to parse default search paths from compiler output\")/\!darwin: error(\"failed to parse default search paths from compiler output\")/g" qtbase/mkspecs/features/toolchain.prf && \
```

2021-12-25 21:10 UTC, UdjinM6 approved these changes
utACK assuming we are going to dashify this later

2021-12-26 20:10 UTC, PastaPastaPasta commented
@Munkybooty do future (non-guix) backports rely on this? Or can we delay this until v19?

2021-12-26 21:45 UTC, Munkybooty commented
I think we should be safe delaying this, all the files are basically isolated and guix seems to be untouched until v20 backports. The only merge conflicts I can see appearing are with qt.mk other than that, it should be fine

2022-02-16 08:47 UTC, UdjinM6 requested changes

2023-04-10 12:38 UTC, knst commented
superseeded by:
 - https://github.com/dashpay/dash/pull/5194 
 - https://github.com/dashpay/dash/pull/5237
 - https://github.com/dashpay/dash/pull/5285

2023-04-10 12:38 UTC, closed without merging