Optimize linters
dashpay/dash pull request #4637
Opened 2021-12-22 16:05 UTC by PastaPastaPasta

This branch achieves a simple 50% speedup for ./test/lint/lint-all.sh (on my 8 thread laptop), and 28% speedup in lint-circular-dependencies.sh, which doesn't make make sense since I haven't actually made any practical changes(just made into functions). Almost all of the time is spent in `handle_module`, so if anyone wants to optimize further, focus on that method. My original plan was to multi-thread it, but that appears non-trivial

The speedup 

This branch
```
lint-all.sh
real    0m44.096s
user    4m6.083s
sys     0m6.241s

lint-circular-dependencies.sh 
real    0m23.161s
user    0m22.997s
sys     0m0.087s
```
develop
```
lint-all.sh
real    1m22.912s
user    4m10.978s
sys     0m10.668s

lint-circular-dependencies.sh 
real    0m32.472s
user    0m32.352s
sys     0m0.076s
```

2021-12-25 22:02 UTC, UdjinM6 requested changes
👍 
pls see 75c9c81d850bd1bcd8e52f1f893a87c9d20e50cc

2021-12-26 20:09 UTC, PastaPastaPasta commented
I'm concerned about using parallel in CI due to the fact that you no longer are able to tell what linter caused the error...

Maybe if the parallel run fails at all (ie b/c not present or b/c linter failed) then we run non-parallel?

2021-12-28 21:45 UTC, UdjinM6 commented
Good point. How about using `--joblog` 2a59e0d5c7?

2021-12-30 16:33 UTC, UdjinM6 approved these changes
~ut~ACK

2021-12-30 16:34 UTC, merged