Backports 0.18 pr19
dashpay/dash pull request #4642
Opened 2021-12-28 21:13 UTC by Munkybooty

There were many test failures that occurred due to #15419, i managed to significantly reduce the amount. However some functional tests still fail. I'm not sure what remains to be fixed.

2022-02-22 19:26 UTC, UdjinM6 requested changes
pls see below + https://github.com/UdjinM6/dash/commits/pr4642

2022-02-24 03:41 UTC, Munkybooty commented on src/Makefile.test.include
> +	$(BENCH_BINARY)
`$(BENCH_BINARY) -evals=1 -scaling=0 > /dev/null` had continually thrown errors at me I'm not sure what to do in that regard

2022-02-24 12:02 UTC, UdjinM6 requested changes

2022-05-01 11:37 UTC, UdjinM6 commented on test/functional/test_framework/test_framework.py
> +            n.importprivkey(privkey=n.get_deterministic_priv_key().key, label='coinbase')
Still not fixed. I'd suggest dropping 14631 for now and backporting it together with 14468 sometimes later.

2022-05-11 18:31 UTC, UdjinM6 requested changes

2022-05-11 18:31 UTC, UdjinM6 commented on src/rpc/rawtransaction.cpp
> +                "If verbose is 'false' or omitted, returns a string that is serialized, hex-encoded data for 'txid'.\n",
15477: this looks different in the original PR

2022-05-11 18:31 UTC, UdjinM6 commented on src/Makefile.bench.include
> +bench_bench_dash_LDADD += $(BACKTRACE_LIB) $(BOOST_LIBS) $(BDB_LIBS) $(MINIUPNPC_LIBS) $(NATPMP_LIBS) $(BLS_LIBS) $(GMP_LIBS)
14212: should only drop the second pair, the first one was added via 15288 and should be kept i.e.
```suggestion
bench_bench_dash_LDADD += $(BACKTRACE_LIB) $(BOOST_LIBS) $(BDB_LIBS) $(EVENT_PTHREADS_LIBS) $(EVENT_LIBS) $(MINIUPNPC_LIBS) $(NATPMP_LIBS) $(BLS_LIBS) $(GMP_LIBS)
```

2022-05-11 18:31 UTC, UdjinM6 commented on src/qt/bitcoingui.cpp
> +void BitcoinGUI::setHDStatus(bool privkeyDisabled, int hdEnabled)
13966: https://github.com/dashpay/dash/pull/4642#discussion_r811417386

2022-05-18 19:37 UTC, UdjinM6 commented
pls see 2d91636a83 and 0423c5dfdd

2022-05-23 16:10 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-05-29 20:03 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-05-29 20:05 UTC, merged