Merge bitcoin#14890 and bitcoin#15390
dashpay/dash pull request #4643
Opened 2021-12-29 01:04 UTC by dzutte-cpp

2021-12-30 15:34 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2021-12-30 16:40 UTC, UdjinM6 requested changes

2021-12-30 16:40 UTC, UdjinM6 commented on test/functional/rpc_rawtransaction.py
> +            self.nodes[2].createrawtransaction(inputs=[{'txid': txid, 'vout': 9}], outputs=[{address: 99}, {address2: '99'}, {'data': '99'}]),
14890:
```suggestion
            self.nodes[2].createrawtransaction(inputs=[{'txid': txid, 'vout': 9}], outputs=[{address: 99}, {address2: 99}, {'data': '99'}]),
```

2022-01-03 12:27 UTC, UdjinM6 approved these changes
utACK

2022-01-10 01:40 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-01-10 02:03 UTC, merged