Merge #14021: Import key origin data through descriptors in importmulti
dashpay/dash pull request #4651
Opened 2021-12-31 02:22 UTC by vijaydasmp

cb3511b9d Add release notes for importing key origin info change (Andrew Chow)
4c75a69f3 Test importing descriptors with key origin information (Andrew Chow)
02d6586d7 Import KeyOriginData when importing descriptors (Andrew Chow)
3d235dff5 Implement a function to add KeyOriginInfo to a wallet (Andrew Chow)
eab63bc26 Store key origin info in key metadata (Andrew Chow)
345bff601 Remove hdmasterkeyid (Andrew Chow)
bac8c676a Add a method to CWallet to write just CKeyMetadata (Andrew Chow)
e7652d3f6 Add WriteHDKeypath function and move *HDKeypath to util/bip32.{h,cpp} (Andrew Chow)
c45415f73 Refactor keymetadata writing to a separate method (Andrew Chow)

Pull request description:

  This PR allows for key origin data as defined by the descriptors document to be imported to the wallet when importing a descriptor using `importmulti`. This allows the `walletprocesspsbt` to include the BIP 32 derivation paths for keys that it is watching that are from a different HD wallet.

  In order to make this easier to use, a new field `hdmasterkeyfingerprint` has been added to `getaddressinfo`. Additionally I have removed `hdmasterkeyid` as was planned. I think that this API change is fine since it was going to be removed in 0.18 anyways. `CKeyMetadata` has also been extended to store key origin info to facilitate this.

Tree-SHA512: 9c7794f3c793da57e23c5abbdc3d58779ee9dea3d53168bb86c0643a4ad5a11a446264961e2f772f35eea645048cb60954ed58050002caee4e43cd9f51215097

2022-02-08 16:16 UTC, Munkybooty commented
Hey Vijay,

Is there an update on the status of this pr?

2022-02-09 05:18 UTC, vijaydasmp commented
Hi Munkybooty,

I am not keeping well , couldn't devote time , probably work on it
tomorrow,  if you are blocked ,please feel free to take over

On Tue, 8 Feb 2022, 21:46 Munkybooty, ***@***.***> wrote:

> Hey Vijay,
>
> Is there an update on the status of this pr?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dashpay/dash/pull/4651#issuecomment-1032799227>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR5IIQIGWRCF2E54NOR6WTU2E6VJANCNFSM5LAUEPXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-29 18:26 UTC, vijaydasmp commented
Hello @UdjinM6  please review

2022-03-29 21:36 UTC, PastaPastaPasta submitted a review, later dismissed
utACK for merging via merge commit

2022-03-30 00:16 UTC, UdjinM6 requested changes

2022-03-30 00:16 UTC, UdjinM6 commented on .travis.yml
> +      name: 'macOS 10.10  [GOAL: deploy] [no functional tests]'
15308: should keep 10.12

2022-03-30 00:16 UTC, UdjinM6 commented on src/rpc/server.cpp
> +            " \"logpath\": \"xxx\" (string) The complete file path to the debug log\n"
16332: requires 15483

2022-03-30 20:24 UTC, UdjinM6 approved these changes
utACK

2022-04-01 05:19 UTC, PastaPastaPasta approved these changes
utACK for merge via merge commit

2022-04-01 05:19 UTC, merged