actions: introduce handle_potential_conflicts.py to only warn on true conflicts. Fail CI when there is a conflict
dashpay/dash pull request #4655
Opened 2022-01-04 22:04 UTC by PastaPastaPasta

The CI action will now run on any any change to the PR, or a review on the PR, such that the conflict information is hopefully as up to date as possible.

2022-01-09 11:46 UTC, UdjinM6 requested changes

2022-01-10 01:36 UTC, PastaPastaPasta commented
should be resolved :) :see_no_evil:

2022-01-10 18:31 UTC, UdjinM6 requested changes

2022-01-11 00:56 UTC, UdjinM6 requested changes

2022-01-11 00:56 UTC, UdjinM6 commented on .github/workflows/handle_potential_conflicts.py
> +            conflicts: [ '.github/workflows/testfile' ] } ] }'''
```suggestion
'''{ pull_number: 26,
    conflictPrs:
        [ { number: 25,
            files: [ '.github/workflows/testfile' ],
            conflicts: [ '.github/workflows/testfile' ] }
        { number: 24,
            files: [ '.github/workflows/testfile' ],
            conflicts: [ '.github/workflows/testfile' ] } ] }'''
```

2022-01-13 14:26 UTC, UdjinM6 approved these changes
utACK, let's see if it works this time :D

2022-01-13 14:26 UTC, merged