evo: introduce IsTriviallyValid() to CheckPro*Tx objects with tests
dashpay/dash pull request #4660
Opened 2022-01-12 10:14 UTC by kittywhiskers

2022-01-13 13:18 UTC, thephez commented on src/test/evo_trivialvalidation.cpp
> +    // do nothing
Perhaps why this PR is only a draft :slightly_smiling_face:

2022-01-14 00:15 UTC, PastaPastaPasta commented on src/test/evo_trivialvalidation.cpp
> +    // do nothing
:see_no_evil:

2022-02-21 07:40 UTC, PastaPastaPasta reviewed
can you please make this 2 prs? the move-only stuff, and then the test additions? I think that'd be better (even though if maybe it was my idea originally to have the tests added here

2022-02-22 13:56 UTC, kittywhiskers commented
Done. See https://github.com/dashpay/dash/pull/4696

2022-02-27 17:03 UTC, PastaPastaPasta commented on src/test/evo_trivialvalidation.cpp
> +                    assert(tx.nType != TRANSACTION_PROVIDER_REGISTER);
why not use boost_check?

2022-02-27 17:45 UTC, kittywhiskers commented on src/test/data/trivially_invalid.json
> +]
Resolved.

2022-02-27 17:45 UTC, kittywhiskers commented on src/test/data/trivially_valid.json
> +]
Resolved.

2022-02-27 17:45 UTC, kittywhiskers commented on src/test/evo_trivialvalidation.cpp
> +            if (txType == "proregtx") {
https://stackoverflow.com/a/650218

2022-02-27 17:46 UTC, kittywhiskers commented on src/test/evo_trivialvalidation.cpp
> +                    assert(tx.nType != TRANSACTION_PROVIDER_REGISTER);
Resolved

2022-02-27 19:02 UTC, PastaPastaPasta commented on src/test/evo_trivialvalidation.cpp
> +                    assert(tx.nType != TRANSACTION_PROVIDER_REGISTER);
no you didn't :)

2022-02-28 05:37 UTC, kittywhiskers commented on src/test/evo_trivialvalidation.cpp
> +                    assert(tx.nType != TRANSACTION_PROVIDER_REGISTER);
Now I did :)

2022-03-04 17:43 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-03-04 18:31 UTC, UdjinM6 requested changes
pls see c2637f9f97097ae069264eb1be8082eaa364a55f + unit tests fail on mac with `std::invalid_argument: Relic library error` (same as here https://gitlab.com/dashpay/dash/-/jobs/2164370549#L2732 but on a different test)

2022-03-05 06:47 UTC, kittywhiskers commented
`Relic library error` failures seem unrelated to this PR

2022-03-05 17:06 UTC, PastaPastaPasta commented
> `Relic library error` failures seem unrelated to this PR but definitely warrants looking into

restarted windows ci build

2022-03-05 18:42 UTC, UdjinM6 commented
https://github.com/UdjinM6/dash/commit/a6254683093e5767878f9c0bf85463ae95bd08c5 should fix it

2022-03-05 19:57 UTC, PastaPastaPasta commented
> UdjinM6@a625468

How about https://github.com/dashpay/dash/commit/d1a7b4dd842f45ee7a7a37a55e0405d27f1db262?

2022-03-05 20:09 UTC, UdjinM6 commented
> > [UdjinM6/dash@a625468](https://github.com/UdjinM6/dash/commit/a625468)
> 
> How about [d1a7b4d](https://github.com/dashpay/dash/commit/d1a7b4dd842f45ee7a7a37a55e0405d27f1db262)?

👍

2022-03-05 20:39 UTC, PastaPastaPasta commented
Okay, I pushed to the branch @kittywhiskers

2022-03-05 20:39 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-03-05 21:51 UTC, UdjinM6 approved these changes
utACK

2022-03-06 06:54 UTC, merged