refactor: break circular dependencies(-13, +2)
dashpay/dash pull request #4670
Opened 2022-01-20 07:04 UTC by PastaPastaPasta

introduces specialtxman, which handles validation of special transactions, specialtx is now simply the primitive underlying type. This breaks a lot of the circular depends

Also removes an unneeded `#include <masternode/payments.h>` in net_processing.cpp, which resolves a circular dependency. (we know it's okay to remove b/c masternode/payments.h isn't included in any header files, and removing it doesn't break compilation)

2022-01-20 16:16 UTC, PastaPastaPasta reviewed
test

2022-01-20 19:16 UTC, UdjinM6 requested changes

2022-01-21 04:32 UTC, PastaPastaPasta commented on src/rpc/rpcevo.cpp
> +    if (!WITH_LOCK(cs_main, return CheckSpecialTx(CTransaction(tx), ::ChainActive().Tip(), state, ::ChainstateActive().CoinsTip()))) {
agree :) I didn't intend for that to be committed here

2022-01-21 09:02 UTC, PastaPastaPasta commented
I made some additional changes, breaking even more circular dependencies

2022-01-24 14:18 UTC, UdjinM6 approved these changes
utACK

2022-01-24 14:20 UTC, merged