refactor: fix numerous compilation warnings
dashpay/dash pull request #4682
Opened 2022-02-09 10:28 UTC by PastaPastaPasta

please see individual commits

2022-02-10 22:50 UTC, UdjinM6 requested changes

2022-02-10 22:50 UTC, UdjinM6 commented on src/wallet/wallet.cpp
> +    if (vecTally.size() == 0) return 0;
empty()

2022-02-10 22:50 UTC, UdjinM6 commented on src/coinjoin/client.cpp
> +        if (nSteps >= int{COINJOIN_ENTRY_MAX_SIZE}) break;
could make `nSteps` `size_t` instead (same for other similar cases)

2022-02-10 22:50 UTC, UdjinM6 commented on src/evo/cbtx.cpp
> +            if (v.size() == uint64_t(llmq_params.signingActiveQuorumCount)) {
`size_t(...)` maybe? or make `signingActiveQuorumCount` `size_t` (same for other `LLMQParams` members, not sure why we use `int` for them...)

2022-02-10 22:50 UTC, UdjinM6 commented on src/prevector.h
> +            if (v.size() != uint64_t(s)) {
why not `size_t`? (same for other similar cases below)

2022-02-10 22:50 UTC, UdjinM6 commented on src/llmq/signing_shares.cpp
> +    assert(attempt >= 0);
`attempt` could be `size_t` here and in `CSignedSession`

2022-02-11 06:00 UTC, PastaPastaPasta commented
see latest

2022-02-11 16:15 UTC, UdjinM6 approved these changes
utACK

2022-02-11 16:15 UTC, merged