test: skip test properly if zmq missing
dashpay/dash pull request #4684
Opened 2022-02-10 20:43 UTC by thephez

Not sure if this is a proper way to fix it. I discovered that `interface_zmq_dash.py` failed with an error if pyzmq wasn't installed unlike `interface_zmq.py` which simply gets skipped in that scenario as shown here:

interface_zmq.py                      | ○ Skipped | 1 s
interface_zmq_dash.py                 | ✖ Failed  | 0 s

This change moves the imports below where the check for the module occurs so the test skips instead of throwing an error. It appeared to work properly for me. Note that the bitcoin-based zmq test also has a double import of zmq although it's structured a little differently.

2022-02-10 21:55 UTC, UdjinM6 requested changes

2022-02-10 21:55 UTC, UdjinM6 commented on test/functional/interface_zmq_dash.py
> +        import zmq
this looks excessive and it works for me without this line, so maybe
```suggestion
```

2022-02-11 16:54 UTC, UdjinM6 commented on test/functional/interface_zmq_dash.py
> +        import zmq
Hmm, right. I probably messed it up somehow 🙈

2022-02-11 21:32 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-02-11 21:33 UTC, merged