Crash fix
dashpay/dash pull request #4697
Opened 2022-02-23 08:39 UTC by ogabrielides

2022-02-23 18:15 UTC, UdjinM6 requested changes

2022-02-24 10:08 UTC, ogabrielides commented
@UdjinM6 Implemented suggestions

2022-02-24 12:05 UTC, UdjinM6 approved these changes
👍 
utACK

2022-02-24 17:08 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-02-24 17:08 UTC, merged