backport: trivial backports Feb 26 2022
dashpay/dash pull request #4709
Opened 2022-02-27 03:07 UTC by PastaPastaPasta

(this will likely fail ci, have only built locally)

2022-03-06 19:41 UTC, UdjinM6 requested changes

2022-03-07 15:40 UTC, PastaPastaPasta commented on doc/rapidcheck.md
> +# RapidCheck property-based testing for Bitcoin Core
dropped

2022-03-07 15:40 UTC, PastaPastaPasta commented on src/qt/bitcoingui.cpp
> +    labelWalletHDStatusIcon->hide();
dropped

2022-03-07 15:41 UTC, PastaPastaPasta commented on src/Makefile.test.include
> +test_fuzz_integer_LDFLAGS = $(RELDFLAGS) $(AM_LDFLAGS) $(LIBTOOL_APP_LDFLAGS)
applied

2022-03-07 15:41 UTC, PastaPastaPasta commented on src/Makefile.test.include
> +test_fuzz_block_LDFLAGS = $(RELDFLAGS) $(AM_LDFLAGS) $(LIBTOOL_APP_LDFLAGS)
applied

2022-03-07 23:52 UTC, UdjinM6 approved these changes
utACK

2022-03-07 23:54 UTC, merged