Add function to validate DSTX message
dashpay/dash pull request #4713
Opened 2022-03-01 02:12 UTC by rkarthik2k21

This PR is part of addressing issue 4078 - Test DSTX validation during propogation #4078 (https://github.com/dashpay/dash/issues/4078) 

A function ValidateDSTX() has been added that essentially captures the existing code to validate a DSTX message. A unit test can be created to call this method in order for testing DSTX validation

2022-03-04 17:43 UTC, PastaPastaPasta commented
still needs rebase

2022-03-05 01:59 UTC, rkarthik2k21 commented
I am not sure what went wrong. I created this branch from develop (and felt I had done a pull before that). I can create a new PR

2022-03-05 04:33 UTC, PastaPastaPasta commented
You'll need to fetch latest develop. something like `git fetch upstream` assuming you've done `git remote add upstream https://github.com/dashpay/dash`

Then `git rebase upstream/develop` and `git push -f` should fix it

2022-03-25 23:35 UTC, UdjinM6 requested changes

2022-03-25 23:35 UTC, UdjinM6 commented on src/net_processing.cpp
> +<<<<<<< HEAD
```suggestion
```

2022-03-25 23:35 UTC, UdjinM6 commented on src/net_processing.cpp
> +>>>>>>> Add function to validate DSTX message
```suggestion
```

2022-03-29 12:06 UTC, rkarthik2k21 commented on src/net_processing.cpp
> +<<<<<<< HEAD
Done

2022-03-29 12:06 UTC, rkarthik2k21 commented on src/net_processing.cpp
> +>>>>>>> Add function to validate DSTX message
Done

2022-03-29 23:55 UTC, UdjinM6 requested changes

2022-03-30 00:43 UTC, UdjinM6 commented on src/net_processing.cpp
> +           // Validate DSTX and return bRet if we need to return from here
```suggestion
           // Validate DSTX and return bRet if we need to return from here
```

2022-03-30 01:14 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-04-02 01:02 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-04-02 01:02 UTC, merged