qt: Fix Repair tab
dashpay/dash pull request #4715
Opened 2022-03-04 13:11 UTC by UdjinM6

It was broken by https://github.com/dashpay/dash/pull/4586/commits/7b8ddda8ea784f764e8790a27d7133251aec3ac5. To reproduce the issue: open testnet wallet (via `--testnet` in cmd line), open Repair tab, click "Upgrade wallet" (the less harmful one) - wallet restarts with `-upgradewallet` but no `--testnet` so it's a mainnet wallet now.

2022-03-04 17:40 UTC, PastaPastaPasta requested changes

2022-03-04 17:40 UTC, PastaPastaPasta commented on src/qt/rpcconsole.cpp
> +        for (const auto& value : key_pair.second) {
nit, please use structured binding and name key_pair.first and key_pair.second

2022-03-05 17:01 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-03-05 19:44 UTC, merged

2022-03-07 13:30 UTC, thephez commented
Ahah, this probably explains why my attempt to reindex a devnet recently resulted in a mainnet reindex :man_facepalming: