Client func tests
dashpay/dash pull request #4730
Opened 2022-03-15 22:49 UTC by Munkybooty

Going to be opening this as a draft because i am not finished but it will probably be better to have more eyes on it than me continuously roadblocking myself at the moment

2022-06-07 19:38 UTC, UdjinM6 requested changes
no need for `nVersion < MIN_PEER_PROTO_VERSION` check, such peers are disconnected right away and should never get this far

2022-06-08 09:59 UTC, UdjinM6 requested changes

2022-06-08 09:59 UTC, UdjinM6 commented on src/coinjoin/client.cpp
> +
```suggestion
```

2022-06-08 09:59 UTC, UdjinM6 commented on src/coinjoin/client.cpp
> +
```suggestion
```

2022-06-08 09:59 UTC, UdjinM6 commented on src/coinjoin/client.cpp
> +
```suggestion
```

2022-06-08 10:01 UTC, UdjinM6 approved these changes
👍 
utACK

2022-06-11 04:05 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-06-11 04:05 UTC, merged