Mechanical/Manual RPC backports
dashpay/dash pull request #4734
Opened 2022-03-19 20:18 UTC by Munkybooty

2022-03-29 16:25 UTC, Munkybooty commented
I need to clean up [27a055d](https://github.com/dashpay/dash/pull/4734/commits/27a055d710c54970a60cab773d50634fbade42ee), the commit message should say why, but It does need to be fixed, as per Pasta's request i will batch the changes for easier review

2022-04-08 21:29 UTC, Munkybooty commented
I honestly am unsure of what all is needed to fix the breakages
@UdjinM6 any thoughts?

2022-04-14 22:38 UTC, UdjinM6 requested changes
Well.. some parts are missing and some changes are excessive :) You also need to revert few things and adjust dash-specific rpcs to make them compatible with `Check()`. Pls see https://github.com/UdjinM6/dash/commits/pr4734. (these changes are huge so pretty sure I messed up somewhere too, pls double check/test)

2022-04-19 05:50 UTC, Munkybooty commented
So I implemented the changes and feature_llmq_rotations has just decided to die

2022-04-19 13:26 UTC, PastaPastaPasta commented
Well, it seems like you messed up the `quorum` rpc command. See 
```
2022-04-16T20:50:22.877000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/test_framework/test_framework.py", line 234, in main
    self.run_test()
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/feature_llmq_rotation.py", line 67, in run_test
    (quorum_info_0_0, quorum_info_0_1) = self.mine_cycle_quorum(llmq_type_name=llmq_type_name, llmq_type=llmq_type)
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/test_framework/test_framework.py", line 1456, in mine_cycle_quorum
    quorum_rotation_info = self.nodes[0].quorum("rotationinfo", best_block_hash, 0, False)
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/builds/dashpay/dash/build-ci/dashcore-linux32/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: quorum "command"
Set of commands for quorums/LLMQs.
To get help on individual commands, use "help quorum command".

Available commands:
  list              - List of on-chain quorums
  info              - Return information about a quorum
  dkgsimerror       - Simulates DKG errors and malicious behavior
  dkgstatus         - Return the status of the current DKG process
  memberof          - Checks which quorums the given masternode is a member of
  sign              - Threshold-sign a message
  verify            - Test if a quorum signature is valid for a request id and a message hash
  hasrecsig         - Test if a valid recovered signature is present
  getrecsig         - Get a recovered signature
  isconflicting     - Test if a conflict exists
  selectquorum      - Return the quorum that would/should sign a request
  getdata           - Request quorum data from other masternodes in the quorum
  rotationinfo      - Request quorum rotation information

Arguments:
1. command    (string, required) The command to execute
 (-1)
2022-04-16T20:50:22.929000Z TestFramework (INFO): Stopping nodes
2022-04-16T20:50:23.596000Z TestFramework (WARNING): Not cleaning up dir /builds/dashpay/dash/build-ci/dashcore-linux32/testdatadirs/test_runner_âˆ‹_ðŸƒ_20220416_214406/feature_llmq_rotation_131
2022-04-16T20:50:23.596000Z TestFramework (ERROR): Test failed. Test logging available at /builds/dashpay/dash/build-ci/dashcore-linux32/testdatadirs/test_runner_âˆ‹_ðŸƒ_20220416_214406/feature_llmq_rotation_131/test_framework.log
```

2022-04-20 20:56 UTC, Munkybooty commented
I wanna say I fixed it but now `p2p_instantsend.py` is broken, it's progress though! One thing fixed and another thing broke

2022-04-21 02:11 UTC, UdjinM6 commented
> I wanna say I fixed it but now `p2p_instantsend.py` is broken, it's progress though! One thing fixed and another thing broke

this should be fixed by #4790, pls rebase

2022-04-25 19:12 UTC, UdjinM6 commented
pls see ff954e0add

2022-05-01 14:20 UTC, UdjinM6 requested changes

2022-05-01 14:22 UTC, UdjinM6 commented on src/rpc/rpcquorums.cpp
>      } else if (command == "rotationinfo") {
```suggestion
    } else if (command == "quorumrotationinfo") {
```

2022-05-12 20:10 UTC, UdjinM6 approved these changes
LGTM, utACK

(sooo many conflicting PRs...)

2022-05-12 20:24 UTC, Munkybooty commented
Totally forgot this thing has sat as a draft this whole time

2022-05-12 20:28 UTC, PastaPastaPasta approved these changes
utACK for squash merge

time to make everything else need rebase :D

2022-05-12 20:29 UTC, merged

2022-05-12 20:29 UTC, Munkybooty commented
Panic Mode