feat: add scriptPayout and scriptOperatorPayout to `protx diff` / CSimplifiedMNListEntry
dashpay/dash pull request #4740
Opened 2022-03-24 17:51 UTC by PastaPastaPasta

As requested by Ivan

2022-03-25 23:37 UTC, UdjinM6 requested changes

2022-03-26 17:43 UTC, QuantumExplorer commented
I would really like it if v18 was feature frozen at this point @PastaPastaPasta

2022-03-27 14:29 UTC, UdjinM6 commented
We could make `scriptPayout` and `scriptOperatorPayout` mem-only if we only need these fields in rpc and don't want to change `mnlistdiff` format 3e7d25ed. But it would still add mns with updated `scriptPayout` and/or `scriptOperatorPayout` to `mnList` (because of changes in `operator==`), so messages will be larger in these cases. Also, (light) nodes won't see any changes comparing to the data they already have and they might get confused. This can be fixed by tweaking `BuildSimplifiedDiff` 310114c7dd and extending `protx diff` params 055bad15d4 (to make sure we can get both results - 0. (default) matching p2p message and 1. with additional fields and items).

2022-06-21 16:39 UTC, PastaPastaPasta commented on src/evo/simplifiedmns.h
> +                obj.scriptOperatorPayout
What if we just remove it?

2022-06-21 16:55 UTC, UdjinM6 commented on src/evo/simplifiedmns.h
> +                obj.scriptOperatorPayout
remove what? serialization? i.e. like in https://github.com/dashpay/dash/commit/3e7d25ed0c0e192b484222c221dd1ca130dcf311? see https://github.com/dashpay/dash/pull/4740#issuecomment-1079943224 then :)

2022-06-23 00:48 UTC, PastaPastaPasta commented on src/evo/simplifiedmns.h
> +                obj.scriptOperatorPayout
Hmm, good idea :P see latest

2022-06-23 20:06 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-06-23 20:16 UTC, UdjinM6 commented
@PastaPastaPasta do we need this in v18? pls set the milestone (and "backport" label if needed)

2022-06-24 18:33 UTC, PastaPastaPasta commented
No we do not need this in v18 and I'd prefer adding another rpc change in this version.

2022-06-24 18:35 UTC, merged