Show penalty score in masternode rpc
dashpay/dash pull request #4751
Opened 2022-04-04 14:22 UTC by ogabrielides

2022-04-05 15:57 UTC, PastaPastaPasta requested changes
Can we add a test for this?

2022-04-05 21:40 UTC, UdjinM6 approved these changes
utACK

2022-04-06 16:45 UTC, kittywhiskers approved these changes
utACK

2022-04-06 21:50 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-04-06 21:50 UTC, merged