chore: bump MIN_PEER_PROTO_VERSION to 70215
dashpay/dash pull request #4764
Opened 2022-04-11 17:47 UTC by PastaPastaPasta

simplifies logic, removes branches

This protocol version is from v14 in May of 2019, should be more than safe to bump this in v18

2022-04-11 20:06 UTC, UdjinM6 requested changes
> should be more than safe to bump this in v18

this needs confirmation from ios/android mobile teams + see below

2022-04-11 20:06 UTC, UdjinM6 commented on src/version.h
> +static const int MIN_COINJOIN_PEER_PROTO_VERSION = 70215;
Should drop it 5d777b5a28 instead of bumping it imo

2022-04-12 13:40 UTC, PastaPastaPasta commented
> > should be more than safe to bump this in v18
> 
> this needs confirmation from ios/android mobile teams + see below

I've already cleared it with android and iOS, android has a small bit of an issue with it, maybe like 1-2% of installs, almost certainly all inactive. iOS has no issue with a bump at all

2022-04-12 17:55 UTC, UdjinM6 commented
> > > should be more than safe to bump this in v18
> > 
> > 
> > this needs confirmation from ios/android mobile teams + see below
> 
> I've already cleared it with android and iOS, android has a small bit of an issue with it, maybe like 1-2% of installs, almost certainly all inactive. iOS has no issue with a bump at all

ok, cool :) and what about https://github.com/dashpay/dash/pull/4764#discussion_r847691282?

2022-04-12 18:02 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-04-12 18:03 UTC, merged