Bp2007
dashpay/dash pull request #4792
Opened 2022-04-21 03:38 UTC by vijaydasmp

2022-04-23 18:37 UTC, vijaydasmp commented
Some Infra Issue going on
fatal: unsafe repository ('/builds/dashpay/dash' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /builds/dashpay/dash
section_end:1650684202:step_script

2022-06-11 04:09 UTC, PastaPastaPasta commented
Hi is this still draft?

2022-06-16 20:53 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commits/pr4792

2022-06-18 02:57 UTC, vijaydasmp commented
mac build is failing at rpc/blockchain.cpp:952:30: error: cannot call function 'blockheaderToJSON' while mutex 'cs_main' is held [-Werror,-Wthread-safety-analysis]     arrHeaders.push_back(blockheaderToJSON(::ChainActive().Tip(), pblockindex));
this appears to be an existing code

2022-06-18 18:28 UTC, UdjinM6 approved these changes
ACK

2022-06-19 05:08 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-06-19 05:08 UTC, PastaPastaPasta commented on src/interfaces/chain.cpp
> +    void getPackageLimits(unsigned int& limit_ancestor_count, unsigned int& limit_descendant_count) override
nit commit name should be `partial Merge...`

2022-06-19 05:12 UTC, merged