ci: isolate non-deterministic tests to its own distinct runner
dashpay/dash pull request #4793
Opened 2022-04-21 05:47 UTC by kittywhiskers

2023-04-05 08:25 UTC, ogabrielides commented
@kittywhiskers Can you write a quick description of the changes you made?

2023-04-05 11:30 UTC, ogabrielides reviewed
From my experience, the following tests are often failing hence could be moved to `NONDETERMINISTIC_SCRIPTS`:
`mempool_unbroadcast.py`, `rpc_net.py`, `interface_zmq_dash.py`

2023-04-06 09:57 UTC, kittywhiskers commented
Added `wallet_listreceivedby.py`, `p2p_addrv2_relay.py` based on previous CI failures

2023-04-06 13:26 UTC, UdjinM6 requested changes

2023-04-06 15:59 UTC, ogabrielides approved these changes
LGTM (Let's wait for CI :) )

2023-04-07 04:55 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-04-07 04:55 UTC, merged