backport: v0.20 pr1
dashpay/dash pull request #4821
Opened 2022-04-29 16:32 UTC by Munkybooty

2022-05-02 14:39 UTC, UdjinM6 requested changes
pls see below + https://github.com/UdjinM6/dash/commits/pr4821

2022-05-02 14:39 UTC, UdjinM6 commented on doc/bips.md
> +* [`BIP 68`](https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki): Sequence locks have been implemented as of **v0.12.1**  ([PR #7184](https://github.com/bitcoin/bitcoin/pull/7184)), and h
17111: requires 16060, drop

2022-05-02 14:39 UTC, UdjinM6 commented on test/functional/feature_block.py
> +    LegacySignatureHash,
17141: ok-ish but maybe DNM would be better

2022-05-16 15:40 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-05-16 21:42 UTC, UdjinM6 approved these changes
utACK

(nit: could squash fixes)

2022-05-17 16:35 UTC, PastaPastaPasta approved these changes
re-utACK

2022-05-17 20:03 UTC, UdjinM6 approved these changes
utACK

2022-05-17 20:12 UTC, merged