merge bitcoin#15141, 15437, 19219: auxiliary backports
dashpay/dash pull request #4830
Opened 2022-05-07 15:32 UTC by kittywhiskers

2022-06-12 11:15 UTC, UdjinM6 requested changes
pls see below + d7784a55ec49db7a799447c2986c4ad7878a9480

Also,
- e8d71fff8830103aae3625bfc86ae900f8f884ce and b94edd75b5a40f22252f91b8492bd3546cb6e521 are not backports and looks unrelated, should be in their own PRs imo
- 15141 and 19219 backports are large enough and pretty critical, I would prefer them in a separate PR/PRs
- not sure about 15437, I remember mobile teams were against bip61 removal https://github.com/dashpay/dash/pull/3414#discussion_r409574864. Pinging @QuantumExplorer @HashEngineering.

2022-06-12 14:05 UTC, kittywhiskers commented
* This pull request was made with https://github.com/dashpay/dash/pull/4829 in mind and so, attempted to meet all the dependencies that it needed.
  * I use the "auxiliary backports" tag as an opportunity to do miscellaneous, minor, unrelated and/or loose end (i.e. completion of partial) backports, that's why we have this trail mix, it's in the name:tm:.
* https://github.com/dashpay/dash/commit/e8d71fff8830103aae3625bfc86ae900f8f884ce was done here so that I can keep https://github.com/dashpay/dash/pull/4829 clean as it's already quite cluttered
* https://github.com/dashpay/dash/commit/b94edd75b5a40f22252f91b8492bd3546cb6e521 was done so that I can complete https://github.com/dashpay/dash/pull/4830/commits/5cb63f853e0fa063db94fa4fa2a02fb398f10afa (migration to `Check()` meant I was forced to bifurcate what is otherwise, essentially two distinct RPC functions) 
* Not opposed to splitting 15141 and 19219 backports, sounds reasonable to me. (pinging @PastaPastaPasta, thoughts? objections?)
* For 15437, am waiting on mobile team to give their opinion.

2022-06-12 14:06 UTC, kittywhiskers commented on test/functional/wallet_dump.py
> +
* In my defence, I tried 
  * Reverting the location of the `args.GetBoolArg` check
  * Reverting the PR itself and adding only the test to see if it's a regression (this was a belt-and-suspenders check if I'm not wrong)
  * Removing the GetBoolArg check entirely and letting `MaybeCompactWalletDB` always run its course
 
   None of the three worked and this seemed like the least worst way to go about it, at the time. Will un-comment code and cherry-pick fix, thanks!

2022-06-12 18:01 UTC, UdjinM6 commented
ok, I see. pls see 1d9d1b7aafe8667b2d8b2540d489827c92a6b4bb for more fixes

2022-06-13 09:13 UTC, kittywhiskers commented
Cherry-picked, squashed and updated!

2022-06-14 15:47 UTC, PastaPastaPasta commented on src/rpc/client.cpp
> +    { "sporkupdate", 1, "value" },
b94edd75b5a40f22252f91b8492bd3546cb6e521 needs a release notes, and really probably should be in it's own PR

2022-06-20 05:39 UTC, HashEngineering commented on doc/bips.md
> -* [`BIP 61`](https://github.com/bitcoin/bips/blob/master/bip-0061.mediawiki): The 'reject' protocol message (and the protocol version bump to 70002) was added in **v0.9.0** ([PR #3185](https://github
If BIP61 is removed completely, the mobile clients will need a means of detecting errors in a transaction based on the fact that a transaction never is mined into the blockchain.

Currently, the mobile clients depend on BIP61, so I would suggest that before BIP61 support is removed the mobile team makes changes to get around this missing feature to detect errors.

2022-06-21 06:45 UTC, kittywhiskers commented
Based on @UdjinM6's suggestion, backports of 15141, and 19219 have been split off to https://github.com/dashpay/dash/pull/4891 and BIP61 removal is now split off to https://github.com/dashpay/dash/pull/4892 so that the PR can proceed while mobile team can figure things out. Is that okay, @HashEngineering?

2022-06-23 06:22 UTC, kittywhiskers commented on doc/bips.md
> -* [`BIP 61`](https://github.com/bitcoin/bips/blob/master/bip-0061.mediawiki): The 'reject' protocol message (and the protocol version bump to 70002) was added in **v0.9.0** ([PR #3185](https://github
Moved BIP61 removal to https://github.com/dashpay/dash/pull/4892

2022-06-23 22:30 UTC, UdjinM6 approved these changes
utACK

2022-07-02 17:57 UTC, PastaPastaPasta submitted a review, later dismissed
utACK for merging via merge commit

2022-07-02 17:59 UTC, PastaPastaPasta commented
IMO let's merge https://github.com/dashpay/dash/pull/4880/commits first @UdjinM6

2022-07-03 08:06 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-07-03 17:13 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-07-03 17:13 UTC, merged