fix!: incorrect CalcCbTxMerkleRootQuorums with rotation
dashpay/dash pull request #4833
Opened 2022-05-10 16:26 UTC by ogabrielides

MerkleRootQuorum calculation for new blocks was handling incorrectly the block containing commitments which are not returned by `GetMinedAndActiveCommitmentsUntilBlock` yet.

Had to remove static variables (caching) because processing got more complex:

The edge case when only some rotated quorums were formed needs to be handled: only the corresponding formed quorum indexes need to be replaced

2022-05-13 15:18 UTC, PastaPastaPasta submitted a review, later dismissed
I guess this is fine? But it really concerns me that we don't have tests.

utACK for squash merge

2022-05-16 22:51 UTC, UdjinM6 reviewed
LGTM, one suggestion

2022-05-16 22:51 UTC, UdjinM6 commented on src/evo/cbtx.cpp
> +                qi.insert(std::make_pair(qc.commitment.quorumIndex, qcHash));
```suggestion
                qi[qc.commitment.quorumIndex] = qcHash;
```
would be a bit more readable imo

2022-05-18 09:28 UTC, ogabrielides commented
@UdjinM6 @PastaPastaPasta Updated

2022-05-18 12:13 UTC, UdjinM6 requested changes

2022-05-18 12:24 UTC, ogabrielides commented on test/functional/test_framework/messages.py
> +        return "quorumIndex:{0}, quorumHash:{1}, nVersion:{2}\n".format(self.llmqType, self.quorumHash, self.nVersion)
You are right

2022-05-18 14:35 UTC, ogabrielides commented
@UdjinM6 Updated again

2022-05-18 15:32 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-05-18 15:37 UTC, QuantumExplorer submitted a review, later dismissed
Approving at the request of @PastaPastaPasta, looked at it, and with my little knowledge, it does look okay.

2022-05-18 15:43 UTC, PastaPastaPasta approved these changes
re-utACK fixed linter

2022-05-18 17:45 UTC, merged