Backports 0.20 pr5
dashpay/dash pull request #4877
Opened 2022-06-09 18:15 UTC by Munkybooty

2022-06-19 04:13 UTC, PastaPastaPasta commented
lint-python fails

2022-06-19 05:57 UTC, PastaPastaPasta requested changes
lint-python fails

2022-06-28 16:23 UTC, Munkybooty commented
Dropping #18407 as it is #4829

2022-08-22 23:49 UTC, Munkybooty commented
I'm unsure of how to go about fixing `mempool_accept.py`

2022-08-23 23:19 UTC, UdjinM6 requested changes

2022-09-06 16:49 UTC, Munkybooty commented on src/net_processing.cpp
> +                                vRelayExpiration.push_back(std::make_pair(nNow + std::chrono::microseconds{RELAY_TX_CACHE_TIME}.count(), ret.first));
I had attempted to add the extra changes, however i kept encountering errors. I may need a little help in regards to this specific backport.

2022-09-07 10:33 UTC, UdjinM6 requested changes
pls see 14f05d8bb22ee90abeb28f4c75d2bebfe137a49f + e9c1ea674ebf149af391cd6c872bebb77800c4e4 to fix 16851 and  561ece03e910d6ab893be3eb47950df64de7d966 + 7b4d2d695cf053d4b07b361f8d424565f999588c to fix 17843

2022-09-13 20:26 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-09-23 23:44 UTC, UdjinM6 approved these changes
utACK

2022-10-04 18:42 UTC, UdjinM6 commented
looks good to merge after #4896 (will have to drop 537f275 (16908) and squash c5adfa7 into 0a8e213 (16851) on rebase)

2022-10-13 18:06 UTC, UdjinM6 approved these changes
utACK

2022-10-16 23:00 UTC, UdjinM6 commented
@PastaPastaPasta

2022-10-17 20:34 UTC, UdjinM6 approved these changes
re-utACK

2022-10-17 20:41 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit however, a subsequent PR that adds release notes for the added RPC should be completed @Munkybooty

2022-10-17 20:41 UTC, PastaPastaPasta commented on src/wallet/rpcwallet.cpp
> +// Copyright (c) 2009-2019 The Bitcoin Core developers
15930 needs release notes please!

2022-10-17 20:42 UTC, merged

2022-12-29 20:25 UTC, thephez commented
@Munkybooty Can you update the PR title to include the conventional commit `backport: ` prefix?