backport: 19754 and necessary pre-reqs
dashpay/dash pull request #4880
Opened 2022-06-10 23:41 UTC by PastaPastaPasta

2022-06-21 13:37 UTC, kittywhiskers requested changes
See https://github.com/kittywhiskers/dash/commits/dash4880, rebased over develop, squashed Udjin's fixes and resolved `test_dash_qt` failure. Also resolved incorrect address bug caused by querying `GetDataDir()` instead of `GetWalletDir()`.

2022-06-23 22:02 UTC, UdjinM6 requested changes

2022-06-29 15:30 UTC, PastaPastaPasta commented on src/wallet/rpcwallet.cpp
> +    UpdateWalletSetting(*context.chain, request.params[0].get_str(), request.params[6], warnings);
Looks like this got removed in a later PR?

2022-06-29 15:34 UTC, PastaPastaPasta commented on src/wallet/rpcwallet.cpp
> +    Optional<bool> load_on_start = request.params[4].isNull() ? nullopt : Optional<bool>(request.params[4].get_bool());
applied and squashed

2022-07-01 19:11 UTC, UdjinM6 requested changes

2022-07-01 20:53 UTC, PastaPastaPasta commented on src/wallet/rpcwallet.cpp
> +    Optional<bool> load_on_start = request.params[5].isNull() ? nullopt : Optional<bool>(request.params[4].get_bool());
whoops

2022-07-02 18:01 UTC, UdjinM6 approved these changes
utACK

2022-07-02 18:01 UTC, merged