rpc: split spork manipulation logic to distinct "sporkupdate" call
dashpay/dash pull request #4885
Opened 2022-06-14 17:56 UTC by kittywhiskers

2022-06-15 21:43 UTC, UdjinM6 requested changes

2022-06-15 21:43 UTC, UdjinM6 commented on src/rpc/misc.cpp
>      { "dash",               "spork",                  &spork,                  {"arg0","value"} },
```suggestion
    { "dash",               "spork",                  &spork,                  {"command"} },
```

2022-06-15 21:43 UTC, UdjinM6 commented on src/rpc/client.cpp
>      { "spork", 1, "value" },
```suggestion
```

2022-06-15 21:43 UTC, UdjinM6 commented on src/rpc/misc.cpp
> +    { "dash",               "sporkupdate",            &sporkupdate,            {"arg0","value"} },
```suggestion
    { "dash",               "sporkupdate",            &sporkupdate,            {"name","value"} },
```

2022-06-18 15:05 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-06-18 16:52 UTC, UdjinM6 approved these changes
utACK

2022-06-18 16:52 UTC, merged