Bitcoin backports #13756 #15770 #17730 #17750 #17752 #17826 #17857 #15886
dashpay/dash pull request #4887
Opened 2022-06-15 11:36 UTC by knst

- By default delay for dialogs is set to 0 instead of 3 seconds - are is it expected value in dash?
In bitcoin it was changed in this pull-request: bitcoin#9697
 - Backport bitcoin#13756 introduces a new feature "avoid_reuse" in wallet.
 - SendConfirmationDialog has now extra details (see a screenshot)
<img width="317" alt="image" src="https://user-images.githubusercontent.com/545784/173817541-3dd49278-53d9-4d3b-9f0a-ea077824699c.png">

2022-06-16 13:28 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commits/pr4887

2022-06-16 18:18 UTC, knst commented
> pls see https://github.com/UdjinM6/dash/commits/pr4887

agree with all 3. Picked-up them.

Should I add in functional test a case of `sendtoaddress` with all 8 arguments that is not tested now?

2022-06-18 18:30 UTC, UdjinM6 approved these changes
ACK

2022-06-19 03:21 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-06-19 03:21 UTC, PastaPastaPasta commented on depends/packages/qt.mk
> +$(package)_config_opts += -no-libjpeg
nit: why is 6e5440d505d351e95266e322ee73aff7fa0e72b4 not squashed into previous?

2022-06-19 03:23 UTC, merged