fix:! Relaxing Pos DKG check on last successful connection
dashpay/dash pull request #4902
Opened 2022-07-04 13:20 UTC by ogabrielides

On testnet we saw that when SPORK_23_QUORUM_POSE is active, newly joining masternodes are getting PoS punished/banned.

When a masternode comes online it initiates connections, but the code on other mns in DKGs would give a PoSe ban if they hadn’t “accepted” a connection from it. This is because new nodes are the ones initiating.

This PR transforms the check from checking if the last outcound success is no older than 60 x 60 seconds to any bound success.

2022-07-05 13:58 UTC, UdjinM6 requested changes
> This is because new nodes are the ones initiating.

They are not the only ones though. "Old" nodes also initiate connections at the start of each DKG. They probe other DKG members and the point of this PoSe check is not only to see if the other node is simply alive but also to make sure (to some degree) that it was configured correctly (the port is open and nodes can see it/connect to it).

concept NACK

2022-07-05 16:22 UTC, UdjinM6 commented
let's try #4904 and #4905

2022-07-05 16:49 UTC, UdjinM6 commented
> Then when a quorum happens, the other nodes don't initiate outbound connections (needed for pose), because they already have a connection to this node.

This should not be the case I think. Which part of code you think does this? `CConnman::ThreadOpenMasternodeConnections()` should handle it and create probe connections regardless afaik https://github.com/dashpay/dash/blob/master/src/net.cpp#L2694-L2716 (it should then be marked as "successful" on `mnauth`).

2022-07-05 18:20 UTC, ogabrielides commented
@UdjinM6 So you think that the situation encountered on tesnet could be fixed by #4904 ?

2022-07-05 18:50 UTC, ogabrielides commented
@UdjinM6 What bothers me is that we encountered the following: 
Some set of masternodes were synced before others. 
Once the we activated SPORK_23 (1 or 2 days after), the masternodes that were synced last were experiencing Pos banning.
Probe connection mechanism as you describe doesn't seem to protect masternodes (at least on small network with high ratio of participating in DKG masternodes)

@QuantumExplorer

2022-07-06 13:25 UTC, QuantumExplorer commented
@UdjinM6 you are probably thinking that the connection will be reset here: 
`                    bool connectedAndOutbound = connectedProRegTxHashes.count(dmn->proTxHash) && !connectedProRegTxHashes[dmn->proTxHash];
                    if (connectedAndOutbound) {
                        // we already have an outbound connection to this MN so there is no theed to probe it again
                        mmetaman.GetMetaInfo(dmn->proTxHash)->SetLastOutboundSuccess(nANow);
                        it = masternodePendingProbes.erase(it);
                        continue;
                    }`

However that only happens if `!connectedProRegTxHashes[dmn->proTxHash]` meaning outbound, so if the connection is inbound we won't set a last outbound success.

2022-07-06 18:34 UTC, PastaPastaPasta commented
@UdjinM6 @ogabrielides 

@QuantumExplorer and I talked a good bit today. I disagree with what he stated above.

Whenever there is an inbound connection then the code in MNAuth will call `SetLastOutboundSuccess` here https://github.com/dashpay/dash/blob/d64b7229cd98b0726d2bfd2303dc23e113bbe0e6/src/evo/mnauth.cpp#L124-L132

That MNAuth message will be received after we initiate an outbound connection which happens here: https://github.com/dashpay/dash/blob/a7ee2c266729c6dba9265e427d997767e5a14e3a/src/net.cpp#L2508

note that this assumes we find / set connectToDmn here: https://github.com/dashpay/dash/blob/a7ee2c266729c6dba9265e427d997767e5a14e3a/src/net.cpp#L2490-L2496)

**However I now believe this outbound connection doesn't actually happen.**

Calling `OpenMasternodeConnection` simply calls (note the fourth param  `const char *pszDest` is set to nullptr) https://github.com/dashpay/dash/blob/a7ee2c266729c6dba9265e427d997767e5a14e3a/src/net.cpp#L2599-L2601

Inside of `OpenNetworkConnection` there is the following. Given that pszDest is nullptr, this if block is entered, and the checks on 2546/2547 will result in us returning early as `FindNode` should return non-null for both since we do already have an inbound connection from this node. As such, the outbound connection will never be initialized, and then the mnauth will never be received, which means we won't call `SetLastOutboundSuccess` leading to the observed banning on testnet.
https://github.com/dashpay/dash/blob/a7ee2c266729c6dba9265e427d997767e5a14e3a/src/net.cpp#L2536-L2547

it seems to me based on this, that if we have an inbound connection from a node, we are unable to initialize a probe connection, resulting in these random PoSe bans.

This could likely be tested via the following patch
```
Index: src/net.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/net.cpp b/src/net.cpp
--- a/src/net.cpp	(revision 22262137a2ee5fb630f169ed3b1e83ce2af882a6)
+++ b/src/net.cpp	(date 1657131592153)
@@ -2543,8 +2543,10 @@
             return;
         // if multiple ports for same IP are allowed, search for IP:PORT match, otherwise search for IP-only match
         if ((!Params().AllowMultiplePorts() && FindNode(static_cast<CNetAddr>(addrConnect))) ||
-            (Params().AllowMultiplePorts() && FindNode(static_cast<CService>(addrConnect))))
+            (Params().AllowMultiplePorts() && FindNode(static_cast<CService>(addrConnect)))) {
+            LogPrintf("Unable to connect");
             return;
+        }
     } else if (FindNode(std::string(pszDest)))
         return;
 ```

2022-08-04 18:41 UTC, closed without merging