backport: merge bitcoin#16900...19619: berkeley db refactoring (part 3)
dashpay/dash pull request #4919
Opened 2022-07-16 09:08 UTC by kittywhiskers

2022-10-15 22:40 UTC, UdjinM6 requested changes
wow, that's a huge one! 👍 

pls see below + https://github.com/UdjinM6/dash/commits/pr4919 for some suggestions

2022-10-17 09:43 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-10-17 15:17 UTC, PastaPastaPasta commented on doc/release-notes-15454.md
> +Dash Core will no longer create an unnamed `""` wallet by default when no wallet is specified on the command line or in the configuration files.
thanks for dashifying this :)

2022-10-17 15:23 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-10-17 15:23 UTC, merged

2024-10-25 09:20 UTC, knst commented on src/wallet/test/wallet_tests.cpp
> +    RemoveWallet(wallet, nullopt, warnings);
anyone remembers, why it requires here `RemoveWallet` ?

https://github.com/bitcoin/bitcoin/pull/18727/files#diff-157f588a09ff1da05b8c74acfcfb4da21917b6a97ed5d2e702228d621d23e66dR40-R44