refactor(llmq): misc refactors
dashpay/dash pull request #4922
Opened 2022-07-16 21:44 UTC by PastaPastaPasta

2022-07-17 17:07 UTC, UdjinM6 requested changes

2022-07-17 18:11 UTC, PastaPastaPasta commented on src/llmq/commitment.h
> +        obj.pushKV("version", int{nVersion});
Why? Using braces gives us compile time guarantee there's no loss

2022-07-17 18:21 UTC, UdjinM6 commented on src/llmq/commitment.h
> +        obj.pushKV("version", int{nVersion});
Ah.. makes sense. Shouldn't we use `{}` for `nVersion` in `CFinalCommitmentTxPayload::ToJson()` below too then?

2022-07-17 20:14 UTC, PastaPastaPasta commented on src/llmq/commitment.h
> +        obj.pushKV("version", int{nVersion});
Yeah, it should

2022-07-18 14:42 UTC, UdjinM6 commented
Looks good but linter complains now 🙈 
```
src/llmq/chainlocks.cpp:30:5: warning: Variable 'scheduler_thread' is assigned in constructor body. Consider performing initialization in initialization list. [useInitializationList]
```
so we need either
```diff
diff --git a/src/llmq/chainlocks.cpp b/src/llmq/chainlocks.cpp
index 6d60200b9a..54fa4b0024 100644
--- a/src/llmq/chainlocks.cpp
+++ b/src/llmq/chainlocks.cpp
@@ -25,9 +25,9 @@ CChainLocksHandler* chainLocksHandler;
 
 CChainLocksHandler::CChainLocksHandler(CTxMemPool& _mempool, CConnman& _connman) :
     scheduler(std::make_unique<CScheduler>()),
-    mempool(_mempool), connman(_connman)
+    mempool(_mempool), connman(_connman),
+    scheduler_thread(std::make_unique<std::thread>([&] { TraceThread("cl-schdlr", [&] { scheduler->serviceQueue(); }); }))
 {
-    scheduler_thread = std::make_unique<std::thread>([&] { TraceThread("cl-schdlr", [&] { scheduler->serviceQueue(); }); });
 }
 
 CChainLocksHandler::~CChainLocksHandler()
```
or add it to the ignore list

2022-07-18 20:55 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-07-18 20:55 UTC, merged