refactor: migrate globals to managed pointers in preparation for deglobalization
dashpay/dash pull request #4930
Opened 2022-07-21 08:02 UTC by kittywhiskers

## Additional Notes

In preparation of moving some Dash-specific globals to `NodeContext` (which cannot contain anything that isn't a pointer), many globals have been transformed into `unique_ptr`s (with the sole exception of `CBLSWorker`, which is a `shared_ptr`). 

To reduce the amount of redundant reference passing, some classes were modified to make a `CConnman` object a member of the class, dereferenced from `NodeContext` during initialisation. 

This could not be done for `CSporkManager` and `CGovernanceManager` as they both rely on Dash's flat database implementation which does not take objects that accept initialisation parameters kindly due to an implicit copy being triggered when dumping database components, so they need their database and management components split out before they can take any arguments.

2022-07-24 16:28 UTC, UdjinM6 requested changes
pls see 733b7b3c4fadda29488fa35c10cd75b296c8369a and 7720157e43fc7705bfe8cd340f6f70401ca8edc0 (and maybe a0c7d347f8e0691d7c67019297e0da63a56b81f9)

2022-07-28 23:02 UTC, UdjinM6 commented
1. pls see https://github.com/UdjinM6/dash/commit/f6e965cea393d4c9a406544359bcc354d923cd55
2. I'm not sure how to fix 6a89c3a (reverting/dropping it helps)

2022-08-03 15:06 UTC, PastaPastaPasta requested changes
agree to drop https://github.com/dashpay/dash/commit/6a89c3adeba2b4303e6e8577bd5916b3a6d13976

2022-08-05 08:33 UTC, UdjinM6 commented
Hmm I think you reverted/dropped changes from my earlier suggestions 733b7b3c4fadda29488fa35c10cd75b296c8369a in the second to last force-push https://github.com/dashpay/dash/compare/81a98af39f7ef71cdcc756548a14158a5d09464c..aa43b9d09d79a789acab317be177df134f9830da so the build is broken again 🤷‍♂️

2022-08-11 15:23 UTC, PastaPastaPasta commented
linter fails
```
src/masternode/sync.h:54:5: warning: Class 'CMasternodeSync' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
[82](https://gitlab.com/dashpay/dash/-/jobs/2843071841#L82)Advice not applicable in this specific case? Add an exception by updating
[83](https://gitlab.com/dashpay/dash/-/jobs/2843071841#L83)IGNORED_WARNINGS in test/lint/lint-cppcheck-dash.sh
[84](https://gitlab.com/dashpay/dash/-/jobs/2843071841#L84)
```

2022-08-22 19:39 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commit/7bd22fbe07bdad1f327445285b083c1e83a5e80c

2022-08-23 18:00 UTC, UdjinM6 requested changes

2022-08-23 18:00 UTC, UdjinM6 commented on src/interfaces/node.cpp
> +        }
```suggestion
        if (governance == nullptr) return;
        governance->GetAllNewerThan(objs, nMoreThanTime);
```
🙈

2022-08-23 18:07 UTC, UdjinM6 approved these changes
re-ACK

2022-08-26 21:52 UTC, PastaPastaPasta approved these changes
utACK

2022-08-26 21:52 UTC, merged