refactor(llmq): substitute memberless class llmq::CLLMQUtils with namespace llmq::utils
dashpay/dash pull request #4931
Opened 2022-07-21 08:14 UTC by kittywhiskers

2022-07-23 12:50 UTC, UdjinM6 requested changes

2022-07-24 18:48 UTC, UdjinM6 requested changes
pls see 215a684951ba688434b79fbdde27838f8634bc6b and 755034695777ad79aa3886580f2e232d8963f5de

2022-07-28 21:01 UTC, UdjinM6 approved these changes
utACK, compiles locally

2022-08-02 17:13 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-08-02 17:14 UTC, merged