Bp21 2
dashpay/dash pull request #5006
Opened 2022-09-11 02:04 UTC by vijaydasmp

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-10-04 03:08 UTC, vijaydasmp commented
for bitcoin#18704 code changes present in upstream (https://github.com/bitcoin/bitcoin/commit/9ea4d8326a9d1641dfacca7ac82c16b7d387d967) file util.py is present in test/functional/test_framework/test_framework.py in dash code, appropriately updated def sync_blocks and def sync_mempools functions for dash

2022-12-06 01:20 UTC, vijaydasmp commented
Hello @UdjinM6

2022-12-06 15:54 UTC, UdjinM6 submitted a review, later dismissed
LGTM, utACK

2022-12-06 17:20 UTC, vijaydasmp commented
Hello @PastaPastaPasta

2022-12-17 02:17 UTC, vijaydasmp commented
Hello @UdjinM6 , please have a look

2022-12-26 17:40 UTC, UdjinM6 requested changes
one tiny issue, LGTM otherwise

2022-12-26 17:40 UTC, UdjinM6 commented on src/policy/fees.h
> +    /** Decay of .9952 is a half-life of 144 blocks or about 1 day */
19630:
```suggestion
    /** Decay of .9952 is a half-life of 144 blocks or about 6 hours */
```

2022-12-26 17:40 UTC, UdjinM6 commented on src/policy/fees.h
> +    /** Decay of .99931 is a half-life of 1008 blocks or about 1 week */
19630:
```suggestion
    /** Decay of .99931 is a half-life of 1008 blocks or about 2 days */
```

2022-12-30 07:11 UTC, vijaydasmp commented on src/policy/fees.h
> +    /** Decay of .99931 is a half-life of 1008 blocks or about 1 week */
Thanks

2022-12-30 23:20 UTC, UdjinM6 commented on src/policy/fees.h
> +    /** Decay of .9952 is a half-life of 144 blocks or about 1 day */
this one is not fixed

2022-12-31 06:53 UTC, vijaydasmp commented on src/policy/fees.h
> +    /** Decay of .9952 is a half-life of 144 blocks or about 1 day */
Oh!, now fixed

2022-12-31 10:40 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-01-02 02:16 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-01-02 02:17 UTC, merged