backport: merge bitcoin#15508, #18764, #19264, #19107, #17577, #18783, #15024, #18204, partial #15508, #13932 (auxiliary backports: part 3)
dashpay/dash pull request #5017
Opened 2022-09-19 08:28 UTC by kittywhiskers

2022-09-20 08:13 UTC, PastaPastaPasta commented on src/rpc/rawtransaction.cpp
> +UniValue analyzepsbt(const JSONRPCRequest& request)
13932 needs release notes

2022-09-20 08:29 UTC, kittywhiskers commented on src/rpc/rawtransaction.cpp
> +UniValue analyzepsbt(const JSONRPCRequest& request)
Done

2022-09-20 08:29 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-09-23 23:44 UTC, UdjinM6 requested changes
👍 
few things I noticed after a quick review:
1. e6616bd backports 14588, not 15508
2. missing changes? (see below)

2022-09-24 03:34 UTC, kittywhiskers commented on src/wallet/psbtwallet.cpp
> +        complete &= SignPSBTInput(HidingSigningProvider(pwallet->GetSigningProvider(), !sign, !bip32derivs), psbtx, i, sighash_type);
Resolved in latest push

2022-09-27 14:48 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2022-09-27 19:39 UTC, UdjinM6 approved these changes
utACK

2022-09-29 19:06 UTC, merged