refactor: llmq only logging
dashpay/dash pull request #5050
Opened 2022-10-18 11:14 UTC by ogabrielides

## Issue being fixed or feature implemented

## What was done?

Enabled a particularly long logging only if llmq logging category is active 

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-10-18 15:23 UTC, PastaPastaPasta submitted a review, later dismissed
utACK for squash merge. LGTM

2022-10-19 14:13 UTC, PastaPastaPasta requested changes

2022-10-19 14:13 UTC, PastaPastaPasta commented on src/llmq/dkgsession.cpp
> +            for (const auto &mn: members) {
Shouldn't change the orientation (keep the ref left)

2022-10-19 14:36 UTC, PastaPastaPasta commented on src/llmq/dkgsession.cpp
> +            for (const auto &mn: members) {
```suggestion
            for (const auto& mn: members) {
```

2022-10-19 14:36 UTC, PastaPastaPasta commented on src/llmq/dkgsession.cpp
> +            for (const auto &r: relayMembers) {
```suggestion
            for (const auto& r: relayMembers) {
```

2022-10-19 18:38 UTC, UdjinM6 requested changes

2022-10-20 07:59 UTC, ogabrielides commented
@UdjinM6 Applied suggestions

2022-10-20 08:15 UTC, UdjinM6 commented on src/llmq/dkgsession.cpp
> +        logger.Batch("DKGComposition h[%d] i[%d] DKG:%s\n", pCycleQuorumBaseBlockIndex->nHeight, quorumIndex, ss.str());
you missed this one
```suggestion
        logger.Batch("DKGComposition h[%d] i[%d] DKG:%s", pCycleQuorumBaseBlockIndex->nHeight, quorumIndex, ss.str());
```

2022-10-20 08:23 UTC, ogabrielides commented
@UdjinM6 Done

2022-10-20 08:23 UTC, UdjinM6 approved these changes
LGTM, utACK

2022-10-20 19:41 UTC, PastaPastaPasta reviewed
Not sure why we changed this

2022-10-20 19:41 UTC, PastaPastaPasta commented on src/llmq/dkgsession.cpp
> +        for (const auto& mn: members) {
```suggestion
        for (const auto& mn : members) {
```

2022-10-20 19:41 UTC, PastaPastaPasta commented on src/llmq/dkgsession.cpp
> +            for (const auto& r: relayMembers) {
```suggestion
            for (const auto& r : relayMembers) {
```

2022-10-20 19:42 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-10-20 19:45 UTC, UdjinM6 approved these changes
utACK

2022-10-20 19:47 UTC, merged