Backports 0.20 pr9
dashpay/dash pull request #5074
Opened 2022-11-08 07:24 UTC by Munkybooty

## Issue being fixed or feature implemented

Bitcoin Backports

## What was done?

Misc v20 Backports, check commit log to see changes.

## How Has This Been Tested?

Compilation and tested unit tests locally

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-11-25 17:23 UTC, Munkybooty commented on src/rpc/blockchain.cpp
> +                    RPCResult{"for verbose = true",
if I remember correctly, all those changes may have already been added in a different pr

2023-02-08 11:20 UTC, knst commented
@Munkybooty please, check this commit

2023-02-12 15:41 UTC, knst requested changes
bitcoin 17959 - LGTM
bitcoin 18173 - check comments
bitcoin 18253 - LGTM
bitcoin 18263 - LGTM
bitcoin 18306 - LGTM
bitcoin 15443 - LGTM
bitcoin 17809 - seems as formatting become worse and broken now in many places. Used to be better. Btw, I will review later if any missing useful changes from 17809.

2023-02-12 15:41 UTC, knst commented on src/test/util/transaction_utils.cpp
> +std::vector<CMutableTransaction> SetupDummyInputs(FillableSigningProvider& keystoreRet, CCoinsViewCache& coinsRet, const std::array<CAmount,4>& nValues)
I see added new function `SetupDummyInputs` but don't see removed old copies in:
 - src/bench/ccoins_caching.cpp
 - src/test/transaction_tests.cpp

2023-02-12 15:41 UTC, knst commented on src/wallet/rpcwallet.cpp
> +                    }
Looks like formatting is broken now, used to be better before... Is it expecting? 
And not only there, but in other places.

2023-02-16 08:00 UTC, UdjinM6 requested changes

2023-03-29 17:59 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-04-04 17:53 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-04-04 21:32 UTC, merged