feat(rpc): Added quorum listextended RPC
dashpay/dash pull request #5076
Opened 2022-11-10 16:33 UTC by ogabrielides

## Issue being fixed or feature implemented

Introduction of RPC `quorum listextended`.
This change was requested by Platform since the already existing RPC quorum list doesn't return all required data.
`quorum listextended` behaves exactly like `quorum list`, but with a more enriched reply.
Data returned per quorum:
- `quorumHash`
- `creationHeight`
- `quorumIndex`
- `minedBlockHash`

Note: I chose to create a new one, since the reply models differs a lot.
array of strings for `quorum list` compared to array of objects for `quorum listextended`.

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2022-11-10 16:44 UTC, thephez requested changes
Been waiting for this :heart: Formatting looks a little off in some places...

2022-11-10 16:44 UTC, thephez commented on src/rpc/quorums.cpp
> +               "Extended list of on-chain quorums\n",
The indentation in here looks wider than usual and a bit inconsistent.

2022-11-14 15:58 UTC, PastaPastaPasta commented
Release notes need to be added

2022-11-15 16:16 UTC, PastaPastaPasta commented
Please implement some functional tests for this. I would expect that to be relatively easy

2022-11-16 16:15 UTC, ogabrielides commented
> Please implement some functional tests for this. I would expect that to be relatively easy

@PastaPastaPasta Done

2022-11-16 16:38 UTC, thephez approved these changes
Slightly tested ACK :+1:

2022-11-18 17:07 UTC, ogabrielides commented
> Would it not make more sense for this to be a map from quorumHash -> data instead of a list of data blobs?

It's the same after all

2022-11-21 11:21 UTC, ogabrielides commented
> Details

@PastaPastaPasta Done

2022-11-21 16:47 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-11-21 16:55 UTC, thephez submitted a review, later dismissed
Slightly test re-ACK

2022-11-21 18:00 UTC, thephez reviewed
Actually it looks like the help doesn't return this line as I'd expect:
``` {RPCResult::Type::OBJ, "xxxx", "Quorum hash. Note: most recent quorums come first.",```

This is what I see...
```Result:
{                                  (json object)
  "quorumName" : [                 (json array) List of quorum details per some quorum type
    {                              (json object) Quorum hash. Note: most recent quorums come first.
      "creationHeight" : n,        (numeric) Block height where the DKG started.
      "quorumIndex" : n,           (numeric) Quorum index (applicable only to rotated quorums).
      "minedBlockHash" : "hex"     (string) Blockhash where the commitment was mined.
    },
    ...
  ]
}```

2022-11-21 18:06 UTC, PastaPastaPasta approved these changes
re-ACK

2022-11-21 18:07 UTC, thephez approved these changes
Let's get this merged! :+1:

2022-11-21 18:09 UTC, ogabrielides commented
@PastaPastaPasta Yup, ACK

2022-11-21 18:17 UTC, merged