fix: built of dashbls for glibc v2.35
dashpay/dash pull request #5082
Opened 2022-11-24 19:53 UTC by knst

## Issue being fixed or feature implemented
That's a fix for build subproject dashbls for glibc v2.35.
Alternate solution to update `catch2` library to version 2.35 or newer: https://github.com/catchorg/Catch2/blob/devel/docs/release-notes.md#2135

## What was done?
Added new define to use static value instead.

## How Has This Been Tested?
Built + run unit tests in problem environment.

## Breaking Changes
no breaking changes.

## Checklist:

- [x] I have performed a self-review of my own code

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2022-12-06 10:17 UTC, knst commented
Let's better merge this pull request: https://github.com/dashpay/dash/pull/5094

And update dash-bls someday in future so far as it is not bothering right now if merge that.

2022-12-09 17:25 UTC, kittywhiskers commented
NACK, PR violates subtree integrity. 

We already have made (rather, had to make) one exception, namely https://github.com/dashpay/dash/pull/5077/commits/90457fad5c7521360eda977b529391ad48573c1b, and I'm still trying to figure out how to get Autotools to stop messing with pre-existing files in the source tree and at least, in my opinion, this shouldn't be a repeating pattern.

2022-12-09 17:26 UTC, kittywhiskers requested changes
NACK, PR violates subtree integrity.

We already have made (rather, had to make) one exception, namely https://github.com/dashpay/dash/commit/90457fad5c7521360eda977b529391ad48573c1b, and I'm still trying to figure out how to get Autotools to stop messing with pre-existing files in the source tree and at least, in my opinion, this shouldn't be a repeating pattern.

2022-12-09 17:48 UTC, knst commented
closed due to https://github.com/dashpay/bls-signatures/pull/57 https://github.com/dashpay/bls-signatures/pull/56

2022-12-09 17:48 UTC, closed without merging