backport:  v0.20 pr10
dashpay/dash pull request #5083
Opened 2022-11-25 18:07 UTC by Munkybooty

## Issue being fixed or feature implemented

Bitcoin Backports

## What was done?

Misc v20 Backports, check commit log to see changes.

## How Has This Been Tested?

Compilation and tested unit tests locally

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-12-26 12:28 UTC, knst requested changes
please, check this patch https://github.com/knst/dash/commit/ee6f3b7a648359bceaab91a89ae6c04559ec9f87 . Otherwise dash can't be compiled.

2022-12-26 12:28 UTC, knst commented on src/rpc/blockchain.cpp
> +        HelpExampleRpc("getblockfilter", "\"00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09\", \"basic\"")
nit: missing space and different empty space

2022-12-27 23:48 UTC, knst submitted a review, later dismissed
utACK

2023-01-02 02:37 UTC, PastaPastaPasta commented on src/init.cpp
> +    node.scheduler->scheduleEvery(std::bind(&CNetFulfilledRequestManager::DoMaintenance, std::ref(netfulfilledman)), 1min);
kinda inconsistant, `1min` here, but `60s` later on

2023-01-02 02:40 UTC, PastaPastaPasta submitted a review, later dismissed
utACK for merging via merge commit, although there were a few slight inconsistencies with like 60s vs 1min

2023-01-03 10:19 UTC, knst commented
LGTM except mentioned formatting in [src/rpc/blockchain.cpp](https://github.com/dashpay/dash/pull/5083/files#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0b)

2023-01-04 12:18 UTC, UdjinM6 approved these changes
utACK

2023-01-04 20:35 UTC, UdjinM6 submitted a review, later dismissed
re-utACK

2023-02-08 17:39 UTC, knst commented
@Munkybooty can you check commits in your force push?
Seems as accidentally you replaced valid commit with backport 18289 to empty commit
https://github.com/dashpay/dash/commit/bae9a8c8da882456993566a27fecbf2e7963b320
->
https://github.com/dashpay/dash/pull/5083/commits/f56477cc27970fade058d8083d8b9df51ef28471

2023-02-12 08:30 UTC, knst submitted a review, later dismissed
utACK

2023-02-14 10:02 UTC, UdjinM6 submitted a review, later dismissed
utACK

2023-02-21 05:53 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-02-21 06:43 UTC, knst approved these changes
re-utACK

2023-02-27 21:07 UTC, merged