feat(rpc): Updated quorum listextended RPC
dashpay/dash pull request #5104
Opened 2022-12-12 13:26 UTC by ogabrielides

## Issue being fixed or feature implemented

- At the request of Platform team, this RPC should accept `height` instead of `count`. RPC replies with the signing quorums active at requested `height`. If `height` isn't specified, then tip is used for the construction of the reply.
- Corrections were made on the description of reply model.

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-12-12 17:02 UTC, ogabrielides commented
@PastaPastaPasta Technically no because `quorum listextended` was never released :)

2022-12-13 17:37 UTC, thephez approved these changes
:+1:

2022-12-13 17:38 UTC, UdjinM6 commented
hmm.. can't we have both `count` and `height`?

2022-12-13 17:41 UTC, ogabrielides commented
> hmm.. can't we have both `count` and `height`?

1. Platform always want signing count
2. `count` and `height` are both optional integer. It would be confusing no?

2022-12-13 17:50 UTC, UdjinM6 commented
> 2. `count` and `height` are both optional integer. It would be confusing no?

good point

2022-12-13 17:51 UTC, PastaPastaPasta commented
Should also add/edit release notes

2022-12-13 17:58 UTC, ogabrielides commented
> Should also add/edit release notes

Updated already existing one

2022-12-13 18:47 UTC, UdjinM6 requested changes

2022-12-13 18:47 UTC, UdjinM6 commented on src/rpc/quorums.cpp
> +                         }}}},
format:
```suggestion
                    {RPCResult::Type::OBJ, "", "",
                    {
                        {RPCResult::Type::OBJ, "xxxx", "Quorum hash. Note: most recent quorums come first.",
                        {
                            {RPCResult::Type::NUM, "creationHeight", "Block height where the DKG started."},
                            {RPCResult::Type::NUM, "quorumIndex", "Quorum index (applicable only to rotated quorums)."},
                            {RPCResult::Type::STR_HEX, "minedBlockHash", "Blockhash where the commitment was mined."}
                        }}
                    }},
```

2022-12-13 21:44 UTC, UdjinM6 approved these changes
utACK

2022-12-14 15:45 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2022-12-14 16:30 UTC, merged