refactor: convert maybe_error into generic `Result` template class
dashpay/dash pull request #5109
Opened 2022-12-15 05:58 UTC by PastaPastaPasta

## Issue being fixed or feature implemented

Removed non-generic maybe_error and replaced with a generic `Result` class paired with `Ok` and `Err` structs

## What was done?

This is a simple implementation of the Result type in C++. The Result type is a type that can either be an Ok value, which represents a successful operation and contains a value, or an Err value, which represents a failed operation and contains an error value.

The Result class is a template class that takes two types: T, which is the type of the value that an Ok result will contain, and E, which is the type of the value that an Err result will contain.

The Ok and Err structs are also templates, and are used to construct Ok and Err values. The Ok struct has a single member val_ of type T, and the Err struct has a single member val_ of type E.

The Result class has a constructor that takes either an Ok value or an Err value, and stores the value internally. It also has several member functions that can be used to access the value of the Result and check whether it is an Ok or Err value.

The is_ok() and is_err() member functions can be used to check whether the Result is an Ok or Err value, respectively. The operator bool() function allows the Result to be used in a boolean context, such as an if statement. The unwrap() and unwrap_err() member functions can be used to get the value contained in the Result, but will assert if the Result is not of the expected type.

## How Has This Been Tested?

building, unit tests

## Breaking Changes

Should be none

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2022-12-15 08:02 UTC, knst reviewed
My concern, that class `Result` always allocate memory for both type Ok<T> and E.
```
    Ok<T> val_;
    E err_;
```
So far as I can see all Ok<> and E<> requires default construct that will be called whatever Result succeed case or not.
Also it always consume memory for both Ok and E even if it is only one needed.

That's fine if it is an implementation for small and rarely used component.
But if the Result is supposed to be general `util` component it will spread someday all over code base and will effect both performance and memory consumption and it is far from production ready.

I think wrapper over std::variant will work better.

2022-12-15 15:18 UTC, PastaPastaPasta commented
> My concern, that class `Result` always allocate memory for both type Ok<T> and E.
> 
> ```
> 
>     Ok<T> val_;
> 
>     E err_;
> 
> ```
> 
> So far as I can see all Ok<> and E<> requires default construct that will be called whatever Result succeed case or not.
> 
> Also it always consume memory for both Ok and E even if it is only one needed.
> 
> 
> 
> That's fine if it is an implementation for small and rarely used component.
> 
> But if the Result is supposed to be general `util` component it will spread someday all over code base and will effect both performance and memory consumption and it is far from production ready.
> 
> 
> 
> I think wrapper over std::variant will work better.

I am worried about this. I think that we could add some static asserts which ensure the types are trivially constructible.

2022-12-15 16:40 UTC, PastaPastaPasta commented
Variant seems to work fine, how does that look?

2022-12-19 19:39 UTC, knst requested changes
Please, check this branch: https://github.com/dashpay/dash/compare/develop...knst:dash:refac/result

2022-12-19 19:39 UTC, knst commented on src/evo/providertx.h
> -    std::string_view message;
why don't you like string_view? It doesn't own string but do not require for string to be C-style null-ended

2023-03-06 17:57 UTC, knst approved these changes
utACK

2023-03-06 17:57 UTC, knst commented on src/util/result.h
> +// Copyright (c) 2018-2022 The Dash Core developers
nit: just 2022-2023?

2023-04-15 16:02 UTC, UdjinM6 commented on src/util/result.h
> +// Copyright (c) 2018-2022 The Dash Core developers
```suggestion
// Copyright (c) 2022-2023 The Dash Core developers
```

2023-04-15 16:55 UTC, UdjinM6 approved these changes
utACK

2023-04-15 18:51 UTC, knst approved these changes
LGTM

2023-07-24 16:17 UTC, knst commented
Let's get this one merged!  @PastaPastaPasta 
Please, check this commit - https://github.com/knst/dash/commit/2bd3d06b3ab433e0902df59e3927c5186be9b64b

p.s. The usages from validation.cpp and evo/ has been replaced to BlockValidationState and TxValidationState to follow bitcoin's changes.

2023-09-29 14:38 UTC, PastaPastaPasta commented
Reviving this PR, currently with no usage; I would like to point towards an implementation of std::expected (which operated similar to Result) here: https://github.com/TartanLlama/expected

2024-01-13 21:10 UTC, knst commented
> Reviving this PR, currently with no usage; I would like to point towards an implementation of std::expected

`std::expected` is indeed a better option.

Super-seeded by https://github.com/dashpay/dash/blob/develop/src/util/expected.h from #5782

2024-01-13 21:10 UTC, closed without merging