feat(rpc): Hide old banned mns by default
dashpay/dash pull request #5125
Opened 2022-12-29 09:21 UTC by ogabrielides

## Issue being fixed or feature implemented

## What was done?

It was requested by service desk to hide by default old banned masternodes when calling rpc `masternodelist`.
The period from which a masternode is considered old banned was set to `24 * 24 * 30 = 17280 blocks = 1 month`.
The new mode `all` was added to support the bypass of the above filter.
Note: If the mode all is used, then the reply mode is `JSON` (can be additionally filtered)

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-12-29 14:43 UTC, thephez reviewed
Concept ACK
This seems like a reasonable idea. Curious how 1 month was chosen - was this based on anything specific? And not for this PR, but it would be nice to be able to filter out the "old" banned MNs from the Masternode List tab in Qt also.

2022-12-29 16:48 UTC, ogabrielides commented
> Concept ACK This seems like a reasonable idea. Curious how 1 month was chosen - was this based on anything specific? And not for this PR, but it would be nice to be able to filter out the "old" banned MNs from the Masternode List tab in Qt also.

The input was given empirically by the service desk team
I guess statistically if a masternode is banned since more than a month, it will very likely stay banned.

2022-12-29 20:18 UTC, UdjinM6 requested changes
concept NACK

2022-12-30 12:46 UTC, ogabrielides commented
@UdjinM6 Inverted the logic. Now the logic is by default show everyone, when calling with `recent` show only enabled + recently banned.

2022-12-30 23:14 UTC, UdjinM6 requested changes

2022-12-30 23:14 UTC, UdjinM6 commented on src/rpc/masternode.cpp
> +        if (!showAllBannedMns && mnList.IsMNPoSeBanned(dmn)) {
`showAllBannedMns` is `!= recent` and then we use `!showAllBannedMns` so it's double-negative which is a bit confusing. Could maybe refactor it to `showRecentMnsOnly` or drop the variable and simply use
```suggestion
        if (strMode == "recent" && mnList.IsMNPoSeBanned(dmn)) {
```

2022-12-30 23:14 UTC, UdjinM6 commented on src/rpc/masternode.cpp
> +    constexpr int monthBlockLength = 24 * 24 * 30;
nit: s/Length/Count/ maybe?

also, could probably use `Params().GetConsensus().nSuperblockCycle` instead - would make it much easier to write tests for this mode cause regtest cycles are much smaller (10 blocks). Though I'm not sure if service desk guys are going to be happy about it cause testnet/devnet cycles are also pretty small (24 blocks).

2022-12-31 11:21 UTC, ogabrielides commented
@UdjinM6 Applied suggestions
@thephez the period was changed to `SuperblockCycle`

2023-01-01 22:54 UTC, UdjinM6 approved these changes
utACK

2023-01-02 01:04 UTC, PastaPastaPasta approved these changes
utACK for squash merge, sure

2023-01-02 01:04 UTC, merged