docs: add release notes for v18.2.x
dashpay/dash pull request #5129
Opened 2022-12-30 05:41 UTC by PastaPastaPasta

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-12-30 22:50 UTC, UdjinM6 requested changes
These changes should go into v18.2.x branch first and should be brought into develop via "merge master into develop" PR after v18.2 release.

2022-12-31 13:48 UTC, thephez reviewed
Couple suggestions

2022-12-31 13:48 UTC, thephez commented on doc/release-notes.md
>  ### The new RPCs are:
#4877 added the `getbalances` RPC if I'm not mistaken

2022-12-31 13:48 UTC, thephez commented on doc/release-notes.md
> +- `quorum listextended` is the cousin of `quorum list` with more enriched reply. By using `height` parameter RPC will list active quorums at specified height (or at tip if `height` is not specified.)
```suggestion
- `quorum listextended` is the cousin of `quorum list` with a more enriched reply. By using the `height` parameter, the RPC will list active quorums at a specified height (or at the tip if `height` is not specified).
```

2023-01-01 01:19 UTC, thephez submitted a review, later dismissed
LGTM

2023-01-01 23:09 UTC, UdjinM6 submitted a review, later dismissed
We used to do it this way https://github.com/dashpay/dash/pull/5129#pullrequestreview-1233306466. But utACK in case you want to do it like for #5128.

2023-01-02 00:09 UTC, UdjinM6 approved these changes
utACK

2023-01-02 00:10 UTC, merged