docs: Release notes for BLS upgrade
dashpay/dash pull request #5137
Opened 2023-01-04 12:41 UTC by ogabrielides

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-01-04 17:02 UTC, thephez requested changes
Some small suggestions...

2023-01-04 17:02 UTC, thephez commented on doc/release-notes-5021.md
> +Once v19 hard fork is activated all remaining messages containing BLS public keys or signatures will serialise them using the new basic BLS scheme.
```suggestion
Once the v19 hard fork is activated, all remaining messages containing BLS public keys or signatures will serialise them using the new basic BLS scheme.
```

2023-01-04 17:02 UTC, thephez commented on doc/release-notes-5021.md
> +`dsq`, `dstx`, `mnauth`, `govobj`, `govobjvote`, `qrinfo`, `qsigshare`, `qsigrec`, `isdlock`, `clsig`, all DKG messages (`qfcommit`, `qcontrib`, `qcomplaint`, `qjustify`, `qpcommit`);
```suggestion
`dsq`, `dstx`, `mnauth`, `govobj`, `govobjvote`, `qrinfo`, `qsigshare`, `qsigrec`, `isdlock`, `clsig`, and all DKG messages (`qfcommit`, `qcontrib`, `qcomplaint`, `qjustify`, `qpcommit`).
```

2023-01-26 16:37 UTC, ogabrielides commented on doc/release-notes-5021.md
> +`qcommit`
I am referring to the final commitment mined on chain. So yes `qfcommit` is the correct one.

2023-01-26 17:20 UTC, thephez reviewed
Maybe these too?

2023-01-26 17:20 UTC, thephez commented on doc/release-notes-5021.md
> +| 1       | Non-rotated qcommit serialised using legacy BLS scheme | No                           |
```suggestion
| 1       | Non-rotated qfcommit serialised using legacy BLS scheme | No                           |
```

2023-01-26 17:20 UTC, thephez commented on doc/release-notes-5021.md
> +| 2       | Rotated qcommit serialised using legacy BLS scheme     | Yes                          |
```suggestion
| 2       | Rotated qfcommit serialised using legacy BLS scheme     | Yes                          |
```

2023-01-26 17:20 UTC, thephez commented on doc/release-notes-5021.md
> +| 3       | Non-rotated qcommit serialised using basic BLS scheme  | No                           |
```suggestion
| 3       | Non-rotated qfcommit serialised using basic BLS scheme  | No                           |
```

2023-01-26 17:20 UTC, thephez commented on doc/release-notes-5021.md
> +| 4       | Rotated qcommit serialised using basic BLS scheme      | Yes                          |
```suggestion
| 4       | Rotated qfcommit serialised using basic BLS scheme      | Yes                          |
```

2023-01-26 18:18 UTC, thephez approved these changes
ACK

2023-02-02 13:46 UTC, ogabrielides commented
@PastaPastaPasta @UdjinM6 Could you review this please?

2023-02-04 15:56 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-02-04 17:56 UTC, UdjinM6 approved these changes
utACK

2023-02-06 15:02 UTC, merged