Bp21 15
dashpay/dash pull request #5153
Opened 2023-01-11 07:26 UTC by vijaydasmp

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-02-23 20:36 UTC, UdjinM6 requested changes

2023-02-23 20:36 UTC, UdjinM6 commented on doc/release-notes.md
> +P2P and network changes
18733: this whole text should go into a separate `release-notes-18733.md` file

2023-02-28 20:22 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-03-03 08:08 UTC, knst submitted a review, later dismissed

2023-03-03 17:33 UTC, vijaydasmp commented on test/functional/test_framework/script_util.py
> +DUMMY_2_P2WPKH_SCRIPT = CScript([b'b' * 22])
ok

2023-03-03 17:38 UTC, vijaydasmp commented
Hello @UdjinM6 @knst @PastaPastaPasta , please review

2023-03-03 18:10 UTC, knst approved these changes
utACK

2023-03-13 12:01 UTC, vijaydasmp commented
Hello @UdjinM6 @PastaPastaPasta , please review

2023-03-22 01:23 UTC, vijaydasmp commented
Dear @UdjinM6 @PastaPastaPasta please review

2023-03-24 08:27 UTC, UdjinM6 approved these changes
re-utACK

2023-03-27 03:12 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-03-27 03:14 UTC, merged