V18.2.1 backports
dashpay/dash pull request #5156
Opened 2023-01-12 04:19 UTC by PastaPastaPasta

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-01-12 14:43 UTC, thephez requested changes
A few minor changes.

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
> +Please note that v18.2.0 was revoked due to a bug, this version fixes that bug.
```suggestion
Please note that v18.2.0 was revoked due to a bug; this version fixes that bug.
```

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
> +able to use both mainnet or testnet. Currently, v18.2.0 is not working on mainnet,
```suggestion
able to use both mainnet and testnet. Currently, v18.2.0 is not working on mainnet,
```

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
>  Please report bugs using the issue tracker at github:
```suggestion
Please report bugs using the issue tracker at GitHub:
```

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
> +It is highly recommended to not downgrade masternodes below 18.2.1, as 18.2.1 (and 18.1.1)
```suggestion
It is highly recommended not to downgrade masternodes below 18.2.1, as 18.2.1 (and 18.1.1)
```

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
> +This release is optional for all nodes. However, v18.2.1 is required to be
```suggestion
This release is optional for all nodes; however, v18.2.1 is required to be 
```

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
> +See #5145 and #5142, these 2 PR fix important bugs in previous versions. Specifically,
```suggestion
See #5145 and #5142; these 2 PR fix important bugs in previous versions. Specifically,
```

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
> +validated and propagated to other nodes. This patch changes it so that old qfcommits
```suggestion
validated and propagated to other nodes. This patch prevents old qfcommits
```

2023-01-12 14:43 UTC, thephez commented on doc/release-notes.md
> +are not relayed. #5142 is a fix which enables this version to function both on testnet
```suggestion
from being relayed. #5142 is a fix which enables this version to function both on testnet
```

2023-01-13 00:11 UTC, UdjinM6 approved these changes
utACK

2023-01-13 00:16 UTC, merged