docs(rpc): added missing legacy rpc in help
dashpay/dash pull request #5161
Opened 2023-01-14 14:49 UTC by ogabrielides

## Issue being fixed or feature implemented

Added the missing rpc in `protx` help.
Release notes can be found in https://github.com/dashpay/dash/pull/5137

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-01-14 15:04 UTC, thephez reviewed
My suggestions...

2023-01-14 15:04 UTC, thephez commented on src/rpc/evo.cpp
> +        "  register_legacy          - Create a ProTx by parsing BLS using legacy scheme and send it to network\n"
```suggestion
        "  register_legacy          - Create a ProTx by parsing BLS using the legacy scheme and send it to network\n"
```

2023-01-14 15:04 UTC, thephez commented on src/rpc/evo.cpp
> +        "  register_fund_legacy     - Fund, create a ProTx by parsing BLS using legacy scheme and send it to network\n"
```suggestion
        "  register_fund_legacy     - Fund and create a ProTx by parsing BLS using the legacy scheme, then send it to network\n"
```

2023-01-14 15:04 UTC, thephez commented on src/rpc/evo.cpp
> +        "  register_prepare_legacy  - Create an unsigned ProTx by parsing BLS using legacy scheme\n"
```suggestion
        "  register_prepare_legacy  - Create an unsigned ProTx by parsing BLS using the legacy scheme\n"
```

2023-01-14 15:26 UTC, thephez submitted a review, later dismissed
utACK :+1:

2023-01-15 22:53 UTC, PastaPastaPasta submitted a review, later dismissed
utACK for squash merge

2023-01-16 18:44 UTC, UdjinM6 requested changes

2023-01-16 18:44 UTC, UdjinM6 commented on src/rpc/evo.cpp
>          "  list              - List ProTxs\n"
should tweak indentation here and below too

2023-01-16 18:53 UTC, UdjinM6 approved these changes
utACK

2023-01-20 05:32 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-01-20 05:34 UTC, merged