backport: deglobalisation of mempool
dashpay/dash pull request #5169
Opened 2023-01-22 02:46 UTC by knst

This pull request is part of deglobalisation of mempool.
Merged backports:
 - bitcoin#15748
 - bitcoin#18541
 - bitcoin#19848
 - [redo] fix: re-run a script from backport bitcoin#17407
 - bitcoin#14384
 - bitcoin#17477
 - bitcoin#19826
 - bitcoin#19556
 - bitcoin#19854

Beside backports was done:
 - fixed a bug in Coin Join (possible UB due to using reference to local variable outside of function)
 - removed locks of mempool from governance's related code (introduced in #4801)

## How Has This Been Tested?
Run unit/functional test and introduce no breaking changes.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have assigned this pull request to a milestone

2023-01-30 00:43 UTC, PastaPastaPasta commented
IMO, the first two non-backport commits should be in another PR

2023-01-30 09:56 UTC, knst commented
> IMO, the first two non-backport commits should be in another PR

Please, review #5175 and #5174

2023-01-31 20:11 UTC, UdjinM6 requested changes

2023-02-01 19:00 UTC, UdjinM6 approved these changes
utACK

2023-02-04 16:05 UTC, knst commented
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/85741ebd7862168987128db1aba9980c5084990e..81931f9380846928a4b927ae165bc9a101405307) the bc-bp-mempool branch from[ 85741eb ](https://github.com/dashpay/dash/commit/85741ebd7862168987128db1aba9980c5084990e)to 81931f9

Resolved conflicts with net_processing's refactorins in develop branch

2023-02-04 18:35 UTC, kittywhiskers commented on src/coinjoin/client.cpp
> +void CCoinJoinClientManager::ProcessMessage(const CTxMemPool& mempool, CNode& peer, CConnman& connman, std::string_view msg_type, CDataStream& vRecv)
nit, in line with the argument order of all other `ProcessMessage`s, consider changing this to `CNode& peer, CConnman& connman, const CTxMemPool& mempool, std::string_view msg_type, CDataStream& vRecv`

2023-02-04 18:35 UTC, kittywhiskers commented on src/coinjoin/client.cpp
> +void CCoinJoinClientSession::ProcessMessage(const CTxMemPool& mempool, CNode& peer, CConnman& connman, std::string_view msg_type, CDataStream& vRecv)
nit, see above

2023-02-04 18:37 UTC, kittywhiskers commented on src/coinjoin/client.h
> +//    CTxMemPool& mempool;
nit, remove unused declaration

2023-02-06 16:49 UTC, UdjinM6 submitted a review, later dismissed
re-utACK

2023-02-06 20:03 UTC, knst commented
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/280a8a34eba49036136b89308adfcd1dd47ac8ec..a0ce90536ac564dbc2ad92802b141a4a1887c6ca) the bc-bp-mempool branch from[ 280a8a3 ](https://github.com/dashpay/dash/commit/280a8a34eba49036136b89308adfcd1dd47ac8ec)to a0ce905
Resolved conflict with #5178

2023-02-06 20:25 UTC, UdjinM6 requested changes

2023-02-06 20:25 UTC, UdjinM6 commented on src/wallet/salvage.cpp
> +#include <validation.h>
19556: I think this is no longer needed after 5178 merge
```suggestion
```

2023-02-06 20:29 UTC, UdjinM6 commented
pls squash [d77e96d](https://github.com/dashpay/dash/pull/5169/commits/d77e96d5eeadca1e0f34cffada5111b01784f46d) into [6e878be](https://github.com/dashpay/dash/pull/5169/commits/6e878becf2ed37ce980ccf8518bda9bb8d807986) (19556)

2023-02-06 20:44 UTC, UdjinM6 submitted a review, later dismissed
re-utACK

2023-02-14 12:23 UTC, UdjinM6 approved these changes
re-utACK

2023-02-14 14:56 UTC, kittywhiskers approved these changes
utACK

2023-02-15 06:07 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-02-15 06:08 UTC, merged