style: adjust template of new PR
dashpay/dash pull request #5193
Opened 2023-02-09 18:38 UTC by knst

## Issue being fixed or feature implemented
Currently template for "New pull request" have a lot of instruction that are formatted as comments by html/markdown tag.
It makes this instruction to append in the final commit message when pull request is merged because they are invisible for reviewer (marked as comment).

With new template the messages would be more likely to be cleaned up before merging.

## What was done?
Replaced commented text in template to cursive test (italic)

## How Has This Been Tested?
By clicking "Preview" on GitHub

## Breaking Changes
No breaking changes, it's trivial change

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have assigned this pull request to a milestone

2023-02-09 19:30 UTC, ogabrielides submitted a review, later dismissed
LGTM

2023-02-09 20:05 UTC, thephez requested changes
I didn't realize that was all included in the commit. I agree, it's probably best to remove it :+1: I'd just recommend a slight change in wording.

2023-02-09 20:05 UTC, thephez commented on .github/PULL_REQUEST_TEMPLATE.md
> +***Please remove the following help written in cursive before merging***
```suggestion
***Please remove the italicized help prompts before submitting or merging***
```

2023-02-11 00:23 UTC, PastaPastaPasta submitted a review, later dismissed
utACK for squash merge. This will make it more likely they are removed.

2023-02-11 16:33 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-02-11 19:32 UTC, thephez approved these changes
utACK

2023-02-13 02:20 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-02-13 03:15 UTC, merged