feat(llmq): Introduction of llmq_devnet_platform + update llmqPlatform from args (devnets only)
dashpay/dash pull request #5205
Opened 2023-02-16 11:45 UTC by ogabrielides

## Issue being fixed or feature implemented

Currently, by default in devnet, the LLMQ set for Platform is `LLMQ_100_67`.
Obviously this is too big for usual devnets, therefore the new `LLMQ_DEVNET_PLATFORM` is created (size 12, threshold 67%).

`LLMQ_100_67` is still the default one: added possibility to overwrite it by passing argument `-llmqplatform` (devnets only)

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-02-16 12:44 UTC, ogabrielides commented
@thephez Do we need release notes for the extra argument `-llmqplatform` ?

2023-02-16 14:28 UTC, thephez commented
> @thephez Do we need release notes for the extra argument `-llmqplatform` ?

If @PastaPastaPasta thinks we do :slightly_smiling_face:

2023-02-16 18:47 UTC, UdjinM6 commented
>Currently, by default in devnet, the LLMQ set for Platform is LLMQ_100_67.
Obviously this is too big for usual devnets

why 
> LLMQ_100_67 is still the default one

then?

2023-02-16 18:57 UTC, ogabrielides commented
> >Currently, by default in devnet, the LLMQ set for Platform is LLMQ_100_67.
> 
> Obviously this is too big for usual devnets
> 
> 
> 
> why 
> 
> > LLMQ_100_67 is still the default one
> 
> 
> 
> then?

Similarly to llmqChainlock, llmqInstantSend, llmqInstantSendDIP0024: by default the larger LLMQs LLMQ_50_60, LLMQ_60_75 are set but they can be overwritten with -llmqchainlock, -llmqinstantsenddip0024 for smaller devnets.

2023-02-16 19:07 UTC, UdjinM6 submitted a review, later dismissed
hmm.. ok, makes sense (for this PR) I guess. But we should probably consider changing devnet defaults to more realistic ones (and drop most likely useless/unused llmqs like the ones with 400 members).

utACK

2023-02-16 19:11 UTC, ogabrielides commented
@UdjinM6 Sometimes we still need to deploy large devnets and rest stuff with conditions close to Testnet 🤷🏼‍♂️

2023-02-16 19:12 UTC, UdjinM6 commented
> @UdjinM6 Sometimes we still need to deploy large devnets and rest stuff with conditions close to Testnet 🤷🏼‍♂️

hmm..ok.

2023-02-16 20:28 UTC, thephez requested changes
Isn't this an issue?

2023-02-16 20:28 UTC, thephez commented on src/llmq/params.h
> +        .threshold = 8,
Threshold can't exceed minsize can it? :thinking:

2023-02-16 20:44 UTC, ogabrielides commented
@thephez good catch!

2023-02-17 18:47 UTC, UdjinM6 approved these changes
utACK

2023-02-17 19:07 UTC, thephez approved these changes
Looks better :+1: 
utACK

2023-02-19 16:52 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-02-19 16:53 UTC, merged