refactor/fix: return `Invalid` mn type instead of crashing on `assert` in `GetMnType`
dashpay/dash pull request #5209
Opened 2023-02-17 18:23 UTC by UdjinM6

## Issue being fixed or feature implemented
We use `GetMnType` in some critical parts of code where we process data from blocks and such. Having `assert` called there makes me nervous 😅

## What was done?
We should simply consider all unknown types invalid instead of crashing here. Introduced new dummy mn type for which no real mn can ever satisfy conditions.

## How Has This Been Tested?
run tests

## Breaking Changes
n/a

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-02-17 19:04 UTC, knst requested changes

2023-02-17 19:04 UTC, knst commented on src/evo/dmn_types.h
> +    return GetMnType(type) != dmn_types::Invalid;
I think better to iomplement it like `return (static_cast<uint16_t>(type) > MnType::LAST);`

2023-02-17 19:04 UTC, knst commented on src/evo/dmn_types.h
> +    return GetMnType(type) != dmn_types::Invalid;
And define LAST like:
...
HighPerformance = 1,
LAST = HighPerformance,
Invalid = ....

2023-02-17 19:50 UTC, knst approved these changes
uACK

2023-02-17 19:50 UTC, knst commented on src/evo/dmn_types.h
> +    return type < MnType::COUNT;
Wow! I didn't know that members of `enum class` can be compared without cast such as`static_cast<uint16_t>(type) < static_cast<uint16_t(MnType::COUNT)`
😮😮😮

2023-02-19 05:06 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-02-19 18:37 UTC, ogabrielides approved these changes
LGTM

2023-02-19 19:18 UTC, merged