docs(rpc): correct help for protx legacy versions
dashpay/dash pull request #5234
Opened 2023-03-03 15:05 UTC by ogabrielides

## Issue being fixed or feature implemented

Help text for protx legacy versions were adjusted.
## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-03-04 18:04 UTC, PastaPastaPasta approved these changes
utACK for squash merge; seems fine

2023-03-07 16:53 UTC, thephez approved these changes
Concept ACK. Didn't test.

2023-03-07 17:08 UTC, thephez requested changes
Just kidding... :see_no_evil: Felt guilty about not testing.
The comparison is inverted in at least some cases.
![image](https://user-images.githubusercontent.com/8145677/223496359-1cdf3301-9a87-481e-b726-23d6e68372e3.png)

Also, `protx register` / `protx register_legacy` don't seem to be covered. Should they be?

2023-03-07 17:24 UTC, thephez reviewed
I think this is the correct order for these...

2023-03-07 17:24 UTC, thephez commented on src/rpc/evo.cpp
> +    std::string rpc_name = legacy ? "register_fund" : "register_fund_legacy";
```suggestion
    std::string rpc_name = legacy ? "register_fund_legacy" : "register_fund";
```

2023-03-07 17:24 UTC, thephez commented on src/rpc/evo.cpp
> +    std::string rpc_name = legacy ? "register" : "register_legacy";
```suggestion
    std::string rpc_name = legacy ? "register_legacy" : "register";
```

2023-03-07 17:24 UTC, thephez commented on src/rpc/evo.cpp
> +    std::string rpc_name = legacy ? "register_prepare" : "register_prepare_legacy";
```suggestion
    std::string rpc_name = legacy ? "register_prepare_legacy" : "register_prepare";
```

2023-03-08 13:34 UTC, thephez commented on src/rpc/evo.cpp
> +                "It has to match the BLS private key which is later used when operating the masternode.\n"}
Looks like this adds an extra blank line.
```suggestion
                "It has to match the BLS private key which is later used when operating the masternode."}
```

2023-03-08 17:41 UTC, thephez submitted a review, later dismissed
LGTM :+1:

2023-03-08 21:55 UTC, thephez approved these changes
:+1: Good catch

2023-03-08 22:26 UTC, UdjinM6 approved these changes
utACK

2023-03-11 17:46 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-03-11 17:46 UTC, merged