backport: guix related backports
dashpay/dash pull request #5237
Opened 2023-03-06 09:32 UTC by knst

## Issue being fixed or feature implemented
This PR improve overall support of guix:
 - bump some packages versions
 - improve guix scripts
 - introduce Mac OS X builds and many other things.

Furthermore Guix is considered as a replacement for gitian for binary builds.

Prior work: https://github.com/dashpay/dash/pull/5194
Related issue: https://github.com/dashpay/dash-issues/issues/47

## What was done?
There is a bunch of backports that is related to guix. These backports improve overall support of guix

- bitcoin/bitcoin#18958
- bitcoin/bitcoin#20318
- bitcoin/bitcoin#20619
- bitcoin/bitcoin#20937
- bitcoin/bitcoin#17920
- bitcoin/bitcoin#20629
- bitcoin/bitcoin#21116
- bitcoin/bitcoin#21163
- bitcoin/bitcoin#21087
- bitcoin/bitcoin#21088
- partial bitcoin/bitcoin#21089
- bitcoin/bitcoin#21078
- bitcoin/bitcoin#21271
- bitcoin/bitcoin#21272
- bitcoin/bitcoin#21321
- bitcoin/bitcoin#21323
- bitcoin/bitcoin#21298
- partial bitcoin/bitcoin#21325
- bitcoin/bitcoin#21337
- bitcoin/bitcoin#21375
- bitcoin/bitcoin#21611
- partial bitcoin/bitcoin#21626
- bitcoin/bitcoin#21304
- bitcoin/bitcoin#21661
- bitcoin/bitcoin#21672
- bitcoin/bitcoin#21655
- bitcoin/bitcoin#19817
- bitcoin/bitcoin#21799
- bitcoin/bitcoin#21462
- bitcoin/bitcoin#21239
- bitcoin/bitcoin#21654
- bitcoin/bitcoin#22075
- bitcoin/bitcoin#22190
- bitcoin/bitcoin#22182
- bitcoin/bitcoin#22365
- bitcoin/bitcoin#22405
- bitcoin/bitcoin#22410
- bitcoin/bitcoin#22465
- bitcoin/bitcoin#22533
- bitcoin/bitcoin#22643
- bitcoin/bitcoin#22847
- [TO BE REVERTED LATER] bitcoin/bitcoin#24215

## What is NOT done yet?
 - there is still no dashification, it would be done in further PR after backport bitcoin/bitcoin#21711
 - currently builds for PowerPC fails, most likely failure is related to outdated `freetype` package. To-be-fixed in further backports
 - backport bitcoin/bitcoin#24215 should be reverted because the proper way to do it to bump `guix` to newer version. It would be done in futher PR, not trivial to be done ATM.

## How Has This Been Tested?
 - Firstly, you need to get SDK path for Mac OS build. Official recommended way is download it from Apple's website using Apple ID
 - set up environment variable `export SDK_PATH=....`. Be aware, that it works only for full path (not relative).
 - run `contrib/guix/guix-build`. You need ~30Gb of free space to get built all platform.
_hashes-to-be-posted-later_

## Breaking Changes
Should not be breaking changes at the moment

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone

2023-03-06 10:50 UTC, knst commented
`contrib/shell/realpath.bash`
> # Based on realpath.sh written by Michael Kropat
> # Found at: https://github.com/mkropat/sh-realpath/blob/65512368b8155b176b67122aa395ac580d9acc5b/realpath.sh

@thephez 
Should we add these credits somewhere else in docs/licenses/etc? Seems as it is licensed by MIT license in the original repo.

2023-03-07 16:32 UTC, thephez commented
> `contrib/shell/realpath.bash`
> 
> > Based on realpath.sh written by Michael Kropat
> > Found at: https://github.com/mkropat/sh-realpath/blob/65512368b8155b176b67122aa395ac580d9acc5b/realpath.sh
> 
> @thephez Should we add these credits somewhere else in docs/licenses/etc? Seems as it is licensed by MIT license in the original repo.

Did this come via a backport? If so, we should probably just handle it however bitcoin did.

2023-03-20 01:12 UTC, PastaPastaPasta commented
my results 
```
pasta@pasta1 /mnt/volume_tor1_01/dash
 % find guix-build-"$(git  rev-parse --short=12 c09129bfff55ee82861998d985f2bc49cc498a6c)"/output -type f | grep -v SHA256 | xargs  sha256sum  | sort -k 2

ef22745c6f4674c314af2e8d47c3b2078025041be7363eaf5a80d2ebe4183cef  guix-build-c09129bfff55/output/aarch64-linux-gnu/bitcoin-c09129bfff55-aarch64-linux-gnu-debug.tar.gz
6901f13b487a0385d3c441f243830d3ee04a070baced5f5a041eb6f6760dafa5  guix-build-c09129bfff55/output/aarch64-linux-gnu/bitcoin-c09129bfff55-aarch64-linux-gnu.tar.gz
a5c19915a39b096b681efd14e649fddc930b9e676a9ebe0d60d04f3eaa368ff7  guix-build-c09129bfff55/output/arm-linux-gnueabihf/bitcoin-c09129bfff55-arm-linux-gnueabihf-debug.tar.gz
0eed27a58acbc0d11776e6950c3f716807aade0d05542b79ae342a23389541ea  guix-build-c09129bfff55/output/arm-linux-gnueabihf/bitcoin-c09129bfff55-arm-linux-gnueabihf.tar.gz
1f86baf527062c7f47ec567fd0ec55f9e104f7ed99c4273fec463e7a086376f1  guix-build-c09129bfff55/output/dist-archive/bitcoin-c09129bfff55.tar.gz
515c071f63c6bd0e9ca1baeea121ff000e47303c507e15a6a5e9db1ae68823bf  guix-build-c09129bfff55/output/riscv64-linux-gnu/bitcoin-c09129bfff55-riscv64-linux-gnu-debug.tar.gz
1a82c21c72126f0dde54cb772fb6f2d1a877982c70c194608fe02ad4a1696a56  guix-build-c09129bfff55/output/riscv64-linux-gnu/bitcoin-c09129bfff55-riscv64-linux-gnu.tar.gz
174619e05109b1c84d18fd4ae34cfc330cd51e4ce8616e919f636abe512c4c52  guix-build-c09129bfff55/output/x86_64-apple-darwin18/bitcoin-c09129bfff55-osx-unsigned.dmg
378fb01c9788217e545cc1de0c376bcd5465d2712ad760c885b924d666a19c0f  guix-build-c09129bfff55/output/x86_64-apple-darwin18/bitcoin-c09129bfff55-osx-unsigned.tar.gz
425808ce4e1ffe658ad3a51055d35aebe33bbeba02003a4d9a6301b7028a3629  guix-build-c09129bfff55/output/x86_64-apple-darwin18/bitcoin-c09129bfff55-osx64.tar.gz
6e6913fb45e8ba2c17af80746666d4d770f5d06e7eea9bac2b54803115393186  guix-build-c09129bfff55/output/x86_64-linux-gnu/bitcoin-c09129bfff55-x86_64-linux-gnu-debug.tar.gz
a9f335769802fb1e57dc54f74f28a4926f05477075b54cc199e5c13c7d34f183  guix-build-c09129bfff55/output/x86_64-linux-gnu/bitcoin-c09129bfff55-x86_64-linux-gnu.tar.gz
75b1c423dff080846176b26ab423173bb85ecfae291d8a932b9adf67ca38f4be  guix-build-c09129bfff55/output/x86_64-w64-mingw32/bitcoin-c09129bfff55-win-unsigned.tar.gz
6f10b508277d30d358548c591f83c6050709faa210715c241c02a64b6d853f49  guix-build-c09129bfff55/output/x86_64-w64-mingw32/bitcoin-c09129bfff55-win64-debug.zip
70c1e6d3278c9ef74c05b1f8ce164c3e5d4c90bc1283edd04981f453861f4948  guix-build-c09129bfff55/output/x86_64-w64-mingw32/bitcoin-c09129bfff55-win64-setup-unsigned.exe
562accd3e4c8e37731aa1077a2d7dfe7c9ac6718c1f77864092995cd21970401  guix-build-c09129bfff55/output/x86_64-w64-mingw32/bitcoin-c09129bfff55-win64.zip
```

2023-03-20 04:57 UTC, knst commented
> my results
hashes matched, but somehow `|sort -k2` sorted hashes in different order

2023-03-22 16:19 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-03-24 18:52 UTC, UdjinM6 requested changes

2023-03-24 18:52 UTC, UdjinM6 commented on contrib/gitian-build.py
> +
19817: should drop this. we do not skip macos build if no sdk is found, we download sdk instead and continue (see line 77).

2023-03-26 08:58 UTC, UdjinM6 approved these changes
ACK

2023-03-26 22:23 UTC, merged