feat: mnUniquePropertyMap repopulate for v19
dashpay/dash pull request #5239
Opened 2023-03-07 16:48 UTC by ogabrielides

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-03-08 17:15 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-03-08 17:36 UTC, PastaPastaPasta commented on src/evo/deterministicmns.cpp
> +        if (v19_just_activated) {
```suggestion
        if (bool v19_just_activated = pindex == llmq::utils::V19ActivationIndex(pindex); v19_just_activated) {
```

2023-03-08 17:45 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-03-08 18:58 UTC, UdjinM6 requested changes

2023-03-08 19:00 UTC, PastaPastaPasta commented on test/functional/feature_dip3_v19.py
> +        b_0 = self.nodes[0].getbestblock_hash()
dangit cmd-f! why didn't you understand my intent!

2023-03-08 20:32 UTC, ogabrielides commented
@PastaPastaPasta Corrections.
Top secret advise: Run the test locally before pushing :)

2023-03-08 22:26 UTC, UdjinM6 submitted a review, later dismissed
re-utACK

2023-03-09 14:09 UTC, ogabrielides commented
@PastaPastaPasta @UdjinM6 Rebased, wanted to test with #5240.

2023-03-09 17:48 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-03-09 18:14 UTC, UdjinM6 approved these changes
utACK

2023-03-11 17:42 UTC, merged