feat: isdlock support without quorum rotation (regtest only)
dashpay/dash pull request #5259
Opened 2023-03-16 19:16 UTC by ogabrielides

## Issue being fixed or feature implemented

In #5229, we disabled rotation when running a regtest with 3 nodes.
Instantsend were non-deterministic islocks.
This PR aims to make them deterministic for a 3-nodes regtest network (Platform dev environment).

## What was done?

Added the possibility to overwrite `llmqinstantsend` and `llmqinstantsenddip0024`.
By starting a regtest with:
`-llmqinstantsend=llmq_test`
`-llmqinstantsenddip0024=llmq_test_instantsend`

Instantsend locks will be deterministic without running quorum rotation.

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2023-03-16 19:27 UTC, knst requested changes

2023-03-16 19:27 UTC, knst commented on src/chainparams.cpp
> +    LogPrintf("Setting llmqinstantsend to size=%ld\n", static_cast<uint8_t>(llmqType));
better to use here `ToUnderlying` because it doesn't require to specify type manually.

2023-03-16 19:27 UTC, knst commented on src/chainparams.cpp
> +    LogPrintf("Setting llmqinstantsenddip0024 to size=%ld\n", static_cast<uint8_t>(llmqType));
same here (`ToUnderlying`)

2023-03-16 19:27 UTC, knst commented on src/chainparams.cpp
> +    for (const auto& params : consensus.llmqs) {
It seems as this loop already implemented several times:
```
         if (auto optLLMQParams = ranges::find_if_opt(Params().GetConsensus().llmqs, 
                                                     [&strLLMQType](const auto& params){return params.name == strLLMQType;})) {
```
in `src/llmq/utils.cpp` and `src/chainparams.cpp`:
```
    Consensus::LLMQType llmqType = Consensus::LLMQType::LLMQ_NONE;
    for (const auto& params : consensus.llmqs) {
        if (params.name == strLLMQType) {
            llmqType = params.type;
        }
    }
```
May be it's time to refactor to a new method:
```
    const Consensus::LLMQParams& GetLLMQ(const std::string& llmqTypeName) const;
```
?

2023-03-17 14:31 UTC, ogabrielides commented
@knst All your suggestions are valid.
But because similar refactoring can be made in `UpdateDevnetLLMQInstantSendFromArgs`,  `UpdateDevnetLLMQInstantSendDIP0024FromArgs` and since this is irrelevant to this PR.
Please feel free to open a new PR refactoring all the cases (once this gets merged)

2023-03-17 14:47 UTC, ogabrielides commented
@PastaPastaPasta @UdjinM6 Moved this to v19 as requested by @markin-io.

2023-03-20 15:39 UTC, merged