Fix missing includes
dashpay/dash pull request #5295
Opened 2023-04-05 20:18 UTC by OlegGirko

The `<stdexcept>` include is needed for `std::runtime_error` definition.
The `<cstdint>` include is needed for `uint8_t` and `uint32_t` definition.

## Issue being fixed or feature implemented
Compilation failure with GCC 13.
GCC 13 is more strict about missing includes that were included indirectly by previous versions of GCC.

## What was done?
Added missing includes.

## How Has This Been Tested?
Successful compilation on Fedora 38 with GCC 13. All tests passed successfully.

## Breaking Changes
None.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

2023-04-05 21:11 UTC, UdjinM6 requested changes

2023-04-05 21:21 UTC, OlegGirko commented on src/util/string.h
> +#include <cstdint>
Done. I was fixing in `main` branch, missed that it's fixed in `develop`.

2023-04-05 21:21 UTC, OlegGirko commented on src/util/bip32.h
> +#include <cstdint>
Done.

2023-04-05 21:25 UTC, OlegGirko commented
Rebased on updated `develop` branch.

2023-04-05 22:42 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-04-06 02:20 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-04-06 02:20 UTC, merged