backport: trivial backports April 6
dashpay/dash pull request #5297
Opened 2023-04-06 06:16 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Trivial backports cherry-picked via script. 

## What was done?
Trivial backports

## How Has This Been Tested?
Light review and make -j8 check and functional tests all passed

## Breaking Changes
None that I saw

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2023-04-06 07:25 UTC, knst requested changes

2023-04-06 07:25 UTC, knst commented on src/test/fuzz/process_message.cpp
> +        g_setup->m_node.peerman->SendMessages(&p2p_node);
```
-g_setup->m_node.peerman->SendMessages(&p2p_node);
+g_setup->m_node.peer_logic->SendMessages(&p2p_node);
```

2023-04-06 07:25 UTC, knst commented on src/test/fuzz/process_messages.cpp
> +            g_setup->m_node.peerman->SendMessages(&random_node);
```
-g_setup->m_node.peerman->SendMessages(&p2p_node);
+g_setup->m_node.peer_logic->SendMessages(&p2p_node);
```

2023-04-06 07:25 UTC, knst commented on src/test/fuzz/process_message.cpp
> +        g_setup->m_node.peerman->SendMessages(&p2p_node);
due to missing 
```
    Merge #19791: [net processing] Move Misbehaving() to PeerManager
```

2023-04-06 15:05 UTC, knst approved these changes
LGTM now. utACK

2023-04-07 19:01 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-04-09 05:07 UTC, merged