Develop trivial 2023 04 15
dashpay/dash pull request #5326
Opened 2023-04-15 17:41 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Trivial backport cherry-picked via script on April 15th

## What was done?
Backports

## How Has This Been Tested?
Make -j8 check

## Breaking Changes
Should be none; did a light review

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-04-15 19:45 UTC, knst requested changes

2023-04-15 19:45 UTC, knst commented on src/test/transaction_tests.cpp
> +    // Check P2WPKH outputs dust threshold
Change a comment P2WPKH -> p2pkh?

2023-04-15 19:45 UTC, knst commented on src/test/transaction_tests.cpp
> +    // Check P2WSH outputs dust threshold
same

2023-04-15 19:45 UTC, knst commented on src/test/transaction_tests.cpp
> +    // Check future Witness Program versions dust threshold
```
-// Check future Witness Program versions dust threshold
+// Check future Pay-2-Script versions dust threshold
```

2023-04-16 03:57 UTC, PastaPastaPasta commented
@knst dropped those as the test failed :)

2023-04-16 08:21 UTC, UdjinM6 commented
linter complains `contrib/devtools/test-symbol-check.py:27:23: F821 undefined name 'get_machine'`

2023-04-16 17:11 UTC, PastaPastaPasta commented
Resolved

2023-04-16 17:56 UTC, knst commented
utACK

2023-04-16 20:40 UTC, UdjinM6 commented
LGTM but CI failed to start for some reason..

2023-04-16 21:56 UTC, UdjinM6 approved these changes
utACK

2023-04-16 21:57 UTC, merged