docs:
dashpay/dash pull request #5390
Opened 2023-05-24 17:07 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Missing docs

## What was done?
Added docs

## How Has This Been Tested?
In release of v19.1

## Breaking Changes
None

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-05-24 19:42 UTC, thephez approved these changes
LGTM from formatting, etc standpoint. Can't speak to whether or not the steps work as listed.

2023-05-25 09:35 UTC, UdjinM6 requested changes

2023-05-25 15:13 UTC, PastaPastaPasta commented on doc/release-process.md
> +Replace "{version}" with the version you are notarizing and "AC_PASSWORD" with your keychain profile. This command uploads the .dmg file to Apple's notary service.
```suggestion
Replace "{version}" with the version you are notarizing. This command uploads the .dmg file to Apple's notary service.
```

2023-05-25 20:52 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-05-26 18:41 UTC, merged