feat: ability to disable clsig creation while retaining clsig enforcement
dashpay/dash pull request #5398
Opened 2023-05-30 03:46 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Currently, Chainlocks are either enabled or disabled. This PR adds a third state: enabled but we will not sign new ones.

Should probably backport this to v19.x

## What was done?
Spork state != 0 but active will now result in chain locks being enforced but not created.

## How Has This Been Tested?

## Breaking Changes
None

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-05-30 07:48 UTC, UdjinM6 requested changes
pls update `feature_llmq_chainlocks.py` to make sure it works as expected

2023-05-31 17:45 UTC, UdjinM6 submitted a review, later dismissed
one nit

utACK

2023-05-31 17:45 UTC, UdjinM6 commented on test/functional/feature_llmq_chainlocks.py
> +            block_hash = self.nodes[0].getbestblockhash()
could do it in one rpc call
```suggestion
            block_hash = self.nodes[0].generate(1)[0]
```

2023-05-31 17:47 UTC, UdjinM6 approved these changes
re-utACK

2023-05-31 18:40 UTC, ogabrielides approved these changes
utACK

2023-05-31 20:34 UTC, merged