perf: avoid rehashing block; use stored hash
dashpay/dash pull request #5435
Opened 2023-06-14 16:39 UTC by PastaPastaPasta

before 12%
<img width="1538" alt="image" src="https://github.com/dashpay/dash/assets/6443210/fa5043fb-4e48-4728-bfaf-8636d5c20a8c">
after 10%
<img width="1544" alt="image" src="https://github.com/dashpay/dash/assets/6443210/1df6aff4-2901-4af1-b421-3604f54df157">

## Issue being fixed or feature implemented
Redundant rehash

## What was done?
Avoid redundant rehash

## How Has This Been Tested?
Reindexed 0-500000 on testnet

## Breaking Changes
None

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-06-14 17:16 UTC, UdjinM6 approved these changes
Good catch! 

utACK

2023-06-16 07:18 UTC, knst commented on src/evo/deterministicmns.cpp
> -        newList.SetBlockHash(block.GetHash());
I guess `UndoBlock` is not called same often as `ProcessBlock`, so, performance impact is much less noticeable. 
But I'd like to suggest to update `UndoBlock` too.
```
uint256 blockHash = block.GetHash();
```

2023-06-20 12:50 UTC, ogabrielides submitted a review, later dismissed
LGTM.
Maybe implement @knst suggestion on `UndoBlock` as well?

2023-06-20 17:34 UTC, PastaPastaPasta commented
Starting a guix build here to ensure that it works here (note this is pre-guix2)

2023-07-04 17:33 UTC, knst approved these changes
utACK

2023-07-04 17:35 UTC, UdjinM6 requested changes

2023-07-04 17:35 UTC, UdjinM6 commented on src/evo/deterministicmns.cpp
> +    uint256 blockHash = pindex->GetBlockHash();
`block` is no longer used

2023-07-07 21:00 UTC, UdjinM6 approved these changes
utACK

2023-07-07 21:03 UTC, merged