feat(wallet): TopUpKeyPool improvements
dashpay/dash pull request #5456
Opened 2023-06-22 20:35 UTC by UdjinM6

## Issue being fixed or feature implemented
- make progress calculations sane
- show progress in GUI but only when you need 100+ new keys
- make it stop on shutdown request
- spam less in debug.log

## What was done?

## How Has This Been Tested?
run tests, run `keypoolrefill` with `1100` (add 100 keys, no gui popup) and `10000` (100+ keys, progress bar) on testnet wallet, check logs, verify it can be interrupted on shutdown

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-06-25 09:40 UTC, knst requested changes

2023-06-25 09:40 UTC, knst commented on src/wallet/scriptpubkeyman.cpp
> +        int64_t i{0};
nit: so far as `i` is used outside of loop maybe give it a better name? Otherwise it feels like LogPrintf is still inside a loop.

2023-06-25 09:40 UTC, knst commented on src/wallet/scriptpubkeyman.cpp
> +        std::string strMsg = _("Topping up keypool...").translated;
nit: missing `const`

2023-06-25 09:40 UTC, knst commented on src/wallet/scriptpubkeyman.cpp
> +        int64_t total_missing = missingInternal + missingExternal;
nit: missing `const`:
```
const int64_t total_missing = ...
```

2023-06-25 09:40 UTC, knst commented on src/wallet/scriptpubkeyman.cpp
> +            double dProgress = 100.f * i / (total_missing);
also missing `const`. dProgress is not changed anyhow below, so, it's const.

2023-06-26 05:13 UTC, PastaPastaPasta commented
Aww I complained about this issue :) I feel heard

2023-06-26 05:16 UTC, PastaPastaPasta commented on src/wallet/scriptpubkeyman.cpp
> +                    uiInterface.ShowProgress(strMsg, (int)dProgress, false);
don't use c-style casts please :)

2023-06-26 05:17 UTC, PastaPastaPasta reviewed
Looks fine, please fix use of c-style casts :)

2023-06-26 06:36 UTC, knst commented on src/wallet/scriptpubkeyman.cpp
>                  if (should_show_progress && (int)dProgress > 0) {
I think here is not needed cast at all. `100.f * i / (total_missing)` seems as always positive; `dProgress > 0.f` should works as well

2023-06-26 20:38 UTC, knst approved these changes
re-ACK

2023-06-28 05:33 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-06-28 16:01 UTC, merged