fix: for HPMN should be used only bls basic, enforce that rule
dashpay/dash pull request #5463
Opened 2023-06-28 08:23 UTC by knst

## Issue being fixed or feature implemented
for HPMN should be used only bls basic, enforce that rule in serialization/unserialization of CProUpServTx.

## What was done?
It splits from https://github.com/dashpay/dash/pull/5443

## How Has This Been Tested?
Run functional/unit tests.

## Breaking Changes
Serialization slightly changed, but it should be not breaking change

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2023-06-28 09:13 UTC, ogabrielides requested changes
Could add the same check on `CProRegTx`.

2023-06-28 12:48 UTC, ogabrielides approved these changes
utACK

2023-06-28 14:28 UTC, UdjinM6 requested changes
we should really have similar checks in corresponding `IsTriviallyValid`s too

2023-06-30 07:50 UTC, ogabrielides submitted a review, later dismissed
utACK

2023-06-30 07:57 UTC, knst commented
> we should really have similar checks in corresponding IsTriviallyValids too

We indeed need to have this validation, I added them in PR. Btw, there's no unit tests for it because:
```
    //TODO: Provide raw data for basic scheme as well
```
I created issue for it: https://github.com/dashpay/dash/issues/5471

2023-06-30 10:51 UTC, UdjinM6 requested changes

2023-06-30 11:03 UTC, knst commented on src/evo/providertx.h
> +        if (obj.nType == MnType::HighPerformance) {
agree, make sense, the error message would be more readable.

2023-10-01 17:46 UTC, ogabrielides approved these changes
ACK :+1:

2023-10-04 11:27 UTC, UdjinM6 approved these changes
utACK

2023-10-30 21:53 UTC, ogabrielides commented
@PastaPastaPasta Reasons for keeping this one open?

2023-10-31 14:29 UTC, PastaPastaPasta commented
It seems like we're not gonna merge this for v20 right? I think that's better but that's correct right?

2023-10-31 14:48 UTC, knst commented
> @[knst](https://github.com/knst) knst modified the milestones: [20](https://github.com/dashpay/dash/milestone/34), [21](https://github.com/dashpay/dash/milestone/38) [Oct 23, 2023](https://github.com/dashpay/dash/pull/5463#event-10742875205) last week

> It seems like we're not gonna merge this for v20 right? I think that's better but that's correct right?

I intentionally changed milestone to v21 - we have already RC; let's don't increase scope for v20.

2023-10-31 15:09 UTC, UdjinM6 commented
Hmm... I would actually suggest to merge it into v20 - it streamlines the logic and extends unit tests a lot. Imo it a valuable one.

2023-11-08 16:28 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-11-08 16:28 UTC, PastaPastaPasta commented on src/evo/providertx.h
> +
nit unrelated

2023-11-08 16:30 UTC, merged