perf: actually only process each dsq once
dashpay/dash pull request #5484
Opened 2023-07-07 17:40 UTC by PastaPastaPasta

5 minute profiling shows previous usage around ~7% and current usage around ~2%

## Issue being fixed or feature implemented
Due to us rapidly receiving multiple duplicates of DSQueue's, we start processing them before it's added the the vector of processed ones, we probably at one point tried to minimize locked time, but that's not productive here

## What was done?
Expand the locked scope to ensure we don't double process. 

## How Has This Been Tested?
Ran full node for 5-10 minutes

## Breaking Changes
Should be none

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-07-07 21:36 UTC, UdjinM6 commented
> we probably at one point tried to minimize locked time, but that's not productive here

```
POTENTIAL DEADLOCK DETECTED
Previous lock order was:
 (2) 'cs_deqsessions' in coinjoin/client.cpp:987 (in thread 'scheduler')
 (1) 'cs_vecqueue' in coinjoin/coinjoin.cpp:191 (TRY) (in thread 'scheduler')
Current lock order is:
 (1) 'cs_vecqueue' in coinjoin/client.cpp:71 (TRY) (in thread 'msghand')
 (2) 'cs_deqsessions' in coinjoin/client.cpp:1243 (in thread 'msghand')
```

2023-07-07 21:37 UTC, UdjinM6 requested changes
NACK

2023-07-09 02:01 UTC, PastaPastaPasta commented
Okay, so partially reverted and added a new mutex to prevent processing DSQueue in parallel. I also ended up changing some TRY_LOCK to just LOCK, can you maybe explain why we're using TRY_LOCK here?

2023-07-09 11:55 UTC, UdjinM6 commented
>can you maybe explain why we're using TRY_LOCK here?

We had some issues with multiple threads locking it back then. I don't remember what these issues were exactly and I'm not sure they are still there, could probably use `LOCK()` now. Mixing on testnet seems to be working ok.

Re changes:
 - no need for extra scope for `cs_ProcessDSQueue`, it's held till the end of the function;
 - should have no unrelated changes in `LogPrint`s.

This PR can/should be trimmed to basically
```diff
diff --git a/src/coinjoin/client.cpp b/src/coinjoin/client.cpp
index d538b277ed..2db59e8e88 100644
--- a/src/coinjoin/client.cpp
+++ b/src/coinjoin/client.cpp
@@ -67,10 +67,10 @@ void CCoinJoinClientQueueManager::ProcessDSQueue(const CNode& peer, PeerManager&
         }
     }
 
-    {
-        TRY_LOCK(cs_vecqueue, lockRecv);
-        if (!lockRecv) return;
+    LOCK(cs_ProcessDSQueue);
 
+    {
+        LOCK(cs_vecqueue);
         // process every dsq only once
         for (const auto &q: vecCoinJoinQueue) {
             if (q == dsq) {
@@ -123,9 +123,7 @@ void CCoinJoinClientQueueManager::ProcessDSQueue(const CNode& peer, PeerManager&
         ranges::any_of(coinJoinClientManagers,
                        [&dsq](const auto &pair) { return pair.second->MarkAlreadyJoinedQueueAsTried(dsq); });
 
-        {TRY_LOCK(cs_vecqueue, lockRecv);
-        if (!lockRecv) return;
-        vecCoinJoinQueue.push_back(dsq);}
+        WITH_LOCK(cs_vecqueue, vecCoinJoinQueue.push_back(dsq));
         dsq.Relay(connman);
     }
 }
diff --git a/src/coinjoin/client.h b/src/coinjoin/client.h
index cd5e28317d..f629df3b74 100644
--- a/src/coinjoin/client.h
+++ b/src/coinjoin/client.h
@@ -159,6 +159,7 @@ class CCoinJoinClientQueueManager : public CCoinJoinBaseManager
 private:
     CConnman& connman;
     const CMasternodeSync& m_mn_sync;
+    mutable Mutex cs_ProcessDSQueue;
 
 public:
     explicit CCoinJoinClientQueueManager(CConnman& _connman, const CMasternodeSync& mn_sync) :
```

2023-07-09 16:03 UTC, PastaPastaPasta commented
I intended for dsq.Relay to be outside of the locked scope; adjusted to reflect that, which means that we do need that additional scope. Thoughts now? I could trim this PR down a bit, but I think I'd prefer to keep relay out of locked scope

2023-07-09 20:20 UTC, UdjinM6 commented
> I'd prefer to keep relay out of locked scope

why?

2023-07-09 20:22 UTC, PastaPastaPasta commented
Just because it's relatively expensive and there's no reason to block processing other dsqueue during that time.

2023-07-09 20:25 UTC, UdjinM6 reviewed
ok. one nit.

2023-07-09 20:25 UTC, UdjinM6 commented on src/coinjoin/client.cpp
>          }
```suggestion
        } // cs_vecqueue
```

2023-07-10 09:06 UTC, UdjinM6 approved these changes
ACK

2023-07-10 15:23 UTC, knst approved these changes
utACK (see comment)

2023-07-10 15:40 UTC, PastaPastaPasta commented on src/coinjoin/client.cpp
> +                    LogPrint(BCLog::COINJOIN, /* Continued */
It's required for linter to not complain

2023-07-16 17:58 UTC, merged