feat: v20 evonodes payment adjustment
dashpay/dash pull request #5493
Opened 2023-07-17 14:57 UTC by ogabrielides

## Issue being fixed or feature implemented
Since v19, Evo nodes are paid 4x blocks in a row.
This needs to be reverted when v20 activates.

## What was done?

## How Has This Been Tested?
`feature_llmq_hpmn.py` with v20 activation.

## Breaking Changes
no

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-07-17 15:02 UTC, knst commented
@ogabrielides check this one: https://github.com/dashpay/dash/pull/5342/commits/a7c3840678c0e59bdb834ca172151e2adc97f629 (part of PR 5342)

2023-07-18 16:57 UTC, ogabrielides commented
> @ogabrielides check this one: [a7c3840](https://github.com/dashpay/dash/commit/a7c3840678c0e59bdb834ca172151e2adc97f629) (part of PR 5342)
> 
> Seems as missing changes inside `CDeterministicMNManager::BuildNewListFromBlock`
> 
> Also `CDeterministicMNList::GetProjectedMNPayees` [used by rpc].

@knst Thanks! 
Implemented it.

2023-07-19 08:43 UTC, knst requested changes
I am looking again `CDeterministicMNList::GetProjectedMNPayees` and I feel like passing boolean with isV20Active and especially with value by default is not a good API because:

 - it's not a default argument such as "print in json", but an agrument that completely change behaviour and should be specified explitely. if specify wrong version it would not be "unexpected format of result" or "some missing optional field", but just wrong one.
 - things that calls GetProjectedMNPayees may not know anything about v19/v20/etc

Despite that it looks like bad api, it will show in qt's interface wrong amount when v20 will be activate. Beside that all methods here do use abstract  interface classes such as interfaces::Node, or provided models. The direct call `llmq::utils::isV20Active` from qt's code requires knowing too much details about of implementation of things that should be far from UI.

Sadly, but a solution that looks good for me is impossible to implement right now, because `CDeterministicMNList` knows nothing about tip - only height. - see a commit https://github.com/knst/dash/commit/a3eb558bf37024ae6cd774ff95346e905511c23c

But because the height is known there's other option to provide payees. Please, check this commit: https://github.com/knst/dash/commit/24622e1ec34f265839d01016807c7d46191d5cfb 


for reference, difference between  [a3eb558bf37024ae6cd774ff95346e905511c23c](https://github.com/knst/dash/commit/a3eb558bf37024ae6cd774ff95346e905511c23c) (not compilable, just a concept) and [24622e1ec34f265839d01016807c7d46191d5cfb](https://github.com/knst/dash/commit/24622e1ec34f265839d01016807c7d46191d5cfb) (working probably):

```
diff --git a/src/evo/deterministicmns.cpp b/src/evo/deterministicmns.cpp
index da21397118..5bc5b6f529 100644
--- a/src/evo/deterministicmns.cpp
+++ b/src/evo/deterministicmns.cpp
@@ -213,7 +213,7 @@ CDeterministicMNCPtr CDeterministicMNList::GetMNPayee(const CBlockIndex* pIndex)
 
 std::vector<CDeterministicMNCPtr> CDeterministicMNList::GetProjectedMNPayeesAtChainTip(int nCount) const
 {
-    return GetProjectedMNPayees(tipIndex, nCount);
+    return GetProjectedMNPayees(::ChainActive()[nHeight], nCount);
 }
 
 std::vector<CDeterministicMNCPtr> CDeterministicMNList::GetProjectedMNPayees(const CBlockIndex* const pindex, int nCount) const
```

2023-07-20 11:25 UTC, ogabrielides commented
@knst You suggested change make sense. Included your commit.

2023-07-20 11:30 UTC, knst submitted a review, later dismissed
utACK

2023-07-24 10:10 UTC, UdjinM6 approved these changes
utACK

2023-07-25 10:00 UTC, ogabrielides commented
> Probably missing changes in `test/functional/rpc_blockchain.py` [1644bc3#diff-c1987c24fa3e5c788d16de5359500a19a1fea4f379e4288d076cf92be89541dc](https://github.com/dashpay/dash/commit/1644bc37b190231f2ed0fbd574f9632b58248a22#diff-c1987c24fa3e5c788d16de5359500a19a1fea4f379e4288d076cf92be89541dc)

Indeed !

2023-07-25 10:10 UTC, knst submitted a review, later dismissed
utACK

2023-07-25 15:44 UTC, UdjinM6 submitted a review, later dismissed
LGTM, utACK

2023-07-28 08:22 UTC, UdjinM6 approved these changes
re-utACK

2023-08-01 04:52 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-08-01 04:52 UTC, merged