backport: (Partial) Merge #18842
dashpay/dash pull request #5534
Opened 2023-08-09 10:16 UTC by vijaydasmp

2023-11-26 15:13 UTC, vijaydasmp commented
Hello @UdjinM6 , requesting review

2023-11-27 12:03 UTC, knst reviewed
Please rename a commit `Merge #162: Add network to peers window and peer details`
to
`Merge bitcoin-core/gui#162: Add network to peers window and peer details`

to avoid confuction with #162 (due to wrong github UI resolving to this link) and to avoid possible confusion while review/looking to history.

2023-11-27 17:08 UTC, knst submitted a review, later dismissed
utACK

2023-11-28 06:07 UTC, vijaydasmp commented
Hello @UdjinM6 @PastaPastaPasta , requesting review

2023-12-02 03:17 UTC, UdjinM6 requested changes
18842: we don't have rbf so 18842 should not be partial (not skipping it because this code will be used later in future backports outside of rbf)

2023-12-02 03:17 UTC, UdjinM6 commented on src/test/fs_tests.cpp
>  BOOST_AUTO_TEST_SUITE_END()
20932: newline at eof
```suggestion
BOOST_AUTO_TEST_SUITE_END()

```

2023-12-02 17:25 UTC, UdjinM6 approved these changes
utACK

2023-12-04 03:44 UTC, vijaydasmp commented
Hello @knst @UdjinM6 and @PastaPastaPasta , Requesting review again, had to fix merge conflict, on src/addrman.h file ,

2023-12-04 10:23 UTC, knst approved these changes
utACK

note for reviewers: bitcoin/bitcoin#18722 is not partial due to prior backporting in https://github.com/dashpay/dash/pull/5681

2023-12-05 11:36 UTC, UdjinM6 commented
also, no commit is marked "partial" now so PR title shouldn't have "(Partial)" either

2023-12-06 04:22 UTC, vijaydasmp commented
> [ff5dcbe](https://github.com/dashpay/dash/commit/ff5dcbe4db128b328703eef52fce7fdce438d05f) is meaningless, should be dropped

dropped 18722

2023-12-06 18:46 UTC, UdjinM6 approved these changes
re-utACK

2023-12-06 18:50 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-12-08 16:44 UTC, UdjinM6 commented
ping @knst

2023-12-09 09:36 UTC, merged