backport: bitcoin#17509, #17579, #18451, #18504, #18581, #18645, #18646, #18667, #18673, #18682
dashpay/dash pull request #5539
Opened 2023-08-18 05:22 UTC by knst

## Issue being fixed or feature implemented
Various backports from v21

## What was done?

- bitcoin/bitcoin#18504
- bitcoin/bitcoin#18673
- bitcoin/bitcoin#18581
- bitcoin/bitcoin#18646
- bitcoin/bitcoin#18451
- bitcoin/bitcoin#18645
- bitcoin/bitcoin#18667
- bitcoin/bitcoin#18682
- bitcoin/bitcoin#17509
- bitcoin/bitcoin#17579

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2023-08-18 22:19 UTC, UdjinM6 requested changes

2023-08-18 22:19 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> -    bool fAddLocked = (!request.params[2].isNull() && request.params[2].get_bool());
17579: missing `fAddLocked` and its usage in `GetReceived`

2023-08-18 22:19 UTC, UdjinM6 commented on src/qt/sendcoinsdialog.cpp
> -{
17509: this should be changed to 
```
        return send(recipients);
    }
    // already unlocked or not encrypted at all
    return send(recipients);
}

bool SendCoinsDialog::send(QList<SendCoinsRecipient> recipients)
{
```
, not dropped. `UnlockContext` is important.

2023-08-18 22:19 UTC, UdjinM6 commented on src/qt/sendcoinsdialog.h
> -    void send(QList<SendCoinsRecipient> recipients);
17509: should be 
```
    bool send(QList<SendCoinsRecipient> recipients);
```

2023-08-21 16:03 UTC, UdjinM6 submitted a review, later dismissed
utACK

2023-08-24 10:20 UTC, knst commented
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/b36f59243ac8072976947a1e87a94a6e07b9795e..fc2a86bee80e45bca9593e9cc0024ff47565d9b9) the bp-v21-p1 branch from[ b36f592 ](https://github.com/dashpay/dash/commit/b36f59243ac8072976947a1e87a94a6e07b9795e)to fc2a86b

rebased on top of develop

2023-08-24 12:11 UTC, UdjinM6 approved these changes
utACK

2023-08-30 02:59 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-08-30 03:03 UTC, merged