docs: Added release notes for #5262
dashpay/dash pull request #5558
Opened 2023-08-31 14:03 UTC by ogabrielides

## Issue being fixed or feature implemented

## What was done?
Added release notes for #5262.

## How Has This Been Tested?

## Breaking Changes

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-08-31 14:16 UTC, PastaPastaPasta commented on doc/release-notes-5262.md
> +Note: Until the first bestCLSignature included in Coinbase once v20 activates, null bestCLSignature and bestCLHeightDiff are perfectly valid.
```suggestion
Note: Until the first bestCLSignature included in Coinbase once v20 activates, null bestCLSignature and bestCLHeightDiff are perfectly valid.

```

2023-08-31 15:00 UTC, thephez requested changes

2023-08-31 15:00 UTC, thephez commented on doc/release-notes-5262.md
> +Although miners are forced to include version 3 Coinbase, actual real-time best Chainlock signature isn't required: as long as blocks will contain at least equal (or newer) bestCLSignature than the p
```suggestion
Although miners are forced to include a version 3 Coinbase, the actual real-time best Chainlock signature isn't required as long as blocks contain a bestCLSignature equal to (or newer than) the previous block.
```

2023-08-31 15:00 UTC, thephez commented on doc/release-notes-5262.md
> +Note: Until the first bestCLSignature included in Coinbase once v20 activates, null bestCLSignature and bestCLHeightDiff are perfectly valid.
```suggestion
Note: Until the first bestCLSignature is included in a Coinbase once v20 activates, null bestCLSignature and bestCLHeightDiff values are perfectly valid.
```

2023-08-31 15:18 UTC, thephez approved these changes

2023-08-31 17:06 UTC, ogabrielides commented on doc/release-notes-5262.md
> +Note: Until the first bestCLSignature is included in a Coinbase once v20 activates, null bestCLSignature and bestCLHeightDiff values are perfectly valid.
Good point. Will open a PR for that.

2023-08-31 17:19 UTC, UdjinM6 approved these changes
LGTM

2023-08-31 17:46 UTC, thephez approved these changes

2023-09-05 02:39 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-09-05 02:39 UTC, merged