docs: add release notes for 5342
dashpay/dash pull request #5568
Opened 2023-09-06 08:52 UTC by knst

## Issue being fixed or feature implemented
docs: add release notes for 5342

## How Has This Been Tested?
N/A

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2023-09-06 08:59 UTC, ogabrielides requested changes

2023-09-06 08:59 UTC, ogabrielides commented on doc/release-notes-5342.md
> +Once mn_rr activates some funds in coinbase would be moved into the Asset lock Pool (on platform)
```suggestion
Once `mn_rr` activates some funds in coinbase would be moved into the Asset lock Pool (on platform)
```

2023-09-06 08:59 UTC, ogabrielides commented on doc/release-notes-5342.md
> +Beside that, evo MN will receive reward only once - not quad reward (4 time continously) as in v19/v20.
```suggestion
Beside that, Evo nodes will receive reward only once - not quad reward (4 time continuously) as in v19/v20.
```

2023-09-06 08:59 UTC, ogabrielides commented on doc/release-notes-5342.md
> +This is to incentivize MNs to upgrade to platform, because only MNs running platform will get these migrated rewards
```suggestion
This is to incentivize Evo nodes to upgrade to platform, because only nodes running platform will get these migrated rewards
```

2023-09-06 09:57 UTC, ogabrielides submitted a review, later dismissed
ACK

2023-09-06 13:33 UTC, thephez reviewed
Some rewording and revising to consider

2023-09-07 08:05 UTC, ogabrielides approved these changes
ACK

2023-09-07 09:49 UTC, UdjinM6 approved these changes
LGTM

2023-09-07 12:33 UTC, thephez approved these changes

2023-09-07 20:11 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-09-08 08:16 UTC, UdjinM6 approved these changes
utACK

2023-09-09 17:26 UTC, merged