backport: merge bitcoin#19326, #20464, #23451, #20852, #20355, #22050, #23115, #23409, #18468, #23413, partial bitcoin#21560, #23438 (auxiliary backports: part 11)
dashpay/dash pull request #5574
Opened 2023-09-09 09:35 UTC by kwvg

2023-09-19 19:31 UTC, UdjinM6 commented on src/test/net_tests.cpp
> -    // TORv2
22050: missing
```
    // TORv2, no longer supported
    BOOST_CHECK(!addr.SetSpecial("6hzph5hv6337r6p2.onion"));
```

2023-09-19 19:31 UTC, UdjinM6 commented on doc/files.md
> +`banlist.dat`  | Stores the addresses/subnets of banned nodes; superseded by `banlist.json` in 22.0 and completely ignored in 23.0 | [PR #20966](https://github.com/bitcoin/bitcoin/pull/20966), [PR #2
22570: should be dashified

2023-09-19 19:31 UTC, UdjinM6 commented on src/addrdb.cpp
> +        LogPrintf("banlist.dat ignored because it can only be read by " PACKAGE_NAME " version 22.x. Remove %s to silence this warning.\n", m_banlist_dat);
22570: should be dashified

2023-09-20 12:45 UTC, kwvg commented on src/test/net_tests.cpp
> -    // TORv2
Resolved in latest push.

2023-09-20 12:45 UTC, kwvg commented on doc/files.md
> +`banlist.dat`  | Stores the addresses/subnets of banned nodes; superseded by `banlist.json` in 22.0 and completely ignored in 23.0 | [PR #20966](https://github.com/bitcoin/bitcoin/pull/20966), [PR #2
Resolved in latest push.

2023-09-20 12:45 UTC, kwvg commented on src/addrdb.cpp
> +        LogPrintf("banlist.dat ignored because it can only be read by " PACKAGE_NAME " version 22.x. Remove %s to silence this warning.\n", m_banlist_dat);
Resolved in latest push.

2023-09-20 12:46 UTC, kwvg commented on src/hash.h
> +inline uint256 Hash(const T1& in1, const T2& in2) {
Functions are unused and have been removed. Resolved in latest push.

2023-09-21 11:20 UTC, knst requested changes
as discussed in slack, please, use Span class here instead std::vector for scriptPubKey's + Hash160

Here's possible implementation: https://github.com/knst/dash/commit/a534b5f9edef94d63bbc67071787419edc8c263a

2023-09-21 15:54 UTC, PastaPastaPasta commented
> as discussed in slack, please, use Span class here instead std::vector for scriptPubKey's + Hash160
> 
> Here's possible implementation: [knst@a534b5f](https://github.com/knst/dash/commit/a534b5f9edef94d63bbc67071787419edc8c263a)

This isn't needed? The purpose of using span is you can implicitly construct one from basically anything; seems fine to me to keep it as is

2023-09-21 17:18 UTC, knst commented
> This isn't needed? The purpose of using span is you can implicitly construct one from basically anything; seems fine to me to keep it as is

These 2 commits are extra context for you @PastaPastaPasta 
https://github.com/knst/dash/commit/5d91e7ecc4c1b00822ff90c2a8f99242d7d5f9df
https://github.com/knst/dash/commit/7d80ffbbb575160aca4323fd64836d05b3d06498

so, for this code will cause compilation error with new Span implementation (after all backports from this batch):
```cpp
uint160 hashBytes(Hash160(prevout.scriptPubKey.begin()+1, prevout.scriptPubKey.end()-1));
```
with new Span implementation compiler will throw an error

kwvg's solution:
```diff
-uint160 hashBytes(Hash160(prevout.scriptPubKey.begin()+1, prevout.scriptPubKey.end()-1));
+uint160 hashBytes(Hash160(std::vector<unsigned char>(prevout.scriptPubKey.begin()+1, prevout.scriptPubKey.end()-1)));
```
my patch:
```diff
-uint160 hashBytes(Hash160(prevout.scriptPubKey.begin()+1, prevout.scriptPubKey.end()-1));
+uint160 hashBytes{Hash160(Span{prevout.scriptPubKey.data()+1, prevout.scriptPubKey.size() - 2})};
```

my solution uses Span instead std::vector and it helps to avoid extra memory allocation, because Span do now copy data, do not own it, it is just container with pointer to data + its length (same as std::span and std::string_view), but std::vector<...> will cause memory allocation + memory copy + memory deallocation when its data no need more.

2023-09-22 14:08 UTC, PastaPastaPasta commented
@knst thanks for the context! I didn't see that current code was allocating a vector.

2023-09-22 14:15 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2023-09-22 14:35 UTC, UdjinM6 approved these changes
utACK

2023-09-22 15:04 UTC, knst approved these changes
LGTM

2023-09-24 14:51 UTC, merged