feat: auto generation EHF
dashpay/dash pull request #5597
Opened 2023-10-01 19:53 UTC by knst

to follow-up #5505
## Issue being fixed or feature implemented
 - _Why is this change required? What problem does it solve?_
 - _If it fixes an open issue, please link to the issue here._

## What was done?
  _Describe your changes in detail_

## How Has This Been Tested?
  _Please describe in detail how you tested your changes._

  _Include details of your testing environment, and the tests you ran
to see how your change affects other areas of the code, etc._

## Breaking Changes
  _Please describe any breaking changes your code introduces_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-10-09 20:58 UTC, UdjinM6 requested changes
pls see 2ccf9d1825

2023-10-09 21:08 UTC, knst commented
@UdjinM6 
A.
https://github.com/dashpay/dash/commit/2ccf9d1825b41d663701ce92c0a5b01a44eb6562#diff-4a04bc0b355c780033960e8c261ee9b6d3c452897e1dcd88a15d272512266c76R1133

> self.activate_mn_rr(expected_activation_height=node.getblockcount() + 12 * 3)

but it can take a time until recovered sigs are ready and tx with EHF signal is submitted more than one loop iteration:

```
       while mn_rr_status == 0:
            time.sleep(1)
            mn_rr_status = get_bip9_details(self.nodes[0], 'mn_rr')['ehf']
            self.nodes[0].generate(1)
```

So, if sig for EHF signal is delayed more than 1 second and 1 block -> it may be more that 12 * 3 blocks required to activate mn_rr, isn't it?


----
B.
consensus.vDeployments[Consensus::DEPLOYMENT_MN_RR].nWindowSize = 4032;
When v20 would be released it will take time until v20 would be activated (several weeks, 4-6?). After that after spork activation it would be required to wait 4-6 weeks more. Is it expected to wait 4-6 weeks more?

2023-10-10 10:07 UTC, UdjinM6 commented
> @UdjinM6 A. [2ccf9d1#diff-4a04bc0b355c780033960e8c261ee9b6d3c452897e1dcd88a15d272512266c76R1133](https://github.com/dashpay/dash/commit/2ccf9d1825b41d663701ce92c0a5b01a44eb6562#diff-4a04bc0b355c780033960e8c261ee9b6d3c452897e1dcd88a15d272512266c76R1133)
> 
> > self.activate_mn_rr(expected_activation_height=node.getblockcount() + 12 * 3)
> 
> but it can take a time until recovered sigs are ready and tx with EHF signal is submitted more than one loop iteration:
> 
> ```
>        while mn_rr_status == 0:
>             time.sleep(1)
>             mn_rr_status = get_bip9_details(self.nodes[0], 'mn_rr')['ehf']
>             self.nodes[0].generate(1)
> ```
> 
> So, if sig for EHF signal is delayed more than 1 second and 1 block -> it may be more that 12 * 3 blocks required to activate mn_rr, isn't it?

bip9 works in periods. Also, in this specific case we start activating at the beginning of the period (block 2796) and we have threshold which is lower than that so missing a couple of blocks is not a problem. But I agree that calculating it like that is probably misleading. We could simply go with a static number instead I guess i.e. `expected_activation_height=2832`.

> B. consensus.vDeployments[Consensus::DEPLOYMENT_MN_RR].nWindowSize = 4032; When v20 would be released it will take time until v20 would be activated (several weeks, 4-6?). After that after spork activation it would be required to wait 4-6 weeks more. Is it expected to wait 4-6 weeks more?

Good point 👍  Pls ignore this part of my suggestions then :)

2023-10-12 18:06 UTC, UdjinM6 approved these changes
lgtm, utACK

2023-10-12 18:07 UTC, UdjinM6 approved these changes
LGTM, utACK

2023-10-17 13:29 UTC, PastaPastaPasta commented on src/evo/mnhftx.h
> +     * helper function to calculare Request ID used for signing
```suggestion
     * helper function to calculate Request ID used for signing
```

2023-10-17 17:14 UTC, UdjinM6 approved these changes
re-utACK

2023-10-17 17:31 UTC, PastaPastaPasta commented on src/llmq/ehf_signals.h
> +    CMNHFManager& mnhfManager;
These can be const (and change constructor)
```suggestion
    const CSporkManager& sporkman;
    const CQuorumManager& qman;
    CTxMemPool& mempool;
    const CMNHFManager& mnhfManager;
```

2023-10-17 18:52 UTC, UdjinM6 submitted a review, later dismissed
LGTM, utACK

2023-10-17 20:42 UTC, PastaPastaPasta approved these changes
light-ACK for squash merge

2023-10-17 21:26 UTC, knst commented
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/b6b165fc43e6bafed3e48cb0c56fd40ab3dd253d..7e96c96a60c06ab0692a4a419cfd92015923e75f) the mnehf-manager branch from[ b6b165f ](https://github.com/dashpay/dash/commit/b6b165fc43e6bafed3e48cb0c56fd40ab3dd253d)to 7e96c96

due to
>This pull request has conflicts, please rebase.

2023-10-17 21:54 UTC, UdjinM6 commented on test/functional/feature_asset_locks.py
> +        assert_equal(platform_reward, 29636590)
somehow this test is not 100% deterministic....
run 1
```
TestFramework (INFO): Wait for mn_rr activation
TestFramework (INFO): height: 2855 credit: 897274252983
```
run 2
```
TestFramework (INFO): Wait for mn_rr activation
TestFramework (INFO): height: 2831 credit: 895835213008
```
and it affects `platform_reward` too so maybe we could rely on formulas only here?
```suggestion
```

2023-10-17 22:19 UTC, UdjinM6 commented on test/functional/feature_asset_locks.py
> +        assert_equal(platform_reward, 29636590)
ok, so it happened only once for me and I can no longer reproduce it... nvm then

2023-10-17 22:20 UTC, UdjinM6 approved these changes
utACK

2023-10-18 03:31 UTC, PastaPastaPasta approved these changes
re-utACK

2023-10-18 03:31 UTC, merged