test: correct calculation of `coinbasevalue` in feature_asset_locks.py
dashpay/dash pull request #5603
Opened 2023-10-06 10:05 UTC by ogabrielides

## Issue being fixed or feature implemented
Fixed a problem forgotten in #5588 in feature_asset_locks.py.

## What was done?
Avoid floating operations when calculating `coinbasevalue`

## How Has This Been Tested?

## Breaking Changes

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-10-06 10:52 UTC, UdjinM6 requested changes
good catch 👍 let's maybe make 100% identical

2023-10-06 10:52 UTC, UdjinM6 commented on test/functional/feature_asset_locks.py
> +        assert_equal(all_mn_rewards, int(bt['coinbasevalue'] * 0.75))  # 75/25 mn/miner reward split
```suggestion
        assert_equal(all_mn_rewards, int(bt['coinbasevalue'] * 3 // 4))  # 75/25 mn/miner reward split
```

2023-10-06 12:41 UTC, UdjinM6 approved these changes
utACK

2023-10-06 16:05 UTC, knst submitted a review, later dismissed
utACK

Thanks for figuring this issue out

2023-10-07 10:00 UTC, ogabrielides commented on test/functional/feature_asset_locks.py
> +        assert_equal(all_mn_rewards, int(bt['coinbasevalue'] * 3 // 4))  # 75/25 mn/miner reward split
Applied suggestions in order to be aligned with #5604

2023-10-07 11:12 UTC, knst approved these changes
utACK

2023-10-07 18:26 UTC, UdjinM6 submitted a review, later dismissed
re-utACK

2023-10-11 13:13 UTC, merged