feat!: fixed subsidy base for blocks in v20
dashpay/dash pull request #5611
Opened 2023-10-12 19:47 UTC by ogabrielides

## Issue being fixed or feature implemented
Currently, the `nSubsidyBase` calculation relies on difficulty. This leads to variable of Block Subsidity.
When Platform will be live, it would constantly require blocks difficulty in order to calculate the `platformReward` (which relies on Block Subsidy)

cc @QuantumExplorer 

## What was done?
Starting from v20 activation,  `nSubsidyBase` will no longer rely on difficulty and will be fixed to 5.

## How Has This Been Tested?

## Breaking Changes
Block rewards will differ.

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-10-12 22:44 UTC, UdjinM6 requested changes
1. pls see below
2. you missed one in `src/governance/classes.cpp` - it's getting harder to track/understand `GetBlockSubsidyInner` calls, we should probably stop relying on default values and also start adding inline comments for params

pls see 63ef4935b5

2023-10-13 17:50 UTC, UdjinM6 submitted a review, later dismissed
utACK

2023-10-16 09:27 UTC, UdjinM6 commented on src/validation.cpp
> +        // Starting from V20 Activation, subsidybase should be stable.
linking here for visibility https://github.com/dashpay/dash/commit/63ef4935b5d09e83152cb29dc935ad568fdb4600#r130063059

2023-10-16 14:23 UTC, PastaPastaPasta commented
I don't really want to merge these until we are ready to reorganize testnet... develop should be able to sync testnet

2023-10-16 16:47 UTC, UdjinM6 approved these changes
ACK

2023-10-17 17:30 UTC, PastaPastaPasta approved these changes
utACK for squash merge; nit: I'd argue title should be something like `static` or `constant` instead of `fixed` as that implies something was broken :)

2023-10-17 17:30 UTC, PastaPastaPasta requested changes
NVM; CI fails

2023-10-17 17:32 UTC, UdjinM6 commented
yeah, rebase is messed up a bit...

2023-10-17 18:32 UTC, ogabrielides commented
> yeah, rebase is messed up a bit...

Sorry about that guys

2023-10-17 19:39 UTC, UdjinM6 approved these changes
ACK (syncs on testnet)

2023-10-17 20:50 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-10-17 20:50 UTC, merged