feat! exclude fees when calculating `platformReward`
dashpay/dash pull request #5612
Opened 2023-10-13 13:29 UTC by ogabrielides

## Issue being fixed or feature implemented
Calculation of `platformReward` should ignore fees and rely only on Block subsidy.

cc @QuantumExplorer 

## What was done?
From now on, the following formula is applied:
```
blockReward = blockSubsidy + feeReward
masternodeReward = masternodeShare(blockSubsidy)
platformReward = platformShare(masternodeReward)
masternodeReward += masternodeShare(feeReward)
```

## How Has This Been Tested?

## Breaking Changes
plaftormReward is changed in networks where `mn_rr` is already active

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-10-15 15:25 UTC, UdjinM6 requested changes
pls see ec6590051167ea7f2d20f886f04d3bec950876b0

2023-10-15 18:35 UTC, UdjinM6 commented
should be good to merge after #5611 (and rebase) imo

2023-10-15 19:26 UTC, ogabrielides commented
Successfully reindex Mainnet and Testnet (until `mn_rr` activation)

2023-10-16 14:54 UTC, UdjinM6 commented
you should actually be able to sync on testnet with these changes https://github.com/dashpay/dash/pull/5612/files#diff-fe65493b850e303fea3e506b54fee5bfd4d9238ead17f4cf26afd47ac88447beR37-R40

2023-10-16 16:50 UTC, UdjinM6 commented
works on testnet now, should be ok to merge after #5611

2023-10-17 19:51 UTC, ogabrielides commented
@UdjinM6 @PastaPastaPasta Rebased and resynced Testnet successfully

2023-10-17 21:48 UTC, UdjinM6 requested changes

2023-10-17 21:48 UTC, UdjinM6 commented on src/masternode/payments.cpp
> +    masternodeReward += masternodeFeeReward;
```suggestion
```

2023-10-17 21:48 UTC, UdjinM6 commented on src/test/block_reward_reallocation_tests.cpp
> -
pls revert this

2023-10-17 23:37 UTC, UdjinM6 approved these changes
ACK (reindexed on testnet)

2023-10-18 03:07 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-10-18 03:07 UTC, merged