test: ensure that mining is possible without CL info
dashpay/dash pull request #5689
Opened 2023-11-09 15:20 UTC by ogabrielides

## Issue being fixed or feature implemented
With DIP29 added to v20, miners include best CL Signature in CbTx.
The purpose of this test, is to ensure that mining is still possible when CL information isn't available.
In such case, miners are expected to copy best CL Signature from CbTx of previous block.

## What was done?
Two scenarios are implemented:

- Add dynamically a node, make sure `getbestchainlock()` fails, let it mine a block.
- Disable `SPORK_19_CHAINLOCKS_ENABLED`, add dynamically a node, make sure `getbestchainlock()` fails, let it mine a block.

In both tests, we make sure the block is accepted by everyone and that the `bestCLSignature` in CbTx is copied from previous block.

## How Has This Been Tested?
`feature_llmq_chainlocks.py`

## Breaking Changes
no

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-11-09 16:05 UTC, knst commented on test/functional/feature_llmq_chainlocks.py
> +            self.log.info("getbestchainlock() failed on the new node as expected")
can `assert_raises_rpc_error` be used here?
Such as 
```suggestion
assert_raises_rpc_error(-32603, "Unable to find any chainlock", self.nodes[added_mn_info_1.idx].getbestchainlock)
````

same for try-except above.
+need to add import `assert_raises_rpc_error`

2023-11-09 18:15 UTC, UdjinM6 requested changes
That's a lot of duplication and you don't need `idx` in `MasternodeInfo` really. Pls see 0d0a9c64e7.

2023-11-09 18:52 UTC, UdjinM6 approved these changes
utACK

2023-11-09 22:51 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-11-10 08:38 UTC, knst approved these changes
LGTM

2023-11-10 14:32 UTC, merged