doc: update release process document to follow-up v20 release
dashpay/dash pull request #5710
Opened 2023-11-16 10:46 UTC by knst

## Issue being fixed or feature implemented
Our [Release Process document](doc/release-process.md) is not exactly matched with our [template issue](https://github.com/dashpay/dash/issues/5694) that created by copy-paste from previous release.

For the next release just copy test from this document to new issue

## What was done?
[Release Process document](doc/release-process.md) is updated to match with our real release process.
This document has also detailed instructions for many steps (in compare to the issue that we use now which is more checklist) to make releasing process easier for all participant. 

## How Has This Been Tested?
Tested on air by 2 last released: v19, v20: https://github.com/dashpay/dash/issues/5694

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2023-11-16 10:54 UTC, knst commented
Link to preview how this MD file is rendered by GitHub: https://github.com/dashpay/dash/blob/ed9d86e9805e93a05fe6b81a2acb764e34b9ffb5/doc/release-process.md

2023-11-16 15:05 UTC, PastaPastaPasta commented on doc/release-process.md
> +* [ ] Ensure that governance is functional after sentinel changes are done
this is not needed moving forward
```suggestion
```

2023-11-16 15:06 UTC, PastaPastaPasta commented on doc/release-process.md
> +* [ ] knst
same

2023-11-20 14:51 UTC, thephez requested changes
Some suggested updates and corrections...

2023-11-20 14:58 UTC, knst commented on doc/release-process.md
> +* [ ] Update [dips.md](https://github.com/dashpay/dips/) to account for changes since the last release.
```suggestion
* [ ] Update DIPs with any changes introduced by this release (see [this pull request](https://github.com/dashpay/dips/pull/142) for an example)
```

2023-11-20 14:58 UTC, knst commented on doc/release-process.md
> +* [ ] Notarize OS X binaries (we can't do this) (talk to @tikhop (pavel) about this
indeed, copy-paste error; I edited this line locally already, thanks for catch!

2023-11-20 15:08 UTC, thephez approved these changes
Looks good. Thanks for updating this :+1:

2023-11-21 11:54 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commit/1038c1a1f9a77815b0314787e2b79c4f3fab48db for some suggestions

2023-11-22 02:24 UTC, UdjinM6 approved these changes
utACK

2023-11-26 21:13 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-11-29 14:27 UTC, merged