backport: bitcoin#24276, #24383, #28561, #24461
dashpay/dash pull request #5758
Opened 2023-12-06 19:11 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Backport

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-12-06 19:13 UTC, knst commented on doc/dependencies.md
> +| Boost | [1.77.0](https://www.boost.org/users/download/) | [1.64.0](https://github.com/bitcoin/bitcoin/pull/22320) | No |  |  |
```suggestion
| Boost | [1.77.0](https://www.boost.org/users/download/) | [1.77.0](https://github.com/bitcoin/bitcoin/pull/24383) | No |  |  |
```

2023-12-06 19:15 UTC, PastaPastaPasta commented on doc/dependencies.md
> +| Boost | [1.77.0](https://www.boost.org/users/download/) | [1.64.0](https://github.com/bitcoin/bitcoin/pull/22320) | No |  |  |
can you clarify what you mean?

2023-12-06 20:39 UTC, UdjinM6 requested changes

2023-12-06 20:39 UTC, UdjinM6 commented on depends/packages/boost.mk
> +$(package)_version=1.77.0
package version format changes should be done via 24276 backport and not squashed silently into 24383

2023-12-07 10:39 UTC, UdjinM6 requested changes
mac build is broken, probably because of 28337

it's also weird that no all GH checks are running here

2023-12-07 15:02 UTC, UdjinM6 commented
28561 missing changes in `doc/dependencies.md`

2023-12-08 11:03 UTC, knst approved these changes
utACK

Should #5671 be closed as a duplicate ?

2023-12-08 12:53 UTC, UdjinM6 approved these changes
utACK

2023-12-08 16:39 UTC, merged