feat(rpc): add chainlock signature if needed RPC.
dashpay/dash pull request #5765
Opened 2023-12-13 23:32 UTC by ogabrielides

## Issue being fixed or feature implemented
Once Platform is live, there could be an edge case where the CL could arrive to an EvoNode faster through Platform quorum than regular P2P propagation.

## What was done?
This PR introduces a new RPC `addchainlock` with the following 3 mandatory parameters:
- `blockHash`, `signature` and `height`.

Besides some basic tests:
- If the block is unknown then the RPC returns an error (could happen if the node is stucked)
- If the signature is not verified then the RPC return an error.
- If the node already has this CL, the RPC returns true.
- If the node doesn't have this CL, it inserts it, broadcast it through the inv system and return true.

## How Has This Been Tested?
`feature_llmq_chainlocks.py` was modified with the following senario:

1. node0 is isolated from the rest of the network
2. node1 mine a new block and waits for CL
3. node0 is re-connected
4. node0 gets the new block but without having the best CL (by checking `getbestchainlock()`)
5. CL is inserted via the new RPC
6. checking `getbestchainlock()` and make sure the CL was processed.

## Breaking Changes
no

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-12-14 00:30 UTC, PastaPastaPasta commented
`submitchainlock` would make this more in line with other RPCs such as `submitblock` or `submitrawtransaction`

2023-12-14 13:49 UTC, UdjinM6 requested changes
>there could be an edge case where the CL could arrive to an EvoNode faster through Platform quorum than regular P2P propagation.

But why is this an issue exactly? Why do we want to submit chainlock ourselves instead of maybe verifying it via `verifychainlock` and allowing the node to receive it the usual way?

Also, that's a lot of code duplication with `verifychainlock` but for some reason behaviour differs in some parts. Why is that?

2023-12-14 13:49 UTC, UdjinM6 commented on src/rpc/quorums.cpp
> +                       {"blockHeight", RPCArg::Type::NUM, RPCArg::Optional::NO, "The height of the ChainLock.."},
```suggestion
                       {"blockHeight", RPCArg::Type::NUM, RPCArg::Optional::NO, "The height of the ChainLock."},
```

Also, why is it not an optional one like in `verifychainlock`?

2023-12-14 13:49 UTC, UdjinM6 commented on src/rpc/quorums.cpp
> +                       {"signature", RPCArg::Type::STR, RPCArg::Optional::NO, "The signature of the ChainLock."},
```suggestion
                       {"signature", RPCArg::Type::STR_HEX, RPCArg::Optional::NO, "The signature of the ChainLock."},
```

2023-12-14 13:49 UTC, UdjinM6 commented on src/rpc/quorums.cpp
> +            throw JSONRPCError(RPC_INVALID_PARAMETER, "invalid blockhash");
```suggestion
            throw JSONRPCError(RPC_INVALID_PARAMETER, "invalid block hash or block height");
```

2023-12-14 13:49 UTC, UdjinM6 commented on src/rpc/quorums.cpp
> +    }
the logic above differs from the one in `verifychainlock` so `pIndex` can't be `nullptr` here

```suggestion
    CHECK_NONFATAL(pIndex != nullptr);

    if (!sig.SetHexStr(request.params[1].get_str(), !llmq::utils::IsV19Active(pIndex))) {
        throw JSONRPCError(RPC_INVALID_PARAMETER, "invalid signature format");
    }
```

2023-12-14 13:49 UTC, UdjinM6 commented on src/rpc/quorums.cpp
> +        }
We usually relay "future" chainlocks (check `ProcessNewChainLock`). Why is it not the case here?

2023-12-14 17:41 UTC, ogabrielides commented
@UdjinM6 
> > there could be an edge case where the CL could arrive to an EvoNode faster through Platform quorum than regular P2P propagation.
> 
> But why is this an issue exactly? Why do we want to submit chainlock ourselves instead of maybe verifying it via `verifychainlock` and allowing the node to receive it the usual way?
> 
> Also, that's a lot of code duplication with `verifychainlock` but for some reason behaviour differs in some parts. Why is that?

I will try to answer to all of your comments here.

> But why is this an issue exactly? Why do we want to submit chainlock ourselves instead of maybe verifying it via verifychainlock and allowing the node to receive it the usual way?

Regarding Core only, this is indeed not an issue. But if we see Core+Platform as a system, this is a race condition for Chainlock signature. This PR will help Platform avoid waiting for Core to get the CL from regular propagation.

> We usually relay "future" chainlocks (check ProcessNewChainLock). Why is it not the case here?

Didn't know that. All right, will change it. That means that height can be optional yes.

2023-12-14 21:06 UTC, ogabrielides commented
@UdjinM6 Applied @PastaPastaPasta 's suggestions. 
It still feels weird to have optional height and accept CL for "future" blocks.

2023-12-15 20:05 UTC, UdjinM6 requested changes

2023-12-15 20:12 UTC, knst commented on test/functional/feature_llmq_chainlocks.py
> +        assert best_0['blockhash'] != best_1['blockhash']
nit: use `assert_equal` for better debug output

2023-12-16 16:57 UTC, UdjinM6 approved these changes
utACK

2023-12-16 17:55 UTC, UdjinM6 commented
Not sure what's going on but Gitlab CI just won't start here for some reason...

2023-12-16 19:35 UTC, UdjinM6 submitted a review, later dismissed
re-utACK

2023-12-16 21:23 UTC, ogabrielides commented
> re-utACK

Thanks for approving your changes 😃

2023-12-17 18:39 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-12-17 18:45 UTC, PastaPastaPasta requested changes
Sorry; needs release notes first; otherwise looks good

2023-12-17 19:03 UTC, knst approved these changes
LGTM

2023-12-18 09:48 UTC, knst submitted a review, later dismissed
LGTM

2023-12-18 13:30 UTC, thephez reviewed
Small typo fix in release notes

2023-12-18 13:30 UTC, thephez commented on doc/release-notes-5765.md
> +Note: This PRC is whitelisted for Platform RPC user.
```suggestion
- `submitchainlock` RPC allows the submission of a ChainLock signature.
Note: This RPC is whitelisted for the Platform RPC user.
```

2023-12-18 13:47 UTC, thephez approved these changes
:+1:

2023-12-18 15:43 UTC, UdjinM6 approved these changes
utACK

2023-12-19 04:26 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2023-12-19 04:27 UTC, merged

2024-01-08 08:10 UTC, QuantumExplorer commented
So we have ```If the block is unknown then the RPC returns an error (could happen if the node is stucked)
If the signature is not verified then the RPC return an error.```

Is it really an error if the block is unknown?, Shouldn't we just be returning false? From platform's perspective this is not an error, and while we do vote down the proposal, this is not an "error" pathway.

2024-01-08 08:27 UTC, knst commented
> Is it really an error if the block is unknown?, Shouldn't we just be returning false?

sounds reasonable.
So, if we don't have a block with `blockHash` known yet - we would return `false`, all other cases are not changed.

2024-01-08 10:23 UTC, QuantumExplorer commented
Yes @knst could you make that happen?

2024-01-08 12:25 UTC, knst commented on test/functional/feature_llmq_chainlocks.py
> +        self.sync_all()
@QuantumExplorer that works not as described in the PR description.
If block is unknown -> CL is still submitted and it succeeds we return `true`.

We do not return error if block is not know, we just quietly process it, verify, re-transmit to network and add to known chainlocks.
Nothing to change already. 

here's even tests for it.

2024-01-09 03:38 UTC, QuantumExplorer commented
@knst Part of the requirement is that it return true or false based on whether it had the block (so we didn't have to call another RPC), right now it can't ever return false.

2024-01-09 04:48 UTC, PastaPastaPasta commented
Talked to Sam; we want change the API in this way
First (if height <= bestchainlockheight return bestchainlockheight)
else submitchainlock then return bestchainlockheight

This provides two benefits; 1st is a short circuiting if we know the proposed chainlock could not overwrite the current one (due to lower height)
Second; returns the bestchainlockheight to platform