backport :
dashpay/dash pull request #5766
Opened 2023-12-14 01:11 UTC by vijaydasmp

***Please remove the italicized help prompts before submitting or merging***

_Provide a general summary of your changes in the Title above_

_Pull requests without a rationale and clear improvement may be closed
immediately._

_Please provide clear motivation for your patch and explain how it improves
Dash Core user experience or Dash Core developer experience
significantly:_

* _Any test improvements or new tests that improve coverage are always welcome._
* _All other changes should have accompanying unit tests (see `src/test/`) or
  functional tests (see `test/`). Contributors should note which tests cover
  modified code. If no tests exist for a region of modified code, new tests
  should accompany the change._
* _Bug fixes are most welcome when they come with steps to reproduce or an
  explanation of the potential issue as well as reasoning for the way the bug
  was fixed._
* _Features are welcome, but might be rejected due to design or scope issues.
  If a feature is based on a lot of dependencies, contributors should first
  consider building the system outside of Dash Core, if possible._

## Issue being fixed or feature implemented
 - _Why is this change required? What problem does it solve?_
 - _If it fixes an open issue, please link to the issue here._

## What was done?
  _Describe your changes in detail_

## How Has This Been Tested?
  _Please describe in detail how you tested your changes._

  _Include details of your testing environment, and the tests you ran
to see how your change affects other areas of the code, etc._

## Breaking Changes
  _Please describe any breaking changes your code introduces_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-01-21 11:18 UTC, vijaydasmp commented
will resume after https://github.com/dashpay/dash/pull/5833 merges

2024-02-06 17:06 UTC, UdjinM6 requested changes
LGTM but 21107 should be partial because we don't have 19509 yet

2024-02-07 13:52 UTC, UdjinM6 commented
pls see 7e47db12472a132905bd80aefa0ddff0deeaf546, 815aaecf5b411b47637451f31a942c37afea5f0b and b7fec6c0376969a4280591bcef7c339ffd4fedbc

2024-02-07 15:09 UTC, vijaydasmp commented
> pls see [7e47db1](https://github.com/dashpay/dash/commit/7e47db12472a132905bd80aefa0ddff0deeaf546), [815aaec](https://github.com/dashpay/dash/commit/815aaecf5b411b47637451f31a942c37afea5f0b) and [b7fec6c](https://github.com/dashpay/dash/commit/b7fec6c0376969a4280591bcef7c339ffd4fedbc)

Thanks @UdjinM6 , I will apply this changes

2024-02-07 16:16 UTC, UdjinM6 commented on src/net.cpp
> +    }
19509: linter complains
```suggestion
    }
```

2024-02-08 18:23 UTC, UdjinM6 approved these changes
utACK

2024-02-09 15:08 UTC, vijaydasmp commented
Hello @PastaPastaPasta , requesting review

2024-02-14 04:25 UTC, vijaydasmp commented
Hello @PastaPastaPasta , Please review

2024-02-14 16:34 UTC, merged