refactor: remove circular dependencies through net_processing (1/N)
dashpay/dash pull request #5782
Opened 2023-12-21 20:46 UTC by knst

## Issue being fixed or feature implemented
The architecture of bitcoin assumes that there's no any external class that processes network messages and knows anything about PeerManager from net_processing; no any external call for `PeerManager::Misbehaving` in bitcoin. All logic related to processing messages are located in net_processing.
Dash has many many extra types of network messages and many of them processed by external components such as llmq/signing or coinjoin/client. Current architecture creates multiple circular dependency.

## What was done?
This PR introduces several key changes:
 - **new helper `tl::expected`** that can be widely used in dash code and it has very similar implementation with `std::expected` and can be replaced to `std::expected` since C++23 is used by default. Please notice that this PR will superseed https://github.com/dashpay/dash/pull/5109
 - new helper `PeerMsgRet` that is defined as `tl::expected<void, MisbehavingError>` inside net_types. That let's external modules that process network messages to don't depend directly on net_processing.
 - removed dependency of many classes on net_processing thanks to new `PeerMsgRet` type: `coinjoin/client`, `coinjoin/server`, `evo/mnauth`, `governance/governance`, `llmq/blockprocessor`, `llmq/chainlocks`, `llmq/quorums`, `spork` 

## What else to do?
Some network messages are processed asynchronously in external components such as llmq/signing, llmq/instantsend, llmq/dkgsessionhandler. It doesn't let to refactor them easily, because they can't just simple return status of processing; status of processing would be available sometime later and there's need callback or otherway to pass result code without spreading PeerManager over codebase.

## How Has This Been Tested?
 - run unit functional tests
 - run a linter `test/lint/lint-circular-dependencies.sh`

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2023-12-22 05:01 UTC, PastaPastaPasta commented
Otherwise LGTM

2023-12-22 05:14 UTC, knst commented on src/net_types.h
> +    MisbehavingError(int score, std::string message = "") :
Most of places doesn't have a text message.
Also for case of text message it's little too verbose: need to write `tl::expected<MisbehavingError>(...)`

For other usages (not net_processing) I'd agree if error usually provides text description

2023-12-22 09:01 UTC, knst commented on src/net_types.h
> +        message{std::move(message)}
updated, please check

2024-01-06 03:21 UTC, PastaPastaPasta reviewed
utACK

2024-01-06 03:22 UTC, PastaPastaPasta approved these changes
utACK

2024-01-10 14:32 UTC, PastaPastaPasta submitted a review, later dismissed
re-utACK; please state preference for merge commit vs squash

2024-01-10 18:02 UTC, UdjinM6 requested changes

2024-01-10 18:56 UTC, knst commented
resolved conflicts and added expections for linter.

2024-01-10 19:08 UTC, UdjinM6 approved these changes
utACK

2024-01-10 21:12 UTC, merged