backport: v20.0.2 backports and release
dashpay/dash pull request #5785
Opened 2023-12-22 13:39 UTC by ogabrielides

## Issue being fixed or feature implemented
v20.0.3 backports and release

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-12-22 13:59 UTC, UdjinM6 commented
Looks good so far, waiting for #5784

2023-12-22 14:00 UTC, UdjinM6 commented on doc/release-notes.md
> +The momory usage during the old quorum data cleanup mechanism was reduced.
```suggestion
The memory usage during the old quorum data cleanup mechanism was reduced.
```

2023-12-22 14:00 UTC, UdjinM6 commented on doc/release-notes-5774.md
> +In `getspecialtxes` `instantlock` and `chainlock` fields were always `false`. They should show actual values now.
should add this to release notes and drop this file

2023-12-22 20:01 UTC, UdjinM6 requested changes

2023-12-22 20:01 UTC, UdjinM6 commented on doc/release-notes.md
> +In `getspecialtxes` `instantlock` and `chainlock` fields are now reflecting actual values now.
such text much `now`
```suggestion
In `getspecialtxes` `instantlock` and `chainlock` fields are reflecting actual values now.
```

2023-12-22 20:16 UTC, ogabrielides commented
So I guess we want to include #5784 as well?

2023-12-22 20:17 UTC, PastaPastaPasta commented
Yes; Looks like it

2023-12-24 12:49 UTC, UdjinM6 approved these changes
utACK

2023-12-24 18:11 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit; I pushed a no-diff rebase so that these commits were gpg signed.

2023-12-24 18:14 UTC, PastaPastaPasta commented
Guix Automation has began to build this PR tagged as v20.0.3-devpr5785.3192d8c9. A new comment will be made when the image is pushed.

2023-12-24 18:16 UTC, merged