backport: trivial 2023 12 25
dashpay/dash pull request #5788
Opened 2023-12-25 07:33 UTC by PastaPastaPasta

## Issue being fixed or feature implemented

## What was done?
Small batch of trivial backports

## How Has This Been Tested?
make -j8 check; functional tests; linters

## Breaking Changes

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2023-12-26 08:27 UTC, knst requested changes
please drop (or dashificate) https://github.com/bitcoin/bitcoin/pull/22822

Probably drop https://github.com/bitcoin/bitcoin/pull/22780 also (see comment)

2023-12-26 08:27 UTC, knst commented on src/protocol.h
> +    //! Always included in serialization.
that's follow-up changes for https://github.com/bitcoin/bitcoin/pull/20541 which is not backported yet.

2023-12-26 08:27 UTC, knst commented on doc/multisig-tutorial.md
> +./src/bitcoind -signet -daemon
```suggestion
./src/dashd -testnet -daemon
```

2023-12-26 08:27 UTC, knst commented on doc/multisig-tutorial.md
> +Before starting this tutorial, start the bitcoin node on the signet network.
```suggestion
Before starting this tutorial, start the bitcoin node on the testnet network.
```

2023-12-26 08:27 UTC, knst commented on doc/multisig-tutorial.md
> +This tutorial also uses the default WPKH derivation path to get the xpubs and does not conform to [BIP 45](https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki) or [BIP 87](https://github.c
`wpkh` is witness pkh.

Let's drop this backport https://github.com/bitcoin/bitcoin/pull/22822 so far as it requires non-trivial dashification?

2023-12-27 10:55 UTC, knst approved these changes
utACK

2023-12-27 18:35 UTC, UdjinM6 approved these changes
utACK

2023-12-27 22:49 UTC, merged