refactor: keep in llmq/utils quorum calculations only new module llmq/options
dashpay/dash pull request #5790
Opened 2023-12-28 08:32 UTC by knst

to get merge after https://github.com/dashpay/dash/pull/5782 (to avoid its conflicts)

## Issue being fixed or feature implemented
`llmq/utils` has simple util code that used all over code base and also have too heavy code for calculation quorums such as: `GetAllQuorumMembers`, `EnsureQuorumConnections` and other.

These helpers for calculation quorums are used only by evo/deterministicmns, evo/simplifiedmns and llmq/*  modules, but llmq/utils is included in many other modules for various trivial helpers.

## What was done?
Prior work:
 - https://github.com/dashpay/dash/pull/5753
 - #5486
 See also #4798

This PR remove all non-quorum calculation code from llmq/utils. Eventually it happens that easier to take everything out rather than move Quorum Calculation to new place atm:
 - new module llmq/options have a code related to various params, command line options, spork-related etc
 - llmq/utils is included in some files which do not use any llmq/utils code
 - helper `BuildCommitmentHash` goes to llmq/commitment
 - helper `BuildSignHash` goes to llmq/signing
 - helper `GetLLMQParam` inlined since it's trivial (it has not been trivial when introduced ages ago)
 - removed dependency of `IsQuorumEnabled` on CQuorumManager which means `quorumManager` deglobalization is done for 90%

## How Has This Been Tested?
 - Run unit functional tests
 - updated circular dependencies `test/lint/lint-circular-dependencies.sh`
 - check that llmq/utils is not included without needs to calculate Quorums Members
```
$ grep -r include src/ 2> /dev/null | grep -v .Po: | grep -vE 'llmq/utils.(h|cpp)': | grep llmq/utils  
src/evo/mnauth.cpp:#include <llmq/utils.h>
src/evo/deterministicmns.cpp:#include <llmq/utils.h>
src/llmq/quorums.cpp:#include <llmq/utils.h>
src/llmq/blockprocessor.cpp:#include <llmq/utils.h>
src/llmq/commitment.cpp:#include <llmq/utils.h>
src/llmq/debug.cpp:#include <llmq/utils.h>
src/llmq/dkgsessionhandler.cpp:#include <llmq/utils.h>
src/llmq/dkgsession.cpp:#include <llmq/utils.h>
src/llmq/dkgsessionmgr.cpp:#include <llmq/utils.h>
src/rpc/quorums.cpp:#include <llmq/utils.h>
```

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2023-12-29 16:59 UTC, UdjinM6 requested changes

2023-12-29 16:59 UTC, UdjinM6 commented on src/llmq/blockprocessor.cpp
> +        AddMineableCommitment(qc);
```suggestion
```

2023-12-29 16:59 UTC, UdjinM6 commented on src/llmq/blockprocessor.cpp
> +               // should not happen as it was verified before processing the block
unrelated, pls revert

2023-12-29 16:59 UTC, UdjinM6 commented on src/llmq/blockprocessor.cpp
> +           }
unrelated, pls revert

2023-12-29 16:59 UTC, UdjinM6 commented on src/llmq/utils.cpp
> +            return false;
can be simplified to `return !fDIP0024IsActive;`

2023-12-29 17:17 UTC, UdjinM6 approved these changes
utACK

2024-01-07 01:38 UTC, PastaPastaPasta commented
> to get merge after https://github.com/dashpay/dash/pull/5782 (due to its conflicts)

2024-01-10 22:28 UTC, UdjinM6 submitted a review, later dismissed
re-utACK

2024-01-11 17:34 UTC, knst commented
need guix image to test a theory with crash:
```
Thread 1 "dashd" received signal SIGSEGV, Segmentation fault.
....
#0  0x0000555555c45198 in llmq::CQuorumManager::ScanQuorums (this=this@entry=0x55555694a110, llmqType=Consensus::LLMQType::LLMQ_TEST_INSTANTSEND, 
    pindexStart=pindexStart@entry=0x555556d66880, nCountRequested=nCountRequested@entry=1) at llmq/quorums.cpp:495
#1  0x0000555555809089 in llmq::utils::IsQuorumTypeEnabledInternal (llmqType=<optimized out>, qman=..., pindexPrev=..., optDIP0024IsActive=..., optDIP0024IsActive@entry=..., 
    optHaveDIP0024Quorums=...) at llmq/utils.cpp:942
#2  0x00005555558091d6 in llmq::utils::IsQuorumTypeEnabled (llmqType=<optimized out>, qman=..., pindexPrev=...) at llmq/utils.cpp:923
#3  0x0000555555c45211 in llmq::CQuorumManager::ScanQuorums (this=this@entry=0x55555694a110, llmqType=Consensus::LLMQType::LLMQ_TEST_INSTANTSEND, 
    pindexStart=pindexStart@entry=0x555556d66880, nCountRequested=nCountRequested@entry=1) at llmq/quorums.cpp:496
#4  0x0000555555809089 in llmq::utils::IsQuorumTypeEnabledInternal (llmqType=<optimized out>, qman=..., pindexPrev=..., optDIP0024IsActive=..., optDIP0024IsActive@entry=..., 
    optHaveDIP0024Quorums=...) at llmq/utils.cpp:942
```

run as `dashd -regtest -llmqtestinstantsenddip0024=llmq_test_instantsend`

2024-01-11 18:34 UTC, PastaPastaPasta commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5790.98457039. A new comment will be made when the image is pushed.

2024-01-11 19:07 UTC, PastaPastaPasta commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5790.98457039. The image should be on dockerhub soon.

2024-01-12 18:44 UTC, knst commented
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/984570393bf9a94831d8b344e4214e19d0bf3641..45957d53bc311ae6fb2cf2aac7b0304c1cf6b299) the refactor-llmq_utils branch from[ 9845703 ](https://github.com/dashpay/dash/commit/984570393bf9a94831d8b344e4214e19d0bf3641)to 45957d5

rebase to top of develop + resolved conflicts

2024-01-14 21:01 UTC, UdjinM6 approved these changes
re-utACK

2024-01-18 01:56 UTC, PastaPastaPasta approved these changes
utACK for squash merge

2024-01-18 01:56 UTC, merged