feat: rpc submitchainlock short circuit if possible and always return…
dashpay/dash pull request #5806
Opened 2024-01-09 04:54 UTC by PastaPastaPasta

… best height

***Please remove the italicized help prompts before submitting or merging***

_Provide a general summary of your changes in the Title above_

_Pull requests without a rationale and clear improvement may be closed
immediately._

_Please provide clear motivation for your patch and explain how it improves
Dash Core user experience or Dash Core developer experience
significantly:_

* _Any test improvements or new tests that improve coverage are always welcome._
* _All other changes should have accompanying unit tests (see `src/test/`) or
  functional tests (see `test/`). Contributors should note which tests cover
  modified code. If no tests exist for a region of modified code, new tests
  should accompany the change._
* _Bug fixes are most welcome when they come with steps to reproduce or an
  explanation of the potential issue as well as reasoning for the way the bug
  was fixed._
* _Features are welcome, but might be rejected due to design or scope issues.
  If a feature is based on a lot of dependencies, contributors should first
  consider building the system outside of Dash Core, if possible._

## Issue being fixed or feature implemented
 - _Why is this change required? What problem does it solve?_
 - _If it fixes an open issue, please link to the issue here._

## What was done?
  _Describe your changes in detail_

## How Has This Been Tested?
  _Please describe in detail how you tested your changes._

  _Include details of your testing environment, and the tests you ran
to see how your change affects other areas of the code, etc._

## Breaking Changes
  _Please describe any breaking changes your code introduces_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-01-09 04:58 UTC, PastaPastaPasta commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5806.e47dba93. A new comment will be made when the image is pushed.

2024-01-09 05:04 UTC, PastaPastaPasta commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5806.e47dba93. The image should be on dockerhub soon.

2024-01-09 13:38 UTC, PastaPastaPasta commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5806.aed3245f. A new comment will be made when the image is pushed.

2024-01-09 13:40 UTC, knst commented on src/rpc/quorums.cpp
> +    if (nBlockHeight <= bestCLHeight) return bestCLHeight;
IMO better to return blockHash or a pair of blockHash + blockHeight

@QuantumExplorer why do you want just a height?

2024-01-09 14:00 UTC, PastaPastaPasta commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5806.aed3245f. The image should be on dockerhub soon.

2024-01-09 14:00 UTC, PastaPastaPasta commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5806.ea58ac61. A new comment will be made when the image is pushed.

2024-01-09 14:23 UTC, PastaPastaPasta commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5806.2292f734. A new comment will be made when the image is pushed.

2024-01-09 14:43 UTC, knst submitted a review, later dismissed
LGTM <s>assuming that returning `nHeight` is okay</s>

2024-01-09 14:45 UTC, PastaPastaPasta commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5806.2292f734. The image should be on dockerhub soon.

2024-01-22 11:57 UTC, UdjinM6 requested changes
why is this still a draft? also pls see 1988e84dcd for some suggestions

2024-01-22 12:45 UTC, knst commented
Let's test both ways in functional test - when there's known CL with bigger height and not: https://github.com/knst/dash/commit/e26103385f57767e337b1ec4d9731c7c8f01d613

2024-01-23 01:36 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5806.a1814ce2. A new comment will be made when the image is pushed.

2024-01-23 01:57 UTC, DashCoreAutoGuix commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5806.a1814ce2. The image should be on dockerhub soon.

2024-01-23 16:46 UTC, UdjinM6 submitted a review, later dismissed
utACK

2024-02-01 15:32 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5806.c788e998. A new comment will be made when the image is pushed.

2024-02-01 16:03 UTC, UdjinM6 approved these changes
re-utACK

2024-02-01 16:14 UTC, merged