backport: bitcoin#17938, #19083, #19177, #19233, #19260, #19276, #19282, #19403, bitcoin-core/gui#3, #6
dashpay/dash pull request #5808
Opened 2024-01-09 19:29 UTC by knst

## Issue being fixed or feature implemented
Just regular bitcoin backports, mostly from v21

## What was done?
 - bitcoin/bitcoin#19233
 - bitcoin/bitcoin#19083
 - bitcoin/bitcoin#19177
 - bitcoin/bitcoin#19282
 - bitcoin/bitcoin#19276
 - bitcoin/bitcoin#19260
 - bitcoin-core/gui#3
 - bitcoin/bitcoin#17938
 - bitcoin-core/gui#6
 - bitcoin/bitcoin#19403
 
## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
N/A

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-01-10 03:26 UTC, PastaPastaPasta requested changes
LGTM; but tests fail. Please fix :)

2024-01-10 19:27 UTC, PastaPastaPasta submitted a review, later dismissed
force pushes seem like correct diffs to fix issues

utACK for merge via merge commit

2024-01-10 19:39 UTC, knst commented
force push to fix test: https://github.com/dashpay/dash/compare/c7372a970caa4aceb225831bcacf8e2891ed01b0..c4f9250f75b19ac38a512d78af207811397e8031
(and make one of backport partial, 2nd force-push is trivial)

2024-01-14 21:02 UTC, UdjinM6 requested changes

2024-01-15 14:23 UTC, knst commented on test/functional/p2p_filter.py
> -            filter_node.send_and_ping(msg_filteradd(data=b'\xcc'*(MAX_SCRIPT_ELEMENT_SIZE+1)))
these lines supposed to be dropped due to merge mistake during https://github.com/bitcoin/bitcoin/pull/18726/files these tests have been twice:
 - first when test_size_limit() is called https://github.com/dashpay/dash/pull/5808/commits/9a984f8a927f35a1813fba5e788fa67a83ec1167#diff-c5c320cd909288d7cf2d82632c6bafcb9085413bfddf5edf361f288dbd76e0cbL98
 - second time is right here (removed lines)

2024-01-15 22:15 UTC, PastaPastaPasta approved these changes
re-utACK

2024-01-16 09:13 UTC, UdjinM6 requested changes

2024-01-16 14:32 UTC, knst commented on test/functional/p2p_filter.py
> +        # filter_peer.wait_for_tx(txid)
but with your patch other test fails:

```
5/6 - p2p_nobloomfilter_messages.py failed, Duration: 69 s

stdout:
2024-01-16T13:21:42.140000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_∋_🏃_20240116_202140/p2p_nobloomfilter_messages_3
2024-01-16T13:21:42.652000Z TestFramework (INFO): Test that peer is disconnected if it sends mempool message
2024-01-16T13:21:44.654000Z TestFramework (INFO): Test that peer is disconnected if it sends filterload message
2024-01-16T13:21:46.657000Z TestFramework (INFO): Test that peer is disconnected if it sends filteradd message
2024-01-16T13:21:48.660000Z TestFramework (INFO): Test that peer is disconnected if it sends a filterclear message
2024-01-16T13:22:49.686000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''
        test_function = lambda: not self.is_connected
'''
2024-01-16T13:22:49.687000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/knst/projects/dash/test/functional/test_framework/test_framework.py", line 155, in main
    self.run_test()
  File "/home/knst/projects/dash/test/functional/p2p_nobloomfilter_messages.py", line 44, in run_test
    self.test_message_causes_disconnect(msg_filterclear())
  File "/home/knst/projects/dash/test/functional/p2p_nobloomfilter_messages.py", line 30, in test_message_causes_disconnect
    peer.wait_for_disconnect()
  File "/home/knst/projects/dash/test/functional/test_framework/mininode.py", line 454, in wait_for_disconnect
    self.wait_until(test_function, timeout=timeout)
  File "/home/knst/projects/dash/test/functional/test_framework/mininode.py", line 450, in wait_until
    wait_until(test_function, timeout=timeout, lock=mininode_lock, timeout_factor=self.timeout_factor)
  File "/home/knst/projects/dash/test/functional/test_framework/util.py", line 243, in wait_until
    raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
AssertionError: Predicate ''''
        test_function = lambda: not self.is_connected
''' not true after 60.0 seconds
```

hm... let me think

2024-01-16 18:04 UTC, UdjinM6 commented on test/functional/p2p_filter.py
> +        # filter_peer.wait_for_tx(txid)
👀  I don't see any issues in my branch (this PR merged on top of develop d0a6284817 + 2 commits I mentioned earlier), neither locally nor in CI https://gitlab.com/UdjinM6/dash/-/jobs/5934477704

2024-01-16 20:14 UTC, knst commented on test/functional/p2p_filter.py
> +        # filter_peer.wait_for_tx(txid)
strange, CI on github succeed: https://gitlab.com/dashpay/dash/-/pipelines/1140283342
your branch on my localhost succeed
my branch succeed on localhost only after full clean & build.

probably some build glitch.

2024-01-16 20:17 UTC, UdjinM6 approved these changes
utACK

2024-01-16 21:04 UTC, PastaPastaPasta approved these changes
re-utACK

2024-01-16 21:06 UTC, merged