backport: bitcoin#18677, #19685, #20046, #20549 (multiprocess related)
dashpay/dash pull request #5815
Opened 2024-01-11 19:40 UTC by knst

## Issue being fixed or feature implemented
Multi-process related backports from v21+

## What was done?
 - bitcoin/bitcoin#18677
 - bitcoin/bitcoin#19685
 - bitcoin/bitcoin#20046
 - bitcoin/bitcoin#20549

## How Has This Been Tested?
Run unit/functional tests

Note for reviewers:
There's no actual multiprocess code yet, that's just part related to build system.
To test build add an option `--enable-multiprocess` to configure 

> I am gonna add one more commit to disable CI because so far as there's no actual multiprocessing there's not much to test.

## Breaking Changes
N/A

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-01-14 21:02 UTC, UdjinM6 requested changes

2024-01-15 14:01 UTC, knst commented
[CI with multiprocess](https://gitlab.com/dashpay/dash/-/pipelines/1138485811) succeed after my fixes

2024-01-15 17:07 UTC, UdjinM6 approved these changes
utACK

2024-01-16 15:33 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2024-01-16 15:35 UTC, merged