backport: bitcoin#20211, #20380, #20884, #20941, #20944, #21028, #21064, #21110, #21117, bitcon-core/gui#204
dashpay/dash pull request #5818
Opened 2024-01-13 18:46 UTC by knst

## Issue being fixed or feature implemented
Just regular bitcoin backports, mostly from v21

## What was done?
 - bitcoin/bitcoin#20884
 - bitcoin/bitcoin#20941
 - bitcoin/bitcoin#20944
 - bitcoin/bitcoin#21117
 - bitcoin/bitcoin#20211
 - bitcoin/bitcoin#20380
 - bitcoin/bitcoin#21064
 - bitcoin/bitcoin#21028
 - bitcoin/bitcoin#21110
 - bitcoin-core/gui#204

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-01-14 01:42 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2024-01-14 21:03 UTC, UdjinM6 requested changes

2024-01-15 10:01 UTC, UdjinM6 approved these changes
utACK

2024-01-16 15:29 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2024-01-16 15:30 UTC, merged