backport: bitcoin#20282
dashpay/dash pull request #5823
Opened 2024-01-14 07:23 UTC by knst

## Issue being fixed or feature implemented
Bitcoin backports with breaking changes

## What was done?
 - bitcoin/bitcoin#20282
 - 

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-01-16 21:07 UTC, PastaPastaPasta commented
> backport: bitcoin#20282 breaking changes! #5823

but yet

> ## Breaking Changes
> N/A

2024-01-16 21:09 UTC, knst commented
> but yet

that's a draft, I hope to bring there more backports before v21 will happen! updated anyway to new placeholder

2024-03-07 15:19 UTC, UdjinM6 requested changes

2024-03-07 15:19 UTC, UdjinM6 commented on doc/release-notes-19200.md
> +  20.1, the `labels` field returns a JSON array of label names. (#19200)
19200: should point to this PR (5823) if to any at all

2024-03-07 15:19 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> -                {RPCResult::Type::STR, "label", "DEPRECATED. The label associated with the address. Defaults to \"\". Replaced by the labels array below."},
19200: missed changes for `"label name"` below

2024-03-07 15:19 UTC, UdjinM6 commented on doc/release-notes-19405.md
> +  `outboundmnconnections` and `mnconnections` are removed (#19405)
19405: s/19405/5823/

2024-03-07 15:19 UTC, UdjinM6 commented on doc/release-notes-19405.md
> +- The `connections` field of `bitcoin-cli -getinfo` is expanded to return a JSON
19405: s/bitcoin/dash/

2024-03-07 15:19 UTC, UdjinM6 commented on doc/release-notes-19405.md
> +  returned a single integer value for the total number of peer connections. (#19405)
19405: s/19405/5823/

2024-03-08 06:23 UTC, PastaPastaPasta submitted a review, later dismissed

2024-03-08 11:37 UTC, UdjinM6 requested changes

2024-03-08 11:37 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> -                    {RPCResult::Type::STR, "label name", "The label name. Defaults to \"\"."},
19200: hmmm... this is not what I meant... check the original PR, should be
```suggestion
                    {RPCResult::Type::STR, "label name", "Label name (defaults to \"\")."},
```
and drop
```
                    {RPCResult::Type::OBJ, "", "json object of label data",
                    {
                        {RPCResult::Type::STR, "name", "The label name. Defaults to \"\"."},
                        {RPCResult::Type::STR, "purpose", "The Purpose of the associated address (send or receive)."},
                    }},
```
block below

2024-03-15 19:47 UTC, UdjinM6 approved these changes
utACK

2024-03-17 17:56 UTC, PastaPastaPasta approved these changes
utACK 9c54cb16de0e78874cfcb83138811d91f9f20f1a

2024-03-17 17:58 UTC, merged