backport: bitcoin#18735, #18790, #19041, #19164, #19226, #19276, #19348, #19422, #19840, #20071
dashpay/dash pull request #5836
Opened 2024-01-19 16:27 UTC by knst

## Issue being fixed or feature implemented
Just regular bitcoin backports, mostly from v21

## What was done?
 - bitcoin/bitcoin#18735
 - bitcoin/bitcoin#19041
 - bitcoin/bitcoin#19164
 - bitcoin/bitcoin#19226
 - bitcoin/bitcoin#19276
 - bitcoin/bitcoin#19348
 - bitcoin/bitcoin#19422
 - bitcoin/bitcoin#19840
 - bitcoin/bitcoin#18790
 - bitcoin/bitcoin#20071

## How Has This Been Tested?
Run unit/functional tests

## note for reviewers: 
 - There's some difference with original PR bitcoin#20071 but that's not important because we do not use travis anyhow.
Moreover, the variable TRAVIS_BRANCH would be removed anyway in bitcoin#20697 - let's just skip it for simplicity

## Breaking Changes
N/A

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-01-24 12:43 UTC, UdjinM6 commented on src/init.cpp
> +    const std::string block_notify = args.GetArg("-blocknotify", "");
19840: would probably make sense to also fix `-chainlocknotify` while at it (in a follow-up commit maybe)

2024-01-24 12:43 UTC, UdjinM6 commented on ci/lint/04_install.sh
> +SHELLCHECK_VERSION=v0.7.1
19348: missing `mypy` bump to `0.781` above

2024-01-26 19:13 UTC, UdjinM6 requested changes

2024-01-26 19:13 UTC, UdjinM6 commented on src/init.cpp
> +    if (chainlock_noify.empty()) {
19840:
```suggestion
    if (!chainlock_notify.empty()) {
```

2024-01-27 17:20 UTC, UdjinM6 approved these changes
utACK

2024-01-28 04:44 UTC, PastaPastaPasta approved these changes
utACK for merging via merge commit

2024-01-28 04:45 UTC, merged