backport: trivial 2024 02 12
dashpay/dash pull request #5870
Opened 2024-02-13 04:00 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Batch of trivial backports

## What was done?

## How Has This Been Tested?
Built; ran functional tests

## Breaking Changes

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-02-13 10:45 UTC, UdjinM6 requested changes

2024-02-13 10:45 UTC, UdjinM6 commented on src/qt/intro.cpp
> +    static constexpr uint64_t nPowTargetSpacing = 10 * 60;  // from chainparams, which we don't have at this stage
gui-125:
```suggestion
    static constexpr uint64_t nPowTargetSpacing = 2.5 * 60;  // from chainparams, which we don't have at this stage
```

2024-02-13 15:14 UTC, UdjinM6 submitted a review, later dismissed
utACK

2024-02-14 03:24 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5870.86d8aeb2. A new comment will be made when the image is pushed.

2024-02-14 08:29 UTC, knst requested changes

2024-02-14 15:29 UTC, PastaPastaPasta commented on src/qt/intro.cpp
> +    static constexpr uint64_t nPowTargetSpacing = 2.5 * 60;  // from chainparams, which we don't have at this stage
meh; it's done at compile time, I think we can trust the compiler here

2024-02-14 15:32 UTC, PastaPastaPasta commented on doc/build-openbsd.md
> +./configure --with-gui=no --disable-external-signer CC=cc CXX=c++ \
done

2024-02-14 15:32 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5870.f57f5d66. A new comment will be made when the image is pushed.

2024-02-14 15:35 UTC, PastaPastaPasta commented on src/qt/intro.cpp
> +    static constexpr uint64_t nPowTargetSpacing = 2.5 * 60;  // from chainparams, which we don't have at this stage
Also; this is exactly how it's set in chainparams; so it least if there's a compiler bug we will be consistent. :D

2024-02-14 15:55 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5870.4c6f8d3b. A new comment will be made when the image is pushed.

2024-02-14 16:32 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5870.8bb2beb4. A new comment will be made when the image is pushed.

2024-02-14 16:55 UTC, DashCoreAutoGuix commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5870.8bb2beb4. The image should be on dockerhub soon.

2024-02-14 17:24 UTC, DashCoreAutoGuix commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5870.bf3d2d44. The image should be on dockerhub soon.

2024-02-14 18:11 UTC, UdjinM6 approved these changes
re-utACK, CI failure https://gitlab.com/dashpay/dash/-/jobs/6173511888 looks unrelated (restarted it just in case)

2024-02-14 19:13 UTC, knst approved these changes
LGTM

2024-02-14 20:58 UTC, merged