Bp22 29
dashpay/dash pull request #5881
Opened 2024-02-18 17:06 UTC by vijaydasmp

bitcoin backport

2024-02-25 15:23 UTC, vijaydasmp commented
Hello @UdjinM6 , requesting review

2024-02-25 18:12 UTC, knst submitted a review, later dismissed
utACK

2024-02-25 18:12 UTC, knst commented on src/test/reverselock_tests.cpp
> +#include <stdexcept>
just a note: bitcoin-22086 is not partial because `policy_fee_tests.cpp` is intentionally ommited due to no Fee Filter message

2024-02-27 00:57 UTC, UdjinM6 requested changes
could probably apply 22086 to some Dash-specific tests too (e.g. 3987d1b5d5f1fb08a29b3eaf57a5f44a6e91d382) + see below

2024-02-27 00:57 UTC, UdjinM6 commented on test/functional/p2p_fingerprint.py
> +        self.nodes[0].generatetoaddress(1, self.nodes[0].get_deterministic_priv_key().address)
20047: should pick missing changes from 20466 we merged earlier
```suggestion
        block_hash = int(self.nodes[0].generatetoaddress(1, self.nodes[0].get_deterministic_priv_key().address)[-1], 16)
```

2024-02-27 00:57 UTC, UdjinM6 commented on test/functional/p2p_fingerprint.py
> +        node0.sync_with_ping()
20047: should not undo 20466 here
```suggestion
        node0.wait_for_block(block_hash, timeout=3)
```

2024-02-28 22:56 UTC, UdjinM6 requested changes

2024-02-29 11:29 UTC, UdjinM6 approved these changes
utACK

2024-03-03 03:18 UTC, vijaydasmp commented
Hello @PastaPastaPasta , requesting review.

2024-03-04 06:20 UTC, PastaPastaPasta approved these changes
utACK

2024-03-04 06:27 UTC, merged