backport: Merge bitcoin#16795
dashpay/dash pull request #5884
Opened 2024-02-19 17:18 UTC by vijaydasmp

2024-05-23 15:18 UTC, vijaydasmp commented
Hello @UdjinM6 @knst @PastaPastaPasta requesting review

2024-05-23 19:01 UTC, UdjinM6 requested changes

2024-05-25 15:35 UTC, UdjinM6 approved these changes
utACK

2024-05-25 16:07 UTC, knst reviewed
utACK 651fad5c01e74d268f46b27756a9ce4616427e67

2024-05-25 16:07 UTC, knst commented on test/functional/p2p_addrfetch.py
> +#!/usr/bin/env python3
Consider to backport bitcoin/bitcoin#22568 in a follow-up PR. There are no any important/critical fix, just tests improvements, so, that's an out-of-scope of current PR

2024-05-25 16:08 UTC, knst approved these changes

2024-05-27 17:18 UTC, PastaPastaPasta approved these changes
utACK 651fad5c01e74d268f46b27756a9ce4616427e67

2024-05-27 17:19 UTC, PastaPastaPasta commented
22423 was already merged in https://github.com/dashpay/dash/pull/6021

2024-05-27 17:20 UTC, merged