feat: migrate to a CA issued certificate
dashpay/dash pull request #5893
Opened 2024-02-22 00:20 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Uses a new CA issued certificate

## What was done?
Certificate changed; the issuer according to the certificate is `GoGetSSL G4 CS RSA4096 SHA256 2022 CA-11` In reality, the CA is digicert and the root CA is `DigiCert Trusted Root G4` and is issued to "Dash Core Group, Inc."

## How Has This Been Tested?
Signed a binary with it see: https://www.virustotal.com/gui/file/a6577f3b8b474cfb1def1ea339795cb229b26d248d71f0b6f0b65e9e9ba3411b/details. I can share the binary if you'd like.

## Breaking Changes
Not really any; unless someone is relying on a specific certificate.

## Signature

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

8154f5a92ffe1124ad1573487f6e1842fe28eed7a455416c82fc6211253117ed  contrib/windeploy/win-codesign.cert
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEKVkDYuyHioH9PCArUlJ77avoeYQFAmXWkZEACgkQUlJ77avo
eYSU2Q//fa6yzHrjW9cjsuxyRn/b+t7ry9lplzHtQDqxADxq5ANhddfurDWKOVNc
Fu3iiK1iCtdaBMDSvlAW9/nWXaJaMSqkCdExaCS63EDyItPRSwiEmCIMe1EzR1Ed
0AWrnWYIRk27huQ3RbCcnsQUEoMI3DbBMDN19ClMzyMtFiTjQfIgB0WO7OLsI785
ZXx2dqcrRYSkDd72YYfuoamJPxFXC9+kOa1Ss531w4F/86jIG+VnqVuH6L0iPkJ1
HM5jF2jLDCiU8eFN/ANsCvC65+a0nSq+xKJLeqSen0KwAPy/lBAcqY9VduvDpAyE
a6gWDhTEbYGzQicVTS3EDp0360Y0UOKixuLibzD/8Vlhk0stgEyOwoeKbNj6vRt4
MuKjAsmvh/WpuYXHmycJU1pJZ1V/udyjmpSRsr8+xB6Ww5T/epu2OJ3Yjsyny5P+
ncVtQfO18rAVIRKb6zWBygz1ITqdU23bVHApp+3pwbZTQP1ilIMRadTX7cMic6/a
eKc8jEW6BWYiXNjCOu3PPOE/P9ML537LqSg4XJXyxdemmJofzcPb1HMpngwmdQHO
jm4tOzAFwe/rdISpthED1zfgLAuWiIYNstCtzdTeDizLOfYICe8kPBjsc3zaZqCx
Cj8qlV/BqvXpua+KpuDLHa11n3amN+trNd5oOb6ewZmJqxLo4NM=
=d3Bu
-----END PGP SIGNATURE-----
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCAAdFiEEYKz3C/cSZFBJ7m8V7+rxZoYiX2QFAmXWkZsACgkQ7+rxZoYi
X2QOOwf/YUm2TPXtrxOT7/CJVTITQa3u0XMwJ6JADuHtJaXlmA9b9ucz2cSKaFdC
noA1q8FFWbMUDM9+RkudAjhO5JCLMkJrfCK/mG2FlZrXV/61lounxyRdMerxk9qF
8/iJS1cf6t3tE4/SziMgo3uCZf5tsORIiNRxdEhBITVmDenPNTpKKGetijH7gr7o
lRHP5lNNPWH629eFqFtVORYiyvFOtSMV2PfG+lauBnm8DMoHIXC+Zs3lT6Soes+L
hxli9z+/ZGnQdHHIFIM+qcQNKIiEoWb4iUmsMK2couGk6beoWZNUmEpTjzubEfbN
QU252WZBsdGwQ/NEr5Gi4rNeUSfvig==
=hlUn
-----END PGP SIGNATURE-----
```

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-02-22 10:20 UTC, UdjinM6 requested changes
signature is ok but hash is different for me

```
> sha256sum contrib/windeploy/win-codesign.cert     
5dcc037bb56205a8744c99d1ba15e8fc7e64144ba3ce728ce57546d804469ea1  contrib/windeploy/win-codesign.cert
```

2024-02-22 15:57 UTC, PastaPastaPasta commented
Very odd...

Here is the diff between the two files; they appear the same to me; maybe some metadata difference or something?
```
> $ diff win-codesign.cert win-codesign.cert.1 -y                                                                                                                                                                                                                     [±feat-new-cert ●]
-----BEGIN CERTIFICATE-----             |       -----BEGIN CERTIFICATE-----
MIIFejCCA2KgAwIBAgIQAlT0uBtKniPybIjyQJ1wwzANBgkqhkiG9w0BA       |       MIIFejCCA2KgAwIBAgIQAlT0uBtKniPybIjyQJ1wwzANBgkqhkiG9w0BA
MQswCQYDVQQGEwJMVjEZMBcGA1UEChMQRW5WZXJzIEdyb3VwIFNJQTEwM       |       MQswCQYDVQQGEwJMVjEZMBcGA1UEChMQRW5WZXJzIEdyb3VwIFNJQTEwM
AxMnR29HZXRTU0wgRzQgQ1MgUlNBNDA5NiBTSEEyNTYgMjAyMiBDQS0xM       |       AxMnR29HZXRTU0wgRzQgQ1MgUlNBNDA5NiBTSEEyNTYgMjAyMiBDQS0xM
MDIyMTAwMDAwMFoXDTI3MDIyMTIzNTk1OVowbjELMAkGA1UEBhMCVVMxE       |       MDIyMTAwMDAwMFoXDTI3MDIyMTIzNTk1OVowbjELMAkGA1UEBhMCVVMxE
BAgTB0FyaXpvbmExDTALBgNVBAcTBE1lc2ExHjAcBgNVBAoTFURhc2ggQ       |       BAgTB0FyaXpvbmExDTALBgNVBAcTBE1lc2ExHjAcBgNVBAoTFURhc2ggQ
cm91cCwgSW5jLjEeMBwGA1UEAxMVRGFzaCBDb3JlIEdyb3VwLCBJbmMuM       |       cm91cCwgSW5jLjEeMBwGA1UEAxMVRGFzaCBDb3JlIEdyb3VwLCBJbmMuM
KoZIzj0CAQYFK4EEACIDYgAEVfkX5+W7xjvfhkd6MIs4rRWtOeYS6ydYm       |       KoZIzj0CAQYFK4EEACIDYgAEVfkX5+W7xjvfhkd6MIs4rRWtOeYS6ydYm
XyMV77aSb2dipLpsb0c1RplEbzJIXMALa3Rm05BPFpaed81n2bf/VPnUI       |       XyMV77aSb2dipLpsb0c1RplEbzJIXMALa3Rm05BPFpaed81n2bf/VPnUI
qwMgYR+YyeIjjFs4FJm8Ew0xo4IB1DCCAdAwHwYDVR0jBBgwFoAUyfwQ7       |       qwMgYR+YyeIjjFs4FJm8Ew0xo4IB1DCCAdAwHwYDVR0jBBgwFoAUyfwQ7
vQhE7zpik+1bXpowHQYDVR0OBBYEFGOo8xDYojxv7+7/cMdufP/vG0GKM       |       vQhE7zpik+1bXpowHQYDVR0OBBYEFGOo8xDYojxv7+7/cMdufP/vG0GKM
IAQ3MDUwMwYGZ4EMAQQBMCkwJwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZ       |       IAQ3MDUwMwYGZ4EMAQQBMCkwJwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZ
cnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBB       |       cnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBB
gZcGA1UdHwSBjzCBjDBEoEKgQIY+aHR0cDovL2NybDMuZGlnaWNlcnQuY       |       gZcGA1UdHwSBjzCBjDBEoEKgQIY+aHR0cDovL2NybDMuZGlnaWNlcnQuY
R2V0U1NMRzRDU1JTQTQwOTZTSEEyNTYyMDIyQ0EtMS5jcmwwRKBCoECGP       |       R2V0U1NMRzRDU1JTQTQwOTZTSEEyNTYyMDIyQ0EtMS5jcmwwRKBCoECGP
Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9Hb0dldFNTTEc0Q1NSU0E0MDk2U0hBM       |       Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9Hb0dldFNTTEc0Q1NSU0E0MDk2U0hBM
MkNBLTEuY3JsMIGDBggrBgEFBQcBAQR3MHUwJAYIKwYBBQUHMAGGGGh0d       |       MkNBLTEuY3JsMIGDBggrBgEFBQcBAQR3MHUwJAYIKwYBBQUHMAGGGGh0d
Y3NwLmRpZ2ljZXJ0LmNvbTBNBggrBgEFBQcwAoZBaHR0cDovL2NhY2Vyd       |       Y3NwLmRpZ2ljZXJ0LmNvbTBNBggrBgEFBQcwAoZBaHR0cDovL2NhY2Vyd
aWNlcnQuY29tL0dvR2V0U1NMRzRDU1JTQTQwOTZTSEEyNTYyMDIyQ0EtM       |       aWNlcnQuY29tL0dvR2V0U1NMRzRDU1JTQTQwOTZTSEEyNTYyMDIyQ0EtM
CQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAgEAkr3cuc0ctBEVxksDW       |       CQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAgEAkr3cuc0ctBEVxksDW
bsnqGoXFsFJrRJ9JU21d4hPVtjT3+z6xJrzIpYTt0r7AZab6NmyNmpyU5       |       bsnqGoXFsFJrRJ9JU21d4hPVtjT3+z6xJrzIpYTt0r7AZab6NmyNmpyU5
aWlu9LVjC4jZbvjVXwjGYMNUUbBOY+qw+xDup4uCYEiHMeRfAZjV2dAVI       |       aWlu9LVjC4jZbvjVXwjGYMNUUbBOY+qw+xDup4uCYEiHMeRfAZjV2dAVI
zceSAiW0Hl7gJBl1PeJyRhU3BylTPW6Pb0b+IDvEBWzlYN6F74Ak8qWeX       |       zceSAiW0Hl7gJBl1PeJyRhU3BylTPW6Pb0b+IDvEBWzlYN6F74Ak8qWeX
R4hSJ8jE7u3edTVx9UPAIAAxNTlTj3RY+HoZR57jfeGyyH1WUpTd9XSCp       |       R4hSJ8jE7u3edTVx9UPAIAAxNTlTj3RY+HoZR57jfeGyyH1WUpTd9XSCp
5nslOTTL4/Eh2joxNqH3tv0RNfQGBd3yTXPuTNcVJTguyR7N24HFubZRs       |       5nslOTTL4/Eh2joxNqH3tv0RNfQGBd3yTXPuTNcVJTguyR7N24HFubZRs
H1eigjFULSym8G8os3G2B9b33voUu4DYTte2xnE5DI2zoYfrcsUhKoX0F       |       H1eigjFULSym8G8os3G2B9b33voUu4DYTte2xnE5DI2zoYfrcsUhKoX0F
jLBUdrXnMWtvW5eCfMjoB4DQoKkrU9PjWpKXE7ze3kI/FFS6AzEcVOA7A       |       jLBUdrXnMWtvW5eCfMjoB4DQoKkrU9PjWpKXE7ze3kI/FFS6AzEcVOA7A
HvQwQHdBoYjwGYoP6fA6jrgejflkxb+SAgQWVw1c4tgiGeSXbg2OiiTbt       |       HvQwQHdBoYjwGYoP6fA6jrgejflkxb+SAgQWVw1c4tgiGeSXbg2OiiTbt
5uzO3YHAKZgWw1kYq+xfZHafpDdoiD9b5LcXwSNtuwdkzodM0NvCeHGb5       |       5uzO3YHAKZgWw1kYq+xfZHafpDdoiD9b5LcXwSNtuwdkzodM0NvCeHGb5
cRV00cF3KgzJeSHheIh2IXeO0Vob9FG6vDCncD3msZ0pBUXN9bhqzmblf       |       cRV00cF3KgzJeSHheIh2IXeO0Vob9FG6vDCncD3msZ0pBUXN9bhqzmblf
a3cV9NbtlicAJ4MEyIs=                            |       a3cV9NbtlicAJ4MEyIs=
-----END CERTIFICATE-----               |       -----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----                                             -----BEGIN CERTIFICATE-----
MIIGoTCCBImgAwIBAgIQB4Q9rQHBFcJ07kGnKCJGeTANBgkqhkiG9w0BA               MIIGoTCCBImgAwIBAgIQB4Q9rQHBFcJ07kGnKCJGeTANBgkqhkiG9w0BA
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDV               MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDV
d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkI               d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkI
RzQwHhcNMjIwNjIzMDAwMDAwWhcNMzIwNjIyMjM1OTU5WjBaMQswCQYDV               RzQwHhcNMjIwNjIzMDAwMDAwWhcNMzIwNjIyMjM1OTU5WjBaMQswCQYDV
VjEZMBcGA1UEChMQRW5WZXJzIEdyb3VwIFNJQTEwMC4GA1UEAxMnR29HZ               VjEZMBcGA1UEChMQRW5WZXJzIEdyb3VwIFNJQTEwMC4GA1UEAxMnR29HZ
RzQgQ1MgUlNBNDA5NiBTSEEyNTYgMjAyMiBDQS0xMIICIjANBgkqhkiG9               RzQgQ1MgUlNBNDA5NiBTSEEyNTYgMjAyMiBDQS0xMIICIjANBgkqhkiG9
AAOCAg8AMIICCgKCAgEArR70B7JDZoqiZ3cllQql+BbWKeRXySzvUodAb               AAOCAg8AMIICCgKCAgEArR70B7JDZoqiZ3cllQql+BbWKeRXySzvUodAb
WLdtcX/If6Syf+2M3inDavc+MxIXnKrQ9MYW70gfJLAQH1gTGTtDS3zk9               WLdtcX/If6Syf+2M3inDavc+MxIXnKrQ9MYW70gfJLAQH1gTGTtDS3zk9
+67/mRc2vpsSEO/bNXQosFDMBqJ2qAyu5qmXw6ShBMUelMigYd2mrU+91               +67/mRc2vpsSEO/bNXQosFDMBqJ2qAyu5qmXw6ShBMUelMigYd2mrU+91
n2E5kBavjfBay7OhYemBBliU4LMcsNXwAoQn4LRHGZHbXICu6rqrJB7Vu               n2E5kBavjfBay7OhYemBBliU4LMcsNXwAoQn4LRHGZHbXICu6rqrJB7Vu
Se091l6c57Djsa896sdAs1o8CvPtyr9l+qYlr3fGEXwDsnEq0+PzzNHBy               Se091l6c57Djsa896sdAs1o8CvPtyr9l+qYlr3fGEXwDsnEq0+PzzNHBy
Jv3pOBQp2EnpuN3aBX7QcWQUJByqD1twbelSK4VSMLzu4a1I4XISSWWHU               Jv3pOBQp2EnpuN3aBX7QcWQUJByqD1twbelSK4VSMLzu4a1I4XISSWWHU
74ief06D+xDb/e1PTLShb5guXc3daeB8RUdKecFpmEG1vst0RZtJ6eh/Z               74ief06D+xDb/e1PTLShb5guXc3daeB8RUdKecFpmEG1vst0RZtJ6eh/Z
dMrJnSY29H+/nVS19zhAVG+h/q9S0S2U/8RDk7sDsRoNkuMNuShi/UggV               dMrJnSY29H+/nVS19zhAVG+h/q9S0S2U/8RDk7sDsRoNkuMNuShi/UggV
zx3iU6FPkx7dD/GUH+AfSBZRsbSytIN7jgJ8EhYCrZjY4ZE5fHGiwEMG4               zx3iU6FPkx7dD/GUH+AfSBZRsbSytIN7jgJ8EhYCrZjY4ZE5fHGiwEMG4
XNG+pNmfPkMIFQC9JyLszPXJCj/MbSHFoPOS9/5dHE5B0HXvoyhgxtgnc               XNG+pNmfPkMIFQC9JyLszPXJCj/MbSHFoPOS9/5dHE5B0HXvoyhgxtgnc
FLcKg+yQNrgsVpSM0TYME9JB9np9PkFfCs4khmqjtq9OpMG6Ktv8cuHvf               FLcKg+yQNrgsVpSM0TYME9JB9np9PkFfCs4khmqjtq9OpMG6Ktv8cuHvf
AwEAAaOCAVkwggFVMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEF               AwEAAaOCAVkwggFVMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEF
yMtrf70IRO86YpPtW16aMB8GA1UdIwQYMBaAFOzX44LScV1kTN8uZz/nu               yMtrf70IRO86YpPtW16aMB8GA1UdIwQYMBaAFOzX44LScV1kTN8uZz/nu
MA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEFBQcDAzB3BggrB               MA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEFBQcDAzB3BggrB
AQRrMGkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvb               AQRrMGkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvb
BgEFBQcwAoY1aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZ               BgEFBQcwAoY1aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZ
c3RlZFJvb3RHNC5jcnQwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2Nyb               c3RlZFJvb3RHNC5jcnQwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2Nyb
aWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcmwwHAYDVR0gB               aWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcmwwHAYDVR0gB
BgVngQwBAzAIBgZngQwBBAEwDQYJKoZIhvcNAQELBQADggIBAAvbCteyH               BgVngQwBAzAIBgZngQwBBAEwDQYJKoZIhvcNAQELBQADggIBAAvbCteyH
RLO/snsISZyeLcqy8DRJ35eh6xvD5ux2dG/uSXPhhqiU/JEXO5oobla3b               RLO/snsISZyeLcqy8DRJ35eh6xvD5ux2dG/uSXPhhqiU/JEXO5oobla3b
ngy/YpobQrrCP61Jo8IbX5afl4C5JoCxq5rBIaNW/pRokaeywv9dHYvEg               ngy/YpobQrrCP61Jo8IbX5afl4C5JoCxq5rBIaNW [...]

2024-02-23 17:44 UTC, UdjinM6 approved these changes
ACK

2024-02-23 18:34 UTC, knst approved these changes
LGTM

hashes matched, pgp signatures is pasta's indeed.

```
$ openssl x509 -in contrib/windeploy/win-codesign.cert -text
...
            Not Before: Feb 21 00:00:00 2024 GMT
            Not After : Feb 21 23:59:59 2027 GMT
...
        Subject: C = US, ST = Arizona, L = Mesa, O = "Dash Core Group, Inc.", CN = "Dash Core Group, Inc."
```

seems as cert is valid too, though I don't know how to test it.

2024-02-24 16:49 UTC, merged