backport: trivial 2024 02 22
dashpay/dash pull request #5897
Opened 2024-02-23 04:34 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
batch of trivial backports

## What was done?

## How Has This Been Tested?
Building locally; tests not ran

## Breaking Changes
Didn't see any yet; didn't review much yet

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-02-23 18:25 UTC, UdjinM6 requested changes

2024-02-23 18:25 UTC, UdjinM6 commented on test/functional/p2p_compactblocks.py
> +        block = from_hex(CBlock(), node.getblock(block_hash, False))
25370: this should fix linter and tests
```suggestion
        bad_peer = self.nodes[0].add_p2p_connection(TestP2PConn(cmpct_version=1))
        block_hash = node.getblockhash(chain_height)
        block = FromHex(CBlock(), node.getblock(block_hash, False))
```

2024-02-25 04:41 UTC, UdjinM6 approved these changes
utACK

2024-02-25 13:54 UTC, knst approved these changes
utACK

2024-02-25 13:54 UTC, knst commented on src/init.cpp
> +        return InitError(Untranslated("peertimeout must be a positive integer."));
bitcoin-25506:

consider including 25511 which is tests for it

2024-02-27 16:03 UTC, merged