backport: trivial 2024 02 28
dashpay/dash pull request #5909
Opened 2024-02-28 23:00 UTC by PastaPastaPasta

## What was done?
Trivial Backports

## How Has This Been Tested?
Built locally; did not run tests or review

## Breaking Changes

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-02-28 23:15 UTC, UdjinM6 requested changes
mostly ok but imo 25925 is blocked by #5579

2024-02-28 23:15 UTC, UdjinM6 commented on doc/descriptors.md
> +- `importdescriptors` takes as input descriptors to import into a descriptor wallet
25925: this rpc was introduced in 16528 which will be backported in not-yet-merged #5579

2024-02-28 23:24 UTC, PastaPastaPasta commented
25925 dropped for now; watching https://gitlab.com/dashpay/dash/-/pipelines/1194837720 for CI.

2024-02-28 23:38 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v20.1.0-devpr5909.e3e4a955. A new comment will be made when the image is pushed.

2024-02-28 23:38 UTC, UdjinM6 commented
Triggered GH Guix build because of 25788, just in case

2024-02-29 11:29 UTC, UdjinM6 approved these changes
utACK

2024-02-29 15:35 UTC, merged