refactor: significant Mutex refactoring
dashpay/dash pull request #5954
Opened 2024-03-24 03:21 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Don't use generic names; recursive mutexes where not needed; etc

## What was done?
Includes:
RecursiveMutex -> Mutex,
renaming of `cs` to something more meaningful,
usage of atomics where trivially possible,
introduce a method CQuorum::SetVerificationVector to avoid needing to lock an internal mutex externally

## How Has This Been Tested?
Compiling

## Breaking Changes
None

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-03-25 15:19 UTC, PastaPastaPasta commented on src/llmq/dkgsessionhandler.cpp
> +    pendingContributions.Clear();
https://github.com/dashpay/dash/blob/cfdb8a6b9c37f5031b76851ff1f6ce7f2c8811c3/src/llmq/dkgsessionhandler.h#L140-L144

2024-03-25 16:14 UTC, UdjinM6 requested changes
smth like 450f66da21 should help fixing test failures

2024-03-26 15:12 UTC, UdjinM6 requested changes

2024-03-26 16:05 UTC, UdjinM6 submitted a review, later dismissed
LGTM, light ACK

2024-05-04 15:31 UTC, UdjinM6 approved these changes
utACK

2024-05-14 14:16 UTC, merged