feat: implement read write locks in threading and use them for CActiveMasternodeManager::cs
dashpay/dash pull request #5961
Opened 2024-03-27 17:54 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
We have some caches or other information in codebase which are read from a lot; but rarely written to. We can use a RW lock here instead of a normal Mutex

## What was done?
Implement a RW lock and use them

## How Has This Been Tested?
Hasn't been much; looking for review atm. Maybe should deploy this on testnet for a bit and make sure it doesn't break. 
## Breaking Changes

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-03-28 00:50 UTC, UdjinM6 requested changes
pls check be16627d8b

2024-03-29 15:08 UTC, knst commented on src/sync.h
> +typedef SharedAnnotatedMixin<std::shared_mutex> SharedMutex;
nit: why won't use modern syntax such as:
`using SharedMutex = SharedAnnotatedMixin<std::shared_mutex>`

2024-03-29 15:20 UTC, knst approved these changes
LGTM

2024-03-29 15:20 UTC, knst commented on src/sync.h
> +        EnterCritical(pszName, pszFile, nLine, Base::mutex(), true);
```suggestion
        EnterCritical(pszName, pszFile, nLine, Base::mutex(), /*fTry = */ true);
```

2024-03-29 15:20 UTC, knst commented on src/sync.h
> +    }
<s> why we need  even to consider a situation when `pmutexIn` can be non-null ptr? </s>
ok it seems as copy-paste of `UniqueLock`

```suggestion
```

2024-03-29 15:20 UTC, knst commented on src/evo/mnauth.cpp
> +    uint256 signHash = [&]() {
missing `const`:

```suggestion
    const uint256 signHash = [&]() {
```

2024-03-30 18:49 UTC, knst commented
hm, what if there would be too many reading operations which are running in many threads - is there any chance that regular lock ever be acquired? or it would wait until all reading operations are done?

2024-04-01 15:45 UTC, PastaPastaPasta commented
> hm, what if there would be too many reading operations which are running in many threads - is there any chance that regular lock ever be acquired? or it would wait until all reading operations are done?

From the [paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2406.html#shared_mutex_imp) that introduces them


> shared_mutex Reference Implementation

> shared_mutex can certainly be implemented on top of an OS supplied read-write mutex. However a portable subset of the implementation is shown here for the purpose of motivating the existence of cond_var: the razor-thin layer over the OS condition variable.

> A secondary motivation is to explain the lack of reader-writer priority policies in shared_mutex. This is due to an algorithm credited to Alexander Terekhov which lets the OS decide which thread is the next to get the lock without caring whether a unique lock or shared lock is being sought. This results in a complete lack of reader or writer starvation. It is simply fair.

> Below is most of the implementation of shared_mutex demonstrating that with this proposal, very high quality synchronization devices can be easily coded, and with the same efficiency as if they were coded straight to the OS. The timed-locking functions are omitted only for brevity. They are similar to the locking functions but make use of cond_var::timed_wait. Dependence on the lower-level C++ API is highlighted.

Based on this I don't think there is an ability for starvation

2024-04-02 15:51 UTC, UdjinM6 approved these changes
utACK

2024-04-03 14:44 UTC, knst approved these changes
utACK 069282611c5058d0ea78ca83f9709034fe2c5ffd

2024-04-03 15:36 UTC, merged