backport: bitcoin#18772, #20690, #20789, #20813, #21531, bitcoin-core/gui#13, #72, 115, #139, #171
dashpay/dash pull request #5973
Opened 2024-04-05 18:53 UTC by knst

## Issue being fixed or feature implemented
Regular backports from bitcoin v22

## What was done?
 - bitcoin-core/gui#13
 - bitcoin-core/gui#115
 - bitcoin/bitcoin#20690
 - bitcoin/bitcoin#18772
 - bitcoin/bitcoin#20813
 - bitcoin/bitcoin#20789
 - bitcoin-core/gui#171
 - bitcoin-core/gui#72
 - bitcoin-core/gui#139
 - bitcoin/bitcoin#21531

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
N/A

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone

2024-04-09 15:36 UTC, knst commented
> check https://gitlab.com/dashpay/dash/-/jobs/6565831300

seems as random failure, because both times failed on different tests. Let's wait CI to run for rebased version

>  @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/23becc3efa5ab684d711cfd50e150ab6341629cd..e4583dee3b68088b82bf4057a9eaebefa209c64f) the bp-v22-p4 branch from[ 23becc3 ](https://github.com/dashpay/dash/commit/23becc3efa5ab684d711cfd50e150ab6341629cd)to e4583de

rebased on top of develop after master merged back

2024-04-09 20:08 UTC, UdjinM6 requested changes
one tiny issue, LGTM otherwise

2024-04-09 20:20 UTC, knst commented on test/functional/example_test.py
> -#!/usr/bin/env python3
good catch! I hope you did check all 300 files manually :) 
Fixed

2024-04-09 20:33 UTC, UdjinM6 approved these changes
utACK

2024-04-12 15:16 UTC, PastaPastaPasta approved these changes
utACK a2f190deff19dc21ffff700ef3a13d5f53a92ae3

2024-04-12 15:16 UTC, merged