backport:  Merge #21836:
dashpay/dash pull request #5998
Opened 2024-04-25 11:53 UTC by vijaydasmp

bitcoin backports

2024-05-10 20:35 UTC, UdjinM6 requested changes
script in 21836 should be

```
-BEGIN VERIFY SCRIPT-
sed -i -E -e 's/\.\.\."\)(\.|,|\)| )/…"\)\1/' -- $(git ls-files -- 'src' ':(exclude)src/qt/dashstrings.cpp' ':(exclude)src/immer/')
sed -i -e 's/\.\.\.\\"/…\\"/' src/qt/sendcoinsdialog.cpp
sed -i -e 's|\.\.\.</string>|…</string>|' src/qt/forms/*.ui
sed -i -e 's|\.\.\.)</string>|…)</string>|' src/qt/forms/sendcoinsdialog.ui
-END VERIFY SCRIPT-
```

2024-05-10 20:35 UTC, UdjinM6 commented on src/immer/extra/guile/benchmark.scm
> +(display ";;;; benchmarking creation…") (newline)
21836: should exclude `src/immer/`

2024-05-10 20:35 UTC, UdjinM6 commented on src/qt/dashstrings.cpp
> +QT_TRANSLATE_NOOP("dash-core", "Found enough users, signing …"),
21836: should dashify script

2024-05-10 20:35 UTC, UdjinM6 commented on src/init.cpp
> +    argsman.AddArg("-maxconnections=<n>", strprintf("Maintain at most <n> connections to peers (temporary service connections excluded) (default: %u). This limit does not apply to connections manuall
21710: missing changes in `src/rpc/net.cpp`

2024-05-17 14:11 UTC, UdjinM6 requested changes
script fails (as expected) - you must drop all changes in `src/immer/*` and `src/qt/dashstrings.cpp` you introduced earlier

2024-05-18 10:12 UTC, UdjinM6 approved these changes
utACK

2024-05-19 16:16 UTC, PastaPastaPasta approved these changes
utACK eeec358f9d5878cd276ee211914599e44f61415c

2024-05-19 16:17 UTC, merged