fix: bump version of libbacktrace library
dashpay/dash pull request #6037
Opened 2024-05-28 13:58 UTC by knst

## Issue being fixed or feature implemented
Old version of `libbacktrace` library doesn't support debug information for ELF produced by modern compilers

It appears like an error:
 > unrecognized DWARF version in .debug_info at 6
 > no debug info in ELF executable

## What was done?
Bump version of `libbacktraces` to the current master. It doesn't seems as it has any releases anymore, so, I chose the latest revision.

## How Has This Been Tested?
With old version:
```
No debug information available for stacktrace. You should add debug information and then run
dashd -printcrashinfo=bvcgc43iinzgc43ijfxgm3ybaacwiyltnbsfw43umq5du5dfojwws3tborssqkjamnqwy3dfmqqgi5lfeb2g6idvnzugc3tenrswiidfpbrwk4dunfxw4csfpbrwk4dunfxw4oraor4xazj5mnugc4ramnxw443ufiwca53imf2d2isiiveekiqed56acaaaaaaaaucrlszzcfaaaaevexftsekaaafvmqbaaaaaaaaaa===
```

With this fixes output as expected:
```
std::terminate() called due to unhandled exception
Exception: type=char const*, what="HEHE"
   0#: (0x5D7C19364C3F) bitcoind.cpp:114          - AppInit
   1#: (0x5D7C19364C3F) bitcoind.cpp:273          - main
   2#: (0x7B0B19C28150) libc_start_call_main.h:74 - __libc_start_call_main
   3#: (0x7B0B19C28209) libc-start.c:128          - call_init
   4#: (0x7B0B19C28209) libc-start.c:347          - __libc_start_main_impl
   5#: (0x5D7C193734D5) <unknown-file>            - ???
```

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-05-28 18:01 UTC, UdjinM6 requested changes
let's use the original repo

2024-05-29 05:26 UTC, knst commented on depends/packages/backtrace.mk
>  $(package)_file_name=$($(package)_version).tar.gz
wow, I didn't know it can work without a tag

2024-05-29 12:58 UTC, UdjinM6 approved these changes
utACK

2024-05-29 16:20 UTC, PastaPastaPasta approved these changes
utACK 0e82bf46d218906dfb674b8aa231728c078636c0

2024-05-29 16:24 UTC, merged