backport: merge bitcoin#22496, #20233, #22627, #22725, #22697, #22740, #22849, #22791, #22848, #22915, #22911, #22974 (addrman backports)
dashpay/dash pull request #6040
Opened 2024-05-31 03:23 UTC by kwvg

## Additional Information

_Work in progress_

## Breaking Changes

_Work in progress_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-06-02 16:49 UTC, UdjinM6 requested changes

2024-06-02 16:49 UTC, UdjinM6 commented on src/init.cpp
>      argsman.AddArg("-checkmempool=<n>", strprintf("Run checks every <n> transactions (default: %u, regtest: %u)", defaultChainParams->DefaultConsistencyChecks(), regtestChainParams->DefaultConsistenc
20233: missing
```suggestion
    argsman.AddArg("-checkmempool=<n>", strprintf("Run mempool consistency checks every <n> transactions. Use 0 to disable. (default: %u, regtest: %u)", defaultChainParams->DefaultConsistencyChecks(), regtestChainParams->DefaultConsistencyChecks()), ArgsManager::ALLOW_ANY | ArgsManager::DEBUG_ONLY, OptionsCategory::DEBUG_TEST);
```

2024-06-03 05:21 UTC, kwvg commented on src/init.cpp
>      argsman.AddArg("-checkmempool=<n>", strprintf("Run checks every <n> transactions (default: %u, regtest: %u)", defaultChainParams->DefaultConsistencyChecks(), regtestChainParams->DefaultConsistenc
Resolved in latest push!

2024-06-04 19:41 UTC, UdjinM6 approved these changes
utACK

2024-06-07 04:23 UTC, PastaPastaPasta approved these changes
utACK f619f8ff802fb2e369e11932ca3c0cc50810c13d

2024-06-07 04:24 UTC, merged