fix: add a missing file util/wpipe to linter lists
dashpay/dash pull request #6053
Opened 2024-06-11 14:10 UTC by knst

## Issue being fixed or feature implemented
Missing a file that is dash specific

## What was done?
Added to list of dash's linters

## How Has This Been Tested?
Run `test/lint/lint-all.sh`

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-06-11 14:20 UTC, PastaPastaPasta approved these changes
utACK 1896490126213ba086acfe3210c9a7e473f897b9

2024-06-11 21:58 UTC, UdjinM6 requested changes

2024-06-13 10:25 UTC, UdjinM6 approved these changes
utACK fbffe06dad6f3dd1e257950f6f304d4a5de414cf

2024-06-15 17:04 UTC, PastaPastaPasta approved these changes
utACK fbffe06dad6f3dd1e257950f6f304d4a5de414cf

2024-06-16 22:11 UTC, kwvg approved these changes
utACK fbffe06dad6f3dd1e257950f6f304d4a5de414cf

2024-06-18 02:57 UTC, merged