backport :
dashpay/dash pull request #6071
Opened 2024-06-21 15:40 UTC by vijaydasmp

bitcoin backports

2024-07-22 03:04 UTC, vijaydasmp commented
Hello @UdjinM6 , @knst , @PastaPastaPasta for review

2024-07-22 20:33 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commit/35b39cfee30395d1613eeb7b672027ed31901637

2024-07-23 05:50 UTC, knst commented on doc/release-notes-22570.md
> +  version 22.x is the only version that can read `banlist.dat` and also write
22570 has been already released with version Dash Core v20: https://github.com/dashpay/dash/pull/5574


DNM 22603

2024-07-23 16:08 UTC, kwvg requested changes
Please backport bitcoin#22593 as well (see https://github.com/dashpay/dash/commit/cb1745bb62f97513f580a2980bf18e6de022051b).

2024-08-05 08:08 UTC, UdjinM6 approved these changes
utACK 26ec2e4a14045291c96c7e2dc04db9c318599977

2024-08-09 03:31 UTC, vijaydasmp commented
> utACK [26ec2e4](https://github.com/dashpay/dash/commit/26ec2e4a14045291c96c7e2dc04db9c318599977)

had to rebase , requesting re-review

2024-08-22 12:03 UTC, UdjinM6 approved these changes
utACK a6ec9bcc3793e0579ee039a204c6d971cfbc797e

2024-08-27 06:34 UTC, knst approved these changes
utACK ad840ec31aca0156272dde9f1bda523bbd444edb

2024-08-27 07:18 UTC, kwvg approved these changes
utACK ad840ec31aca0156272dde9f1bda523bbd444edb

2024-08-28 17:17 UTC, merged