Fix descriptor mixing unlock
dashpay/dash pull request #6092
Opened 2024-07-03 08:42 UTC by knst

## Issue being fixed or feature implemented
As [noticed by kwvg](https://github.com/dashpay/dash/pull/6090#pullrequestreview-2153639183), mixing doesn't work with descriptor wallets if do "unlock only for mixing". This PR is aiming to fix this issue.
https://github.com/dashpay/dash-issues/issues/59

## What was done?
Removed default argument "bool mixing = false" from WalletStorage interface,
Refactored a logic of CWallet::IsLocked to make it shorter, clearer and unified with bitcoin.

## How Has This Been Tested?
Run Dash-Qt with descriptor wallet, run mixing, enter passphrase.
The wallet is partially unlocked (for mixing only) - possible to see yellow lock in status. Mixing happens.
I tried to run a transaction - it ask unlocking password, so, seems as it works as expected.

Though, I am not sure how exactly to test that **all** rpc are indeed locked when descriptor wallet is unlocked for mixing only.

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-07-03 14:32 UTC, kwvg requested changes
w.r.t c94490839912e21965a01655fa24f837f037b4f6

**UPDATE 3:** References to a potential transaction history bug have been removed as they were caused by a filter setting and was not a bug (see [correcting comment](https://github.com/dashpay/dash/pull/6092#issuecomment-2212478426)), balance reporting was working as expected. Approved.

2024-07-03 14:32 UTC, kwvg commented on src/wallet/scriptpubkeyman.cpp
> -    if (m_storage.IsLocked() || m_storage.IsWalletFlagSet(WALLET_FLAG_KEY_ORIGIN_METADATA) || !IsHDEnabled()) {
nit: `m_storage.IsLocked(/* fForMixing = */ false) `

2024-07-07 15:01 UTC, knst commented
@kwvg you don't see transaction history for CJ because you have a filter "most common" activated:
![image](https://github.com/dashpay/dash/assets/545784/1fc6e7f6-b3fd-48ef-b002-769bcdb54848)

2024-07-07 17:09 UTC, kwvg commented
> you don't see transaction history for CJ because you have a filter "most common" activated

@knst Odd, it was a clean instance, hadn't activated any filter in any instances, current or prior. Thanks for pointing it out!

2024-07-07 18:24 UTC, UdjinM6 approved these changes
LGTM, ~utACK~ light ACK c94490839912e21965a01655fa24f837f037b4f6

2024-07-09 12:29 UTC, kwvg approved these changes
ACK c94490839912e21965a01655fa24f837f037b4f6

Disregard previous review.

2024-07-09 14:36 UTC, PastaPastaPasta approved these changes
utACK c94490839912e21965a01655fa24f837f037b4f6

2024-07-09 14:37 UTC, merged

2024-07-23 17:44 UTC, PastaPastaPasta commented
back ported in #6115