backport: bitcoin#19801, #20228, #20556, #21141, #21235, #21331, #21343, #21424, #21691, #21777
dashpay/dash pull request #6114
Opened 2024-07-15 06:44 UTC by knst

## What was done?
Backports from bitcoin v22:
 - bitcoin/bitcoin#21331
 - bitcoin/bitcoin#20556
 - bitcoin/bitcoin#21424
 - bitcoin/bitcoin#21141
 - bitcoin/bitcoin#21343
 - bitcoin/bitcoin#21235
 - bitcoin/bitcoin#20228
 - bitcoin/bitcoin#21691
 - bitcoin/bitcoin#19801
 - bitcoin/bitcoin#21777

## How Has This Been Tested?
Run unit and functional tests

## Breaking Changes
N/A

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-07-15 18:16 UTC, UdjinM6 requested changes

2024-07-17 13:59 UTC, UdjinM6 submitted a review, later dismissed
utACK

2024-07-19 23:23 UTC, UdjinM6 approved these changes
utACK 4731f7045fb17458d01c1775f7eb8414d73da44c

2024-07-20 16:25 UTC, PastaPastaPasta approved these changes
utACK 4731f7045fb17458d01c1775f7eb8414d73da44c

2024-07-20 16:27 UTC, merged