doc: fix missing 'apt get install', make build steps more prominent, format consistently
dashpay/dash pull request #6120
Opened 2024-07-16 21:51 UTC by coolaj86

- `apt-get` => `apt-get install` (fix typo)
- `apt install` => `apt-get install` (due to subtle bugs with `apt` in non-interactive scripts)
- correct grammar `doc folder` => `./doc/`
- make build / compile documentation prominent
- use `` ```sh `` consistently for shell formatting (rather than mixing indents, `` ```bash ``, `` ```shell ``, and `` 

Developers come to Dash should have clear instruction for how to build / compile just by scanning the README.

Also, the instructions should be correct and consistent.

## What was done?

See above.

## How Has This Been Tested?

See <https://github.com/dashhive/dash/tree/doc-build-docs>.

Note that it's formatted well and consistently and the typos are fixed.

## Breaking Changes

N/A

Only fixes here.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] ~~I have added or updated relevant unit/integration/functional/e2e tests~~
- [x] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-07-17 13:18 UTC, thephez approved these changes
LGTM :+1:

2024-07-17 14:08 UTC, UdjinM6 approved these changes
utACK 72a322a4066c118e9b8aa77079915d97fff860c8

2024-07-17 14:59 UTC, UdjinM6 requested changes
needs rebase on develop

2024-07-17 19:45 UTC, PastaPastaPasta commented
> needs rebase on develop

Yes; we don't merge into master directly; please PR these changes to develop instead

2024-07-18 07:27 UTC, coolaj86 commented
Updated.

2024-07-18 08:31 UTC, UdjinM6 approved these changes
utACK 185e0fa1e8940a54de97c462ec6b44e3e499f69b

2024-07-18 16:00 UTC, PastaPastaPasta approved these changes
utACK 185e0fa1e8940a54de97c462ec6b44e3e499f69b

2024-07-18 16:01 UTC, merged