Bp23 99 1
dashpay/dash pull request #6129
Opened 2024-07-19 00:15 UTC by vijaydasmp

bitcoin backports

2024-07-22 03:44 UTC, vijaydasmp commented
Hello @UdjinM6 for review

2024-07-22 11:11 UTC, UdjinM6 requested changes

2024-07-22 15:38 UTC, vijaydasmp commented on src/test/miner_tests.cpp
> +#include <versionbits.h>
tried to bring 22277

2024-07-22 20:33 UTC, UdjinM6 requested changes
pls see d07dee1ebf

2024-07-23 10:09 UTC, UdjinM6 requested changes
You missed a couple of things it seems

(btw, no need to copy/paste or reimplement patches, you can simply `fetch` + `cherry-pick` them)

2024-07-23 10:09 UTC, UdjinM6 commented on src/test/miner_tests.cpp
> -            txCoinbase.vout[0].scriptPubKey = CScript();
should keep `txCoinbase.vout[0].scriptPubKey = CScript();`

2024-07-23 10:09 UTC, UdjinM6 commented on src/test/miner_tests.cpp
> +            txCoinbase.vin[0].scriptSig = CScript() << (m_node.chainman->ActiveChain().Height() + 1) << blockinfo[i].extranonce;
```suggestion
            txCoinbase.vin[0].scriptSig = CScript() << (m_node.chainman->ActiveChain().Height() + 1) << BLOCKINFO[i].extranonce;
```

2024-07-23 12:25 UTC, vijaydasmp commented
> You missed a couple of things it seems
> 
> (btw, no need to copy/paste or reimplement patches, you can simply `fetch` + `cherry-pick` them)

Thanks @UdjinM6 , will do it from now

2024-07-23 18:14 UTC, UdjinM6 requested changes

2024-07-24 14:52 UTC, UdjinM6 approved these changes
utACK 123b034b4997745a3920cdc5efcd507796eebd86

2024-07-25 15:49 UTC, merged