feat: make a support of Qt app to show withdrawal transaction
dashpay/dash pull request #6131
Opened 2024-07-19 10:30 UTC by knst

## Issue being fixed or feature implemented
Withdrawals from platform are incorrectly shown amount in Dash Core wallet app.
They also shown in Qt app as self-send.

## What was done?
Added a new filter for withdrawal, added new type of transaction to Qt App, fixed calculation of output for them.
Also added a new type of transaction `withdrawal` in rpc output of `gettransaction` RPC

## How Has This Been Tested?
Make a withdrawal transaction on RegTest and check it in Dash Core

![image](https://github.com/user-attachments/assets/aea0f0ca-8c94-46ee-ac2f-fa94c757767d)

Helper to see it: export dpath=/tmp/dash_func_test_PATHPATH/ ; src/qt/dash-qt -regtest -conf=$dpath/node0/dash.conf -datadir=$dpath/node0/ -debug=0 -debuglogfile=/dev/stdout

## Breaking Changes
There's new type of transaction "withdrawal" in rpc output of `gettransaction`.

**This PR DOES NOT change any consensus rules.**
There's a relevant PR with futhermore improvements to make withdrawal transaction immature: https://github.com/dashpay/dash/pull/6128

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-07-19 23:23 UTC, UdjinM6 requested changes
b9118f5671d2bc9947f02dbeb0c6d3331be08e4f looks incomplete - you just import a key but you don't check any tx/rpc

2024-07-20 01:39 UTC, kxcd commented
The term `withdrawal` will be confusing.  Suggest different name eg  `Asset pool` to denote it comes from an asset pool, or more specifically `Platform` to indicate this is coming from Platform.  It will be clear this a credit to the wallet, so no need to muddy the waters with terms like `withdrawal`.

2024-07-20 05:12 UTC, knst commented
@thephez 
> The term withdrawal will be confusing.

Could you suggest? just "Asset unlock" is not good too.
 Internally we already call it asset unlock or withdrawal.

2024-07-20 16:22 UTC, PastaPastaPasta requested changes
General NACK for v21.0; we are in feature freeze and releasing in 9 days. We need to avoid new features at all costs. We can include this in a fast following 21.1

2024-07-20 16:37 UTC, thephez commented
> @thephez
> 
> > The term withdrawal will be confusing.
> 
> Could you suggest? just "Asset unlock" is not good too. Internally we already call it asset unlock or withdrawal.

Yes, we should think about this. I agree with @kxcd. It will be confusing because it is _not_ a withdrawal from the wallet's perspective - it's an incoming tx just like a masternode reward, incoming payment, etc. Maybe something like `platform transfer` or `asset/credit pool distribution`. If we used `* transfer`, it could also be used to show asset lock txs as well as unlocks. What do you guys think?

2024-07-22 06:48 UTC, kxcd commented
Thanks Phez, I like `Platform Transfer` best.  Though I also like `asset/credit pool` and then let the wallet show you the direction since we can both send into Platform and receive from Platform, ideally, the name is the same for both transactions, just the direction will be different. The good thing about `Platform Transfer` is it can be in or out, it's directionless.

2024-07-22 20:34 UTC, UdjinM6 approved these changes
utACK 70cbef978ca808c74b00d378ca120317c8da7bb5 (mac-build CI failure is unrelated)

2024-08-02 15:40 UTC, PastaPastaPasta commented
I want @thephez's approval for terminology / UX. I think I generally agree with him and @kxcd that "withdrawal" is confusing

2024-08-02 15:41 UTC, PastaPastaPasta requested changes
general NACK on "withdrawal" terminology. Want utACK from @thephez / suggestions

2024-08-02 15:44 UTC, knst commented
> general NACK on "withdrawal" terminology. Want utACK from @thephez / suggestions

current version has mentioning of `withdrawal` only in functional tests, Qt & rpc are updated already

2024-08-02 19:31 UTC, PastaPastaPasta commented
> > general NACK on "withdrawal" terminology. Want utACK from @thephez / suggestions
> 
> current version has mentioning of `withdrawal` only in functional tests, Qt & rpc are updated already

Maybe add information about what the terms are then in description?

2024-08-02 19:33 UTC, PastaPastaPasta commented on src/interfaces/wallet.h
> +    bool is_platform_transfer;
I know none of the others do it, but we should ensure these are always initialized
```suggestion
    bool is_platform_transfer{false};
```

2024-08-05 10:25 UTC, knst commented
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/70cbef978ca808c74b00d378ca120317c8da7bb5..3cd2115b17e8750a1519a64a158e19d5331aaba8) the feat-withdrawals-qt branch from[ 70cbef9 ](https://github.com/dashpay/dash/commit/70cbef978ca808c74b00d378ca120317c8da7bb5)to 3cd2115

there's extra fixes and improvements. Also PR description is updated and re-made a screenshot with "platform transfer" instead "withdrawal"

> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/3cd2115b17e8750a1519a64a158e19d5331aaba8..9748a048b41a83be9703bf76d69ca46f73330d31) the feat-withdrawals-qt branch from[ 3cd2115 ](https://github.com/dashpay/dash/commit/3cd2115b17e8750a1519a64a158e19d5331aaba8)to 9748a04

rebased on the top of current develop

2024-08-06 13:35 UTC, thephez reviewed
The "Platform transfer" terminology works for me :+1:

2024-08-07 01:26 UTC, PastaPastaPasta commented on src/interfaces/wallet.h
> +    bool is_platform_transfer;
please squash 9748a048b41a83be9703bf76d69ca46f73330d31 into a9a7f0766844543c90e249896f5ca10243c56c1d

2024-08-07 01:28 UTC, PastaPastaPasta commented on src/interfaces/wallet.h
> +    bool is_platform_transfer;
done in 9748a048b41...21f174aff10

2024-08-07 02:01 UTC, PastaPastaPasta approved these changes
utACK [21f174a](https://github.com/dashpay/dash/pull/6131/commits/21f174aff107f9aec9b758a00bde67b96ad3cd55)

2024-08-07 02:04 UTC, merged