backport : Merge bitcoin/bitcoin#22797
dashpay/dash pull request #6133
Opened 2024-07-20 17:05 UTC by vijaydasmp

bitcoin backports

2024-07-21 05:46 UTC, vijaydasmp commented
Hello @knst for review

2024-07-21 19:24 UTC, UdjinM6 requested changes

2024-07-21 19:24 UTC, UdjinM6 commented on test/functional/p2p_invalid_tx.py
>          # Transactions that do not end up in the mempool
22797:
```suggestion
        # Transactions that do not end up in the mempool:
```

2024-07-21 19:24 UTC, UdjinM6 commented on src/wallet/rpcwallet.cpp
> + * @param  wallet         The wallet.
Good catch! 👍 `develop` is currently broken because of this https://gitlab.com/dashpay/dash/-/pipelines/1381488325

2024-07-22 11:12 UTC, UdjinM6 approved these changes
utACK 29720540b349a456cb4b3811d8b7674880bac204

2024-07-22 14:33 UTC, vijaydasmp commented
Hello @PastaPastaPasta requesting for review

2024-07-23 05:40 UTC, knst approved these changes
utACK 29720540b349a456cb4b3811d8b7674880bac204

2024-07-23 16:04 UTC, merged