backport: merge bitcoin#21732, #21762, #21754, #21953, #21850, #22593, #22619, #22633, #22738, #22501, bitcoin-core/gui#399 (auxiliary backports: part 14)
dashpay/dash pull request #6137
Opened 2024-07-21 18:42 UTC by kwvg

## Additional Information

_Work in progress._

## Breaking Changes

None expected.

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-07-22 20:32 UTC, UdjinM6 requested changes
pls see https://github.com/UdjinM6/dash/commits/pr_6137/ (CI: https://gitlab.com/UdjinM6/dash/-/pipelines/1382702435)

pls note that 22501 and 397b432 are also parts of #6133, 22619 is a part of #6071

2024-07-23 18:14 UTC, UdjinM6 approved these changes
utACK 1c5ea38c681d82a1ae8a30a15ef377f77e9c507a

2024-07-23 18:53 UTC, PastaPastaPasta approved these changes
utACK 1c5ea38c681d82a1ae8a30a15ef377f77e9c507a

2024-07-23 18:59 UTC, merged

2024-07-24 15:07 UTC, knst commented on contrib/linearize/linearize-data.py
> -from binascii import unhexlify
missing changes in `contrib/signet/miner` - should be partial https://github.com/bitcoin/bitcoin/pull/22633

2024-07-24 15:11 UTC, knst commented on doc/assumeutxo.md
> +- [draft PR](https://github.com/bitcoin/bitcoin/pull/15606) (Bitcoin)
nit: https://github.com/dashpay/dash-issues/issues/36 can be added here