feat: only require reindexing when the index was off going to off
dashpay/dash pull request #6203
Opened 2024-08-12 11:15 UTC by PastaPastaPasta

## What was done?
It does not seem reasonable that we need to reindex when turning indexes off. this logic was introduced in https://github.com/dashpay/dash/commit/e0781095f0d797c978fa25d2e0afb4b6dbffddfe

## How Has This Been Tested?
Hasn't

## Breaking Changes
None, basically

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-08-12 11:16 UTC, DashCoreAutoGuix commented
Guix Automation has began to build this PR tagged as v21.1.0-devpr6203.c412d905. A new comment will be made when the image is pushed.

2024-08-12 12:10 UTC, DashCoreAutoGuix commented
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v21.1.0-devpr6203.c412d905. The image should be on dockerhub soon.

2024-08-20 20:29 UTC, PastaPastaPasta commented
Anything else needed here?

2024-08-21 12:42 UTC, UdjinM6 commented
> Anything else needed here?

https://github.com/dashpay/dash/pull/6203#discussion_r1713702806:
> Will have to update tests too.

2024-08-21 14:38 UTC, PastaPastaPasta commented
> > Anything else needed here?
> 
> [#6203 (comment)](https://github.com/dashpay/dash/pull/6203#discussion_r1713702806):
> 
> > Will have to update tests too.

Whoops! I swear I already did that locally, just forgot to push it I guess

2024-08-21 16:33 UTC, UdjinM6 requested changes
see below + same for 2 more tests `feature_spentindex.py` and `feature_timestampindex.py`

2024-08-21 16:33 UTC, UdjinM6 commented on test/functional/feature_addressindex.py
> +        self.nodes[1].assert_start_raises_init_error(["-addressindex=0"], "You need to rebuild the database using -reindex to enable -addressindex", match=ErrorMatch.PARTIAL_REGEX)
`-addressindex=0` == _disable_
you don't need to reindex to _disable_ it...

2024-09-24 14:10 UTC, knst commented on test/functional/feature_addressindex.py
> +        self.start_node(1, ["-addressindex=0"])
-self.stop_node(1)
-self.start_node(1, ["-addressindex=0"])
+self.restart_node(1, "[-addressindex=0"])

2024-09-24 14:13 UTC, knst reviewed
let's wait CI, also consider replacement `stop+start` to `restart_nodes` which has been refactored in all functional tests long time ago

2024-09-24 21:18 UTC, UdjinM6 commented
pls consider 7399b7ade5

2024-10-24 01:00 UTC, PastaPastaPasta commented
Finally pulled in your commit 🙈 I forget about too many PRs

2024-10-24 16:33 UTC, UdjinM6 approved these changes
utACK 492204dc4e9ad856f5ff8a25f5c6cbb44b8a7fe5

2024-10-24 17:50 UTC, PastaPastaPasta commented
no diff; squashed these 4 commits into 1

2024-10-24 17:57 UTC, knst approved these changes
utACK c96f9e028571e3d592c5043f3ff1a6f672cba7f3

2024-10-24 18:26 UTC, merged