chore: deprecate an option `platform-user` in favour of whitelist
dashpay/dash pull request #6209
Opened 2024-08-13 04:23 UTC by knst

## Issue being fixed or feature implemented
Hard-coded restrictions for platform-user are super-seeded by whitelist feature.

## What was done?
Before actually removing feature, let's make it deprecated for now
Split from https://github.com/dashpay/dash/pull/6105/
6105 - to close and re-open for next major release.

It deprecates old command line argument `-platform-user` by renaming to `-deprecated-platform-user`

## How Has This Been Tested?
See new 2 functional tests: `rpc_deprecated_platform_filter.py` and `rpc_external_queue.py` which are split from `rpc_platform_filter.py`

## Breaking Changes
Command line argument `-platform-user` is renamed to `-deprecated-platform-user`

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-08-13 13:32 UTC, UdjinM6 requested changes

2024-08-29 00:32 UTC, PastaPastaPasta commented on src/init.cpp
> +    argsman.AddArg("-deprecated-platform-user=<user>", "Set the username for the \"platform user\", a restricted user intended to be used by Dash Platform, to the specified username.", ArgsManager::A
bump

2024-09-03 13:52 UTC, UdjinM6 approved these changes
utACK 668efc4f1a2d700b56334f2d439ea7135223caf5

2024-09-04 18:10 UTC, PastaPastaPasta reviewed
LGTM; gonna wait to review until 21.2 is branched off to approve / merge

2024-09-27 15:27 UTC, PastaPastaPasta approved these changes
utACK e2c66ae3e9eef0d59cbd2f509bad25292b9ee66f

2024-09-27 15:35 UTC, merged