backport: merge bitcoin#19572, #20953, #20523, #21008, #21310, #22079, #23471, #24218 (zmq backports)
dashpay/dash pull request #6231
Opened 2024-08-24 11:19 UTC by kwvg

## Additional Information

* [bitcoin#19572](https://github.com/bitcoin/bitcoin/pull/19572) introduces tests in `interface_zmq.py` that validate newly introduced "sequence" reporting of all message types (`C`, `D`, `R` and `A`). The `R` message type (removed from mempool) is tested by leveraging the RBF mechanism, which isn't present in Dash.
  
  In order to allow the tests to successfully pass, all fee bumping and RBF-specific code had to be removed from the tests. This test also involves creating a new block to test the `C` message (connected block) that would return a `time-too-new` error and fail unless mocktime has been disabled (which has been done in this test). 

* When backporting [bitcoin#18309](https://github.com/bitcoin/bitcoin/pull/18309) ([dash#5728](https://github.com/dashpay/dash/pull/5728)), Dash-specific ZMQ notifications did not have those changes applied to them and that particular backport was merged upstream *after* [bitcoin#19572](https://github.com/bitcoin/bitcoin/pull/19572), meaning, for completion, the changes from [bitcoin#18309](https://github.com/bitcoin/bitcoin/pull/18309) have been integrated into [bitcoin#19572](https://github.com/bitcoin/bitcoin/pull/19572)'s backport.

  As for the Dash-specific notifications, they have been covered to ensure uniformity in a separate commit.

* The ZMQ notification interface has been converted to a smart pointer in the interest of safety (this change is eventually done upstream in 8ed4ff8e05d61a8e954d72cebdc2e1d1ab24fb84 ([bitcoin#27125](https://github.com/bitcoin/bitcoin/pull/27125)))

## Breaking Changes

None expected.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-08-26 08:49 UTC, UdjinM6 requested changes

2024-08-26 18:23 UTC, kwvg commented on src/init.cpp
> +        UnregisterValidationInterface(g_zmq_notification_interface.get());
I was planning to make changes of this nature anyway (see https://github.com/dashpay/dash/commit/a5f9110b25c7578708b2ddfbb83f61b3f0a54def for a similar change to `pdsNotificationInterface`, will be part of a PR dedicated to misc. changes) and the change isn't strictly speaking _essential_ for the functionality of the backports in this PR nor is the change something that doesn't serve value standalone (as opposed to being a part of a larger backport valuable in this immediate PR). 

Added attribution in commit comment.

2024-08-26 18:23 UTC, kwvg commented on contrib/zmq/zmq_sub.py
> +        self.zmqSubSocket.setsockopt_string(zmq.SUBSCRIBE, "sequence")
Resolved in latest push!

2024-08-26 18:23 UTC, kwvg commented on contrib/zmq/zmq_sub.py
> +            print(hash, label, mempool_sequence)
Resolved in latest push!

2024-08-26 18:23 UTC, kwvg commented on doc/zmq.md
> +    -zmqpubsequence=address
Resolved in latest push!

2024-08-26 18:23 UTC, kwvg commented on doc/zmq.md
> +    -zmqpubsequencehwm=address
Resolved in latest push!

2024-08-26 18:23 UTC, kwvg commented on src/zmq/zmqnotificationinterface.cpp
> +        return notifier->NotifyTransaction(tx) && notifier->NotifyTransactionAcceptance(tx, mempool_sequence);
Resolved in latest push!

2024-08-26 18:23 UTC, kwvg commented on test/functional/interface_zmq.py
> +            assert label == "A"
I've reintroduced most of the `R`-specific logic and added a TODO suggesting that such tests may be added in the future. Thoughts?

2024-08-27 17:53 UTC, UdjinM6 approved these changes
utACK b75e83b298377f59e242479fc243a457ff04c2e0

2024-08-29 22:23 UTC, PastaPastaPasta approved these changes
utACK b75e83b298377f59e242479fc243a457ff04c2e0

2024-08-30 06:13 UTC, knst approved these changes
utACK b75e83b298377f59e242479fc243a457ff04c2e0

we should have release notes for, it can be added by a new PR:
 - zmq support sequence events
 - zmq address can be IPv6 now

2024-08-31 03:19 UTC, merged