refactor: add a new flag disable_mocktime to set_test_params()
dashpay/dash pull request #6242
Opened 2024-08-30 13:03 UTC by knst

## Issue being fixed or feature implemented
To disable mocktime you should re-implement setup_nodes(). It seems as bug-friendly solution

## What was done?
This PR introduce a new flag "disable_mocktime" which can be set in `set_test_params`.
It seems more error prune and the code is shorter

## How Has This Been Tested?
Run unit/functional tests including future changes from https://github.com/dashpay/dash/pull/6235

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-08-30 14:30 UTC, UdjinM6 requested changes

2024-08-30 14:30 UTC, UdjinM6 commented on test/functional/test_framework/test_framework.py
> +                    extra_args=['-disablewallet', "-mocktime={TIME_GENESIS_BLOCK}"],
```suggestion
                    extra_args=['-disablewallet', f"-mocktime={TIME_GENESIS_BLOCK}"],
```

2024-08-30 14:30 UTC, UdjinM6 commented on test/functional/test_framework/test_node.py
> +            self.args.append("-mocktime={mocktime}")
```suggestion
            self.args.append(f"-mocktime={mocktime}")
```

2024-08-30 14:52 UTC, UdjinM6 approved these changes
LGTM, utACK ae71455a8c909465838d43188c8f394cf47b0fa3

2024-09-01 11:25 UTC, knst commented
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/ae71455a8c909465838d43188c8f394cf47b0fa3..5339eb67f5dcfe000b3e9d54e0d00cfd1df92cb3) the refactor-disable-mocktime-flag branch from[ ae71455 ](https://github.com/dashpay/dash/commit/ae71455a8c909465838d43188c8f394cf47b0fa3)to 5339eb6

Force pushed due to [new functional test with no-mocktime:](https://github.com/dashpay/dash/blob/7a9e475c26c54687f3638c0a45d289470e3f2ef9/test/functional/interface_zmq.py#L112-L114) `interface_zmq.py`

2024-09-01 15:50 UTC, UdjinM6 approved these changes
utACK ef4d74a669bce1d59a54f72b2ee9b593745b8ba5

2024-09-01 20:02 UTC, kwvg approved these changes
utACK ef4d74a669bce1d59a54f72b2ee9b593745b8ba5

2024-09-04 16:22 UTC, PastaPastaPasta approved these changes
utACK ef4d74a669bce1d59a54f72b2ee9b593745b8ba5

2024-09-04 16:26 UTC, merged