backport: Merge bitcoin#22217, 23025, 22362
dashpay/dash pull request #6250
Opened 2024-09-05 04:12 UTC by vijaydasmp

btc backport

2024-09-11 01:44 UTC, vijaydasmp commented
Hello @UdjinM6 @knst requesting review

2024-09-11 10:20 UTC, UdjinM6 requested changes

2024-09-12 15:37 UTC, UdjinM6 submitted a review, later dismissed
utACK 2fdfe6fc9c8174df365c08d2e4d20b77c3a04f16

2024-09-13 03:45 UTC, vijaydasmp commented
Hello @PastaPastaPasta requesting review

2024-09-19 16:02 UTC, vijaydasmp commented
Hello @PastaPastaPasta requesting review

2024-09-19 16:02 UTC, vijaydasmp commented
Hello @PastaPastaPasta requesting review

2024-09-22 19:39 UTC, knst reviewed
check comments for 23025

22217, 22362 is OK

2024-09-22 19:39 UTC, knst commented on src/wallet/load.cpp
> +    for (const auto& wallet  : chain.getSettingsList("wallet")) {
22217: nit: extra space

2024-09-22 19:39 UTC, knst commented on src/bench/bench_bitcoin.cpp
>      args.output_json = fs::PathFromString(argsman.GetArg("-output_json", ""));
23035: lost `regex_filter` and `is_list_only`:

```
+args.is_list_only = argsman.GetBoolArg("-list", false);
+args.regex_filter = argsman.GetArg("-filter", DEFAULT_BENCH_FILTER);
```

2024-09-22 19:39 UTC, knst commented on src/bench/bench.cpp
> +#include <vector>
23025: sort it alphabetically

2024-09-22 19:40 UTC, knst requested changes
check comments for 23025

22217, 22362 is OK

2024-09-25 12:55 UTC, knst approved these changes
utACK  bd67f806343314962198b463758f7dca3fd56d54

2024-09-25 14:21 UTC, UdjinM6 approved these changes
utACK bd67f806343314962198b463758f7dca3fd56d54

2024-09-26 17:32 UTC, merged