feat(perf): reduced delays and syncs in functional tests to run faster
dashpay/dash pull request #6268
Opened 2024-09-12 12:06 UTC by knst

## Issue being fixed or feature implemented
Functional tests take too long time to run.

## What was done?
 - removed sleep(1) from each stage of mine_quorum
 - removed sleep(6) from final stage of mine_cycled_quorum
 - no more slow generation blocks per batch in `feature_asset_locks.py`, in `feature_mnehf.py` and in `activate_fork_by_name()`
 - reduced window size in feature_mnehf.py from 12 blocks to 4 blocks only
 - removed dead code from test_framework.py
 - removed dependency of mnehf.py on mn_rr hardfork - its actually useless here but brings bugs

## How Has This Been Tested?
Locally, it speeds up with these fixes for 15% for overall time and 20% for accumulated time.

Before:
```
ALL                                                | ✓ Passed  | 7860 s (accumulated)  
Runtime: 481 s
```  

After:
```
ALL                                                | ✓ Passed | 6237 s (accumulated) 
Runtime: 416 s
```

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-09-16 21:02 UTC, UdjinM6 requested changes
`feature_llmq_simplepose.py` starts to fail much more often for me locally after d561419a63e62a4ad8824497d7ce197bd531e32e (when running 8 of them in parallel). 5d4301d7156f140d5e5809fb2de6bae271160ec7 fixes that.

2024-09-17 02:13 UTC, PastaPastaPasta reviewed
re-request with udjin applied

2024-09-17 15:16 UTC, UdjinM6 commented
Looks like we are getting different results here, my commit makes things a bit less stable for knst for some reason. @PastaPastaPasta pls confirm the issue (and that my commit actually helps).

2024-09-18 17:07 UTC, knst commented
> Looks like we are getting different results here, my commit makes things a bit less stable for knst for some reason. 
on laptop udjin's patch continue to fail, but on PC (different kernel version, different hardware) it doesn't fail that much.

Let's see how CI behaves

2024-09-18 18:14 UTC, closed without merging