feat: bury mn_rr fork - fire up test chains by first block - 6/n
dashpay/dash pull request #6275
Opened 2024-09-17 09:03 UTC by knst

It depends on https://github.com/dashpay/dash/pull/6269 !!!

## Issue being fixed or feature implemented
MN_RR is activated on mainnet: time to bury it!

## What was done?
Hard-fork mn_rr is buried. Prior fixes are done here: https://github.com/dashpay/dash/pull/6270 and https://github.com/dashpay/dash/pull/6269

## How Has This Been Tested?
Run unit and functional tests

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-09-27 14:58 UTC, UdjinM6 requested changes

2024-09-27 14:58 UTC, UdjinM6 commented on src/llmq/context.cpp
> +                                                                 *qman, peerman)}
clang format complains:
```suggestion
    ehfSignalsHandler{
        std::make_unique<llmq::CEHFSignalsHandler>(chainstate, mnhfman, *sigman, *shareman, mempool, *qman, peerman)}
```

2024-09-27 20:32 UTC, UdjinM6 requested changes

2024-09-30 11:59 UTC, UdjinM6 approved these changes
reindexed with no issues on mainnet and testnet

light ACK 9a9d0d5b79d3886ce94985f01e9e59bfc5d4846c

2024-10-01 15:10 UTC, PastaPastaPasta approved these changes
utACK 9a9d0d5b79d3886ce94985f01e9e59bfc5d4846c

2024-10-01 18:45 UTC, merged