backport: cmake prereq 3
dashpay/dash pull request #6295
Opened 2024-09-27 05:28 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
depends on https://github.com/dashpay/dash/pull/6294

## What was done?
  _Describe your changes in detail_

## How Has This Been Tested?
  _Please describe in detail how you tested your changes._

  _Include details of your testing environment, and the tests you ran
to see how your change affects other areas of the code, etc._

## Breaking Changes
  _Please describe any breaking changes your code introduces_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-10-01 19:56 UTC, UdjinM6 requested changes

2024-10-01 19:56 UTC, UdjinM6 commented on src/qt/guiutil.cpp
> +    LogInfo("Qt %s (%s), plugin=%s\n", qVersion(), qt_link, QGuiApplication::platformName().toStdString());
30567: `LogInfo` was introduced in 28318 which we don't have yet

2024-10-02 08:46 UTC, UdjinM6 approved these changes
utACK 1b622944c43b3013597625ab83eab4c781c6702d

2024-10-03 06:15 UTC, merged

2024-10-03 12:52 UTC, knst reviewed
post utACK 1b622944c43b3013597625ab83eab4c781c6702d