backport
dashpay/dash pull request #6300
Opened 2024-10-03 02:59 UTC by vijaydasmp

Bitcoin Backports

2024-11-25 14:30 UTC, knst requested changes

2024-11-25 14:30 UTC, knst commented on src/rpc/rawtransaction.cpp
> +                {RPCResult::Type::STR, "address", /* optional */ true, "The Bitcoin address (only if a well-defined address exists)"},
23642: missing dashification in this line and below: Bitcoin -> Dash

2024-11-25 14:30 UTC, knst commented on src/rpc/rawtransaction.cpp
> +                     {RPCResult::Type::STR, "type", "The type of the script public key (e.g. witness_v0_keyhash or witness_v0_scripthash)"},
23642: missing dashification we don't have type here

2024-11-25 14:30 UTC, knst commented on src/rpc/rawtransaction.cpp
> +                     {RPCResult::Type::STR, "p2sh-segwit", "address of the P2SH script wrapping this witness redeem script"},
23642: missing dashification no segwit for dash

2024-11-26 08:14 UTC, knst commented on src/rpc/rawtransaction.cpp
> +            },
all of these lines should not have any diff except whitespaces, but it's removed substrings "DEPRECATED", added "segwit", etc... Please check carefully

original patch (ignoring whitespaces chages):
![image](https://github.com/user-attachments/assets/cfaadeeb-c78e-459b-af9a-81d37441d4d3)
vs your patch (ignoring whitespaces changes):
![image](https://github.com/user-attachments/assets/782bf02f-b733-467d-9e34-7154ac9c3609)

2024-11-26 08:16 UTC, knst commented on src/rpc/rawtransaction.cpp
> +            },
@vijaydasmp you can use feature `git diff -b` and `git show -b` to compare diff without whitespace-changes or use similar feature on GitHub to do self-review of changes
![image](https://github.com/user-attachments/assets/a67e0a8d-fe35-4262-97ae-105285102e95)

2024-11-27 07:18 UTC, knst approved these changes
LGTM 0cf0b9135afc2eba700469c3ea5ccf6e2e660473

2024-11-30 15:11 UTC, vijaydasmp commented
Hello @PastaPastaPasta @UdjinM6 requesting review

2024-12-07 14:01 UTC, UdjinM6 approved these changes
utACK 39316088585984faf4ea422745e64f0adef916f8

2024-12-10 11:59 UTC, vijaydasmp commented
Hello @knst @PastaPastaPasta , requesting review

2024-12-15 10:25 UTC, vijaydasmp commented
Hello @knst @PastaPastaPasta , requesting review

2024-12-16 15:25 UTC, vijaydasmp commented
Hello @PastaPastaPasta requesting review

2024-12-17 02:56 UTC, PastaPastaPasta approved these changes
utACK 39316088585984faf4ea422745e64f0adef916f8

2024-12-17 03:01 UTC, merged