backport: bump boost min
dashpay/dash pull request #6313
Opened 2024-10-04 20:12 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
See commit

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-10-04 20:25 UTC, UdjinM6 commented on doc/dependencies.md
> +| zlib |  |                                                                 |  |  | [Yes](https://github.com/dashpay/dash/blob/develop/depends/packages/qt.mk) |
29066: why messing with whitespaces/markdown table here?

2024-10-04 20:26 UTC, PastaPastaPasta commented on doc/dependencies.md
> +| zlib |  |                                                                 |  |  | [Yes](https://github.com/dashpay/dash/blob/develop/depends/packages/qt.mk) |
cause clion f***s up..

2024-10-04 21:19 UTC, UdjinM6 requested changes
debug build fails for me with
```
test/util/setup_common.cpp:444:9: error: use of undeclared identifier 'BOOST_ASSERT'
  444 |         BOOST_ASSERT(cbTx.has_value());
      |         ^
test/util/setup_common.cpp:447:13: error: use of undeclared identifier 'BOOST_ASSERT'
  447 |             BOOST_ASSERT(false);
      |             ^
test/util/setup_common.cpp:450:13: error: use of undeclared identifier 'BOOST_ASSERT'
  450 |             BOOST_ASSERT(false);
      |             ^
```

backporting 24395 (23a4d5d9) fixes it.

2024-10-04 22:39 UTC, UdjinM6 commented
Hmm... lots of failures in CI.. there must be smth else then. Also, it looks like 24395 caused high CPU usage https://github.com/bitcoin/bitcoin/issues/27586 and was reverted in 27724... so we need that too (or drop 24395 for now) 🙈

2024-10-04 23:34 UTC, UdjinM6 commented
let's try 27783 (887241a07d)?

2024-10-08 13:55 UTC, knst approved these changes
utACK c0154c0d8cfb4ca05b1953586b7ea5fd40b7ab7a

2024-10-08 14:32 UTC, merged