backport: bitcoin/bitcoin#22229 test: consolidate to f-strings and related fixes
dashpay/dash pull request #6357
Opened 2024-10-24 18:03 UTC by knst

## Issue being fixed or feature implemented
Just one backport bitcoin#22229 because it is a big size.

Though, even it is called as part I, there has not been part II yet.

## What was done?
Some preparation, code unifications to make bitcoin#22229 with less conflicts and finally backport of itselfl.

## How Has This Been Tested?
Run unit & functional test

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

2024-10-24 18:16 UTC, knst commented
> This pull request has conflicts, please rebase.

That's a lie!

2024-10-24 19:06 UTC, PastaPastaPasta approved these changes
utACK fc8436832b9b230e3aab2592245c6f71b618f3f6

2024-10-24 19:20 UTC, UdjinM6 requested changes

2024-10-24 19:20 UTC, UdjinM6 commented on test/functional/feature_notifications.py
> +            seed = "cTdGmKFWpbvpKQ7ejrdzqYT2hhjyb3GPHnLAK7wdi5Em67YLwSm9"
cafc78c0869c1b6712829b8944dfd94b753d07ba : linter complains `test/functional/feature_notifications.py:71:13: F841 local variable 'seed' is assigned to but never used`

2024-10-24 19:20 UTC, UdjinM6 commented on test/functional/feature_loadblock.py
>              cfg.write("netmagic=fcc1b7dc\n")
22229: missed `f` here (to align with upstream even though `f` is not really needed here)

2024-10-24 20:16 UTC, UdjinM6 submitted a review, later dismissed
utACK a15e33937c8551acd73e8d992824b7cc9659ab8a

2024-10-24 20:20 UTC, PastaPastaPasta submitted a review, later dismissed
utACK a15e339, good to merge once CI is happy

2024-10-25 07:07 UTC, knst commented
CI fails for sqlite build

2024-10-25 11:19 UTC, UdjinM6 commented
reverting/dropping 1b6baa5899 fixes it https://gitlab.com/UdjinM6/dash/-/pipelines/1511972465

2024-10-25 13:56 UTC, knst commented
> reverting/dropping https://github.com/dashpay/dash/commit/1b6baa58994ad596c7d8da1cf193146d6fecd4f2 fixes it https://gitlab.com/UdjinM6/dash/-/pipelines/1511972465


yes I am looking to the same commit, but not sure how exactly to fix it yet. I will try to find a fix it and if it is not easy I will just drop it.

2024-10-25 14:40 UTC, knst commented
I dropped that problematic commit for feature_notifications.py; will resolve issue some other day

2024-10-25 20:49 UTC, PastaPastaPasta approved these changes
utACK https://github.com/dashpay/dash/commit/7c6c93d201b7338257ebc413f58b22bea490b8a2

2024-10-25 20:49 UTC, merged