backport: trivial 2024 10 25 pr3
dashpay/dash pull request #6364
Opened 2024-10-25 20:46 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
Trivial backports

## What was done?

## How Has This Been Tested?
built locally

## Breaking Changes

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-10-26 17:26 UTC, UdjinM6 requested changes

2024-10-26 17:31 UTC, PastaPastaPasta commented on src/net.h
> +static constexpr bool DEFAULT_V2_TRANSPORT{true};
Hmmm, I think I wanna drop this anyhow. I don't think we want v22 final having default v2. only maybe a 22.1?

2024-10-26 17:34 UTC, PastaPastaPasta commented
dropped non-trivial commits

2024-10-26 17:37 UTC, UdjinM6 submitted a review, later dismissed
utACK 66566f30d2363cf55dcf272f0776bc00d103e539 but also needs confirmation that Guix is ok (GH had and issue, couldn't reproduce it on my machine though)

2024-10-26 19:13 UTC, kwvg approved these changes
utACK 66566f30d2363cf55dcf272f0776bc00d103e539

2024-10-28 07:48 UTC, UdjinM6 commented
25677 need a fix:
```diff
diff --git a/src/node/interfaces.cpp b/src/node/interfaces.cpp
index e1418aa442..f15026cf7b 100644
--- a/src/node/interfaces.cpp
+++ b/src/node/interfaces.cpp
@@ -767,7 +767,7 @@ public:
     bool checkFinalTx(const CTransaction& tx) override
     {
         LOCK(cs_main);
-        return CheckFinalTxAtTip(m_node.chainman->ActiveChain().Tip(), tx);
+        return CheckFinalTxAtTip(*Assert(m_node.chainman->ActiveChain().Tip()), tx);
     }
     bool isInstantSendLockedTx(const uint256& hash) override
     {
```

2024-10-28 15:39 UTC, UdjinM6 commented on test/functional/feature_dbcrash.py
> +    getnewdestination,
25087: linter complains
```
test/functional/feature_dbcrash.py:41: error: Module 'test_framework.wallet' has no attribute 'getnewdestination' 
```

2024-10-29 20:00 UTC, UdjinM6 approved these changes
utACK fbc0bce2e62592817676408daaeb33384b76aa78

2024-10-29 22:15 UTC, merged