backport: merge bitcoin#23499, #23832, #24136, #24265, #23819, #23595, #24486, #15423, #24784, #24956, #25016, #25060
dashpay/dash pull request #6370
Opened 2024-10-28 10:47 UTC by kwvg

## Breaking Changes

None expected.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-10-28 19:01 UTC, PastaPastaPasta approved these changes
utACK b9177a374401df301fafdeaf88a8559109201ef1

2024-10-28 19:48 UTC, UdjinM6 requested changes

2024-10-28 19:48 UTC, UdjinM6 commented on src/validation.cpp
> +        nTime5 - nTimeStart // in microseconds (µs)
23819: we have a couple more `nTime`s
```suggestion
        nTime8 - nTimeStart // in microseconds (µs)
```

2024-10-28 19:48 UTC, UdjinM6 commented on src/rpc/blockchain.cpp
> +    }
24956: nit: unrelated refactoring

2024-10-29 09:28 UTC, kwvg commented on src/validation.cpp
> +        nTime5 - nTimeStart // in microseconds (µs)
Resolved in latest push!

2024-10-29 09:28 UTC, kwvg commented on src/rpc/blockchain.cpp
> +    }
Split off into separate commit

2024-10-29 10:11 UTC, UdjinM6 approved these changes
utACK 02320032c7c779a04a8e7347b48af368a56a32cf

2024-10-30 01:12 UTC, merged