refactor: remove C++17 workarounds
dashpay/dash pull request #6380
Opened 2024-11-02 21:13 UTC by kwvg

## Additional Information

* Using an existing namespace as an alias for a namespace part of the `std` namespace (as done in `ranges`) has been done before, see namespace `fs`, an alias to `std::filesystem` ([here](https://github.com/dashpay/dash/blob/396573d09cff5c65b2e3b4ba965185ac532b8b5c/src/fs.h#L18-L21)).

* While the comment in `wallet.cpp` did mention that there would be a better way to do the cast than in C++17, the method to do so, using `std::chrono::clock_cast`, has still not been implemented in Clang ([source](https://stackoverflow.com/a/77540287)). The issue has been sidestepped by not using `std::time_t` at all and instead relying on `fs::file_time_type`, the type returned by `fs::last_write_time`.

## Breaking changes

None expected.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas **(note: N/A)**
- [x] I have added or updated relevant unit/integration/functional/e2e tests **(note: N/A)**
- [x] I have made corresponding changes to the documentation **(note: N/A)**
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2025-02-12 22:24 UTC, UdjinM6 approved these changes
GH CI in my repo https://github.com/UdjinM6/dash/actions/runs/13294351944
Guix https://github.com/UdjinM6/dash/actions/runs/13294351921

light ACK c4b3dacb09c98a7ddee03c19e3b4e66626de0b0f

2025-02-13 02:21 UTC, PastaPastaPasta requested changes
Currently unable to merge in due to configure error:

```
checking whether /opt/homebrew/opt/llvm/bin/clang accepts -g... yes
checking for /opt/homebrew/opt/llvm/bin/clang option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /opt/homebrew/opt/llvm/bin/clang... gcc3
checking whether /opt/homebrew/opt/llvm/bin/clang supports C++20 features with -std=c++20... no
checking whether /opt/homebrew/opt/llvm/bin/clang supports C++20 features with +std=c++20... no
checking whether /opt/homebrew/opt/llvm/bin/clang supports C++20 features with -h std=c++20... no
configure: error: *** A compiler with support for C++20 language features is required.
```

this is with both system clang16 and brew clang19

2025-02-15 08:55 UTC, kwvg commented
@PastaPastaPasta is the issue still present? Unable to reproduce locally.

2025-02-15 21:40 UTC, PastaPastaPasta commented
Was able to successfully build in a fresh clone

2025-02-15 21:41 UTC, PastaPastaPasta approved these changes
light ACK c4b3dacb09c98a7ddee03c19e3b4e66626de0b0f

2025-02-15 21:42 UTC, merged