ci: add macOS and Windows builds to GitHub Actions
dashpay/dash pull request #6421
Opened 2024-11-21 16:18 UTC by kwvg

## Additional Information

* Depends on https://github.com/dashpay/dash/pull/6400
* `WINEPREFIX` needs to be overridden because of permissions issues with GitHub Actions ([build](https://github.com/kwvg/dash/actions/runs/11952384181/job/33318706080#step:8:3297)), SC2155 ([info](https://www.shellcheck.net/wiki/SC2155)) has been suppressed as the expected syntax is clunky and unnecessary (if `mktmp` fails, `wine` would refuse to run due to invalid `WINEPREFIX`, which would trigger an error).
* The `HOST` check before running `setup_sdk.sh` isn't a part of the shell script itself as the script is written to not have to rely on external variables being set, so the caller is expected to know the conditions it'll impose to run `setup_sdk.sh`, the script itself remaining agnostic.
  * `guix-start` doesn't benefit from deduplication because the scripts there are expected to be self-contained and therefore, cannot link back to this script as it will not be present in the container.

## Breaking Changes

None expected.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas **(note: N/A)**
- [x] I have added or updated relevant unit/integration/functional/e2e tests **(note: N/A)**
- [x] I have made corresponding changes to the documentation **(note: N/A)**
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-11-21 16:19 UTC, kwvg commented
GitHub Actions run for 66b7197fb1d292a919e1ff88031245629fb41c4f, https://github.com/kwvg/dash/actions/runs/11955577182.

2024-11-22 14:08 UTC, kwvg commented
GitHub Actions run for fe08442, https://github.com/kwvg/dash/actions/runs/11973573180

2024-11-23 06:44 UTC, kwvg commented
GitLab Actions run for a5959da, https://github.com/kwvg/dash/actions/runs/11976668589.

2025-02-14 19:44 UTC, kwvg commented
* GitHub Actions build for 243f209ee2374dd31deaf59d38509ec456f60d18, https://github.com/kwvg/dash/actions/runs/13335118547
  * Caching tested by adding empty commit on top (c9a0031a55992896f7625894165df83c48ec4d10) and triggering new run, https://github.com/kwvg/dash/actions/runs/13336213348.
  * macOS depends rebuilds are short ([build](https://github.com/kwvg/dash/actions/runs/13336213348/job/37251911978)) and `ccache` has a high hit rate ([source](https://github.com/kwvg/dash/actions/runs/13336213348/job/37251959147#step:8:3035)).

2025-02-15 11:28 UTC, UdjinM6 approved these changes
GH CI https://github.com/UdjinM6/dash/actions/runs/13336497998
GH Guix https://github.com/UdjinM6/dash/actions/runs/13336498009

light ACK 243f209ee2374dd31deaf59d38509ec456f60d18

2025-02-17 04:26 UTC, PastaPastaPasta requested changes
some thoughts / concerns

2025-02-17 04:26 UTC, PastaPastaPasta commented on .github/workflows/build-depends.yml
> +            depends/SDKs
why do we need both of these? if this is like depends, then one is compressed, and the other is usable. We should only cache the compressed one.

2025-02-17 04:26 UTC, PastaPastaPasta commented on .github/workflows/build-depends.yml
> +          key: depends-sdks-${{ hashFiles('depends/hosts/darwin.mk') }}
can we use https://github.com/dashpay/dash/blob/632b8b43dddf8f0c34c5a0c379c54829422727f2/ci/test/00_setup_env_mac.sh#L13 instead? I think the way you have it now is plausible to have stale cache

2025-02-17 04:26 UTC, PastaPastaPasta commented on .github/workflows/build-depends.yml
> +            depends-${{ hashFiles('contrib/containers/ci/Dockerfile', 'depends/packages/*') }}-
this feels like a not ideal order; if anything in depends/packages changes we will completely miss cache. Isn't it better to have it as `depends-${{ inputs.build-target }}-hashfiles-dep_hash`? this was if something in dep_hash or depends/packages changes we'll still get some cache restore

2025-02-17 04:26 UTC, PastaPastaPasta commented on .github/workflows/build-depends.yml
> +          fi
nit: feels wrong to use guix script in general ci

2025-02-17 06:43 UTC, kwvg commented on .github/workflows/build-depends.yml
> +            depends-${{ hashFiles('contrib/containers/ci/Dockerfile', 'depends/packages/*') }}-
Want to keep around `hashFiles('contrib/containers/ci/Dockerfile')` because we _want_ the cache to be invalidated if we bump the base image to avoid the need for manually clearing caches when we do bumps, can drop `depends/packages/*` though.

2025-02-17 06:47 UTC, kwvg commented on .github/workflows/build-depends.yml
> +          fi
`contrib/containers/guix` is a Dash-specific directory introduced in https://github.com/dashpay/dash/pull/5449 (Bitcoin's directory is `contrib/guix`) and `setup-sdk` was introduced in https://github.com/dashpay/dash/pull/6490, placed in that directory on review suggestion ([source](https://github.com/dashpay/dash/pull/6490#discussion_r1885800358)) but otherwise isn't tied to Guix at all.

We use it in GitLab CI without problems ([source](https://github.com/dashpay/dash/blob/bb469687d3d936f82fd8e8fbe0934eec5e17df5e/.gitlab-ci.yml#L50-L52)).

2025-02-17 06:50 UTC, kwvg commented on .github/workflows/build-depends.yml
> +          key: depends-sdks-${{ hashFiles('depends/hosts/darwin.mk') }}
`depends/hosts/darwin.mk` is what decides the Xcode version, LLD version and uses them to define the SDK path ([source](https://github.com/dashpay/dash/blob/bb469687d3d936f82fd8e8fbe0934eec5e17df5e/depends/hosts/darwin.mk#L1-L8)) used by the compiler ([source](https://github.com/dashpay/dash/blob/bb469687d3d936f82fd8e8fbe0934eec5e17df5e/depends/hosts/darwin.mk#L57)), any bump in the SDK version requires changes to `hosts/darwin.mk`.

Would instead propose to drop those variables from `00_setup_env_mac.sh`.

2025-02-17 06:51 UTC, kwvg commented on .github/workflows/build-depends.yml
> +            depends/SDKs
Because if the extracted directory is present, it short-circuits the script ([source](https://github.com/dashpay/dash/blob/bb469687d3d936f82fd8e8fbe0934eec5e17df5e/contrib/containers/guix/scripts/setup-sdk#L18)).

2025-02-17 10:21 UTC, kwvg commented on .github/workflows/build-depends.yml
> +          env ${{ steps.setup.outputs.DEP_OPTS }} make -j$(nproc) -C depends
As `DEP_OPTS` are supposed to hold key-value pairs that are space-delimited (hence the `env`), word splitting is desirable behavior here.

2025-02-17 10:22 UTC, kwvg commented
GitHub Actions run for 90743ee4ada0a0d6da3c0bf6f522fe9bb3fc2509, https://github.com/kwvg/dash/actions/runs/13365816148

2025-02-17 20:20 UTC, PastaPastaPasta commented on .github/workflows/build-depends.yml
> +            depends-${{ hashFiles('contrib/containers/ci/Dockerfile', 'depends/packages/*') }}-
I think we need to include depends/packages/* as well no? otherwise we will get exact cache hit, when we actually still need to build the depends? and then that means we won't save that new cache

2025-02-17 21:26 UTC, kwvg commented on .github/workflows/build-depends.yml
> +            depends-${{ hashFiles('contrib/containers/ci/Dockerfile', 'depends/packages/*') }}-
Reintroduced `${{ hashFiles('depends/packages/*') }}` in latest push

2025-02-17 21:26 UTC, kwvg commented on .github/workflows/build-depends.yml
> +            depends/SDKs
Dropped `depends/sdk-sources` in latest push

2025-02-17 21:53 UTC, kwvg commented
GitHub Actions run for 2bcc5b31094795900201278b06616a9f8e3bae75, https://github.com/kwvg/dash/actions/runs/13378782910.

2025-02-18 09:46 UTC, kwvg commented
GitHub Actions for 106500c1124073c80869fae4eddb3f0a407ca670, https://github.com/kwvg/dash/actions/runs/13385988110.

2025-02-21 19:57 UTC, UdjinM6 approved these changes
utACK 106500c1124073c80869fae4eddb3f0a407ca670

2025-02-21 20:09 UTC, PastaPastaPasta approved these changes
utACK 106500c1124073c80869fae4eddb3f0a407ca670; gonna do CI on my repo, and push an empty commit and ensure caches are working as expected

2025-02-21 21:48 UTC, merged