refactor: make `Get`{`Quorum`, `MinedCommitment`, `InstantSendLock*`, `*MN*`} and friends return `std::optional`
dashpay/dash pull request #6446
Opened 2024-12-03 13:06 UTC by kwvg

## Additional Information

* Depends on https://github.com/dashpay/dash/pull/6132

## Breaking Changes

_Work in progress_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2025-07-28 18:27 UTC, DashCoreAutoGuix commented
## ✅ Backport Verification - Issues Fixed
I found and fixed 1 issue:
- Missing include: Added `#include <optional>` to src/evo/deterministicmns.h → Fixed CI build failures

**Original Bitcoin commit:** N/A (Dash-internal refactoring)
**Fix commit pushed:** `c65a52fe0c`
**Reviewed commit hash:** `a197cb7bcf-verify-1753727224`

<details>
<summary>✅ Analysis Summary</summary>

This PR refactors Dash's masternode and quorum management functions to return `std::optional` instead of raw pointers, which is a good practice for safer null handling. The main issue was that `src/evo/deterministicmns.h` was using `std::optional` without including the required header, causing build failures across multiple CI configurations.

**Fix Applied:**
- Added `#include <optional>` to src/evo/deterministicmns.h

This should resolve the catastrophic CI failures (8 failures) that were occurring due to the missing include.

**Note:** This is a Dash-internal refactoring PR, not a Bitcoin backport, which is why no Bitcoin commit hash is available.
</details>

This fix should resolve the CI build failures. ✅

2025-07-28 18:34 UTC, knst commented on src/evo/deterministicmns.cpp
> +std::optional<CDeterministicMNCPtr> CDeterministicMNList::GetMN(const uint256& proTxHash) const
why? Could you justify this refactoring?
std::optional to shared_ptr is not really good solution.

shared_ptr can be nullptr and std::optional can be nullopt.

You still need to check if it is "null" or not; you still get UB if there's null and you haven't checked it.
But there are 2 downsides - std::optional add overhead (extra bool flag, constructor, etc); and 2nd (which is worse), you need to compare not only for nullopt, but for nullptr also.

```
auto mn =  GetMN(); if (mn != nullopt && mn.value() != nullptr) .... 
```

2025-07-28 18:34 UTC, knst requested changes
conceptual NACK; shared_ptr & std::optional should not contain each other

2025-07-28 20:19 UTC, kwvg commented on src/evo/deterministicmns.cpp
> +std::optional<CDeterministicMNCPtr> CDeterministicMNList::GetMN(const uint256& proTxHash) const
This PR has been conceptually abandoned, am looking to rework it someday but agree in principle it's currently not in a great shape. Bot's taken everyone for a loop, eh?

2026-09-11 21:02 UTC, PastaPastaPasta commented
Closing this abandoned implementation following the [author’s confirmation](https://github.com/dashpay/dash/pull/6446#discussion_r2237787061) and the conceptual NACK in the review. The current refactor still wraps nullable shared pointers in optional, leaving two absence states and a broad call-site conversion without an agreed benefit.

A future proposal can address the return-value contract with a narrower design and fresh tests; this thread preserves the original discussion.

---
🤖 Posted autonomously by Codex on behalf of pasta.

2026-09-11 21:02 UTC, closed without merging