perf: introduce ToBytes in bls.h and use it in all spots trivially possible, convert vecBytes to std::array
dashpay/dash pull request #6515
Opened 2024-12-29 01:11 UTC by PastaPastaPasta

## Issue being fixed or feature implemented
we made changes to bls library library to allow std::array based serialization, which resulted in ~10% speedups in serialization in library benchmarks. I noticed today: 

pre-this change:
<img width="1562" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/cd7824c7-de75-4faa-892c-10270c6e4a02" />

post this change:￼￼
<img width="1555" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/ba939f10-47f0-4f86-b675-b99077ca0393" />

this shows that roughly 2.5% of total cycles during reindex are spent on vector new in our bls.h object.

## What was done?
Convert to array to avoid dynamic allocation slowdown

## How Has This Been Tested?
reindexing atm, looks good so far, and performance is improved as expected

## Breaking Changes
None

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

2024-12-29 08:18 UTC, knst commented
it conflicts with my PR https://github.com/dashpay/dash/pull/6508 which already had one review iteration by Udjin.
Consider reviewing 6508 and rebase this PR on top.

2025-01-27 14:47 UTC, knst requested changes

2025-01-27 14:47 UTC, knst commented on src/bls/bls.h
> +        s.write(AsBytes(Span{ToBytes(specificLegacyScheme).data(), SerSize}));
here's UB: ToBytes returns temporary object and Span doesn't own it.

```suggestion
        const auto bytes{ToBytes(specificLegacyScheme)};
        s.write(AsBytes(Span{bytes.data(), SerSize}));
```

2025-01-27 14:47 UTC, knst commented on src/bls/bls.h
> +        if (memcmp(vecBytes.data(), ToBytes(specificLegacyScheme).data(), SerSize)) {
here's UB. after call data() temporary object is erased.

```suggestion
        const auto bytes{ToBytes(specificLegacyScheme)};
        if (memcmp(vecBytes.data(), bytes.data(), SerSize)) {
```

2025-01-27 18:43 UTC, knst commented on src/bls/bls.h
> +        return impl.SerializeToArray(specificLegacyScheme);
```suggestion
        if (!fValid) {
            return std::array<uint8_t, SerSize>{};
        }
        return impl.SerializeToArray(specificLegacyScheme);
```

it works for me with this fix 5b4b333958a2816c520e701cf65b427ea05e8a87

2025-01-28 14:52 UTC, knst approved these changes
utACK 2ca49da6a91ad606ec3f3b469a286c898f38addd

2025-01-28 20:50 UTC, UdjinM6 approved these changes
utACK 2ca49da6a91ad606ec3f3b469a286c898f38addd

2025-01-29 16:15 UTC, kwvg approved these changes
utACK 2ca49da6a91ad606ec3f3b469a286c898f38addd

2025-01-29 21:52 UTC, merged